### ISSUE TITLE
FR: modal add support for autoload

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#100]
It will be nice to have some attribute in modal which will automatically load modal on page load.

for example 
`<b:modal id="myModal" visible="true" />`

This js should work for that (just googled didn't test yet):
`<script type="text/javascript">
 $(window).load(function(){
        $('#myModal').modal('show');
    });
</script>`

**Comment by xystra** [comment]
why not use the <body onload="myFunction()"> instead?

**Comment by bilak** [comment]
How to use it when you are using jsf templates?

**Comment by stephanrauh** [comment]
There's nothing wrong with the inline script, but to answer your question: since JSF 2.2 you can use pass-through attributes to call the onload handler:
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      >
    <h:head />
    <h:body pt:onload="alert(1)">
```...

**Comment by stephanrauh** [comment]
Opening a modal dialog when entering a JSF view seems to be an exotic use case to me. I suggest we simply mention your Javascript snippet in the BootsFaces documentation.

**Comment by stephanrauh** [comment]
Added the snippet to the documentation.

**Comment by bilak** [comment]
Imagine this situation:
there's main template which contains body and other elements and then there's one page (subpage.xhtml so body is "inherited" from template) in which you want to have modal opened on page load. Of course you can do it inside MB init method, but it would be nice to have it controlled from within xhtml.
