### ISSUE TITLE
Upgrading app from BF 1.2.0 to 1.3.0 causes Resource Not Found: bsf.css: css/default/bsf.css

### ISSUE THREAD

**Issue by jimmc929** [TheCoder4eu/BootsFaces-OSP#1003]
The full error is:

JSF1064: Unable to find or serve resource, css/default/bsf.css, from library, bsf.

We have made no other changes to the app other than upping BF from 1.2.0 to 1.3.0. It is a very simple app with minimal UI (one JSF page). The page does load and display properly but we get the above-described exception thrown and displayed through FacesMessages (growl). When debugging the page in Edge with F12 Developer Tools, we can see that there is a css/bsf.css, but under the "default" folder there is only a core.css. "Default" seems to be the name of a theme. (We don't use any special themes with BF, so presumably BF is using whatever it would consider to be a default theme?) Is Bootsfaces 1.3.0 looking for bsf.css under the "default" theme/folder, and if so, why? Is there supposed to be an opportunity to include an optional, custom bsf.css with a theme? If so, and the bsf.css file is not present for that theme, shouldn't the system just fall back to use the existing css/bsf.css file and ignore the other missing bsf.css file? We'd love to upgrade from 1.2.0 to 1.3.0 but can't until this issue is addressed. Thanks!
Jim

**Comment by TheTimeWalker** [comment]
Strange, I've updated a web app from 1.2.0 to 1.3.0 and had no issues with that. Can you check if your web.xml has something similar like this:
```xhtml
<context-param>
<param-name>BootsFaces_USETHEME</param-name>
<param-value>default</param-value>
</context-param>
```

**Comment by jepsar** [comment]
I've overloaded the class in my project where I've removed the line mentioned in #1021 and for me that solved the issue.

**Comment by tg47** [comment]
@stephanrauh, I work with @jimmc929 . We have tested the change you made and it works. The error is no longer appearing. You can close this issue. Thanks

**Comment by stephanrauh** [comment]
That's great news! Thanks for testing!
