### ISSUE TITLE
b:dateTimePicker should support both LocalDateTime and converters

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#1007]
[According to Donald Kariro](https://twitter.com/donkariro/status/1027540986518560768), BootsFaces `<b:dateTimePicker>` neither supports converters not `LocalDateTime`. We should fix both issues.

**Comment by jepsar** [comment]
Related to #1020?

**Comment by jepsar** [comment]
@stephanrauh `LocalDateTime` is Java 8 and BootsFaces is currently using Java 7. Sounds like something for the next version.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
