### ISSUE TITLE
datepicker does not have space after css class name 'form-group'

### ISSUE THREAD

**Issue by optimus29** [TheCoder4eu/BootsFaces-OSP#1008]
datepicker does not have space after css class name 'form-group' which causes appearance problem when the validation fails and new css classes are added to datepicker.

**Comment by Lb-lea** [comment]
I looked up datePicker on  1.3.0 version
DatePicker doesn't seem to have any element of class 'form-group'....Did you mean input-group or  input-group-addon..
Do you remember on which html element was the problematic class tag?

**Comment by optimus29** [comment]
<b:form id="register">
      <b:datepicker required="true" value="#{register.dateOfBirth}" id="dateOfBirth" label="Date of birth" />
      
      <b:formGroup>
        <b:commandButton value="Submit"/>
      </b:formGroup>
    </b:form>

This will generate the html something like following:

    <div class="form-group" id="register:dateOfBirth">
      <label for="register:dateOfBirth_input" class=" bf-required null control-label">Date of birth</label>
      <div class="input-group ">
        <input id="register:dateOfBirth_input" name="register:dateOfBirth" class="form-control bf-required hasDatepicker" data-dpisvisible="false" type="text">
        <button type="button" class="ui-datepicker-trigger">...</button>
        <span id="register:dateOfBirth_input-group-addon" class="input-group-addon">
          <span><i id="register:dateOfBirth_icon" class="glyphicon glyphicon-calendar"></i></span>
        </span>
      </div>
    </div>

The outer most `div` was supposed to have a space after the class name `form-group`.
I am using bootsfaces version `1.3.0`.

**Comment by stephanrauh** [comment]
Solved by merging #1008.
