### ISSUE TITLE
Enhancement: Implement Toast/Growl style messages

### ISSUE THREAD

**Issue by xystra** [TheCoder4eu/BootsFaces-OSP#101]
Have you ever considered implementing a Bootsfaces version of Growl (Primefaces) or Toastr (JS)?

**Comment by stephanrauh** [comment]
Yes. One of our users is currently working on a JSF version of http://bootstrap-growl.remabledesigns.com/. If we're lucky, he sends us a pull request.

**Comment by Pauldic** [comment]
I cant wait to see this feature

**Comment by jpiersanti** [comment]
Hello there, do you know if the library you mentioned (http://bootstrap-growl.remabledesigns.com/) is compatible with bootsfaces?

**Comment by zhedar** [comment]
As of https://github.com/TheCoder4eu/BootsFaces-OSP/pull/315 the Growl is already implemented. There are several other components @asterd has already put some great work in, so we can probably close some of those issues now.
As far as I can see, Growl uses bootstrap-notifiy, which is probably what you have linked. So If you want to test that, it should be included in the current Snapshot. See the [Snapshot Showcase](http://www3.bootsfaces.net/Showcase/forms/Growl.jsf) for usage information.
At least we should reference those changed in the issues, so tracking progress is easier.

**Comment by asterd** [comment]
Hi, yes it is compatible but we have already developed a b:growl component that uses this library. You can find it in the source code and i think we will release it with bootsfaces 0.8.2.

**Comment by zhedar** [comment]
The linked [Snapshot Showcase](http://www3.bootsfaces.net/Showcase/forms/Growl.jsf) produces a `Configuration error:` on every request it seems. I couldn't reproduce this in my current local build.
@TheCoder4eu maybe you can look the server error up somehow, if you got some spare time?

**Comment by zhedar** [comment]
As already said, this was already implemented back in 0.8.5, somehow we just forgot to close this issue.
