### ISSUE TITLE
dataTable onselect is fired when expansion button is clicked.

### ISSUE THREAD

**Issue by abcivashritt** [TheCoder4eu/BootsFaces-OSP#1013]
I created a responsive dataTable with onselect. The onselect works perfectly well, but when the dataTable renders with the expansion button for rows, both events are fired on clicking the expansion button.

The same issue occurs when there are other actions in the row(E.g. Icons to Delete). Both actions are fired.

I am using Bootsfaces 1.3.0 and PrimeFaces 6.2

**Comment by stephanrauh** [comment]
Actually, I wasn't even aware we've already implemented expandable rows. I'd guess it's still in our list of open issue. Did you implement the feature yourself?

**Comment by abcivashritt** [comment]
No. This is what I meant by expandable rows.

![image](https://user-images.githubusercontent.com/5622818/46410950-bf751a80-c71a-11e8-9809-6f7a09f8ccae.png)

**Comment by stephanrauh** [comment]
I feel stupid - the demo rings a bell, it's a screenshot from our showcase, but still, I don't find it. Can you help me?

Nonetheless, I can help you with the buttons you've added to the datatable. Just add an <code>return false;</code> to the <code>onclick</code> handler of the button. Strictly speaking, it  should be preceded with an <code>javaScript:</code> prefix, but the simple and intuitive version seems to do the trick just as well:

```xml
 <b:dataTableColumn>
      <b:commandButton value="edit" icon="edit" ajax="true" update="@(.editableCarTable)"
                                         onclick="ajax:car.edit(); return false;" >
      </b:commandButton>
 </b:dataTableColumn>
```

**Comment by abcivashritt** [comment]
https://showcase.bootsfaces.net/forms/DataTable.jsf
The example table under the section 'Responsiveness' loads like this in mobile devices.

And for the button onclick, I tried your fix, it is not working in my application.

`<b:dataTableColumn>
	<b:commandButton ajax="true" onclick="ajax:bean.delete(var.id);javascript:return false;" update="@(.table)">
		<h:graphicImage library="folder" name="imageName.abc"/>
	</b:commandButton>
 </b:dataTableColumn>`

**Comment by stephanrauh** [comment]
Ah, this only happens if the commandButton is in the first column. Put it in the second column, and you won't have any conflicts.

After looking at the implementation, I have little hope to solve the bug. So I've documented it in the showcase.
