### ISSUE TITLE
JSF 2.3 b:commandLink not recognized as a tag

### ISSUE THREAD

**Issue by ErickPezoa** [TheCoder4eu/BootsFaces-OSP#1014]
I upgrated to jsf 2.3 from 2.0 version and everything is working fine except the fact that one of my pages is not loading because I am using the component <b:commandLink> and I am getting the error:

`<b:commandLink> Tag Library supports namespace: http://bootsfaces.net/ui, but no tag was defined for name: commandLink`

I am using Apache Tomcat app server version 7.0, JSF 2.3 and bootsfaces 1.3.0. Any ideas of what might be happening here?

**Comment by stephanrauh** [comment]
The demo is broken on my local copy of https://staging.bootsfaces.net/Showcase//forms/commandLink.jsf, but I don't see the error message you're mentioning.

Would you mind to provide us a reproducer - i.e. a minimum program showing the bug without forcing us to invest a lot of time to get it up an running?

**Comment by stephanrauh** [comment]
@ErickPezoa Did you manage to solve the bug? What was the problem?

**Comment by ErickPezoa** [comment]
@stephanrauh I made a mistake. There is no issue with bootsfaces. The problem was for some reason Tomcat was loading bootsfaces version 1.1 instead of 1.3.

**Comment by stephanrauh** [comment]
I see. Thanks for reporting back!
