### ISSUE TITLE
Find a way to override the core BootStrap.css files instead of modifying them

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#1016]
In #997 @vsvetoslavov asked us to find a better way to modify the core Bootstrap files.

Currently, BootsFaces is shipped with a bundle of modified Bootstrap theme. This modification prevent users from using third-party themes. Let's collect the list of modifications, and try to use the override mechanism of CSS to achieve the same goal.

**Comment by vsvetoslavov** [comment]
Popovers are something that is more or less problematic to get using BootsFaces - I had to download specific files from bootstrap in order to get them.

**Comment by stephanrauh** [comment]
I suppose we'll close the ticket since our team has run out of contributors.
