### ISSUE TITLE
Bootstrap 4 and Liferay 7.1 support

### ISSUE THREAD

**Issue by pulijalahari** [TheCoder4eu/BootsFaces-OSP#1018]
Hi Devs:

We are using liferay 7.0 with bootsfaces 1.3.0 as of now which has bootstrap 3.x support. Can any one share the future roadmap of the product and also if it supports Liferay 7.1 and upgrading to bootstrap 4?

thanks,
hari

**Comment by stephanrauh** [comment]
Oops - @ngriffin7a, does Liferay 7.1 update to Bootstrap 4? More to the point, does it force developers to update to Bootstrap 4?

@pulijalahari As for your other question: we've got a great prototype for Bootstrap 4. But we need a helping hand. What about you? Talking of which, would you, @chsreedhar , like to participate?

**Comment by ngriffin7a** [comment]
@stephanrauh Liferay 7.0 is Bootstrap 3 and 7.1 is Bootstrap 4.

If upgrading to 7.1, then this might help https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/using-the-bootstrap-3-lexicon-css-compatibility-layer

**Comment by jepsar** [comment]
@stephanrauh if there are concrete things to do on BootsFaces 2, let me know. There are no issues in your BFNext repo...

**Comment by stiemannkj1** [comment]
For anyone wanting to use BootsFaces in Liferay 7.1/7.2, it should still work well and be styled correctly. [Liferay 7.1 and 7.2 have a Bootstrap 3 compatibility layer](https://portal.liferay.dev/docs/7-1/tutorials/-/knowledge_base/t/using-the-bootstrap-3-lexicon-css-compatibility-layer) that ensures Bootstrap 3 CSS styles still render correctly.

**Comment by stephanrauh** [comment]
@stiemannkj1 Thanks! Our team is currently short of contributors, so I'll close the ticket.

Truth to tell, I don't see any point in implementing a Bootstrap 4 version in the age of Angular, Vue.js, and React.js.
