### ISSUE TITLE
Enhancement: collapsable panel

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#102]
It would be nice to have ability ty collapse panel by some attribute.
Something like this code snippet

`<b:panel id="collapsablePanel" contentStyle="panel-collapse collapse in">
                <f:facet name="heading">
                    <a data-toggle="collapse" href=".panel-body">collapse</a>
                </f:facet>
            </b:panel>`

**Comment by stephanrauh** [comment]
This fiddle shows a possible implementation:  http://jsfiddle.net/Wc4xt/1052/

**Comment by stephanrauh** [comment]
Added and documented a simple collapse feature.

To do: the collapsed state doesn't survive post requests, and it can't be controlled by the Java code.

**Comment by stephanrauh** [comment]
The expand/collapse state now is persistent (provided the panel is put into an h:form). The collapsed state is also exposed by an attribute.

**Comment by bilak** [comment]
Is it also possible to have some attribute to control if collapsible panel is shown/hidden by default?

**Comment by stephanrauh** [comment]
Yes, that's what the ```collapsed``` attribute does. You can bind it to an expression language.

**Comment by bilak** [comment]
yes that's correct, I didn't seen it in taglib. Thanks
