### ISSUE TITLE
Breadcrumbs tries to load theme/bfs.css while no other component does

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#1021]
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/70398c2e744c86cd558d4bc27a09ee3fafc4b8f4/src/main/java/net/bootsfaces/component/breadcrumbs/Breadcrumbs.java#L49

.. this results in an error message. I think this line is supposed to be disabled.

**Comment by tg47** [comment]
This may be the cause of Issue #1003

**Comment by stephanrauh** [comment]
Weird. Where do these commented lines come from? Be that as it may - I've deleted the offending line. Thanks for the hint!

**Comment by stephanrauh** [comment]
I assume my last code change fixes the bug, so I'll close the ticket now.
