### ISSUE TITLE
lazy dataTable

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#1023]
i am using primefaces for lazy data tables and while i love prime i miss the bootsfaces look.  it would be fairly easy to write a lazy loader wrapper similar to 
```
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortMeta;
import org.primefaces.model.SortOrder;
```
but i am not sure how easy it is to integrate into datatables.net

we could even build it on top of primefaces components?

i don't really want to rip off their stuff but it seems like a necessary feature?

**Comment by jepsar** [comment]
I would love to see lazy loading. Datatables.net does support it:

https://datatables.net/examples/server_side/defer_loading.html

**Comment by jepsar** [comment]
The closest thing to lazy loading on DataTables.net I could find is https://datatables.net/examples/server_side/pipeline.html

**Comment by chongma** [comment]
@jepsar thanks. i didn't think to search the datatables.net website. those examples look like they would plug into a prime type lazy data model.  we need to consider which attributes would need to be added to `b:dataTable` to control it

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
