### ISSUE TITLE
BlockUI not working on commandButton with onclick attribute

### ISSUE THREAD

**Issue by t-oster** [TheCoder4eu/BootsFaces-OSP#1029]
I am using bootsfaces 1.3.0. I globally enabled blockUI and it works, but if the commandButton has an onclick attribute, the UI is not blocked. I work around this by adding $.blockUI(); to the onclick handler, but I want to know if this is intended.

**Comment by stephanrauh** [comment]
No, not intended. Actually, all the demos in the showcase do have an `onclick` attribute. So I wonder what you're doing different.

The BlockUI activation is part of the AJAX engine. It intercepts every AJAX request (well, at least the requests triggered by BootsFaces components).
