### ISSUE TITLE
Support more/new languages in components using i18n files

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#1034]
See https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1022#issuecomment-439548283

Follow up on #1022

https://github.com/jquery/jquery-ui/tree/master/ui/i18n

https://datatables.net/plug-ins/i18n/

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
