### ISSUE TITLE
FEATURE REQUEST - Select rows in DataTable using checkboxes

### ISSUE THREAD

**Issue by hvsharma** [TheCoder4eu/BootsFaces-OSP#1038]
Can we have feature of selecting rows using checkboxes in next release? This is helpful since it is more user-friendly and doesn't require someone to hold ctrl or shift. Moreover, it will be helpful for mobile users as well as it's more intuitive. 

For Example : [Primefaces Datatable](https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml#form:checkboxDT)

**Comment by stephanrauh** [comment]
The other day, one of our users used the `datatables.checkbox` plugin to achieve your goal. I've asked him to write a short walk-through. Please give him a couple of days time, he'll fill in the details soon.

**Comment by stephanrauh** [comment]
BTW, I think we won't implement the feature. Instead, we'll add the walk-through to the documentation.

**Comment by frankyhoffmann** [comment]
To expand the datatable with selectable checkboxes, you have to do following configuration: 

1.)	Download the JavaScript File „dataTables.checkboxes.min.js“ 
        from the URL: https://www.gyrocode.com/projects/jquery-datatables-checkboxes
2.)	Import the JavaScript File to the JSF-Page. 
        An example for a Import of a JSF-Resource:  
        <h:outputScript library="adt21app" name="js/dataTables.checkboxes.min.js"></h:outputScript>
3.)	Insert the option „customOptions“ in the Bootsfaces datatable with the following parameter:
        'columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi'}

       Example: 
       customOptions="pagingType:'full_numbers','columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi'}"

 „0“ in the 'targets': parameter means that the first column of the datatable will be the checkbox-column. If you set it to „1“  it will be the second column and so on. 

The checkbox column must have a unique ID in the datatable.
An example for the output of the first column in the Bootsfaces datatable:
<b:dataTableColumn id="checkboxDT" >#{resultList.id}</b:dataTableColumn>

**Comment by sometowngeek** [comment]
@stephanrauh I'm curious... Why would this not be implemented in the future? It's nice to be able to incorporate it into BootsFaces, but the walkthrough @frankyhoffmann shared seems to suggest using strict jQuery.

The nice thing about using BootsFaces framework is so we wouldn't have to try to come up with a variety of functions to get the feature.

I think the current selection isn't 100% user friendly because there still are some users who doesn't know about ctrl- and shift-clicking.

Please reconsider and add this as a new feature.

**Comment by Lb-lea** [comment]
I'd like to add that there is an issue with the language management when using the plug-in.

- If I don't use the plug-in and don't specify the language, my browser language is used => awesome
- Now I add the line:
` "customOptions="'columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi'}"`

I now have my datatable still in my browser language except for the "1 row selected" that appears in English
- So I force the language manually : 
```
<b:dataTable 
customOptions="'columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi'}"
lang="fr">
```
Nothing changed, the datatable infos are still ok but the selection info are still in English...
- So I added custom messages in the custom options following the plugin's doc https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/basic/localization/:
```
<b:dataTable 
customOptions="'columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi'},
	'language': {
	   	 'select': {
	         'rows': {
	             '_': '%d lignes sélectionées',
	             '0': '',
	             '1': '%d ligne sélectionée'
	         }
	     }
	   }"It's starting to look long for component header but
lang="fr">
```
and now ....the datatable stuffs are in English but, good for me, the selection related infos are in French..... 

I am guessing there is something to do about stuff that is done server side vs stuff that is done client side.

Even if bootsfaces doesn't implements the feature it might be good make it easier to combine BF and the checkbox plugin ....

**Comment by stephanrauh** [comment]
@frankyhoffmann @Lb-lea I've added the feature to BootsFaces, but it seems I didn't get it right yet. For some reason, the message below the table always reports "1 row selected", never "2 rows selected". Any idea what I'm doing wrong?

**Comment by stephanrauh** [comment]
Now it works! The feature supports both `selection-mode="single"` and `selection-mode="multiple"`.

**Comment by sometowngeek** [comment]
I think this is broken in 1.4.1

It shows as numbers instead of checkboxes in the documentations.

https://showcase.bootsfaces.net/forms/DataTable.jsf#selectioncolumn

**Comment by sometowngeek** [comment]
I plan on helping out once I move to an apartment and have good internet at home. Where I currently live, I only get 250 Kbps >.>

**Comment by stephanrauh** [comment]
Oops - it's broken in the showcase, but works on my machine. Looks like a forgotten JavaScript file.

**Comment by stephanrauh** [comment]
Missing imports:
```html
<link type="text/css" rel="stylesheet" href="/BootsFacesWeb/javax.faces.resource/css/dataTables.checkboxes.css.jsf?ln=bsf">
<script type="text/javascript" src="/BootsFacesWeb/javax.faces.resource/js/dataTables.checkboxes.min.js.jsf?ln=bsf"></script>
```

**Comment by stephanrauh** [comment]
This feature is going to ship with BootsFaces 1.4.2.
