### ISSUE TITLE
Maven support for legacy java

### ISSUE THREAD

**Issue by srbala** [TheCoder4eu/BootsFaces-OSP#1041]
Any plans to add maven support for legacy java, like bootsfaces-jre7.

Trying to use bootfaces in a maven project which uses JDK 1.7, default build causes issues on deployment.

**Comment by stephanrauh** [comment]
Sooner or later, we'll have to cut compatibility to older Java versions. Chances are BootsFaces 1.4.0 still compiles with Java 7. But I don't know if (or how)  it's possible to publish different flavours of the same file on Maven. Do you happen to know?

**Comment by vsvetoslavov** [comment]
@stephanrauh perhaps you could use classifiers for the compability versions?

**Comment by stephanrauh** [comment]
Java 7 has officially reached its end-of-life phase. Of course there's the paid extended support until 2022. By the way: if you really need this, you can compile BootsFaces yourself.
