### ISSUE TITLE
problem with OpenStretMap

### ISSUE THREAD

**Issue by Catucuamba** [TheCoder4eu/BootsFaces-OSP#1043]
if I use  a <b:openStreetMap> inside of a form it don work, the message say:

> Uncaught Error: Map container not found

and I inspect the script and found :

```JavaScript
> var fmrConsultasIndividualesmapa_map = L.map('**fmrConsultasIndividualesmapa**',.... 
```

The bug is that the id container is badly built, the correct will be

```JavaScript
var fmrConsultasIndividualesmapa_map =  L.map('**fmrConsultasIndividuales:mapa**',...
```

 sorry if my english is bad.

Al utilizar un <b:openStreetMap> dentro de un form me da problemas, el script que se genera automáticamente está mal, conforme se indica en las líneas superiores, favor su colaboración solventado este error.

This is my code:
Este es el código utilizado:
 
```html
<b:form id="fmrConsultasIndividuales" styleClass="vertical_align_top">
             <b:openStreetMap id="mapa" width="100%" height="500px" center="42.3402,-3.6972"  />
</b:form>
```

**Comment by Catucuamba** [comment]
I found the error:
In the package:

> package net.bootsfaces.component.openStreetMap;

in the class:

> public class OpenStreetMapRenderer extends CoreRenderer

in the method: 

> public void encodeEnd(FacesContext context, UIComponent component) throws IOException {

you have: 

> String **clientIdRaw** = openStreetMap.getClientId();
> String **clientId** = clientIdRaw.replace(":", "");
> ...
> rw.writeText("var " + clientId + "_map = L.map('" + **clientId** + "', {center: [" + openStreetMap.get......

in my opinion, the correct way will be:

> rw.writeText("var " + clientId + "_map = L.map('" + **clientIdRaw** + "', {center: [" + openStreetMap.get......

**Comment by stephanrauh** [comment]
¡Gracias por tu análisis!

**Comment by stephanrauh** [comment]
Acabó reproducir tu bug. Parece que tu solución funciona bien.  Es una sorpresa, por que librerias como jQuery no funcionan con los ids de JSF.

**Comment by stephanrauh** [comment]
He cargado BootsFaces 1.4.1-SNAPSHOT al Maven Central. Mira al #369 para aprender como descargarlo en tu project. ¿Quieres probarlo?

**Comment by stephanrauh** [comment]
Done and documented.
