### ISSUE TITLE
b:commandLink where no action defined

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#1044]
i have noticed a slight problem with `b:commandLink`.  if an action is defined it refreshes the page normally, otherwise it jumps to the top of the page as if the whole page has reloaded.  e.g.

this works:
```xml
<h:commandLink value="No action defined">
    <f:setPropertyActionListener target="#{myBean.myValue}" value="#{someValue}" />
    <f:ajax render="@form" />
</h:commandLink>
```
this works:
```xml
<b:commandLink value="Action defined" action="#{myBean.doSomething}">
    <f:setPropertyActionListener target="#{myBean.myValue}" value="#{someValue}" />
    <f:ajax render="@form" />
</b:commandLink>
```
this causing the jumping issue:
```xml
<b:commandLink value="No action defined">
    <f:setPropertyActionListener target="#{myBean.myValue}" value="#{someValue}" />
    <f:ajax render="@form" />
</b:commandLink>
```
NB you would need to test it in a really long page for the issue to be noticeable.

**Comment by stephanrauh** [comment]
Simply setting `ajax="true"` or `update="@form"` solves the issue. I've implemented support for `<f:ajax>` as an afterthought, so some things don't work perfectly with `<f:ajax>`.
