### ISSUE TITLE
is it possible to create database modeling diagram using Bootsfaces / JSF .

### ISSUE THREAD

**Issue by primeO** [TheCoder4eu/BootsFaces-OSP#1045]
Hello All ,   
Out of interest iam asking this . 

Is it possible to create database modeling diagram using bootsfaces or any other jsf library .
By which the user will be creating a diagram and when save it will be generated as JSON and tables will be generated . had attached the image of the sample . Whether we can do something similar to this in Bootsfaces / JSF.

Please provide your views on this . 

![dpmuddiagram](https://user-images.githubusercontent.com/5968200/50087659-cb0ab480-0226-11e9-9066-3bfe4f5171b1.gif)

**Comment by stephanrauh** [comment]
I like the PrimeFaces diagram component (https://www.primefaces.org/showcase/ui/data/diagram/flowchart.xhtml). Of course, their `p:diagram` doesn't exactly match your needs. 

The next alternative would be to use a pure JavaScript widget. I've run a quick Google search and came up with this page. It looks promising, but I've tried none of the solutions on this page, so take it with a grain of salt. That said, here you are: https://modeling-languages.com/javascript-drawing-libraries-diagrams/
