### ISSUE TITLE
DataTable Dom Positioning

### ISSUE THREAD

**Issue by cavalka** [TheCoder4eu/BootsFaces-OSP#1046]
Unable to change the placement of features in datatable.  I tried using custom options using the datatables example seen here [https://datatables.net/examples/basic_init/dom.html](https://datatables.net/examples/basic_init/dom.html).  Top and bottom classes are missing.  This is a much desired feature.  Ideally it would be good to have 6 possible placement locations top left, top middle, top right, bottom left, bottom middle, bottom right.

**Comment by mtvweb** [comment]
Try, i.E.

`custom-options="dom:&quot;&lt;'row'&lt;'col-sm-12'f&gt;&gt;&lt;'row'&lt;'col-sm-12'tr&gt;&gt;&lt;'row'&lt;'col-sm-5'i&gt;&lt;'col-sm-7'p&gt;&gt;&quot;"
`

See https://datatables.net/reference/option/dom for Bootstrap positing
