### ISSUE TITLE
DataTable - server side code execution in multiple form page issue

### ISSUE THREAD

**Issue by cavalka** [TheCoder4eu/BootsFaces-OSP#1049]
I have a Datatable that is on a page in a multi-form page.  Specifically, it is in the 2nd sequential form tag on the page.  I have commandButton in datatable that executes an AJAX command.  In my datatable below the Edit button when clicked doesn't execute the server side `onclick="ajax:mrTableBean.editMrTableRecord(mrTableRecord)"`; however it will execute the client side code `oncomplete="$('.mr1000Modal').modal()"`.  The issue is server side code will not execute when the Datatable is not in the first form on the page.  I confirmed the commandButton works when I move the datatable to the first form on the page.  The server side code executes.  

```xml
<b:dataTable value="#{mrTableBean.tableIdDtlListFromDb()}"
    var="mrTableRecord"
    rendered="#{mrTableBean.selectedMrTableId=='1000'}">

    <b:dataTableColumn value="#{mrTableRecord.mr1000LicTypeCode}"
        label="Type Code"></b:dataTableColumn>
    <b:dataTableColumn value="#{mrTableRecord.mr1000LicTypeNarr}"
        label="License Narrative"></b:dataTableColumn>
    <b:dataTableColumn label="Action">
        <b:commandButton value="Edit" icon="edit" style-class="btn-sm"
            oncomplete="$('.mr1000Modal').modal()"
            onclick="ajax:mrTableBean.editMrTableRecord(mrTableRecord)"
            update="mr1000Modal" ajax="true" />
        <b:commandButton
            onclick="ajax:mrTableBean.deleteMrTableRecord(mrTableRecord)"
            value="Delete" icon="trash" style-class="btn-sm" ajax="true"
            update="mrTable" />
    </b:dataTableColumn>
</b:dataTable>

```

**Comment by stephanrauh** [comment]
Sounds weird and unexpected. Just to be sure, your JSF page looks something like this:

```xml
<h:body>
  <h:form>
    <b:input value="#{what.ever}" />
  </h:form>
  <h:form>
    <b:dataTable>
      <b:commandButton value="I'm broken">
    </b:dataTable>
  </h:form>
</h:body>
```xml

Our showcase looks similar. The commandButton demo is in the second or third form. So I believe that there *should* be no error. Obviously, your experience says something different. That's the kind of bug that's difficult to hunt down for us.

May I kindly ask you for a reproducer, i.e. a simple but complete project showing the problem that runs out-of-the-box? Ideally a GitHub project I can simple compile with "mvn install" and run on any application server?

**Comment by cavalka** [comment]
I can't easily provide a full working example.  In the showcase can you test the existing commandButton in Datatable showcase(code below)?  Change the `ajax:car.edit()` to execute a backing bean or something server side.  My problem is that it will not execute server side logic..client side logic executes fine.  That would be a good test, as I believe this is not the first form on the Datatable showcase.  If it executes for you then it is something in my code.

```
<h:form>
  <b:dataTable value="#{carPool.carPool}" var="car" class="editableCarTable">
    <b:dataTableColumn value="#{car.brand}" />
    <b:dataTableColumn value="#{car.type}" />
    <b:dataTableColumn value="#{car.color}" />
    <b:dataTableColumn value="#{car.year}" order="asc" />
    <b:dataTableColumn label="Price">
      <b:inputText value="#{car.price}" rendered="#{car.editable}" />
      <h:outputText value="#{car.price}" rendered="#{not car.editable}" />
    </b:dataTableColumn>
    <b:dataTableColumn>
      <b:commandButton value="edit" icon="edit" ajax="true" update="@(.editableCarTable)"
                       onclick="ajax:car.edit()" >
      </b:commandButton>
    </b:dataTableColumn>
  </b:dataTable>
</h:form>
``

**Comment by cavalka** [comment]
Actually, looking at the showcase the Edit and Delete buttons are not working correctly.  When the edit button is clicked nothing happens and when the Delete button is clicked it puts the field in edit mode.

**Comment by cavalka** [comment]
carPool.doSomeStuff(car) is what I mean.  Thanks.
________________________________

**Comment by stephanrauh** [comment]
I can confirm the showcase is broken. Clicking on "edit" results in an exception. Clicking on "delete" does what "edit" is suppose to do.

**Comment by stephanrauh** [comment]
Here are two options how to do it:

```xml
         <b:dataTableColumn>
            <b:commandButton value="edit" icon="edit" ajax="true" update="@(.editableCarTable)"
                             onclick="ajax:car.edit(); javascript:return false;" >
            </b:commandButton>

          </b:dataTableColumn>
          <b:dataTableColumn>
            <b:commandButton value="Delete" iconAwesome="trash"
                             action="#{carPool.delete(car)}">
              <f:ajax execute="@this" render="@form" />
            </b:commandButton>
          </b:dataTableColumn>
```

```java
public class CarPool implements Serializable {
	private List<Car> carPool;

	public void delete(Car car) {
		this.carPool.remove(car);
	}
```

I hope I'll find out how to pass the `value` attribute in a regular `ajax:` expression, but until than, that's the workaround.

**Comment by stephanrauh** [comment]
FWIW, in our showcase the simple approach `click="ajax:carPool.delete(car)"` also works. I just didn't commit the third option yet because I didn't want to add two delete buttons. Any idea which button I could add?

**Comment by stephanrauh** [comment]
The showcase shows that AJAX buttons work even if there's more than one form. I suppose the bug is something different. I suggest you send us a reproducer. In the meantime, I'll close the ticket.
