### ISSUE TITLE
FR: multiselect

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#105]
Hello,
it will be nice to have multiselect in BF project. Something like this http://davidstutz.github.io/bootstrap-multiselect/

**Comment by stephanrauh** [comment]
Finished an early prototype.

**Comment by TheCoder4eu** [comment]
stephanrauh modified the milestone: v0.6.7, v0.7.0 3 days ago => is it intended for the actual v0.8.0 then?

**Comment by stephanrauh** [comment]
No, I think we can include it in  version 0.7. it's almost finished.

**Comment by TheCoder4eu** [comment]
Thanks, I asked to be sure :-)

**Comment by stephanrauh** [comment]
I added a couple of options to b:selectMultiMenu. 

To dos left:
* nSelectText is not generated
* I suppose it'd be a good idea to add the CSS class options, too,
* There are several JS callback we could add.
* Most JS callback the widget inherited from the regular combobox aren't rendered, They should be removed from the taglib.
* Dropping the "multiple" attribute converts the widget to a radio-button-widget

**Comment by stephanrauh** [comment]
Done. The documentation isn't perfect yet, but good enough to close this ticket.
