### ISSUE TITLE
Partial Refresh after modal hide

### ISSUE THREAD

**Issue by cavalka** [TheCoder4eu/BootsFaces-OSP#1051]
It is common to refresh parts of a page after closing/hiding modal.  If I encounter a validation error in the modal I only want to update the modal content and not any additional content.  Do you have a solution/script for this scenario?

Here is sample code.  I am unsure how to execute a partial refresh in the oncomplete property.  Right now I am updating :mainForm:messages1 :mainForm:mrTable on a failed and successful validation.  These ID's only need refreshed when modal closes in oncomplete. 

``` xml
<b:commandButton value="Update" icon="save" look="success"
			          oncomplete="if (!validationFailed) $('.mrTableModal').modal('hide');"
				  action="#{mrTableBean.updateMrTableRecord()}"
				  col-sm="6"
				  rendered="#{!mrTableBean.isAddRecord()}" ajax="true" update=":mainForm:mr1000ModalPanel :mainForm:messages1 :mainForm:mrTable">
</b:commandButton>
```

This is how xpages framework implements the solution. https://www.ibm.com/support/knowledgecenter/en/SSVRGU_9.0.1/user/extlib_controls_dialog.html

**Comment by stephanrauh** [comment]
You can also achieve the same with OmniFaces. Let's close the ticket now.
