### ISSUE TITLE
fontawesome only included by static references

### ISSUE THREAD

**Issue by mtvweb** [TheCoder4eu/BootsFaces-OSP#1052]
If you add components using fontawesome icons, fontawesome will not be included, if the references are not static. This happens if the iconreference is set by an EL expression. Even if you use a composite, awesome isn't recognised to be included by AddResourcesListener.

**Comment by geopossachs** [comment]
Hello @mtvweb ,
you can add a simple code example to reproduce the error

**Comment by mtvweb** [comment]
Here is a test page

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title>Test</title>
</h:head>
<h:body>
	<b:container fluid="false">
		<b:form>
			<b:row>
				<b:column>
					<b:commandButton action="/issue1052.xhtml" value="Test"
						icon-awesome="#{ 'mo' += 'ney' }" />
				</b:column>
			</b:row>			
		</b:form>
	</b:container>
</h:body>
</html>
`
