### ISSUE TITLE
TabViewRenderer.encodeTabContentPanes does not set offset correctly

### ISSUE THREAD

**Issue by gitmotte** [TheCoder4eu/BootsFaces-OSP#1054]
Version: 1.4.1, 1.5.0-SNAPSHOT

If there are multiple tabs and the first one is disabled, but the last one is always enabled, the activeIndex="-1" does not work to load the last enabled Tab.  The offset is only incremented on active Tabs ... 

```java	
for (int index = 0; index < tabs.size(); index++) {
	final Tab tab = (Tab) tabs.get(index);
	if (tab.isRendered()) {
		final int currentIndex = numberOfTabsRendered;
		Runnable r = new Runnable() {
			int offset = 0;
			public void run() {
				try {
					encodeTabPane(context, writer, tab, (currentIndex+offset == currentlyActiveIndex) && (!tabView.isDisabled()));
					offset++;
				} catch (IOException ex) {
					// exotic case, suffice it to log it
					LOGGER.log(Level.SEVERE, "An exception occurred while rendering a tab.", ex);
				}
			}
		};
		if (tab.getValue() == null) {
			r.run();
			numberOfTabsRendered ++;
		} else {
			numberOfTabsRendered += ((Tab)tabs.get(currentIndex)).encodeTabs(context, r);
		}
	} 
}
```
Btw. where do i find the unit-tests ? https://github.com/TheCoder4eu/BootsFaces-Tests seems to be outdated ..

**Comment by stephanrauh** [comment]
Oops. Thanks for correcting this bug!

BTW: sorry for the long delay. I've been moving to another town. That's a full-time project of its own. :)

**Comment by stephanrauh** [comment]
As for your question: there are no unit tests. We've started to think about tests when it was too late. Plus, we didn't find out yet how to write useful and efficient unit tests for JSF components with a reasonable effort.

**Comment by stephanrauh** [comment]
I've merged your PR.
