### ISSUE TITLE
datatable export to excel without using CDN

### ISSUE THREAD

**Issue by maciass2008** [TheCoder4eu/BootsFaces-OSP#1057]
Hi, 
i want to use p:datatable with the export options (excel, pdf ...) without using internet (CDN)
the export bar does not appear on posts that are not connected to the internet
any suggestion? 
thanks

**Comment by stephanrauh** [comment]
Most likely it's simply a missing plugin. Select all the features you need on https://datatables.net/download/, download the JavaScript and the CSS files and store them in your projects. Add the two files as `h:outputStylesheet` and `<h:outputScript>`. Don't forget to add the attribute `target="head"` to the outputScript.

Now the datatable should work properly even without internet. Maybe you need to add a parameter to the web.xml to deactivate loading the datatables.js file from the internet.
