### ISSUE TITLE
Checkboxes not working in DataTable (follow-up to #1038)

### ISSUE THREAD

**Issue by julianbenner** [TheCoder4eu/BootsFaces-OSP#1059]
The newly implemented checkbox feature in BF 1.4.1 doesn't work properly as it doesn't include the necessary parameters in the `customOptions` parameter. I suspect this happens because the `columnDefs` part of the parameter is set initially and then overridden when passing a custom value.

For instance, using this as a value for `customOptions` does work:
```
'columnDefs': [{'targets':0, 'checkboxes': {'selectRow': true}}],'select':{'style':'multi+shift'}
```

**Comment by Lb-lea** [comment]
Do have a more detailed explanation of what does not work for you?
Here is an example of a very simple table with checkbox that works,  please add the option you wanted to have on it:

```html
<b:dataTable id="table-example" value="#{lineList}" var="line"
		customOptions="'language': { select': { 'rows': {  '_': '%d custom plural',    '0': '',   '1': '%d custom singular'     }  }    } " 
		onselect="ajax:datatableControleur.onSelect(line, typeOfSelection, indexes);"
	        ondeselect="ajax:datatableControleur.onDeselect(line, typeOfSelection, indexes);"
		paginated="false" searching="false">
```
