### ISSUE TITLE
Bootsfaces components break dynamic p:tabView 

### ISSUE THREAD

**Issue by michbeck100** [TheCoder4eu/BootsFaces-OSP#1061]
I am using BootsFaces components inside of a dynamic Primefaces `TabView` (https://www.primefaces.org/showcase/ui/panel/tabView.xhtml). The beans behind the tabs are `@ViewScoped`. The expected behavior would be that the beans are initialized only when the tab is clicked.
When using BootsFaces components however, the beans are initialized even though the tab was not clicked. A simple Ajax call inside the active tab is enough to trigger the initialization.

I've created a simple project to show the behavior: https://github.com/michbeck100/bootsfaces-dynamic-tabview

Just run `mvn clean wildfly:run` and point your browser to `http://localhost:8080/bootsfaces-dynamic-tabview-1.0-SNAPSHOT/index.xhtml`. 
On the first tab there is an Ajax-enabled `h:selectOneRadio`. When switching the radio buttons twice, you will see the following message in the log: `ReviewBean init`. This shows, that the bean, which is just used on the second tab, was just initialized. 
It won't happen if you just switch the radio button once. Just after the second Ajax Call the bean gets initialized.
Once you remove the `b:row` from the second tab, everything works as expected, and the bean doesn't get initialized anymore.

Is there anything I am missing when using Primefaces and Bootsbaues in one project?

Thanks for your help!

**Comment by knoppt** [comment]
I can confirm this problem - is there a solution?

**Comment by geopossachs** [comment]
Hello @michbeck100 
not only bootfaces will break the dynamic p:tabView of primefaces.

I switch in your example from primeface-ajax to jsf-core-ajax and eliminate all third party stuff with the same result, the dynamic p:tabView was also broken.

In my option, this is a bug in the primeface implementation of the dynamic aspect 


`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" 
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <h2>PrimeFaces TabView Example</h2>

            <p:tabView dynamic="true" cache="false">
                <p:tab id="about" title="About">
                    <h:panelGroup id="panelGroup">
                        <h:selectOneRadio value="#{aboutBean.test}">
                            <f:selectItem itemLabel="false" itemValue="#{false}"/>
                            <f:selectItem itemLabel="true" itemValue="#{true}"/>
                            <f:ajax execute="@this" render="panelGroup" listener="#{aboutBean.refresh}"/>
                        </h:selectOneRadio>
                        <h:button value="#{aboutBean.test}"/>
                    </h:panelGroup>
                </p:tab>
                <p:tab id="review" title="Review">     
                    <h:panelGroup layout="span">
                        <h:outputLabel value="#{reviewBean.review}"/>
                    </h:panelGroup> 
                    <h:panelGroup layout="block">                          
                        <ui:repeat value="#{reviewBean.values}" var="value">
                            <h:outputLabel value="#{value}"/>
                        </ui:repeat>                      
                    </h:panelGroup>                   
                </p:tab>
            </p:tabView>

        </h:form>
    </h:body>
</html>
`

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
