### ISSUE TITLE
DatePicker: internationalisation ( very minor bug)

### ISSUE THREAD

**Issue by Lb-lea** [TheCoder4eu/BootsFaces-OSP#1064]
The titles for the "previous month" and "next month" buttons must be hard coded so they do not follow the local. It is not very crucial since the date picker are being skipped when navigating in an accessible way but if you find an easy fix it will look more professional for foreign developers not to have some English parts on their sites.

Thank you for your work.

**Comment by geopossachs** [comment]
i found the strings in the bootstrap-datetimepicker.min.js on https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/mavenResources/META-INF/resources/bsf/js/bootstrap-datetimepicker.min.js

The Names in the jQuery Widget are nextText and prevText 
https://api.jqueryui.com/datepicker/#option-prevText

But in the bootstrap-datetimepicker.min.js is a tooltip with  
prevMonth; nextMonth; prevYear; nextYear; ...

But where are the sources for the bootstrap-datetimepicker.min.js?
It is this externel project https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js?

**Comment by stephanrauh** [comment]
@geopossachs Yes, as far as I remember, it's the Eosasdan project.

**Comment by stephanrauh** [comment]
Today, the author of the datetimepicker has resumed their work. Maybe the next version solves the bug.

**Comment by geopossachs** [comment]
the last release today of Eonasdan/bootstrap-datetimepicker was on the 28 Feb 2017

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
