### ISSUE TITLE
iconAwesome problem in 1.4.1

### ISSUE THREAD

**Issue by fdzaebel** [TheCoder4eu/BootsFaces-OSP#1066]
Hello,

I just recognized that there is a problem with iconAwesome icons in version 1.4.1:

I have some buttons with iconAwesome icons and a commandButton. When the commandButton is pressed I call the backing bean and then I reload the page. After the page gets reloaded the icons of the buttons are missing.

Here is an example code:
```xml
<b:form>    
  <b:panelGrid id="grid" colSpans="1,1,10" size="sm"> 
    <b:commandButton id="save" value="Save" icon="save" 
                ajax="false" action="#{depositBean.doSave()}" look="success" width="100%" />
    <b:button id="reset" value="Reset" width="100%" href="..." look="default" 
                iconAwesome="recycle" />          
    <b:button id="delete" value="Delete" look="danger" width="100%" 
                onclick="$('.modalPseudoClass').modal()" iconAwesome="trash" />	 		
   </b:panelGrid>
</b:form>
```

```java
public String doSave() {
 ...
FacesMessages.info("Data updated!", "Your data are now uptodate.");
return "#";
}
```

First load of the page...everything is ok...
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46503230/53688892-34d92b80-3d4b-11e9-86db-a777099a92b0.png">

Reload after pressing the save commandButton...
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46503230/53688898-43bfde00-3d4b-11e9-9ec7-fc8e2d843278.png">

With version 1.3.0 I did not have this problem.

Could you please take a look a this?

Thanks!

Frank

**Comment by geopossachs** [comment]
I can adjust the error. He comes only when using iconAwesome. The CSS resources are missing in the response to the POST request. If you manually add these CSS resources statically, the icons will appear. I suspect the bug in the AddResourcesListener, but I was not able to find it exactly.

**Comment by stephanrauh** [comment]
The bug looks a bit convoluted. The CSS resource seems to be removed after running the `AddResourcesListener`. That happens even if I add the CSS resource every time.

For now, I recommend adding the CSS file to the XHTML file.

**Comment by geopossachs** [comment]
@stephanrauh I think I found a solution but I do not understand why

AddResourcesListener. addResourceIfNecessary

				// remove old
				root.removeComponentResource(context, c, "head");

				// add new 
				root.addComponentResource(context, output, "head");

The existing instance c of InternalFALink has wrong flags
I replace the existing c with the other instance of InternalFALink output and it works

https://github.com/TheCoder4eu/BootsFaces-OSP/tree/issues/1066

**Comment by stephanrauh** [comment]
@geopossachs I've tried to send you an email, but your spam filter doesn't like me. 

Gut feeling: just go ahead, probably the change you've suggested works. But I don't have any idea why it works, too. :)
