### ISSUE TITLE
Ajax Update for SelectBooleanCheckbox is wrong

### ISSUE THREAD

**Issue by ElectroStar** [TheCoder4eu/BootsFaces-OSP#1069]
In Bootsfaces 1.4.1:
When you use a selectBooleanCheckbox with the a fixed Value (value="true") it isn't fix.
When changing the Value and trigger an ajax-request with onchange="ajax:controller.function())" update="@parent" the response will have the "new" value (checked if it was unchecked before the change OR unchecked if it was checked before the change).

According to the standard h:selectBooleanCheckbox this behaviour is an error.

```xml
<h:panelGroup id="blup">
    <b:selectBooleanCheckbox value="true" caption="Test" update="@parent" ajax="true" onchange="ajax:testController.action()" /> 
    <!-- The Checked Value will change and isnt fix to true -->
</h:panelGroup>
```

```xml
<h:panelGroup id="blup">
  <h:selectBooleanCheckbox value="true">
    <f:ajax render="blup" event="change" listener="#{testController.action()}"/>  
  </h:selectBooleanCheckbox> <!-- The Checked Value is fix as it should be -->
</h:panelGroup>
```

**Comment by stephanrauh** [comment]
Strange bug. I can see how and when it hurts.

What I can't confirm is that the checkbox works any different with standard JSF. I've tried both Mojarra and PrimeFaces, and they show the same bug.

**Comment by stephanrauh** [comment]
I've also tested Liberty Profile, which uses MyFaces. Same result.

**Comment by stephanrauh** [comment]
I'm closing the ticket now because I don't see any point in fixing a bug when the bug fix makes BootsFaces differently than any other JSF framework. I'm just confused why the `h:selectBooleanCheckbox` behaves different on your machine.
