### ISSUE TITLE
ReferenceError: "jQuery is not defined" is thrown by tooltip.js in pages without <b:container>

### ISSUE THREAD

**Issue by yersan** [TheCoder4eu/BootsFaces-OSP#107]
Hi,

If the xhtml page doesn't contain a <b:container> tag, a java script error is thrown by tooltip.js.
Is `<b:container>` tag mandatory for all bootsFaces pages ?

For example, using this page:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
              <b:inputText value="dummy" />
        </h:form>
    </h:body>
</html>
```

**Comment by stephanrauh** [comment]
Yes, that's a side-effect of my simplistic implementation. I hope to find a way to fix it, but as for now, there's tooltip-related code in every page.

**Comment by stephanrauh** [comment]
I tested the page again. No there's no error, and no reference to tooltip.js. Our latest work on tooltips and dependencies seems to have solved this bug.
