### ISSUE TITLE
b:dropMenu with elements from collection

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#1070]
Hi
I use navBars and dropMenus for the main navigation in my app. I am facing the following problem:
I have one place where I have some menu items rendered dynamically. This works with c:set but not with ui:repeat. While I understand why it works with c:set, I wonder if there is some JSF (not JSTL) way to have the menu items from a collection...

**Comment by stephanrauh** [comment]
`<ui:repeat>` adds another container. The `<b: navBar>` assumes to contain things like `<b:navItem>`. So it's confused by the additional container.

Here's the catch: I believe I've implemented a solution for this problem some time ago. Chances are I didn't catch every use-case. Can you send me a sketch of a reproducer, please?

**Comment by stephanrauh** [comment]
Closing the ticket after waiting for the answer for several months.
