### ISSUE TITLE
b:openstreetmap loads extremely slow in jsf application

### ISSUE THREAD

**Issue by Alina-PANG** [TheCoder4eu/BootsFaces-OSP#1071]
I writing bootfaces with jsf 2.2 and Netbeans. I tried the example code:
```     
<b:openStreetMap width="100%" height="500px"
        center="40,-5" marker="40,-5"
        popupMsg="Museo de la evolución humana, Burgos, Spain."
        zoom="14"
        urlTemplate="https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png" />
```
It takes around 2 minutes for the map to load and the loaded map does not have any buttons for zooming. 

![Screen Shot 2019-04-10 at 2 18 42 PM](https://user-images.githubusercontent.com/21374587/55856085-d39f4600-5b9b-11e9-90ac-450d52845bf5.png)

Can I know what is the possible problem with that? I am using BootsFaces 1.4.1, Bootstrap 1.0.10 and PrimeFaces 6.2 as my front-end libraries. All my JSF files are written in .xhtml.

**Comment by stephanrauh** [comment]
Strange. If you've got a decent internet connection, the map should load within seconds. Actually, using DSL I don't even notice the delay.

Can you check both the console and the network tab in your browsers F12 tool? I.e. the debugger tools  you open by hitting the F12 key on Windows or CMD+I on OSX?

**Comment by stephanrauh** [comment]
@Alina-PANG Ping! Is this still an issue to you? Did you solve it? Or did you find another way get your job done?

Until I hear from you, I'll close this ticket. However, I keep listening to it, so if I hear from you, I can re-open the ticket.
