### ISSUE TITLE
dateTimePicker disabledDays issues

### ISSUE THREAD

**Issue by kuytsce** [TheCoder4eu/BootsFaces-OSP#1078]
I guess this would come under User Support.

I'm using Bootsfaces for the first time and I've got the dateTimePicker component working however I need to disable weekends and certain holidays so they can't be selected.

I've tried using the week-days-disabled attribute to disable weekends however this isn't working and all days are still available to be selected.

```
<b:dateTimePicker id="datePicker" value="#{bean.date}" show-time="false" format="DD/MM/YYYY" week-days-disabled="[0,6]" />
```

In addition I've tried using the disabled-days/enabled-days attributes to disable certain holidays however your documentation advises that the attribute accepts an array of date, moment, string. I can work out what to enter for date and moment but I don't know what string would be required? Can you advise, preferably with an example that would be great. I can't find any examples online.

Thanks

**Comment by stephanrauh** [comment]
It seems we've simply forgotten to implement `week-days-disabled`. Now it's there.

**Comment by stephanrauh** [comment]
The "String" refers to a JavaScript `string`. Such as `disabledDates="'08/03/2019'"`. I've added an example to the documentation.
