### ISSUE TITLE
b:inputTags broken on IE

### ISSUE THREAD

**Issue by jaberu** [TheCoder4eu/BootsFaces-OSP#1080]
I'm trying to use b:inputText with tags to edit mulitple labels. However the component is not rendered on IE (but for Chrome). On IE 11 I see an error in JS Console LOG:
![image](https://user-images.githubusercontent.com/9799860/59032122-cafa8180-8865-11e9-9d91-121f489af487.png)
I'm using bootsfaces 1.4.1

**Comment by jaberu** [comment]
I had the same issue in another context
The solution on stackoverflow:
https://stackoverflow.com/a/30867255
might work here as well.

**Comment by stephanrauh** [comment]
Should it be so easy? My approach was to use all the polyfills from my Angular projects.

**Comment by stephanrauh** [comment]
I didn't find the source of the Angular polyfills yet. So I've taken the polyfills file from one of my Angular projects. Unzip it, copy it to your project. Do not use the resources folder, but the regular src/main/webapps folder. Assuming you're putting it into the root folder, import it like so in your XHTML file:

```html
<script src="polyfills-es5.js" nomodule></script>
```

Notice the `nomodule` bit: it ensures IE11 and below load the script, but no other browser.

I'll close the ticket now. But don't hesitate to reach out to us if that doesn't work - we're still listening to this ticket, even after closing it! 

[polyfills-es5.js.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/3478519/polyfills-es5.js.zip)
