### ISSUE TITLE
illegal-access, jdk-11, jsr376, on jboss wildfly 17

### ISSUE THREAD

**Issue by StephenDoody** [TheCoder4eu/BootsFaces-OSP#1089]

**Comment by StephenDoody** [comment]
I was experimenting with bootsfaces-1.4.1 on wildfly 17 , received:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.as.server.deployment.reflect.ClassReflectionIndex (jar:file:/C:/Wildfly/wildfly-17.0.1.Final/modules/system/layers/base/org/jboss/as/server/main/wildfly-server-9.0.2.Final.jar!/) to field java.util.Date.gcal

For details, please see the JBoss forum post:  https://developer.jboss.org/message/990456?et=watches.email.thread#990456

The combination of the bootsfaces  META-INF/faces-config.xml
<managed-bean>
        <description>
            <![CDATA[
            This makes an instance of <code>java.util.Date</code> as current datetime available by
            <code>#{now}</code>.
            ]]>
        </description>
        <managed-bean-name>now</managed-bean-name>
        <managed-bean-class>java.util.Date</managed-bean-class>
        <managed-bean-scope>request</managed-bean-scope>
    </managed-bean>

Causes the JBoss server deployment to attempt to treat java.util.Date as a managed bean, which then causes java-11 to issue illegal-access warnings.

Thanks to JBoss developer, Jaikiran Pai for the root cause investigation support.

My $0.1
 Reconsider #Now use of a long deprecated Date class?
 Update bootsfaces to a JPMS/JDK-11 ready version, and test with Wildfly.
 Publish some doc/info on intended future support for JPMS/jdk-11, I couldn't find anything relevant.

Kind regards

Stephen Doody
sd AT acm DOT org

**Comment by stephanrauh** [comment]
@StephenDoody Please have a look at the current developer version 1.4.2-SNAPSHOT. I've removed `#{now}` yesterday because OmniFaces provides the same bean, only better.

**Comment by StephenDoody** [comment]
> @StephenDoody Please have a look at the current developer version 1.4.2-SNAPSHOT. I've removed `#{now}` yesterday because OmniFaces provides the same bean, only better.

@stephanrauh   Please verify which maven repo holds that published artifact?  could not locate it, got:  Could not find artifact net.bootsfaces:bootsfaces:pom:1.4.2-SNAPSHOT in Maven Central (https://repo1.maven.org/maven2/)

`            <dependency>
                <groupId>net.bootsfaces</groupId>
                <artifactId>bootsfaces</artifactId>
                <version>1.4.2-SNAPSHOT</version>
            </dependency>`

**Comment by stephanrauh** [comment]
It's in the snapshot directory of Maven Central. Try this one:
```xml
	<repositories>
		<repository>
			<id>central</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

**Comment by StephenDoody** [comment]
@stephanrauh
Yep, that did it, no illegal access warnings deploying to Wildfly17 running on AWS Corretto OpenJDK-11

Please advise when the change becomes permanent.

Thank you for the prompt response.  

Kind Regards
Steve

**Comment by geopossachs** [comment]
We solved the issue by "remove undocumented bean #{now}" #1086
