### ISSUE TITLE
Upgrade Bootstrap to v3.4.1 and Bootswatch themes to v3.4.1+1 and test.

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#1093]
Upgrade Bootstrap to v3.4.1 and Bootswatch themes to v3.4.1+1 and test.

**Comment by mtvweb** [comment]
With 3.4.1 the filter field of the data table looks strange. (But seems to be a DataTables problem)
Even the b:selectOneMenu text is not positioned well. At least with field-size="sm"

**Comment by geopossachs** [comment]
hello @mtvweb that's wonderful that you want to support the project.

i would like to review your changes. It is possible to shorten the pull request to the central changes here? (rebase; chery pick; ...)

**Comment by geopossachs** [comment]
> Even the b:selectOneMenu text is not positioned well. At least with field-size="sm"
#1097

**Comment by stephanrauh** [comment]
@mtvweb I  don't see any problems with the datatable. I've just pushed the update to Boostrap 3.4.1, and I've also published a new snapshot on Maven Central. Can you have a look if the glitches you've reported are still there?

**Comment by mtvweb** [comment]
Still there. Just downloaded bootsfaces-1.5.0-20200429.204938-1.jar and modified selectOneMenu.xhtml from BootfacesWeb.xml second b:selectOneMenu to 

`<b:selectOneMenu value="#{selectOneMenuBean.type}" colMd="2" required="true" label="Select your car's type:" labelColMd="2" styleClass="car-class" field-size="sm">`

Attached Screenshots from MacOS Safari, Chrome, Firefox
<img width="463" alt="safari" src="https://user-images.githubusercontent.com/2180107/80649517-80cc5100-8a72-11ea-9b44-b274a513b364.png">
<img width="386" alt="chrome" src="https://user-images.githubusercontent.com/2180107/80649527-845fd800-8a72-11ea-8383-c1b541973d45.png">
<img width="598" alt="firefox" src="https://user-images.githubusercontent.com/2180107/80649535-875ac880-8a72-11ea-8120-6628f56da2f5.png">

**Comment by mtvweb** [comment]
I think Datatables problem is already fixed in master by upgrading datatables.net to a newer version by @geopossachs

**Comment by stephanrauh** [comment]
We've finally managed to solve the showcase bug. Now the datatable looks mostly OK, apart from the first dropdown. Does anyone have an idea why this happens?

**Comment by mtvweb** [comment]
Is the current version only at your showcase?

The dropdown doesn't reference an entry in the data tables.css
I can see a difference in the header

Your header:
`
/*
 * This combined file was created by the DataTables downloader builder:
 *   https://datatables.net/download
 *
 * To rebuild or modify this file with the latest versions of the included
 * software please visit:
 *   https://datatables.net/download/#dt/jszip-2.5.0/dt-1.10.18/af-2.3.3/b-1.5.6/b-colvis-1.5.6/b-html5-1.5.6/b-print-1.5.6/fc-3.2.5/fh-3.1.4/r-2.2.2/rg-1.1.0/rr-1.2.4/sc-2.0.0/sl-1.3.0
 *
 * Included libraries:
 *  JSZip 2.5.0, DataTables 1.10.18, AutoFill 2.3.3, Buttons 1.5.6, Column visibility 1.5.6, HTML5 export 1.5.6, Print view 1.5.6, FixedColumns 3.2.5, FixedHeader 3.1.4, Responsive 2.2.2, RowGroup 1.1.0, RowReorder 1.2.4, Scroller 2.0.0, Select 1.3.0
 */
`

Header at https://bootsfaces.sebsoftware.de
`/*
 * This combined file was created by the DataTables downloader builder:
 *   https://datatables.net/download
 *
 * To rebuild or modify this file with the latest versions of the included
 * software please visit:
 *   https://datatables.net/download/#bs/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/b-print-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/r-2.2.3/rg-1.1.1/rr-1.2.6/sc-2.0.1/sl-1.3.1
 *
 * Included libraries:
 *  JSZip 2.5.0, DataTables 1.10.20, AutoFill 2.3.4, Buttons 1.6.1, Column visibility 1.6.1, HTML5 export 1.6.1, Print view 1.6.1, ColReorder 1.5.2, FixedColumns 3.3.0, FixedHeader 3.1.6, Responsive 2.2.3, RowGroup 1.1.1, RowReorder 1.2.6, Scroller 2.0.1, Select 1.3.1
 */`

**Comment by mtvweb** [comment]
Just checked out your current GitHub repository, and build it. Everything looks fine.
