### ISSUE TITLE
selectOneMenu visual problem since 1.4.2

### ISSUE THREAD

**Issue by fdzaebel** [TheCoder4eu/BootsFaces-OSP#1097]
Hello together,

since version 1.4.2 of BootsFaces the b:selectOneMenu component is not good readable on Safari browsers. Please see an attached example picture.
<img width="201" alt="Bildschirmfoto 2019-10-03 um 18 08 50" src="https://user-images.githubusercontent.com/46503230/66144294-dfc70600-e608-11e9-93c1-f17bf844cb00.png">

With version 1.4.1 everything was fine.

It would be great if anybody could give me a quick workaround for this.

Thanks a lot!

**Comment by geopossachs** [comment]
Hello, @fdzaebel  thank you for your feedback. 

I believe the bug was coming with the fix for #1090 
You can take a look at the CSS of 'select' and change it. 
If you find a solution we are interested in it too

**Comment by fdzaebel** [comment]
> You can take a look at the CSS of 'select' and change it.
> If you find a solution we are interested in it too

Do you mean this select?

```
select {
        -webkit-appearance: none;

        -moz-appearance: none;

        appearance: none;

        background: url(dropdown.ico) right / 20px no-repeat #fff;

        padding-right: 20px;
}
```

**Comment by geopossachs** [comment]
yes, i mean this section

**Comment by fdzaebel** [comment]
I Am very sorry but I am not a CSS specialist.

But I tried around with BootsFaces "select2=true" option and can say that using this option everything looks ok in IE, Firefox and Safari. 
<img width="201" alt="safari" src="https://user-images.githubusercontent.com/46503230/66149440-6680e080-e613-11e9-90b9-dfd331e29fca.png">
<img width="201" alt="ie" src="https://user-images.githubusercontent.com/46503230/66149441-67197700-e613-11e9-8e69-8772ef7bf176.png">
<img width="201" alt="ff" src="https://user-images.githubusercontent.com/46503230/66149442-67197700-e613-11e9-8dbb-6f3669a75623.png">


Does this help?

**Comment by sebsoftware** [comment]
Upgrading to Bootswatch does not fix this issue.
After setting -webkit-appearance to none the line height is set to 30px by the core.css for a "sm" sized select i.E.. With -webkit-appearance set to the default "menu list-button" it works fine. Another way would be modifying the line-height to individual values in bsf.css.

**Comment by stephanrauh** [comment]
It seems updating to Bootstrap 3.4.1 fixes the problem. Can you please verify if it works on the source I've just pushed to GitHub?
