### ISSUE TITLE
InputText mask library not included with dynamic mask

### ISSUE THREAD

**Issue by stjheitc** [TheCoder4eu/BootsFaces-OSP#1098]
If the mask is added as a constant it is working, well, but if the mask is taken i.E. from a message than the "js/jquery.inputmask.bundle.min.js" script will not be included.

This works:
`<b:inputText	value="#{schedules.startDate }"
label="${ _msg.startDate }" mask="dd.mm.yyyy"
render-label="true"
span="6" maxlength="20" tabindex="4" required="true" />`

This doesn't work, it it is the only field with a mask within xhtml:

`<b:inputText	value="#{schedules.startDate }"
label="${ _msg.startDate }" mask="${ _common.longDateMask }"
render-label="true"
span="6" maxlength="20" tabindex="4" required="true" />`

**Comment by geopossachs** [comment]
cool that you have found a solution. i would like to review your changes. Is it possible to shorten the pull request to the central changes?

**Comment by mtvweb** [comment]
Any component that uses conditional includes, i.E. commandButton like this.

``` java
public void setIconAwesome(String _iconAwesome) {
   AddResourcesListener.setNeedsFontsAwesome(this);
  super.setIconAwesome(_iconAwesome);
}
```

but these are not called, if a ValueExpression is used, i.E. iconAwesone="#{ bean.iconName }"
instead setValueExpression is called, with the expression. In these cases I include the corresponding resources, by the property name.

``` java
@Override
public void setValueExpression(String name, ValueExpression binding) {
	name = BsfUtils.snakeCaseToCamelCase(name);
	super.setValueExpression(name, binding);
		
	if ("iconAwesome".equals(name))
		AddResourcesListener.setNeedsFontsAwesome(this);
	else if ("iconBrand".equals(name) || "iconLight".equals(name) || "iconRegular".equals(name) || "iconSolid".equals(name))
		AddResourcesListener.setFontAwesomeVersion(5, this);
}
```

Even if the final value may be null, but at least the includes are rendered, if it may be necessary for a non empty value. The same is for fontAwesome  5 properties, or the mask, tag and typeahead properties of the input text element.

> Is it possible to shorten the pull request to the central changes?

Forget about the maven resources in the pull request they are generated by the build
