### ISSUE TITLE
DataTableRenderer:encodeEnd wrong logic

### ISSUE THREAD

**Issue by TheOneSV** [TheCoder4eu/BootsFaces-OSP#1101]
There is a problem in the DataTableRenderer::encodeEnd function

int start = customOptions.indexOf("language" + "language".length());

Should be

int start = customOptions.indexOf("language") + "language".length();

**Comment by vsvetoslavov** [comment]
To clarify a bit - this causes the language url to be injected after the first `{` occurrence. This breaks custom options quite aggressively.

**Comment by stephanrauh** [comment]
Thanks for pointing this out and for providing a PR!
