### ISSUE TITLE
DataTables in v. 1.4.2 are not with bootstrap theme

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#1104]
In BootsFaces version 1.4.2 the DataTable does not use the bootstrap theme from datatables.net. Is there any reason for that? Seems like a bit of downgrade...

**Comment by stephanrauh** [comment]
I just noticed that in the showcase, too. Whatever has happened, it wasn't intended!

**Comment by stephanrauh** [comment]
It seem we've fixed the bug some time ago, but it doesn't show in the showcase yet. We're investigating what's wrong. This may take some time.

**Comment by frankyhoffmann** [comment]
join.skype.com/ltcvXRujoEed

**Comment by stephanrauh** [comment]
We've managed to repair the showcase tonight. There's a minor layout glitch of the datatable, but that's covered by another ticket, so I'll close this ticket now.

**Comment by stephanrauh** [comment]
The display glitch is a false positive. It has been caused by the cache of my browser.
