### ISSUE TITLE
b:remoteCommand snake-case "action-listener" is not working

### ISSUE THREAD

**Issue by sebsoftware** [TheCoder4eu/BootsFaces-OSP#1105]
JSF treats snake-case property "action-listener" as a standard value, passed to setValueExpression. Due to the fact that Mojarra expect action-listener as 'methodBindingActionListener'" with type MethodBinding inside state properties it is not recognised by jsf.

The actionListener attribute, which is working, is handled special by applyRule from ActionSourceRule, which only handles camelCase properties "action" and "actionListener".

I don't think it is possible to fix this easily, so maybe it's the best to fix the documentation for it, and remove "action-listener" from the properties list.

**Comment by geopossachs** [comment]
@TheCoder4eu is there a possibility that all action-listener will not work? I tested comandButton with the same result

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
