### ISSUE TITLE
b:selectOne render incorrect

### ISSUE THREAD

**Issue by ibrajim19** [TheCoder4eu/BootsFaces-OSP#1107]
I´m using b:selectOne inside a b:panel in b:modal, but it renders incorrect 

![image](https://user-images.githubusercontent.com/49858714/69752881-dd1ff300-1117-11ea-993c-e11bf3375c5b.png)

I´m my code it's something like this

```xml
<b:modal>
    <b:panel>
          <b:selectOneMenu style="width: 100% !important">
               <f:selectItem  />
                <f:selectItem  />
          </b:selectOneMenu >
    </b:panel>
<b:modal>
```

I don't apply any css to this component and  why is it rendered in that form with that big white box?

**Comment by stephanrauh** [comment]
On my machine, it looks a bit different:

Firefox:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3045767/69761640-4596c080-1168-11ea-9b84-e61bc244e112.png">

Chrome:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3045767/69761652-4d566500-1168-11ea-81d0-912e551218f8.png">

Maybe you've forgotten to add the CSS file of the theme? https://showcase.bootsfaces.net/miscellaneous/Configuration.jsf#themes

I've added a demo to the BootsFaces showcase. I recomment you clone https://github.com/TheCoder4eu/BootsFacesWeb.git, import it as a Maven project, start the application server, and navigate to http://localhost:8080/BootsFacesWeb/issues/issue1107.jsf#. Probably you need to edit the pom.xml - it uses the current development version of BootsFaces, which isn't available on Maven Central yet.

Does the demo still show the error? If not, you can compare the showcase project to your projekt to find the error.

**Comment by stephanrauh** [comment]
Oh, and please tell us if you've solved the error. Especially if you've managed to solve it. Otherwise we'll never know when to close the ticket!

¡Gracias!,
Stephan

**Comment by ibrajim19** [comment]
Hi I think this could be a bug because I run in another machine and works correctly then I open the same page in my pc  in edge, firefox, IE(I was using Chrome) and render properly, I clean all cookies, cache and data from Chrome but the b:selectOne render incorrectly

![image](https://user-images.githubusercontent.com/49858714/69878687-39efea80-128b-11ea-8d9d-3016085f7a9e.png)

**Comment by stephanrauh** [comment]
I can't reproduce the bug. Chances are it has been caused by third-party CSS code.
