### ISSUE TITLE
504 Gateway Time-out nginx 

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#1108]
Can someone check it? I can't access the showcase anymore

**Comment by geopossachs** [comment]
@stephanrauh can you reboot the app please

**Comment by stephanrauh** [comment]
@TheCoder4eu Ping! :)

**Comment by geopossachs** [comment]
@TheCoder4eu the vm for https://showcase.bootsfaces.net/ ist down :-(

**Comment by geopossachs** [comment]
@stephanrauh can you check the VM?

**Comment by stephanrauh** [comment]
I've restarted the server, but it didn't help much. Now it's a 502 error. I'll ask Riccardo for help.

**Comment by stephanrauh** [comment]
Oops - it seems I was simply to impatient. The server is up and running again. Sorry for the inconvenience!
