### ISSUE TITLE
selectBooleanCheckbox is loosing its value

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#111]
If I have selectBooleanCheckbox with true value on form (disabled at first), and then update the form, checkbox is loosing it's value. With standard jsf selectBooleanCheckbox all works OK.

I've already sent test application to @stephanrauh (just creating issue on github to know about it)

**Comment by stephanrauh** [comment]
Finally managed to reproduce the bug.

**Comment by stephanrauh** [comment]
As Lukas correctly reported, it's a bug that occurs when a checkbox is disabled. In this case, the browser doesn't send the value. Unfortunately, BootsFaces didn't check the disabled state before updating the value. I'm going to fix this in the next version (0.7.0++).

**Comment by stephanrauh** [comment]
Done.
