### ISSUE TITLE
Canvas event.getX() and event.getY() for onclicked() bound to underlying ManagedBean

### ISSUE THREAD

**Issue by cdberkstresser** [TheCoder4eu/BootsFaces-OSP#1112]
Is there any possibility of capturing an onclick event in the canvas class that can be bound to the underlying JSF ManagedBean with an x and y property denoting the location of where the canvas was clicked?

**Comment by geopossachs** [comment]
Hallo @cdberkstresser 
You can try at first with jsf pass-through to add js callback function for a canvas event. 
A second you can call from this js callback function a <b:remoteCommand>

**Comment by cdberkstresser** [comment]
Thanks for the reply!  remoteCommand was the missing piece of the puzzle.  I finally got a clickable canvas!  
https://cberkstresser.name:8443/QuantumWeb/faces/QuantumCircuitDesigner.xhtml
