### ISSUE TITLE
b:InputText label is not rendering while using facet append inside it.

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#1114]
The main problem is the z-index of input-group that is generated when I use the append. 

Input without append
![image](https://user-images.githubusercontent.com/17599235/71530113-f65ac180-28c6-11ea-8a0b-5560538e11cd.png)

Input with append
![image](https://user-images.githubusercontent.com/17599235/71530123-02df1a00-28c7-11ea-989d-1174a05dd56a.png)

How to change the z-index in label inside inputtext?

**Comment by geopossachs** [comment]
Hello @atsoares, it is possible that you post a JSF example and a screenshot of the error in the browser here so that we can understand the case

**Comment by atsoares** [comment]
Hi @geopossachs , thanks for your help but I already gave up of this approach, did solve it using columns without the facet append.

**Comment by geopossachs** [comment]
![grafik](https://user-images.githubusercontent.com/10324450/84603197-be533500-ae8c-11ea-8f64-b9ea4485e987.png)

```
            <b:formGroup>
                <b:inputText id="bInputText" 
                             value="#{myBean.myItem5}"
                             required="true" 
                             requiredMessage="please fill out the select field e"
                             immediate="true" 
                             label="Show for 1114"
                             >
                    <f:facet name="prepend">
                        <h:outputText value="$" />
                    </f:facet>
                    <f:facet name="append">
                        <h:outputText value=".00" />
                    </f:facet>
                </b:inputText>                
                <b:message for="bInputText" />
            </b:formGroup>
```
