### ISSUE TITLE
Modal with button doesn't execute action

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#1115]
I'm trying to use the google reCaptcha like [this](https://developers.google.com/recaptcha/docs/invisible#automatically_bind_the_challenge_to_a_button) inside a modal, it works normally in a normal page but I'm stuck with this problem around modal + ajax... 

Tried everything but the button acts like a submit and ignores the data-callback function...

**Comment by stephanrauh** [comment]
@atsoares Did you manage to use the captcha in a modal?

**Comment by atsoares** [comment]
@stephanrauh yeah, I was using the v2 version of recaptcha bc it was the same on the non-responsive site but used v3 instead and worked fine!

**Comment by stephanrauh** [comment]
Ah, I see. It's great to learn you've found the cause of the problem. As far as I can tell, that was a difficult problem. The solution looks simple, but that's often the case with difficult puzzles!

BTW, I'm also sorry we're not as responsive as we used to be. Anybody who's reading this: BootsFaces is looking for new contributors. We're ready to help you, so don't worry about the complexity. Interested?
