### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by NeothisYoko** [TheCoder4eu/BootsFaces-OSP#1116]
Hello,

I tried many times to access the documentation but it's impossible to join it.
![image](https://user-images.githubusercontent.com/22350440/72217499-ebdb3180-352e-11ea-8712-ab9d265e41e9.png)
![image](https://user-images.githubusercontent.com/22350440/72217471-7707f780-352e-11ea-8547-bcb3c7ae6be4.png)
I know that's not a real issue on the code but very it's very difficult to work.

**Comment by geopossachs** [comment]
@TheCoder4eu can you restart the app please? And can i get access to the ci job / runtime?

**Comment by stephanrauh** [comment]
We'll restart the server later this evening. Sorry for the inconvenience!

**Comment by NeothisYoko** [comment]
Thanks you!!!
