### ISSUE TITLE
Could you help how to use bootstrap pagination bar

### ISSUE THREAD

**Issue by anemdhana** [TheCoder4eu/BootsFaces-OSP#112]
I would say the attributes to support are, action, rowsPerPage, totalRows

**Comment by stephanrauh** [comment]
Would you mind to elaborate?

I can only guess you'd like us to implement a new BootsFaces component, which implements http://getbootstrap.com/components/#pagination. Is this correct?

**Comment by xystra** [comment]
everything is already available for you to do pagination with jsf and bootsfaces. h:datatable already has a rows per page setting and you already have the total rows in your backing bean.

for example I have a base backing bean that I extend when I need to have a datatable to manage
```java
public class DatatableBaseBean
   implements Serializable
{
   private static final long serialVersionUID = 1L;

   private HtmlDataTable pagedDataTable;

   public void pageFirst()
   {
      pagedDataTable.setFirst(0);
      log(Integer.valueOf(pagedDataTable.getFirst()));
   }

   public void pagePrevious()
   {
      pagedDataTable.setFirst(pagedDataTable.getFirst() - pagedDataTable.getRows());
      log(Integer.valueOf(pagedDataTable.getFirst()));
   }

   public void pageNext()
   {
      pagedDataTable.setFirst(pagedDataTable.getFirst() + pagedDataTable.getRows());
      log(Integer.valueOf(pagedDataTable.getFirst()));
   }
   
   public void viewPage(final int page)
   {
      pagedDataTable.setFirst((page - 1) * pagedDataTable.getRows());
      log(Integer.valueOf(pagedDataTable.getFirst()));
   }

   public void pageLast()
   {
      final int count = pagedDataTable.getRowCount();
      final int rows = pagedDataTable.getRows();
      
      if (rows > 0)
      {
         pagedDataTable.setFirst(count - ((count % rows != 0) ? count % rows : rows));
         log(Integer.valueOf(pagedDataTable.getFirst()));
      }
      else
      {
         pageFirst();
      }
   }
   
   public int getCurrentPage()
   {
       final int rows = pagedDataTable.getRows();
       final int first = pagedDataTable.getFirst();
       final int count = pagedDataTable.getRowCount();
       
       if (rows > 0)
       {
          return (count / rows) - ((count - first) / rows) + 1;
       }
       return 0;
   }

   public int getTotalPages()
   {
      final int rows = pagedDataTable.getRows();
      final int count = pagedDataTable.getRowCount();

      if (rows > 0)
      {
         return (count / rows) + ((count % rows != 0) ? 1 : 0);
      }
      return 0;
   }
   
   public void setPagedDataTable(final HtmlDataTable pagedDataTable)
   {
       this.pagedDataTable = pagedDataTable;
   }
   
   public HtmlDataTable getPagedDataTable()
   {
      return pagedDataTable;
   }
}
```

then in my template i bind the datatable to my bean and configure a pagination section, I dynamically add 1 or 2 pages prev and next as they are available, just to show you the flexibility:
```html
<h:form>
					<h:dataTable binding="#{bean.pagedDataTable}" var="map" value="#{bean.mappedCodes}" styleClass="table table-sorting table-hover table-striped table-bordered datatable" rows="10">
						<h:column headerClass="tableIcon">
							<f:facet name="header"><b:iconAwesome name="pencil-square-o" size="lg"/></f:facet>
							<h:commandLink action="#{bean.onRowEdit(map)}" rendered="#{not map.enabled}" styleClass="text-warning"><b:iconAwesome name="pencil-square-o" size="lg"/></h:commandLink>
							<h:commandLink action="#{bean.onRowSaved(map)}" rendered="#{map.enabled}" styleClass="text-success"><b:iconAwesome name="floppy-o" size="lg"/></h:commandLink>
						</h:column>
						
						<h:column headerClass="someClass">
							<f:facet name="header"><h:outputText value="Some Value"/></f:facet>
							<h:outputText value="#{map.importCode}" rendered="#{not map.enabled}"/>
							<b:inputText value="#{map.importCode}" style="width:100%; background-color: #fff;" rendered="#{map.enabled}"/>
						</h:column>
						
						<h:column headerClass="someOtherClass">
							<f:facet name="header"><h:outputText value="Another Value"/></f:facet>
							<h:outputText value="#{map.description}" rendered="#{not map.enabled}"/>
							<b:selectOneMenu value="#{map.code}" style="width:100%; background-color: #fff;" rendered="#{map.enabled}">
								<f:selectItems value="#{bean.commonData}" var="common" itemLabel="#{common.description}" itemValue="#{common.code}" />
							</b:selectOneMenu>
						</h:column>						
					</h:dataTable>
					
					<!-- Pagination -->
					<div class="row">
                       	<b:container rendered="#{bean.pagedDataTable.rowCount > 0}" styleClass="col-md-12" style="margin-top: -25px;">
                        	<ul class="pagination pull-right">
								<li>
									<h:commandLink action="#{bean.pageFirst}" disabled="#{bean.pagedDataTable.first == 0}">
										<b:iconAwesome name="angle-double-left"/>
									</h:commandLink>
								</li>
								<li>
									<h:commandLink action="#{bean.pagePrevious}" disabled="#{bean.currentPage - 1 == 0}">
										<b:iconAwesome name="angle-left"/>
									</h:commandLink>
								</li>

								<c:if test="#{bean.currentPage - 2 gt 0}">
									<li><h:commandLink value="#{bean.currentPage - 2}" action="#{bean.viewPage(bean.currentPage - 2)}" /></li>
								</c:if>

								<c:if test="#{bean.currentPage - 1 gt 0}">
									<li><h:commandLink value="#{bean.currentPage - 1}" action="#{bean.viewPage(bean.currentPage - 1)}" /></li>
								</c:if>
								
								<li class="active"><h:commandLink value="#{bean.currentPage}" /></li>
								
								<c:if test="#{bean.pagedDataTable.first + bean.pagedDataTable.rows lt bean.pagedDataTable.rowCount}">
									<li><h:commandLink value="#{bean.currentPage + 1}" action="#{bean.viewPage(bean.currentPage + 1)}" /></li>
								</c:if>

								<c:if test="#{bean.pagedDataTable.first + (bean.pagedDataTable.rows * 2) lt bean.pagedDataTable.rowCount}">
									<li><h:commandLink value="#{bean.currentPage + 2}" action="#{bean.viewPage(bean.currentPage + 2)}" /></li>
								</c:if>
								
								<li>
									<h:commandLink action="#{bean.pageNext}" disabled="#{bean.pagedDataTable.first + bean.pagedDataTable.rows >= bean.pagedDataTable.rowCount}">
										<b:iconAwesome name="angle-right"/>
									</h:commandLink>
								</li>
								<li>
									<h:commandLink action="#{bean.pageLast}" disabled="#{bean.pagedDataTable.first + bean.pagedDataTable.rows >= bean.pagedDataTable.rowCount}">
										<b:iconAwesome name="angle-double-right"/>
									</h:commandLink>
								</li>
							</ul>
						</b:container>
					</div>
			    </h:form>
```

**Comment by stephanrauh** [comment]
@xystra +1 for your post. I prefer PrimeFaces, which also has excellent built-in support for pagination.

However, I'm not sure that pagination is always linked to datatables. When I look at the Bootstrap documentation, the paginator reminds me of a wizard component.

BTW, many a people ask for a ```<b:dataTable />``` component. I we decide to implement such a thing, we'd also implement a paginator.

**Comment by anemdhana** [comment]
Thanks and you clarified very well. I have implemented this way and as you said, <b:dataTable /> makes sense to implement in our bootsfaces.
An example of sorting on a column
<pre>
&lt;h:column&gt;
	&lt;f:facet name=&quot;header&quot;&gt;
		&lt;h:commandLink action=&quot;retrieveAllMembers&quot; actionListener=&quot;#{memberListBean.dataTable.sort.setColumn('name')}&quot;&gt;
			Name &lt;b:iconAwesome name=&quot;arrow-#{memberListBean.dataTable.sort.arrowUpString}&quot; rendered=&quot;#{memberListBean.dataTable.sort.column=='name'}&quot;/&gt;
		&lt;/h:commandLink&gt;
	&lt;/f:facet&gt;
	&lt;h:commandLink action=&quot;editSelectedMember&quot; actionListener=&quot;#{memberListBean.setSelectedMember(_member)}&quot;&gt;#{_member.name}&lt;/h:commandLink&gt;
&lt;/h:column&gt;
</pre>
Here is the pagination links
<pre>
&lt;nav&gt;
  &lt;ul class=&quot;pagination&quot;&gt;
	&lt;c:choose&gt;
		&lt;c:when test=&quot;${memberListBean.dataTable.firstPage}&quot;&gt;
		   &lt;li class=&quot;disabled&quot;&gt;&lt;a href=&quot;#&quot; aria-label=&quot;Previous&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&laquo;&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
		&lt;/c:when&gt;
		&lt;c:otherwise&gt;
			&lt;li&gt;&lt;h:commandLink action=&quot;retrieveAllMembers&quot; actionListener=&quot;#{memberListBean.dataTable.pagePrevious}&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&laquo;&lt;/span&gt;&lt;/h:commandLink&gt;&lt;/li&gt;
		&lt;/c:otherwise&gt;
	&lt;/c:choose&gt;
	&lt;c:forEach var=&quot;pageNum&quot; items=&quot;#{memberListBean.dataTable.pages}&quot;&gt;
	   &lt;c:choose&gt;
			&lt;c:when test=&quot;${memberListBean.dataTable.currentPage == pageNum}&quot;&gt;
			   &lt;li class=&quot;active&quot;&gt;&lt;a href=&quot;#&quot;&gt;${pageNum} &lt;span class=&quot;sr-only&quot;&gt;(current)&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
			&lt;/c:when&gt;
			&lt;c:otherwise&gt;
				&lt;li&gt;&lt;h:commandLink value=&quot;#{pageNum}&quot; action=&quot;retrieveAllMembers&quot; actionListener=&quot;#{memberListBean.dataTable.page}&quot; /&gt;&lt;/li&gt;
			&lt;/c:otherwise&gt;
		&lt;/c:choose&gt;
	&lt;/c:forEach&gt;
	&lt;c:choose&gt;
		&lt;c:when test=&quot;${memberListBean.dataTable.lastPage}&quot;&gt;
		   &lt;li class=&quot;disabled&quot;&gt;&lt;a href=&quot;#&quot; aria-label=&quot;Next&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&raquo;&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
		&lt;/c:when&gt;
		&lt;c:otherwise&gt;
			&lt;li&gt;&lt;h:commandLink action=&quot;retrieveAllMembers&quot; actionListener=&quot;#{memberListBean.dataTable.pageNext}&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&raquo;&lt;/span&gt;&lt;/h:commandLink&gt;&lt;/li&gt;
		&lt;/c:otherwise&gt;
	&lt;/c:choose&gt;
 &lt;/ul&gt;
&lt;/nav&gt;
</pre>
<pre>
@Named
@FlowScoped("memberSearch")
public class MemberListBean implements Serializable {

	@Inject
	private MemberService memberService;

	private Results<Member> members;

	private Member selectedMember;

	@Inject
	private PaginableDataTable dataTable;
	
	public void initMemberSearch() {
		dataTable.setFilterCriteria(new MemberSearch());
		retrieveAllMembers();
	}

	public void retrieveAllMembers() {
		members = memberService.findAllMembers(dataTable);
		dataTable.setTotalRows(Long.valueOf(members.getTotal()).intValue());
	}
</pre>
<pre>
public class PaginableDataTable extends DataTable {

	// Paging.
	private int totalPages;

	private int pageRange;

	private Integer[] pages;

	private int currentPage = 1;

	// Result
	private int totalRows;

	public PaginableDataTable() {
		// Set default values somehow (properties files?).
		super();
		this.pageRange = 10; // Default page range (max amount of page links to be displayed at once).
	}

	// Paging actions -----------------------------------------------------------------------------

	public void pageFirst() {
		page(0);
	}

	public void pageNext() {
		page(getFirstRow() + getMaxRows());
	}

	public void pagePrevious() {
		page(getFirstRow() - getMaxRows());
	}

	public void pageLast(int totalRows) {
		page(totalRows - ((totalRows % getMaxRows() != 0) ? totalRows % getMaxRows() : getMaxRows()));
	}

	public void page(ActionEvent event) {
		page(((Integer) ((UICommand) event.getComponent()).getValue() - 1) * getMaxRows());
	}

	private void page(int firstRow) {
		System.out.println("--->Firstrow " + firstRow);
		setFirstRow(firstRow);
		currentPage = (totalRows / getMaxRows()) - ((totalRows - firstRow) / getMaxRows()) + 1;
	}

	public boolean isFirstPage() {
		return this.currentPage == 1;
	}

	public boolean isLastPage() {
		return (getFirstRow() + getMaxRows()) >= getTotalRows();
	}

	public int getTotalPages() {
		return totalPages;
	}

	public void setTotalPages(int totalPages) {
		this.totalPages = totalPages;
	}

	public int getPageRange() {
		return pageRange;
	}

	public void setPageRange(int pageRange) {
		this.pageRange = pageRange;
	}

	public int getCurrentPage() {
		return currentPage;
	}

	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}

	public int getTotalRows() {
		return totalRows;
	}

	public void setTotalRows(int totalRows) {
		this.totalRows = totalRows;
		this.totalPages = (totalRows / getMaxRows()) + ((totalRows % getMaxRows() != 0) ? 1 : 0);
		int pagesLength = Math.min(pageRange, totalPages);
		pages = new Integer[pagesLength];

		// firstPage must be greater than 0 and lesser than totalPages-pageLength.
		int firstPage = Math.min(Math.max(0, currentPage - (pageRange / 2)), totalPages - pagesLength);

		// Create pages (page numbers for page links).
		for (int i = 0; i < pagesLength; i++) {
			pages[i] = ++firstPage;
		}
	}

	public Integer[] getPages() {
		return pages;
	}

}
</pre>
<pre>
@Named
public class DataTable implements Serializable {

	private static final int MAX_ROWS_PER_PAGE = 10;

	private FilterCriteria filterCriteria;

	private int maxRows;

	private int firstRow;

	private Sort sort;

	public DataTable() {
		this.firstRow = 0; // first row index initialized to 0.
		this.maxRows = MAX_ROWS_PER_PAGE;
	}

	public DataTable(FilterCriteria filterCriteria) {
		this();
		this.filterCriteria = filterCriteria;
		this.sort = new Sort(filterCriteria.getDefaultSortColumn(), true);
	}

	public int getMaxRows() {
		return maxRows;
	}

	public void setMaxRows(int maxRows) {
		this.maxRows = maxRows;
	}

	public int getFirstRow() {
		return firstRow;
	}

	public void setFirstRow(int firstRow) {
		this.firstRow = firstRow;
	}

	public FilterCriteria getFilterCriteria() {
		return filterCriteria;
	}

	public void setFilterCriteria(FilterCriteria filterCriteria) {
		this.filterCriteria = filterCriteria;
		this.sort = new Sort(filterCriteria.getDefaultSortColumn(), true);
	}

	public Sort getSort() {
		return sort;
	}

	public void setSort(Sort sort) {
		this.sort = sort;
	}

	public static class Sort {

		private String column;

		private boolean ascending;

		public Sort(String column, boolean ascending) {
			super();
			this.column = column;
			this.ascending = ascending;
		}

		public String getColumn() {
			return column;
		}

		public void setColumn(String column) {
			if (!this.column.equals(column)) {
				this.ascending = true;
			} else {
				toggleSort();
			}
			this.column = column;
		}

		public boolean isAscending() {
			return ascending;
		}
		
		public void toggleSort() {
			setAscending(!isAscending());
		}
		
		public String getArrowUpString() {
			return isAscending()? "down" : "up";
		}

		public void setAscending(boolean ascending) {
			this.ascending = ascending;
		}

		@Override
		public String toString() {
			return "Sort [column=" + column + ", ascending=" + ascending + "]";
		}

	}

}
</pre>
<pre>
public interface FilterCriteria {

	public String getDefaultSortColumn();
}
</pre>

**Comment by vsvetoslavov** [comment]
I tried to combine PrimeFaces DataTable and Bootstrap. For me this is not the desired way to go:
* In order to not mix-up Bootstrap and PrimeFaces styles I had to prevent loading PrimeFaces CSS file (create an empty file in the appropriate resources folder). 
* The former led to losing some of the features of the PF datatable.
* The rendered HTML was much more complex, containing class names that did not exist (since I removed the PF css file)
* My best chances were with the default theme - I'm not sure custom themes would work that well

Instead, I switched to Apache Tomahawk - a bit old library, that was priceless  back in the ages of JSF 1.0. It still has paging and a pager component that I was able to adapt to Bootstrap's pager structure. In return Tomahawk's data table does not render extra-complicated HTML.

**Comment by stephanrauh** [comment]
As things go, I've started to implement a client-side b:dataTable, based on https://www.datatables.net/manual/styling/bootstrap. I'm not sure my datatable will make in into the 0.8.0 version. There's a lot of work to do left. Nonetheless, the current prototype looks promising.

**Comment by anemdhana** [comment]
You could try using bootstrap-table rather.

On Mon, Oct 5, 2015 at 2:06 AM, Stephan Rauh <notifications@github.com>
wrote:

> As things go, I've started to implement a client-side b:dataTable, based
> on https://www.datatables.net/manual/styling/bootstrap. I'm not sure my
> datatable will make in into the 0.8.0 version. There's a lot of work to do
> left. Nonetheless, the current prototype looks promising.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheCoder4eu/BootsFaces-OSP/issues/112#issuecomment-145385539>
> .
>



-- 
Thanks,
Dhana kumar.

**Comment by stephanrauh** [comment]
This one? http://bootstrap-table.wenzhixin.net.cn/
Why do you prefer it over the other datatable?

**Comment by anemdhana** [comment]
Right, on looking their documentation and examples, one can feel this has
everything, go through one by one of these examples,
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getOptions.html

One example is, table->thead is like top freeze pane, and much more options
what can be done from table.

On Mon, Oct 5, 2015 at 11:37 AM, Stephan Rauh <notifications@github.com>
wrote:

> This one? http://bootstrap-table.wenzhixin.net.cn/
> Why do you prefer it over the other datatable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheCoder4eu/BootsFaces-OSP/issues/112#issuecomment-145440027>
> .
>



-- 
Thanks,
Dhana kumar.

**Comment by zhedar** [comment]
As of v0.8.0 we seem to have implemented an experimental datatable component, which is also capable of pagination. Further progress is currently tracked in several issues e.g. #389. Therefore I guess we can close this old issue.
