### ISSUE TITLE
Bootsfaces showcase is returning a 502 bad gateway

### ISSUE THREAD

**Issue by exabrial** [TheCoder4eu/BootsFaces-OSP#1125]
Bootsfaces showcase is returning a 502 bad gateway. https://showcase.bootsfaces.net/

**Comment by exabrial** [comment]
dupe of #1108

**Comment by stephanrauh** [comment]
Not really a duplicate - the other ticket is from December. :)

**Comment by stephanrauh** [comment]
Restarting the server solved the problem.
