### ISSUE TITLE
b:message, b:messages not adding class when using styleClass

### ISSUE THREAD

**Issue by wearingart** [TheCoder4eu/BootsFaces-OSP#1126]
I saw that this was fixed in version 1.0.1, but it seems to be happening again in 1.4.2.

`<b:message for="companyName" id="companyNameErr" styleClass="special-error" />`

Produces this HTML without class:
`<div id="companyNameErr"></div>`

**Comment by geopossachs** [comment]
Hallo, only if a message is shown, the class will be added

``
<div id="companyNameErr">
	<div class="special-error alert alert-warning  bf-message" role="alert">
		<span class="bficon bficon-warning-triangle-o bf-message-icon" aria-hidden="true"/>
		<span class="bf-message-detail">The button/link/text component needs to have a Form in its ancestry. Please add &lt;h:form&gt;.</span>
	</div>
</div>
``

**Comment by geopossachs** [comment]
<div id="companyNameErr">
	<div class="special-error alert alert-warning  bf-message"
			role="alert">
		<span class="bficon bficon-warning-triangle-o bf-message-icon"
				aria-hidden="true"/>
		<span class="bf-message-detail">The button/link/text component needs to have a Form in its ancestry. Please add &lt;h:form&gt;.</span>
	</div>
</div>

**Comment by geopossachs** [comment]
`<div id="companyNameErr">
	<div class="special-error alert alert-warning  bf-message"
			role="alert">
		<span class="bficon bficon-warning-triangle-o bf-message-icon"
				aria-hidden="true"/>
		<span class="bf-message-detail">The button/link/text component needs to have a Form in its ancestry. Please add &lt;h:form&gt;.</span>
	</div>
</div>`

**Comment by geopossachs** [comment]
> 
> 
> `
> 
> 
> 
> The button/link/text component needs to have a Form in its ancestry. Please add <h:form>.
> 
> `

**Comment by geopossachs** [comment]
```
<div id="companyNameErr">
	<div class="special-error alert alert-warning  bf-message"	role="alert">
		<span class="bficon bficon-warning-triangle-o bf-message-icon"	aria-hidden="true"/>
		<span class="bf-message-detail">The button/link/text component needs to have a Form in its ancestry. Please add &lt;h:form&gt;.</span>
	</div>
</div>
```

Hallo, only if a message is shown, the class will be added
