### ISSUE TITLE
Support setting `help-block` either by facet or attribute.

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#1129]
Bootstrap supports adding a help text to form controls. 
https://getbootstrap.com/docs/3.3/css/#forms
```html
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
```
It would be nice to be able to define this help-block part - as a facet, as some attribute... To me facet seems more appropriate since it can contain html.
Best regards!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
