### ISSUE TITLE
Carousel not working

### ISSUE THREAD

**Issue by jorgesm15** [TheCoder4eu/BootsFaces-OSP#1131]
I'm new to bootsfaces, and I'm trying to add a carousel to my webpage but the image is not loading.

![carousel](https://user-images.githubusercontent.com/54010698/77569940-9b6a4380-6e90-11ea-8b1c-f3bdf4ce4667.PNG)

My code: 

![image](https://user-images.githubusercontent.com/54010698/77570003-b6d54e80-6e90-11ea-8c4d-51e73c61af37.png)

**Comment by stephanrauh** [comment]
Hi Jorge,

no idea... your sourcecode looks fine by me. I've added it to the BootsFaces showcase, so you can have a look yourself. Maybe you can spot the difference. My best guess is the image isn't found. That results in an error message in the error log and / or the console window of your browser.

Live demo: https://staging.bootsfaces.net/Showcase/issues/issue1131.jsf

Source code: https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/issues/issue1131.xhtml

Best regards,
Stephan

**Comment by jorgesm15** [comment]
Thank you, but I can't make it to work, I've tried to modify the image source multiple times, but for some reason the image is not loading.

**Comment by geopossachs** [comment]
Hallo @jorgesm15 
try to use the JSF resource access for example 
<h:graphicImage name="images/comida1.jpg" />
or 
<b:image name="images/comida1.jpg" />

https://showcase.bootsfaces.pecer.de/BootsFacesWeb//layout/Image.jsf
https://mkyong.com/jsf2/resources-library-in-jsf-2-0/

**Comment by jorgesm15** [comment]
> Hallo @jorgesm15 
> 
> try to use the JSF resource access for example 
> 
> <h:graphicImage name="images/comida1.jpg" />
> 
> or 
> 
> <b:image name="images/comida1.jpg" />
> 
> 
> 
> https://showcase.bootsfaces.pecer.de/BootsFacesWeb//layout/Image.jsf
> 
> https://mkyong.com/jsf2/resources-library-in-jsf-2-0/

Thank you very much! It finally worked!
