### ISSUE TITLE
DataTables CDN Alternative when developing locally

### ISSUE THREAD

**Issue by geisonrodrigo** [TheCoder4eu/BootsFaces-OSP#1132]
I'm getting trouble when trying to use DataTables inside a maven project, running on an intranet (locally, without internet access). I found explicit references to https://cdn.datatables.net and https://cdnjs.cloudflare.com. Is there a way to disable those references and point to a local cdn repository?
On a previous version of this project I was not using maven, so I was able to download BootsFaces source code and recompile it, replacing those remote references...

**Comment by stephanrauh** [comment]
Of course BootsFaces supports your use case. Basically, all you have to do is to download the `datatables.*` files to your project. If BootsFaces finds an include of such a file, it stops trying to download the `datatables.*` files from the CDN.

I've also documented this in the showcase (or at least, I've tried to do so).

**Comment by stephanrauh** [comment]
Does my comment help you? If so, just add a "+1" emoji, so I know I can close the ticket. If not, don't hesitate to ask again!

**Comment by geisonrodrigo** [comment]
> Of course BootsFaces supports your use case. Basically, all you have to do is to download the `datatables.*` files to your project. If BootsFaces finds an include of such a file, it stops trying to download the `datatables.*` files from the CDN.
> 
> I've also documented this in the showcase (or at least, I've tried to do so).

Dude, it worked like a charm!
I've tried to read the documentation from showcase, but I don't know why it's working for me...

![erro_bootsfaces_showcase](https://user-images.githubusercontent.com/22194729/78366227-92ffc000-7596-11ea-91d4-817ae6e9f042.png)

**Comment by geisonrodrigo** [comment]
> Does my comment help you? If so, just add a "+1" emoji, so I know I can close the ticket. If not, don't hesitate to ask again!

Thanks a lot!

**Comment by stephanrauh** [comment]
I'm afraid the showcase has crashed again. We're trying to find the root cause of the crashes, so we didn't simply restart it. It seems to be something difficult, something wrong with the setup of the virtual machine, so it's not a BootsFaces problem.

Until we've fixed the showcase, you can use the secondary showcase: https://showcase.bootsfaces.pecer.de/
