### ISSUE TITLE
<b:selectOneMenu> select2="true" ignores contentDisabled

### ISSUE THREAD

**Issue by flo-png** [TheCoder4eu/BootsFaces-OSP#1143]
Hello together,

it seems that b:selectOneMenu ignores contentDisabled when select2="true" is set.
I prepared the sample down below so you can verify it.

Thanks in advance. 
Regards flo-png

Version: BootsFaces-OSP-default-1.4.2
Server: tomcat-9.0.36

Sample:
```html
<b:container fluid="true">
		<b:row>
			<b:column id="content">
				<!--  Start -->

				<h3>Select MenuIssue Example</h3>
				
				<h4>Disable Issue</h4>
				
				<h:form>
					<b:row>
						<b:commandButton value="toggle contentDisabled" ajax="true" update="output"
							action="#{selectMenuIssueExample.toggleContentDisabled}" />
							
						<b:commandButton value="toggle selectOneMenu" ajax="true" update="output"
							action="#{selectMenuIssueExample.toggleSelectOneMenu}" />
					</b:row>
						
					<b:row contentDisabled="#{selectMenuIssueExample.contentDisabled}"
						id="output">

						<b:column medium-screen="3">
							<b:selectOneMenu value="Cannot be disabled"
								label="Child selection:" ajax="true" contentDisabled="#{selectMenuIssueExample.selectOneMenuContentDisabled}"
								select2="true" update="@form">
								<f:selectItems value="#{selectMenuIssueExample.selectedParent.childs}" var="c"
									itemValue="#{c}" itemLabel="#{c.name}" />
							</b:selectOneMenu>
						</b:column>
						
						<b:column medium-screen="3">
							<b:selectOneMenu value="Can be disabled"
								label="Child selection:" ajax="true" contentDisabled="#{selectMenuIssueExample.selectOneMenuContentDisabled}"
								update="@form">
								<f:selectItems value="#{selectMenuIssueExample.selectedParent.childs}" var="c"
									itemValue="#{c}" itemLabel="#{c.name}" />
							</b:selectOneMenu>
						</b:column>
					</b:row>

				</h:form>

				<!--  END -->
			</b:column>
		</b:row>
	</b:container>
```

Java Bean:
```java
	private boolean contentDisabled = false;
	private boolean selectOneMenuContentDisabled = false;

	public void toggleContentDisabled() {
		contentDisabled = !contentDisabled;
	}
	
	public void toggleSelectOneMenu() {
		selectOneMenuContentDisabled = !selectOneMenuContentDisabled;
	}
```

**Comment by geopossachs** [comment]
Hallo, the selectOneMenu do no has an attribute contentDisabled, so it do not support it

**Comment by flo-png** [comment]
Hello geopossachs ,

thanks for your reply. Iam confused about the tag "couldnt reproduce" and the add to v1.6.0 milestone at the same time. 
Will this be adressed in v1.6.0 or must i change the usage of contentDisabled to disable the content of <b:selectOneMenu> with select2="true" ?

Would the attribute disabled work for <b:selectOneMenu>with select2="true" ?

Looking forward to you reply.
Regards

**Comment by geopossachs** [comment]
hallo, 

i would like to label each new issue with a version to handle each issue in the project via the version tags. 
regardless of whether we solve it or not.

the component selectOneMenu do not support contentDisabled, this is not the same like _ignore_
https://showcase.bootsfaces.pecer.de/BootsFacesWeb//forms/selectOneMenu.jsf#reference_section

if a component ignores something then it sounds like a bug, for example if you enable option A the functionality B do not work like expected.

what exactly is your wish? what do you expect from the component?

**Comment by flo-png** [comment]
_what exactly is your wish? what do you expect from the component?_

I see the select2 attribute as an option of <b:selectOneMenu>, i expect that the <b:selectOneMenu> behaves in the same way like without select2="true" and all other components i worked with before. That means if the contentDisabled for one of the parent components will be set to "true", all components below that in the component tree will be disabled. 

At  the moment this works for components like InputText, Button and even for the SelectOneMenu when select2="false". When i understand contentDisabled correctly, it allows to disabled complete component trees if needed. <b:selectOneMenu> with attribute select2="true" does not support this behaviour. 

 My workaround is to do not render the <b:selectOneMenu> if i want to disable its content. To see the difference behaviour i provided the sample in the first post.

Hope the issue adresses got clear now. 

Regards

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
