### ISSUE TITLE
showcase - links broken

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#1150]
all links in the left hand side navigation menu are broken - they seem to have a relative URL prefixed with https://

**Comment by geopossachs** [comment]
@TheCoder4eu by the deployment into the primary system showcase.bootsfaces.net went something wrong. please let use reset the vm setup

the fallback system is working well https://showcase.bootsfaces.pecer.de/BootsFacesWeb/ with the nearly same code

**Comment by vsvetoslavov** [comment]
Since instabilities in the showcase/demo site are, unfortunately, not that uncommon, I think it would be a good idea to have a link to the fallback site - either on the main site, or on the showcase site, or both

**Comment by geopossachs** [comment]
#1161

**Comment by stephanrauh** [comment]
The showcase seems to work again.
