### ISSUE TITLE
Setting custom-option for datatable column breaks rendering, if table is empty

### ISSUE THREAD

**Issue by sebsoftware** [TheCoder4eu/BootsFaces-OSP#1153]
setting i.E. max-width:80px in the custom-option of a b:dataTableColumn, breaks rendering, if the table is empty.

Seems to be a bug, in the generated script code.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
