### ISSUE TITLE
Documentation on the Main Site is Broken

### ISSUE THREAD

**Issue by mfreeman-xtivia** [TheCoder4eu/BootsFaces-OSP#1154]
None of the links for component documentation in the left sidebar work on the main site.

They seem to be missing the host portion of the URL somehow

**Comment by exabrial** [comment]
+1. If there's anything I could do to help out this please let me know. I'd be happy to get involved

**Comment by exabrial** [comment]
just noticed this is a duplicate of #1150

**Comment by vsvetoslavov** [comment]
@mfreeman-xtivia They seem to not work even if you add the host portion by hand...

**Comment by geopossachs** [comment]
#1161

**Comment by stephanrauh** [comment]
The showcase seems to work again.
