### ISSUE TITLE
The links are broken in Showcase 

### ISSUE THREAD

**Issue by gdiazs** [TheCoder4eu/BootsFaces-OSP#1161]
There are components (most of those) that lands users to unreachable pages. For instance if I click on Button component from the sidebar it generates a url like https://forms/buttons.jsf.

**Comment by stephanrauh** [comment]
¡Si, eso es! And I agree, we should do something about it. It's a weird bug: the feature worked without problems until recently.

In the meantime, you can use the main menu (the menu bar at the top of the screen). You can also use the secondary showcase at https://showcase.bootsfaces.pecer.de/BootsFacesWeb/. We're still investigating what's different, but the primary showcase is broken, and the secondary showcase runs without problems... while being compiled from the same source code.

**Comment by vsvetoslavov** [comment]
@stephanrauh Actually the showcase has been broken for quite a while. Every time I check the showcase - it's broken, and I come here to check for the backup links... ;) Can I do something to help with this issue?

**Comment by stephanrauh** [comment]
@vsvetoslavov That'd be great! I'm afraid I don't have time to bring you up to speed, but what about you, @geopossachs and @TheCoder4eu? Can you analyze the task together with Васил?

**Comment by geopossachs** [comment]
Hello, 
I think only the .war file on prod was damaged and not the git-code base. 
Or there is something wrong with the build pipeline for prod.

I have rebuilt the .war file manually and upload it into the prod wildfly.
I think now it will work better :-)


A domain is very cheap in Germany so I have made my mirror from my fork a little bit easier to remember

https://github.com/geopossachs/BsF-front/tree/system/production -> https://www.bootsfaces.de/
https://github.com/geopossachs/BootsFacesWeb/tree/system/production -> https://showcase.bootsfaces.de/

https://github.com/geopossachs/BsF-front/tree/system/stage -> https://stage-www.bootsfaces.de/
https://github.com/geopossachs/BootsFacesWeb/tree/system/stage -> https://stage-showcase.bootsfaces.de/

**Comment by exabrial** [comment]
Let me know where to send the beer money to anyone helping on this project :) We love bootsfaces!

**Comment by stephanrauh** [comment]
The showcase seems to work again.
