### ISSUE TITLE
All side bar links are sending to a 404 pages

### ISSUE THREAD

**Issue by rodrigovidalxc** [TheCoder4eu/BootsFaces-OSP#1168]
All side bar links in "https://showcase.bootsfaces.net/" are sending to an 404 page. 
some examples bellow
https://layout/Accordion.jsf
https://bootstrap/alerts.jsf

**Comment by geopossachs** [comment]
Hallo,pleace use the fallback systemhttps://showcase.bootsfaces.de/Sorry the old server setup is a little bit broken.Have a nice day-------- Ursprüngliche Nachricht --------Von: rodrigovidalxc ***@***.***>Datum: Di., 4. Mai 2021, 22:37An: TheCoder4eu/BootsFaces-OSP ***@***.***>Cc: Subscribed ***@***.***>Betreff: [TheCoder4eu/BootsFaces-OSP] All side bar links are sending to a 404 pages (#1168)
All side bar links in "https://showcase.bootsfaces.net/" are sending to an 404 page.
some examples bellow
https://layout/Accordion.jsf
https://bootstrap/alerts.jsf

**Comment by geopossachs** [comment]
we have relead the server, now it will work

https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1128
