### ISSUE TITLE
b:switch left label and <b:form horizontal="true" /> support

### ISSUE THREAD

**Issue by nando2301** [TheCoder4eu/BootsFaces-OSP#1169]
**Problem:**
When I use this code to create page elements:
```
<b:form id="infoConf" horizontal="true">
    ...
    <ui:repeat var="conf" value="#{configBean.items}" varStatus="status">
        <b:inputText labelColLg="2" colLg="6"
                     labelColMd="2" colMd="6"
                     labelColSm="2" colSm="6"
                     label="#{conf.label}"
                     value="#{conf.value}" 
                     rendered="#{conf.type == 'text'}"/>
        <b:formGroup>
            <b:switch onColor="success"
                      offColor="default"
                      label="#{conf.label}"
                      value="#{conf.value}"
                      rendered="#{conf.type == 'boolean'}"/>
        </b:formGroup>
    </ui:repeat>
    ...
</b:form>
```
**This is the result:**

![image](https://user-images.githubusercontent.com/32605309/120030236-d39d7280-bfbc-11eb-98d9-dcd25a961573.png)

**Version used:**
```
        <dependency>
            <groupId>net.bootsfaces</groupId>
            <artifactId>bootsfaces</artifactId>
            <version>1.5.0</version>
            <scope>compile</scope>
        </dependency>
```

**Expected result:**
![image](https://user-images.githubusercontent.com/32605309/120029512-d186e400-bfbb-11eb-9a54-23932de4f6b0.png)

**I Think:** Switch doesn't support horizontal forms **(labelColXX and colXX attributes)** and always its label is on top. The same case y I use separate label y looks like this using <b:formGroup></b:formGroup>:
```
...
<b:formGroup>
    <h:outputLabel value="#{conf.label}"
                   rendered="#{conf.type == 'boolean'}"/>
    <b:switch onColor="success"
              offColor="default"
              value="#{conf.value}"
              rendered="#{conf.type == 'boolean'}"/>
</b:formGroup>
...
```
![image](https://user-images.githubusercontent.com/32605309/120031136-03994580-bfbe-11eb-8473-3a0c51256eed.png)

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
