### ISSUE TITLE
FR: sub menu

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#117]
Hello,
what about [sub menu](https://github.com/vsn4ik/bootstrap-submenu)? I red somewhere that author of bootstrap removed this in version 3 because of incompatibility in mobile devices (or something like that), but for web development this could be very helpful.

**Comment by TheCoder4eu** [comment]
We could inspire to this project:
http://www.monolinea.com/responsive-multilevel-menu-with-bootstrap-3/

http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html

https://github.com/vadikom/smartmenus

However let's also investigate what is new in the upcoming 4.0 version of Bootstrap.

**Comment by stephanrauh** [comment]
For some reason this tickets missed my eye when I implemented a simple solution (#133).Riccardo, should we still have a look at the smartmenus widgets, or does the simple solution already do the trick?

**Comment by TheCoder4eu** [comment]
I think that it is something we can have a look at when we have time...

**Comment by stephanrauh** [comment]
Let's close the issue. We've already a decent submenu.
