### ISSUE TITLE
the example page showcase.bootsfaces.net/layout/basic.jsf appears to be broken

### ISSUE THREAD

**Issue by jmccay-work** [TheCoder4eu/BootsFaces-OSP#1170]
The page showcase.bootsfaces.net/layout/basic.jsf appears to be broken.  It doesn't load anything and the navigation at the top doesn't work anymore.  On other pages, the menu on the left doesn't work at all.

**Comment by geopossachs** [comment]
we have relead the server, now it will work

https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1128

**Comment by TheCoder4eu** [comment]
@geopossachs @stephanrauh ,
the page seems ok to me by now...
