### ISSUE TITLE
Growl: passthrough attribute is rendered at script tag only

### ISSUE THREAD

**Issue by flange-ipb** [TheCoder4eu/BootsFaces-OSP#1172]
Hi folks,

I'm adding a passthrough attribute to a growl component:
```xml
<b:growl id="someId" pt:myattribute="some value"/>
```
with the PT namespace `xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"`.

The result is a bit unexpected:
The JavaScript snippet becomes rendered with the PT attribute `<script id="someId" myattribute="some value">`, but the HTML this snippet renders does not have the attribute. I would expect that all rendered HTML tags get this attribute, like it's done for instance in b:inputText or b:message.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
