### ISSUE TITLE
dataTable disappears when use scrollHorizontally="true" on md/lg screen

### ISSUE THREAD

**Issue by nando2301** [TheCoder4eu/BootsFaces-OSP#1174]
Hi,

When I use scrollX="true" dataTable show good al rows and scroll in md and lg screen, but table information foot exceeds dataTable scroll bar size in sm screen (smartphone), then I try to use scrollHorizontally="true" and works fine in sm screen and fails into ms and lg screen sizes.

scrollX="true"
![image](https://user-images.githubusercontent.com/32605309/133006386-ebf7c40d-ceb9-413f-bcd4-b050889ae5b9.png)

scrollHorizontally="true" in medium screen
![image](https://user-images.githubusercontent.com/32605309/133006376-54607ee5-5bb1-43de-be34-420623118285.png)

scrollHorizontally="true" in small screen (smartphone)
![image](https://user-images.githubusercontent.com/32605309/133006466-2e32d362-6786-4119-a687-da7a7a71eb1f.png)

Thanks!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
