### ISSUE TITLE
DateTimePicker does not show regular iconAwesome when on the right side

### ISSUE THREAD

**Issue by bmilcke** [TheCoder4eu/BootsFaces-OSP#1178]
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/4678f401998430f4386f6c347037c3c3d6a1bdfa/src/main/java/net/bootsfaces/component/dateTimePicker/DateTimePickerRenderer.java#L318

should be ``dtp.isIconSolid());`` instead (like in the code for iconPosition left)

**Comment by stephanrauh** [comment]
Indeed. Thanks for reporting the error and for providing a bugfix, Björn!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Holy moly... I can't publish to Maven Central for some reason. I don't understand the error message:

```
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project bootsfaces: Execution sign-artifacts of goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign failed. NullPointerException -> [Help 1]
```

When I type "gpg" on the command prompt, the gpg command is available. Does anybody have an idea what happened to my installation?

**Comment by bmilcke** [comment]
Sorry, no idea. Sounds a bit unspecific. I suppose, trying again does not help. (I once had an issue on publishing, that did)

-Björn

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
