### ISSUE TITLE
Support JakartaEE 9

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#1180]
Let's support JakartaEE 9.

**Comment by frankyhoffmann** [comment]
Thanks, I think that's great. 👍

**Comment by stephanrauh** [comment]
The new version is available on Maven Central as 1.6.0-SNAPSHOT. If you need the JakartaEE version, add the classifier `jakarta`:
<dependency>
			<groupId>net.bootsfaces</groupId>
			<artifactId>bootsfaces</artifactId>
			<version>1.6.0-SNAPSHOT</version>
			<classifier>jakarta</classifier>
		</dependency>
```xml

```

**Comment by geopossachs** [comment]
https://github.com/TheCoder4eu/BootsFaces-OSP/pull/1191
