### ISSUE TITLE
JAVA 17 Support

### ISSUE THREAD

**Issue by frankyhoffmann** [TheCoder4eu/BootsFaces-OSP#1181]
Does the Bootsfaces Framework support JAVA version 17?
If not, can your team please implement it. That would be great.
Many thanks in advance.

**Comment by stephanrauh** [comment]
Yes, it does. The core library runs without problems. I've tested it with Temurin (https://adoptium.net/).

We only have to trim down one of the demos of the showcase because the old scripting support has been removed.
