### ISSUE TITLE
Jakarta EE9 - JSF 3 support

### ISSUE THREAD

**Issue by DavidBaddeley** [TheCoder4eu/BootsFaces-OSP#1187]
Hi Guys,

I saw a comment in the previous discussion about support for Jakarta Faces but I can't see any mention of it in the docs, is there any work ongoing to support this, I guess its a copy 'n paste job on all the .javax dependencies?

We are migrating a legacy app and I would like to use a full Jakarta EE 9 stack but I think that won't be possible with current Bootfaces 1.5.0? So maybe we should be targeting Jakarta EE 8 instead

Regards

David

**Comment by stephanrauh** [comment]
JakartaEE 9 support works with the current snapshot. At the moment, I'm not sure if it's already 1.5.0-SNAPSHOT or still 1.4.2-SNAPSHOT.

The feature didn't make it into the documentation yet because we're short on developers. I'm afraid I'm one of the bottlenecks. I can't predict when we'll publish version 1.5.0. We've been pushing to to "next week" for several months now.

Maybe you can help us. Would you like to test the current developer build, review pull requests, and answer questions?

**Comment by stephanrauh** [comment]
For the sake of convenience, here are the download coordinates:

The new version is available on Maven Central as 1.6.0-SNAPSHOT. If you need the JakartaEE version, add the classifier `jakarta`:
```xml
<dependency>
	<groupId>net.bootsfaces</groupId>
	<artifactId>bootsfaces</artifactId>
	<version>1.6.0-SNAPSHOT</version>
	<classifier>jakarta</classifier>
</dependency>

```

**Comment by DavidBaddeley** [comment]
Thanks Stephan, but I can't see that version on Maven Central, latest is 1.5.0??

I would be happy to help test this build since we are starting a migration to Jakarta EE 9 and will be doing a lot of testing anyway

**Comment by stephanrauh** [comment]
I'm talking about the snapshot repository. Issue #369 has some info how to access it.

**Comment by geopossachs** [comment]
Hello,

i will add the link to the snapshot repository for the sake of completeness.
https://oss.sonatype.org/content/repositories/snapshots/net/bootsfaces/bootsfaces/1.6.0-SNAPSHOT/

For testing you can define in your projekt this repository too, so you can access this Snapshot.


```
  <repositories>
    <repository>
      <id>oss.sonatype.org-snapshot</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

**Comment by geopossachs** [comment]
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1180

**Comment by geopossachs** [comment]
Notice:
Someone has contributed a nice pull-request for upgrade to jakarta-10.
An official release will certainly come next month.

**Comment by NikeeAgrawal** [comment]
Hi @geopossachs 
After adding this in build.gradle , not able to downloaded  .
Could you suggest me how to configure it my project?
https://oss.sonatype.org/content/repositories/snapshots/net/bootsfaces/bootsfaces/1.6.0-SNAPSHOT/

Scenario is I am migration the project from 8 to 17 version and previously we are using bootsfaces version 1.5.0
facing error 
Class 'net.bootsfaces.listeners.AddResourcesListener' is missing a runtime dependency: java.lang.NoClassDefFoundError: javax/faces/event/SystemEventListener

**Comment by geopossachs** [comment]
Hallo @NikeeAgrawal ,

you can use my current snapshot of the next version.
This next version will be compatible for jarkarta 10.

You can found my snapshot in my fork repo here:
https://github.com/geopossachs/BootsFaces-OSP/packages/1969902

And here you can found an example how you can pull my current snapshot into a project
https://github.com/geopossachs/BootsFacesWeb/blob/feature/jakarte-10-ready/pom.xml#L288


-----

plan b  - if you can't pull somthing from github, you can also pull an one of the first snapshots of the draft support of jakarta from the 
<snapshotRepository>
<url>https://oss.sonatype.org/content/repositories/snapshots</url>

```
<dependency>
  <groupId>net.bootsfaces</groupId>
  <artifactId>bootsfaces</artifactId>
  <version>1.6.0-SNAPSHOT</version>
  <classifier>jakarta</classifier>
</dependency>
```

**Comment by NikeeAgrawal** [comment]
Hi @geopossachs  
Thank u for this solutions. I will try the first one because the second one, i tried but not able to download
![Screenshot 2024-08-06 041827](https://github.com/user-attachments/assets/3f2b6fbf-51e5-4407-b91c-fef13513d225)
Directory listing forbidden

Thanks!!

**Comment by NikeeAgrawal** [comment]
Hi @geopossachs 

After including the bootsfaces 1.6.0 getting this issuse.

Could you please guide me how to resolve this issue ?


java.lang.RuntimeException: Could not match a select item for submittedOptionValue:2 menu:net.bootsfaces.component.selectOneMenu.SelectOneMenu@3ba56c24
	at net.bootsfaces.component.selectOneMenu.SelectOneMenuRenderer.findValue(SelectOneMenuRenderer.java:94)
	at net.bootsfaces.component.selectOneMenu.SelectOneMenuRenderer.decode(SelectOneMenuRenderer.java:72)
	at jakarta.faces.component.UIComponentBase.decode(UIComponentBase.java:500)
	at jakarta.faces.component.UIInput.decode(UIInput.java:646)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:872)
	at jakarta.faces.component.UIInput.processDecodes(UIInput.java:550)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIForm.processDecodes(UIForm.java:191)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
	at jakarta.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:997)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:51)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	
	Thanks!!

**Comment by charlycong** [comment]
@geopossachs , any plan to release the official version of jakarta? We realy need it.

**Comment by stephanrauh** [comment]
Soon. There's no fixed due date yet, but I plan to publish it soon.

**Comment by stephanrauh** [comment]
Version 2.0.0-SNAPSHOT has landed in Maven Central. See #369 on how to get the snapshot. It's a Jakarta-only version. We've dropped support for the older `jaxax` namespace.
