### ISSUE TITLE
1.6 Release, Joinfaces and Jakarta

### ISSUE THREAD

**Issue by t-oster** [TheCoder4eu/BootsFaces-OSP#1189]
Hi,
I have to migrate my project from joinfaces 4 to joinfaces 5 (http://joinfaces.org/), which includes the migration from the javax classes to the jakarta classes.
As I understand joinfaces will make this transition in 1.6.0 (i am getting it to work partly with the 1.6.0 snapshot).
However, since 1.6.0 is not released, joinfaces seemed to decide to remove the bootsfaces support, which makes it harder for me to keep it in my project.

So my question is: Is there a time plan for the 1.6.0 release, which will have jakarta support? Maybe we can get the Joinfaces people then to re-include bootsfaces.

**Comment by stephanrauh** [comment]
Jakarta support is already there, but not in an official version. The latest snapshot supports the jakarta namespace.

I'm afraid we won't ever manage to publish version 1.6.0. And I'm sure we won't publish a version supporting JSF 4.0. Maybe someone picks up the work. That'd make me happy. But at the moment, I don't see anyone. Adding insult to injury, none of my customers is using JSF these days. JavaScript-based UI frameworks dominate the market. So it's unlikely we'll find volunteer supporting the project.

That's a pity, because I still see 3000-4000 downloads each month.

**Comment by t-oster** [comment]
Okay, thank you for your quick answer and for the work in general.
Maybe you could add a warning to the bootsfaces main page that it won't be developed further so people don't start depending on it and will be forced to remove it when migrating to spring boot 3.

**Comment by geopossachs** [comment]
Hello,
unfortunately, a complete conversion of the old framework to the new one is not an easy task.
But I think the other JSF frameworks are also facing this challenge.
And we can see how they solve it.

Here i found Primeface published a second JAR as a JAR for the new framework too
https://primefaces.github.io/primefaces/10_0_0/#/gettingstarted/download?id=jakarta-jsf-30

**Comment by geopossachs** [comment]
Tickets with the same topic
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1180
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1187

**Comment by geopossachs** [comment]
I have a question @t-oster 

How does the Framework switch work there?
They import primefaces on version 12 there, but the normal jar
https://github.com/joinfaces/joinfaces/blob/5.0.x/joinfaces-dependencies/build.gradle#L30

But there is no branching change in this normal primeface jar - they use Jarkarte 8
https://mvnrepository.com/artifact/org.primefaces/primefaces/12.0.0

or i'm wrong?

**Comment by t-oster** [comment]
> Jakarta support is already there, but not in an official version. The latest snapshot supports the jakarta namespace.
> 
> I'm afraid we won't ever manage to publish version 1.6.0. And I'm sure we won't publish a version supporting JSF 4.0. Maybe someone picks up the work. That'd make me happy. But at the moment, I don't see anyone. Adding insult to injury, none of my customers is using JSF these days. JavaScript-based UI frameworks dominate the market. So it's unlikely we'll find volunteer supporting the project.
> 
> That's a pity, because I still see 3000-4000 downloads each month.

Hi @TheCoder4eu could you please upload the source of the 1.6.0 snapshot with jakarta support to a new branch? The main branch seems not to be the same and I would like to fix some things on the 1.6.0 version. Maybe I can create a fork.

**Comment by geopossachs** [comment]
Hallo,
someone has contributed a nice pull-request for upgrade to jakarta-10.
An official release will certainly come next month.

**Comment by stephanrauh** [comment]
"Certainly" is a bold promise, but I'll do my best! :)

**Comment by geopossachs** [comment]
https://github.com/TheCoder4eu/BootsFaces-OSP/pull/1191

**Comment by charlycong** [comment]
Hi there,
We are migrating our project from Java EE to Jakarta EE.
Is there any plan for the release of 1.6 official version? We don't want to use the development version in our production environment.
Thanks!

**Comment by jogilham** [comment]
I need to do this too and I'm really keen for there to be a production version please

**Comment by stephanrauh** [comment]
@geopossachs @TheCoder4eu We're so close to publishing the new version - but for some reason, we never manage. How can we speed up things?

**Comment by geopossachs** [comment]
Hallo @TheCoder4eu 

In my opinion, you can close the current snapshot on master and release it to Maven-Central as version 2.0.

**Comment by jogilham** [comment]
Hi, is this any closer to happening?

Thanks :-)

**Comment by geopossachs** [comment]
@stephanrauh

**Comment by stephanrauh** [comment]
Yes, it's highly probably that we're going to publish version 2.0 soon.

**Comment by NikeeAgrawal** [comment]
Hi @stephanrauh 
Nice to hear that this is going to release 
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1189#issuecomment-2246222363
when we can accept this version on maven , waiting for this..

Thanks!!

**Comment by stephanrauh** [comment]
Version 2.0.0-SNAPSHOT has landed in Maven Central. See #369 on how to get the snapshot.
