### ISSUE TITLE
[Feature] OpenStreetMap (OSM): allow multiples points in map

### ISSUE THREAD

**Issue by nokiajavi** [TheCoder4eu/BootsFaces-OSP#1192]
Hi, it would be interesting if multiple points could be included on the map, with an array or something similar, and if each point could be customized with a color, for example, and its own tooltip.

Thanks!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
