### ISSUE TITLE
RESOURCE_NOT_FOUND while using bootsfaces 1.6.0-SNAPSHOT and Wildfly 31

### ISSUE THREAD

**Issue by dwcorium** [TheCoder4eu/BootsFaces-OSP#1199]
I described my problem here
https://stackoverflow.com/questions/78602476/resource-not-found-while-using-bootsfaces-1-6-0-snasphot-on-wildfly-31

**Comment by geopossachs** [comment]
Hallo @dwcorium,

wildfly 31 is an application server for Jakarta 10, the next release 2.0 of bootsfaces will bring the support for Jakarta 10.

For example, the upcoming showcase based on bootfaces 2.0 is able to run on wildfly 31.
You can try it by yourself this commit https://github.com/geopossachs/BootsFacesWeb/tree/2024-06-10 is running on wildfly 31 here https://stage-showcase.bootsfaces.de/. You will see the behavior of loading the resources of bootfaces 2.0 will be working on wildfly 31.

**Comment by geopossachs** [comment]
A similar question with further information
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1187

**Comment by dwcorium** [comment]
thanks with the Version 2.0.0-Snapshot ist does indeed work
