### ISSUE TITLE
Enhancement:  Add to Maven repository

### ISSUE THREAD

**Issue by sdnakhla** [TheCoder4eu/BootsFaces-OSP#12]
BootsFaces is built using Maven, but is not made available on any of the more well-known Maven repositories (as best I can tell).  Adding it to these repositories would make it much easier to integrate into a development project.

**Comment by MSzturc** [comment]
+1

**Comment by stephanrauh** [comment]
BootsFaces now has been released to Maven Central. It should be available as soon as Sonatype activates distribution to the repositories (probably on Monday). You can see the files here: 
https://oss.sonatype.org/content/repositories/releases/net/bootsfaces/bootsfaces/0.6.0/

**Comment by TheCoder4eu** [comment]
Great!
Thanks, should we tweet or write about it? :-)

Riccardo

**Comment by stephanrauh** [comment]
Both, of course :). 

BTW, I haven't added the minified version yet. I plan to do it next week, when Sonatype has activated the distribution.
