### ISSUE TITLE
bootsfaces not respecting css order

### ISSUE THREAD

**Issue by xystra** [TheCoder4eu/BootsFaces-OSP#121]
when using 
```html
	<h:body>
		<f:facet name="last">
			<h:outputStylesheet name="css/main.css"/>
        </f:facet>
```
your custom CSS stylesheet should be the last `<link />` tag in your document. unfortunately this common rule is not respected and the `<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/css/theme.css.xhtml?ln=bsf">` line is being generated after your custom CSS hence your overrides don't work.

```html
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/theme.css.xhtml?ln=primefaces-aristo" />
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/fa/font-awesome.css.xhtml?ln=primefaces&amp;v=5.2" />
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/css/bsf.css.xhtml?ln=bsf" />
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/css/core.css.xhtml?ln=bsf" />
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/css/main.css.xhtml" />
<link type="text/css" rel="stylesheet" href="/iesi/javax.faces.resource/css/theme.css.xhtml?ln=bsf" />
```

**Comment by stephanrauh** [comment]
The problem is the method AddResourceListener.enforceCorrectLoadOrder(). I started to sort the resource files alphabetically to reduce the complexity of the algorithm. Seems this wasn't a good idea.

@xystra as far as I remember the "last" facet was never supported in <h:body>, but only in <h:head>. But we've dropped it anyways, because it was only evaluated in the HeadRenderer - which caused us a lot of incompatiblities - and we didn't see the use case.

**Comment by xystra** [comment]
From what I've read putting the "last" facet in the `<h:body>` for stylesheets was the only way to guarantee your CSS was the last one loaded. I'll search for the document and post the link if I can find it.

**Comment by ripper2hl** [comment]
okay this bug is present on all jsf pages not only on the one use the library. 
I checked the time responses from the server and this library adds a lag every time on ajax events adding a few miliiseconds in each event, check this image where is the same call every time
![captura de pantalla de 2015-07-20 13 10 46](https://cloud.githubusercontent.com/assets/2611201/8783346/d7dabaf6-2ee0-11e5-8665-3855c6232ffc.png)

any ideas ?

**Comment by stephanrauh** [comment]
That's definitely an unexpected finding. At the moment, I don't have an idea how and why BootsFaces might add such a huge time lag to each request.

**Comment by stephanrauh** [comment]
I've found the problem. It occurs only with AJAX request. I'm going to fix it ASAP.

**Comment by ripper2hl** [comment]
@stephanrauh thanks, I was not sure it was related to the bug in the css, but because they relate to integrate the library affects the entire application not only the JSF pages that implement.

My English is very bad xD

**Comment by stephanrauh** [comment]
@ripper2hl Actually, there's little to complain about your English - pero, claro, si prefieres, puedes escribirnos en tu idioma.

**Comment by stephanrauh** [comment]
To do: add an option to add CSS files at the end.

**Comment by ripper2hl** [comment]
Disculpa, podrias decirme si existe una fecha de salida para la version 0.7.1 y si tiene la corrección del error en las peticiones ajax, la razón de mi pregunta es por que tengo una aplicación en producción y le está afectando mucho, no se si este es el mejor lugar para hablar de este tema.

**Comment by stephanrauh** [comment]
@ripper2hl No hemos concertado una fecha de salida de la próxima versión todavía. Supongo que publicaremos la versión 0.8.0 al fin de agosto. Si necesitas un bug fix mas pronto, avisame. Puedo publicar la versión 0.7.1 mas pronto. En esta caso, seria una versión sin las correcciones AJAX.

En cualquier caso, si prefieres contactarme con correo electrónico: webmaster1 arroba beyondjava punto de.

**Comment by stephanrauh** [comment]
@xystra For some reason, I couldn't get the PrimeFaces approach (using the facets) to work. So I decided to take a different approach, adding an extra attribute to `<h:h:outputStylesheet>`. Set `position="first"´ to ensure your resource leads the pack, set `position="middle"` to put it somewhere in the middle (most likely, but not always in front of the BootsFaces and PrimeFaces resources) and `position="last"` to put it at the end of the header section. Note that I didn't care about resources in the body yet. However, your problem were the CSS files, so I suppose my solution is up to the task.

My approach also works with the `CombinedResourcesHandler` of OmniFaces.

```xml
    <h:head>
        <title>BootsFaces: the next-gen JSF Framework based on Bootstrap</title>
        ...
        <h:outputStylesheet library="sh" name="css/shCoreEclipse.css"/>
        <!-- These CSS don't do anything. The just demonstrate the position attribute. -->
        <h:outputStylesheet name="last.css" position="last"/>
        <h:outputStylesheet name="first.css" position="first"/>
        <h:outputStylesheet name="middle.css" position="middle"/>
    </h:head>
```

![image](https://cloud.githubusercontent.com/assets/3045767/11017053/7fc0f15a-8593-11e5-9e49-924a4c5736f7.png)

**Comment by stephanrauh** [comment]
Documented the new options: http://bootsfaces.net/Staging/layout/resourcemanagement.jsf.

**Comment by ScreamingTree86** [comment]
Hi,
as of today i try to use the Syntaxhighlighter http://alexgorbatchev.com/SyntaxHighlighter/ for an own showcase application in addition to primefaces and bootsfaces. So i try to add the syntaxhighlighter css after the bsf css files with the 

```
<h:head>
    <f:facet name="first">
        <title>Showcase</title>
        <link rel="shortcut icon" type="image/x-icon" href="#{resource['images/favicon.png']}"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </f:facet>

    <h:outputScript library="scripts" name="js/shCore.js" target="head"/>
    <h:outputScript library="scripts" name="js/shBrushJava.js" target="head"/>
    <h:outputScript library="scripts" name="js/shBrushXml.js" target="head"/>

    <h:outputStylesheet library="css" name="shCore.css" position="last"/>
    <h:outputStylesheet library="css" name="shThemeDefault.css" position="last"/>
</h:head>
```
but the code generated looks like this
```
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/theme.css.xhtml?ln=primefaces-bootstrap" />
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/fa/font-awesome.css.xhtml?ln=primefaces&amp;v=5.3" />
[...]
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/shCore.css.xhtml;jsessionid=W8T4nZnQRHeBwdeBGL45Iz7Ejb-1tgtqftYHF9Qt.pcpn?ln=css" />
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/shThemeDefault.css.xhtml;jsessionid=W8T4nZnQRHeBwdeBGL45Iz7Ejb-1tgtqftYHF9Qt.pcpn?ln=css" />
<!--[if lt IE 9]><script src="/showcase/javax.faces.resource/js/html5shiv.js.xhtml?ln=bsf"></script>
<script src="/showcase/javax.faces.resource/js/respond.js.xhtml?ln=bsf"></script><![endif]-->
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/css/default/tooltip.css.xhtml;jsessionid=W8T4nZnQRHeBwdeBGL45Iz7Ejb-1tgtqftYHF9Qt.pcpn?ln=bsf" />
<link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/css/default/core.css.xhtml;jsessionid=W8T4nZnQRHeBwdeBGL45Iz7Ejb-1tgtqftYHF9Qt.pcpn?ln=bsf" />
[...]
```
As you can see the `shCore.css` is before the bsf css files and after the primefaces stuff. I cannot get the SyntaxHighlight to work because it has to be after the bsf files. Any suggestions?
