### ISSUE TITLE
New component: switch

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#124]
We could add a switch to display and edit boolean values. For instance, this one looks promising:
http://www.bootstrap-switch.org/

**Comment by yersan** [comment]
I'm taking care of this issue.

**Comment by TheCoder4eu** [comment]
+1 it is exactly what I used for the customizer:
http://www.bootsfaces.net/custom/customize.html

**Comment by AlexanderBl4h** [comment]
+1. That would be really nice!

**Comment by stephanrauh** [comment]
The component has been implemented and documented.
