### ISSUE TITLE
Bug: b:panel collapsible=false

### ISSUE THREAD

**Issue by jottyfan** [TheCoder4eu/BootsFaces-OSP#126]
regarding bootsfaces 0.7.0 from maven central repository

on using <b:panel collapsible="false" ..., the renderer renders a closing </a> tag from the collapsible=true configuration. This comes up by myfaces in a warning: HTML nesting warning on closing a: element h4 rendered by component...

Solution: fix rendering </a> only when collapsible != false

**Comment by jottyfan** [comment]
This is found in net.bootsfaces.component.panel.PanelRenderer line 162:

replace rw.endElement(H.A); by

if (isCollapsible) {
  rw.endElement(H.A);
}

Could anyone with write access please add this fix? Thanks!

**Comment by stephanrauh** [comment]
Done. Thanks for pointing this out!

**Comment by jottyfan** [comment]
Created a pull request for 0.8.0 that contains that bug even longer

**Comment by stephanrauh** [comment]
Oops - did I forget to commit my bugfix? In any case: thanks for your pull request!

Regards,
Stephan
