### ISSUE TITLE
Bug: Tooltip does not work without <b:button />

### ISSUE THREAD

**Issue by Pauldic** [TheCoder4eu/BootsFaces-OSP#128]
Think there is a bug with including tooltip.css file for pages that uses tooltip in components other than ```<b:button />```. Though in my case I had fix this by adding ```<b:button style="display: none" value=""  />``` in the template file that is shared across pages but I look towards a permanent fix

**Comment by stephanrauh** [comment]
Might be related to #107.

**Comment by AlexanderBl4h** [comment]
:+1:

**Comment by stephanrauh** [comment]
I localized the bug and started to work on it.

**Comment by stephanrauh** [comment]
Done.
