### ISSUE TITLE
Could you please add styleClass attribute to <b:dropMenu and <b:navLink

### ISSUE THREAD

**Issue by Pauldic** [TheCoder4eu/BootsFaces-OSP#129]
I would have loved to tweak the <b:navLink the achieve a multi-level menu as in this sample without writing raw html http://bootsnipp.com/snippets/featured/multi-level-navbar-menu or  http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3.

**Comment by stephanrauh** [comment]
According to the BootsFaces.jsfdsl, the attributes are also missing in
* alert
* badge
* buttonGroup
* buttonToolbar
* datepicker
* dropButton
* icon
* iconAwesome
* jumbotron
* label
* listLinks
* modal (only style)
* navBar
* navCommandLink
* navBarLinks
* selectMultiMenu (only styleClass)
* slider
* tabView (only style)
* thumbnail
* well

**Comment by stephanrauh** [comment]
b:dropMenu also needs a contentStyle and a contentStyleClass for the area that's dropping down.

**Comment by stephanrauh** [comment]
b:navLink also needs a contentStyle and a contentStyleClass for the anchor tag itself. Some of the dropdown CSS classes override the CSS attributes defined by style and styleClass (which are applied to the li tag surrounding the anchor tag).

**Comment by stephanrauh** [comment]
Done, tested and documented for b:navLink and b:dropMenu. There's an example project at https://github.com/stephanrauh/BootsFaces-Examples/tree/master/MultiLevelDropDown.

I'll open a separate ticket for the remaining components lacking style and / or styleClass.
