### ISSUE TITLE
Add style and styleClass to every visible BootsFaces component

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#131]
According to the BootsFaces.jsfdsl, the attributes are missing in
* ```<b:alert />``` (done)
* ```<b:badge />``` (done)
* ```<b:buttonGroup />``` (done since 0.9.0)
* ```<b:buttonToolbar />``` (done since 0.9.0)
* ```<b:datepicker />``` (done since 0.9.0)
* ```<b:dropButton />``` (done since 0.9.0)
* ```<b:icon />``` (done)
* ```<b:iconAwesome />``` (done)
* ```<b:jumbotron />``` (done since 0.9.0)
* ```<b:label />```
* ```<b:listLinks />```
* ```<b:modal />``` (only style)
* ```<b:navBar />```
* ```<b:navCommandLink />``` (done) (should be done in the same way as in b:navLink)
* ```<b:navBarLinks />```
* ```<b:selectMultiMenu />``` (only styleClass)
* ```<b:slider />``` (style and styleClass influence only the badge)
* ```<b:tabView />``` (done)
* ```<b:thumbnail />``` (done since 0.9.0)
* ```<b:well />``` (done since 0.9.0)

Container components may also need the attribute contentStyle and contentClass.

**Comment by yersan** [comment]
I'm taking care of this issue.

**Comment by MitchTalmadge** [comment]
:+1: Definitely needed. Thanks guys.

**Comment by stephanrauh** [comment]
We're almost there. The only components without styles are:

* accordion
* listLinks
* navBarLinks
* pillLinks
* scrollUp
* scrollSpy
* tabLinks
* tree

`b:selectMultiMenu` doesn't support `style-class`for technical reasons.

**Comment by stephanrauh** [comment]
Finally, the issue has been completed and documented!

**Comment by MitchTalmadge** [comment]
Nice :)
