### ISSUE TITLE
Improve b:modal

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#132]
@dabloem suggests to improve the ```<b:modal />``` component. Currently, neither the header, nor the content, nor the footer has an id, which makes it a little awkward to implement an AJAXified wizard within a modal dialog.

**Comment by TheCoder4eu** [comment]
+1

**Comment by stephanrauh** [comment]
@dabloem I didn't hear from you for a long time. Is this still something you want to do?

**Comment by Robblle** [comment]
A footer for b:modal that appears inside a <h:form> would be nice since the <f:facet type="footer"/> disappears.

**Comment by TheCoder4eu** [comment]
@Robblle could you explain a little what you mean exactly?

**Comment by Robblle** [comment]
I'm sorry. I forgot to add the insert code marks

**Comment by stephanrauh** [comment]
@Robblle I've just made your code visible :).

**Comment by TheCoder4eu** [comment]
@stephanrauh thx I just didn't think about it ;-)

**Comment by TheCoder4eu** [comment]
@Robblle ok, now I understand better, would you mind open a different issue about this?

**Comment by TheCoder4eu** [comment]
@Robblle I'm closing this issue, please add another Issue for what we discusser earlier. Thanks.
