### ISSUE TITLE
Parameters in taglib do not match names in code.

### ISSUE THREAD

**Issue by kainoffke** [TheCoder4eu/BootsFaces-OSP#137]
The bootsfaces-taglib defines a parameter named '*columnclasses*' for the panelGrid component.
However, the parameter evaluated in the corresponding renderer class is named '*columnClasses*' (capital c). The result is, that when using the parameter name from the taglib as suggested by the IDE, the css classes are not being rendered. 

For better explanation; this works:

`<b:panelGrid colSpans="2,10"  columnClasses="class,class"/>`

This does not:

`<b:panelGrid colSpans="2,10"  columnclasses="class,class"/>`

**Comment by stephanrauh** [comment]
Plus, the attribute `rowClasses` was missing both in the documentation and in the taglib.
