### ISSUE TITLE
Modals do not escape component clientId

### ISSUE THREAD

**Issue by jbmb** [TheCoder4eu/BootsFaces-OSP#138]
When using `<b:modal>` component, initializing javascript is generated. However, the clientId contained here does not escape special chars (e.g. '`:`'), there is an error in the javascript console, even in the bootsfaces showcase.

**Comment by jbmb** [comment]
I have a fix prepared, I'm gonna commit it in a while.

**Comment by stephanrauh** [comment]
Thanks. Whow, you even added a unit test! 

May I ask why you removed the "fade" class? Is it unnecessary or wrong?

``` java
String styleClasses = "modal" + " fade";
```

**Comment by stephanrauh** [comment]
Successfully tested (see http://www.bootsfaces.net/BootsFacesWeb/bootstrap/modal.jsf).

**Comment by jbmb** [comment]
Sorry, I haven't commented the 'fade' thing - from my perspective, this class in undesirable. It enforces the fade effect even if I don't want it. However, it may be added via `styleClass` whenewer needed.
Are you ok with this change?

**Comment by stephanrauh** [comment]
Yes, it's fine by me. But we have to document it because it's sort of a breaking change.

**Comment by stephanrauh** [comment]
Done: #143.
