### ISSUE TITLE
`<b:messages` does not display any severity (warn, info, etc)

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#141]
`<b:messages` does not display any severity (just plain text).
Working minimal example to reproduce the error: 
```xml
	<h:form>
		<b:messages id="messsage" />	
		<b:inputText required="true"
			requiredMessage="That field is required, dude!" />

		<b:commandButton value="Invoke me!" update="@form" />
	</h:form>
```
I got an OK workaround with adding `	<b:alert rendered="false" />` below the `<b:messages`.

**Comment by stephanrauh** [comment]
Actually, your minimal code snippet doesn't look that bad to me:
<img width="493" alt="bildschirmfoto 2015-07-27 um 23 40 20" src="https://cloud.githubusercontent.com/assets/3045767/8918578/211fd984-34b9-11e5-968a-33894b8d2875.png">

I take it that it looks different on your machine?

**Comment by AlexanderBl4h** [comment]
Yes, it did. I added a complete example of my page, with screenshot. I am using WildFly 8.2.0 and BootsFaces 0.7.0.
![examplemessagefailed](https://cloud.githubusercontent.com/assets/13524849/8918692/f080952e-34b9-11e5-8aff-58726b14a2d2.PNG)

**Comment by stephanrauh** [comment]
Strange. Try https://github.com/stephanrauh/BootsFaces-Examples/tree/master/Messages. This project contains both your minimal example (localhost:8080/BootsFacesMessages/faces/minimal.xhtml) and a - slightly silly - example showing three severity levels (localhost:8080/BootsFacesMessages/faces/index.xhtml).

**Comment by AlexanderBl4h** [comment]
Sorry, I have no real idea, how to include this examples into my eclipse. I tried importing this one and then create a maven project (with archtype). It does not work properly. Maybe you can give me a step by step introduction? I'd really like to see your examples.

**Comment by stephanrauh** [comment]
It already is a Maven project. So everything you have to do is to import it as a Maven project:
<img width="533" alt="bildschirmfoto 2015-07-28 um 22 25 42" src="https://cloud.githubusercontent.com/assets/3045767/8942826/e86f2c92-3577-11e5-89bd-9bfcc45652f4.png">
<img width="652" alt="bildschirmfoto 2015-07-28 um 22 26 57" src="https://cloud.githubusercontent.com/assets/3045767/8942832/f10c00c8-3577-11e5-9c37-455793239cdb.png">

**Comment by AlexanderBl4h** [comment]
Thanks! I could reproduce the working example very well. I copied your example into my test-page. It does not work there. But it does work with your project. It is not the BF version, I am using `0.7.0` in both cases.

**Comment by stephanrauh** [comment]
I'm sure there's a difference :). Maybe a forgotten h:head tag? You can also check the generated HTML code, and the list of CSS classes that are loaded (or not). I suppose there's an important resource file missing.

**Comment by AlexanderBl4h** [comment]
No, no! The code is EXACTLY the same. No difference. Really, no difference. It is maybe the project-setup. But I am out of ideas.

**Comment by stephanrauh** [comment]
Maybe the CombinedResourceHandler in the faces-config.xml or the BootsFaces theme in the web.xml?

**Comment by AlexanderBl4h** [comment]
The BootsFaces theme in the web.xml did the trick. Can you please explain, what this exactly is?

**Comment by stephanrauh** [comment]
The BootsFaces theme is the definition of the look and feel of the components. Bootstrap is a base framework defining a couple of CSS classes you can use to layout HTML pages. The typical Bootstrap look is just the default theme. Apart the default theme, there are quite a few custom themes. In fact, there are even web designers you create your individual custom theme for small money. A good source for free themes is https://bootswatch.com/.

We want to support each of these custom themes. Therefore, you have to activate the default theme manually.
