### ISSUE TITLE
BootsFaces 0.8.0 ship list

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#143]
**New components:**
* <code>&lt;b:switch /&gt;</code>
* <code>&lt;b:image /&gt;</code>
* <code>&lt;b:carousel /&gt;</code>
* <code>&lt;b:inputTextarea /&gt;</code>

**Themes:**
We introduced support for Bootswatch Themes, for those wanting to use the build system to build a version with a Bootswatch Theme instead of plain Bootstrap.

**Improvements:**
* We've converted the build system to Gradle, making it more simple to install the source code version of the project. There's also a Maven build, which is even more simple, but relies on Gradle to build the resource files (CSS and JS files). Have a look to BUILD-GRADLE.txt and BUILD-MAVEN.txt respectively for details.
* We've experimented with Grunt to concatenate and minify the CSS sources. That didn't work reliably enough, so we've dropped Grunt again.
* Unified and improved AJAX for b:commandButton, b:selectBooleanCheckbox, b:selectOneMenu, b:inputText, b:icon, b:iconAwesome, b:image, b:carousel, b:tabView, b:tab (to be continued).
* The unified AJAX engine now supports both partial processing and partial updates.
* BootsFaces AJAX offers limited support for <code>&lt;prime:ajax /&gt;</code>.
* The asterik of required fields is added by the CSS class `bf-required`.
* Both the field and the label bear the CSS class `bf-no-message`, `bf-info`, `bf-warning`, `bf-error` or `bf-fatal`, depending on the severity (or existence) of the FacesMessage associated with the input field.
* By default, `bf-error` and `bf-fatal` color the label red. `bf-warning` colors the label orange.
The feature has been implemented for `b:inputText`, `b:selectOneMenu`, `b:selectMultiMenu` (although this currently doesn't render labels) and `b:slider`.
* The new BootsFaces Seach Expressions API supports most of the advanced PrimeFaces Search Expressions and adds a few new search expressions, such as Unix-style wildcards.
* Many options to influency resource file loading and ordering (#121, #197).
* <code>&lt;b:dropMenu /&gt;</code> can optionally show an icon.
* We've added a <code>disabled</code> attribute to most BootsFaces components.
* Menus and submenus can now be nested (see #133).
* We've added the attributes <code>style</code> and <code>styleClass</code> to many components. In some cases, we've also added <code>contentStyle</code> and <code>contentStyleClass</code>.

**Bug fixes:**
* Various bugfixes concerning tooltips:
** A tooltip now has a <code>tooltip-container</code> attribute that's converted to the Bootstrap attribute <code>data-container</code>. The default value is "body".
** The last button of a <code>&lt;b:buttonGroup /&gt;</code> didn't have rounded corners when it had a tooltip. Now that's fixed.
* <code>&lt;b:selectBooleanCheckbox /&gt;</code> now works without AJAX. Previously, it could be checked, but it couldn't be unchecked again.
* If you page had multiple navbars, they didn't expand and collapse independently on small screens. Expanding one of them expanded each of them. We've fixed that.
* <code>&lt;b:messages /&gt;</code> now has a "close" icon.
* We've improved the escaping of IDs and modified several IDs  so they don't have to be escaped. The rationale behind that is that jQuery doesn't cope with the standard JSF IDs which contain colons.
* Corrected the taglib. It didn't always align with the real components. So your IDE offered you wrong attributes, attributes that didn't exist or it didn't show every attribute. Now that's fixed.
* <code>&lt;b:selectOneMenu /&gt;</code> respects the attribute <code>required</code>.
* <code>&lt;b:commandButton /&gt;</code> can now be used with <code>&lt;ui:repeat /&gt;</code>.
* Fixed the resource dependencies of several components. 
* Corrected the HTML code of collapsed panels (see #126).
* <code>&lt;b:button /&gt;</code> now supports <code>outcome="@none"</code>, <code>outcome=""</code> or simply no outcome to suppress the default behavior.
* fixed disabled <code>&lt;b:selectBooleanCheckboxes /&gt;</code>. It lost its value after a request (#111).

**Breaking changes:**
* We've removed the "fade" class from modal dialogs (`<b:modal />`). This gives you the opportunity to decide yourself if you need the fade effect or not. If you do, add "fade" to the list of styleClasses.
* The id of b:icon and b:iconAwesome is not the regular client id, without the suffix _icon, unless it's an appended or a prepended icon.
* The HTML code of several components uses a slightly different id than they used in previous versions. Instead, they use ids that are compatible to jQuery. In most cases, you shouldn't even notice, because you couldn't do anything with the ids anyways.

**Comment by TheCoder4eu** [comment]
We started Release.
