### ISSUE TITLE
some icons are not working in `<b:commandButton>`

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#146]
I got a datatable with editing entries: pencil-button to edit an item, minus-button to delete, plus-button to create and ok-button to save the edited item. The ok-icon does not work, properly? 

![iconsbf](https://cloud.githubusercontent.com/assets/13524849/8959086/1dcb2508-3609-11e5-9b44-145123370d56.PNG)

As you can see, the icon is missing with following mark up:

    <b:commandButton value="" iconAwesome="ok" rendered="#{jahrgang.editable}"
								look="info" size="xs" ajax="true" update="@form"
								action="#{adminKonfigurationJahrgang.speichereJahrgang(jahrgang)}">
    </b:commandButton>

Just to compare (all of those are working, doesnt matter if pencil. minus or plus (see below)):

     <b:commandButton value="" iconAwesome="pencil/minus/plus"
								rendered="#{!jahrgang.editable}" look="info" size="xs"
								ajax="true" update="@form"
								action="#{adminKonfigurationJahrgang.editiereJahrgang(jahrgang)}" />

**Comment by yersan** [comment]
BootsFaces is using Font Awesome v4.3.0. In that version ok icon is named check.
Use check instead of ok and you should be able to see the correct icon:

```xml
<b:commandButton value="" iconAwesome="check"
                            rendered="#{!jahrgang.editable}" look="info" size="xs"
                            ajax="true" update="@form"
                            action="#{adminKonfigurationJahrgang.editiereJahrgang(jahrgang)}" />
```

**Comment by AlexanderBl4h** [comment]
Oh, I did not know that, apperently. Thanks for the hint. It does work perfectly.

**Comment by yersan** [comment]
Your're welcome !
