### ISSUE TITLE
missing disabled attribute in components

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#147]
Like many other components, the `<b:slider>` for example has no `disabled` as attribute. 
I really have no idea, if that is your intended or not. It might be useful - all components should have one. 

Is there any chance to get a new version with those fix, quickly? 

If not, for a `<b:slider>` is there any workaround to use `mode="badge"` and NOT manipulating the value with the slider?

**Comment by stephanrauh** [comment]
Let's start with "how to get a new version". I've uploaded an untested developer snapshot of BootsFaces 0.8.0:
https://oss.sonatype.org/content/repositories/snapshots/net/bootsfaces/bootsfaces/0.8.0-SNAPSHOT/

You can access this in your pom.xml after adding a new repository:
``` xml
     <repositories>
        <repository>
          <id>central</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
```

The download coordinates of the snapshot version are:
``` xml
<dependency>
	<groupId>net.bootsfaces</groupId>
	<artifactId>bootsfaces</artifactId>
	<version>0.8.0-SNAPSHOT</version>
	<scope>compile</scope>
</dependency>
```

**Comment by AlexanderBl4h** [comment]
I am getting following error while using the snapshot version. :( 

08:53:25,849 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-11) Unable to save dynamic action with clientId 'j_id9' because the UIComponent cannot be found

**Comment by stephanrauh** [comment]
I added the disabled attribute and uploaded a developer snapshot. I've opened a dedicated ticket to track the snapshots (#150).

@AlexanderBl4h Does the new snapshot fix your problem with the b:commandButton?

**Comment by AlexanderBl4h** [comment]
Yes, both is solved. Thanks!
