### ISSUE TITLE
f:param ignored in b:commandButton

### ISSUE THREAD

**Issue by radarada** [TheCoder4eu/BootsFaces-OSP#152]
The `f:param` tags of `b:commandButton` are being ignored.

Using standard `h:commandButton` they are passed via the HTTP POST request but they are missing when using the `b:commandButton`.

**Comment by AlexanderBl4h** [comment]
Those buttons are making such hard problems, so far.

**Comment by stephanrauh** [comment]
Actually, I'm not sure why I should implement ```f:param```. EL 2.2 allows you to pass parameters to the method. Does ```f:param``´ add any additional value?

**Comment by radarada** [comment]
Hmmm... yes, if I change my code to use the parameters then everything works fine...
So why not to do it because... because the JSF supports it :-)
...also b:button supports it so I'd assume that adding this functionality into the command button won't be a big challenge.

**Comment by AlexanderBl4h** [comment]
Well, it may not be a big deal to implement this. You may want to head to [Stackoverflow](http://stackoverflow.com). You can ask your question there. I bet, it is not the fault of not implementing the `<f:param>`.

**Comment by stephanrauh** [comment]
Well, if ```<b:button />``` supports ```<f:param />``´, there's no point in denying these params to ```<b:commandButton />```.

**Comment by AlexanderBl4h** [comment]
Oh, I misread this, because there was no code highlight of `<b:button>`. :/ Yes, than why not. :+1:

**Comment by stephanrauh** [comment]
Postponed to 0.9.0.

**Comment by cooper-lyt** [comment]
+1
CDI conversation Id need f:param

`  <f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>`

**Comment by stephanrauh** [comment]
@cooper-lyt THX for the hint! I wasn't aware of this.

**Comment by stephanrauh** [comment]
I've just started to investigate the topic. First impression: I can confirm the bug. Using f:param means to put the parameter into the request scope, but b:commandButton won't do such a thing.

**Comment by stephanrauh** [comment]
Done and documented.
