### ISSUE TITLE
<b:commandButton> got multiple times invoked in a <h:dataTable>

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#153]
FYI: I am using the latest snapshot version, see #151.

Consider following example:

	<h:form>
		<h:dataTable var="benutzer" value="#{bean.users}">
			<h:column>
				<b:commandButton look="info" size="xs" action="#{bean.print}"
					ajax="true" update="@form" value="#{user.name}" />
			</h:column>
	</h:form>

`users` is just a `java.util.List` with an user entity, nothing special. The method got invoked for *EVERY* row.

Also  I got following error message: 

`15:38:39,804 WARNING [javax.enterprise.resource.webcontainer.jsf.application.view] (default task-31) Unable to save dynamic action with clientId 'j_id35' because the UIComponent cannot be found`

**Comment by stephanrauh** [comment]
Most likely, that's the same problem as #135.

**Comment by AlexanderBl4h** [comment]
Well, #153 is fixed in 0.7.0. It does work perfectly in this version (for me!).

**Comment by stephanrauh** [comment]
Solved in BootsFaces 0.8.0. You can already test it in the developer snapshot (see #151 ),
