### ISSUE TITLE
<b:selectonemenu> error

### ISSUE THREAD

**Issue by vishwasreddy** [TheCoder4eu/BootsFaces-OSP#155]
<h:form>
<b:selectOneMenu  value="#{----}" onchange="submit();">
<f:selectItems value="#{------}"/></b:selectOneMenu>
</h:form>

included jar files . But my page is in .jsp page i cannot change it into jsf (project requirement)
but included taglibs.....what should i do urgent please.....

**Comment by stephanrauh** [comment]
I guess you've solved your urgent problem yourself? Wish every problem would solve itself so quickly :).
