### ISSUE TITLE
Tomcat 7.x ist not working with resources

### ISSUE THREAD

**Issue by okroener** [TheCoder4eu/BootsFaces-OSP#157]
Hi,

I tried to setup bf with Tomcat 7.x and the CSS resources are not working, I can only see an empty file ... tried already all tricks in "quickstart".

With Tomcat 8.x everything works out excellent? Are there some known issues with Tomcat 7?

Thanks,

Oliver

**Comment by stephanrauh** [comment]
I checked it a minute ago, just to be sure: BootsFaces runs fine with both Tomcat 7 and Tomcat 8.

But there's a nasty problem with resources. Usually, adding the CombinedResourceListener of OmniFaces solves the problem. BTW, most of the times it not every resource that's missing, but only certain classes of resources (Glyphicons or FontAwesome icons). Which class of resources are missing in your application?

There's a working example at https://github.com/stephanrauh/BootsFaces-Examples/tree/master/AJAX. Try the NavBar demo page (http://localhost:8080/BootsFacesAJAX/NavBar.jsf)

**Comment by stephanrauh** [comment]
I just noticed something very strange: the AJAX example I mentioned above had a wrong welcome file ("faces/index.xhtml" instead of "index.jsf"). The default page was rendered more or less correctly nonetheless, only the expand/collapse icon of the panel (a Glyphicon) was missing. Oliver, maybe that's something worth checking?

**Comment by okroener** [comment]
I checked that now also .... when I run it with Tomcat 8 /javax.faces.resource/css/bsf.css?ln=bsf the ln=bsf is added correctly, if running with Tomcat 7 the ln=bsf is missing and the resource is not loaded ... however if manually add ln=bsf the resource is loading ...

**Comment by stephanrauh** [comment]
That's a very strange error. It suspect there's something wrong with the configuration of either your Tomcat 7 or of your application. What does your faces-config.xml and you web.xml (in particular the servlet mapping) look like?

**Comment by okroener** [comment]
faces-config.xml:

<?xml version="1.0" encoding="UTF-8"?>

<faces-config version="2.2" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd">

	<application>
		<resource-handler>net.bootsfaces.render.UnmappedResourceHandler</resource-handler>
	</application>

</faces-config>

web.xml:

<?xml version="1.0"?>
<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
	<display-name>Health8</display-name>
	<welcome-file-list> <welcome-file>index.xhtml</welcome-file> </welcome-file-list> 
	<servlet>
		<servlet-name>Faces Servlet</servlet-name>
		<servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>Faces Servlet</servlet-name>
		<url-pattern>*.xhtml</url-pattern>
		<url-pattern>/javax.faces.resource/*</url-pattern>
	</servlet-mapping>
	<context-param>
		<param-name>BootsFaces_USETHEME</param-name>
		<param-value>true</param-value>
	</context-param>
	
</web-app>

thx

**Comment by stephanrauh** [comment]
* Remove the url-pattern `javax.faces.resource/*`. It true that I once recommended it, but I believe that's wrong.
* Replace  (just for a test) our `UnmappedResourceHandler` by the `CombinedResourceHandler` of OmniFaces and set the development stage to `Production`. Does that help?

**Comment by okroener** [comment]
Yes, many thanks! That solved the issue!

**Comment by okroener** [comment]
Yes, many thanks! That solved the issue!

**Comment by okroener** [comment]
Yes, many thanks! That solved the issue!
