### ISSUE TITLE
Enhancement: components with "label" attribute lack the ability to apply label styles

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#158]
Components like b:inputText have the "label" attribute and nicely render a form-group with a label etc. However in order to do horizontal forms one needs to set class of the label to "control-label". Currently there isn't (to my knowledge) an easy way to do this with BootsFaces.

It would have been nice if we had some "labelClass" attribute available.

**Comment by vsvetoslavov** [comment]
Also another alternatives may be considered, like:
* facet: <facet name="label"><h:outputLabel value="test" styleClass="myClass" /></facet>
* support for some sort of layout - i.e. layout attribute with values "normal", "inline", "horizontal" - like the types of forms supported by Bootstrap. Then depending on the layout different html code might be rendered.
* maybe something better
* combinations of the above suggesttions
Please also bear in mind that at least in the examples, horizontal forms tend to rely on columns for both labels and controls, so setting columns for labels might also turn out to be a necessity

**Comment by stephanrauh** [comment]
We've already implemented similar things for other aspects of an component, so I think we should implement this feature analogously: by adding the attributes `label-style` and `label-style-class` to each of these widgets:
![image](https://cloud.githubusercontent.com/assets/3045767/14724812/b16f9a3c-0818-11e6-8ab9-86be315d7c68.png)

**Comment by stephanrauh** [comment]
I've just implemented and tested this feature.
