### ISSUE TITLE
Severity is not working in <b:badge>

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#160]
```xml
<b:badge value="1" severity="warning"/>
<b:badge value="1" severity="success"/>
<b:badge value="1" severity="info"/>
<b:badge value="1" severity="error"/>
<b:badge value="1" severity="important"/>
<b:badge value="1" severity="inverse"/>
```

None of them is working. It is always `default`.

**Comment by stephanrauh** [comment]
Bootstrap 2 did support colorful badge. However, they removed the `severity` css from badges in Bootstrap 3. I noticed this yesterday, too, and removed the `severity` attribute from the taglib. Starting with BootsFaces 0.8.0, it won't be offered by the autocomplete function.
