### ISSUE TITLE
How can I implement a <b:modal> as security check?

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#161]
Imagine, I have a `<h:dataTable>` with some entries do modify (for instance delete this entry). 
Now, I implemented a security check, with `<b:modal>` and two `<b:comamndButton>` inside.  The `<b:modal>` is inside the same form. (I know, that is bad, but it works fine so far.). 
In the modal, the selected data should be shown - I did it with calling the setter and a property in the managed bean. Well, for now, the modal crushes other components of my page (eg tooltip). I want to extract the modal and put it outside the form. The modal should include a form (for the comamndbuttons).

I got a example right below: 

	<h:form>
		#{bean.text}
		<b:commandButton value="Trigger Dialog" ajax="true" update="@form modalDialogID"
			action="#{bean.setText('Text')}"
			oncomplete="$('.modalPseudoClass').modal();return false;" />
	</h:form>

	<b:modal id="modalDialogID" styleClass="modalPseudoClass" title="My Modal">
		<h:form>
			#{bean.text}
			<b:commandButton value="ok" action="#{bean.submit}" oncomplete="$('.modalPseudoClass').modal('hide');return false;" />
			<b:commandButton value="cancel" />
		</h:form>
	</b:modal>

Just create a Managed Bean and put it in ViewScope. Create a method `submit`, which changes the text of the property.

Actually, the modal does not display the correct text after invoking via `<b:commandButton>` 

Can you help me out? :)

**Comment by stephanrauh** [comment]
You must be aware that the modal dialog is rendered when the JSF page is rendered - which is before the use made their choice. You fixed this by adding AJAX (`update="@form"`) and by opening the modal dialog in the `oncomplete` callback. When you moved the modal out of the form, it isn't updated any more. So you have to expand the update region. In BootsFaces 0.8.0, you can write `update="@form @form:@next"`. Actually,  `update="@form:@next"` probably does the trick, too, because it's only the modal dialog you want to update. Until BootsFaces 0.7.0, you can't use @form:@next. Instead, you can add an id to the modal: `update="modalDialogID"`.

**Comment by AlexanderBl4h** [comment]
Actually, the CommandButton is not invoked. it is, because the button isn't rendered in first instance?

**Comment by stephanrauh** [comment]
@AlexanderBl4h Do you refer to number 8 of Baukes long list?

**Comment by AlexanderBl4h** [comment]
@stephanrauh Yes, I did. :) Sorry, that should I have mentioned.

**Comment by stephanrauh** [comment]
OK, it's really the error Bauke refers to. The interesting thing is that the error even occurs with out new unified AJAX engine. I've provided a reproducer here: https://github.com/stephanrauh/BootsFaces-Examples/blob/master/AJAX/src/main/webapp/issue161.xhtml.

To fix the example, don't update the modal dialog, but just the form inside it:
```Java
<h:form id="firstForm">                                                            
  #{bean161.text}                                                                  
  <b:commandButton value="Change text and trigger Dialog" ajax="true"              
		update="@form :secondForm" action="#{bean161.setText('new text')}"         
		oncomplete="$('.modalPseudoClass').modal();return false;" />               
</h:form>                                                                          
                                                                                   
<b:modal id="modalDialogID" styleClass="modalPseudoClass"                          
	title="My Modal">                                                              
	<h:form id="secondForm">                                                       
#{bean161.text}                                                                    
<br />                                                                             
Closing this dialog will update the main form.                                     
<b:commandButton value="OK" action="#{bean161.ok}"                                 
			onclick="ajax:bean161.ok()" ajax="true" update=":firstForm"            
			oncomplete="$('.modalPseudoClass').modal('hide');return false;" />     
		<b:commandButton value="cancel" />                                         
	</h:form>                                                                      
</b:modal>                                                                         
```
