### ISSUE TITLE
Command Button not working

### ISSUE THREAD

**Issue by okroener** [TheCoder4eu/BootsFaces-OSP#162]
Hello,

Im have a simplte form with an commandButton:

```xml
<ui:fragment rendered="#{!user.isLoggedIn}">

				<div class="form-group">
					<b:inputText placeholder="Email" fieldSize="sm"
						value="#{login.email}" />
					<!--input type="text" class="form-control" placeholder="Search"/-->
				</div>
				<div class="form-group">
					<b:inputText placeholder="Password" fieldSize="sm"
						value="#{login.password}" />
				</div>
                #{' '} 
                <b:commandButton action="#{login.processLogin}" 
					value="Login" icon="glyphicon-lock"></b:commandButton>

			</ui:fragment>
```

But action is not fired ... when I use

**<h:**commandButton>

instead, it works? Any idea why this happens?

thx

Oliver

**Comment by stephanrauh** [comment]
At first glance, I don't see anything wrong. You're using BootsFaces 0.7.0, I guess? And when you open your browsers F12 tools, does the `<b:commandButton />` fire any request? If so, is it an AJAX request or a post request?

**Comment by okroener** [comment]
Yes, directly from the repository ...

<**b**:...> renders:

```html
<button type="submit" id="login:j_idt24" name="login:j_idt24" class="btn btn-default"><span><i id="login:j_idt24" class="glyphicon glyphicon-lock"></i></span> Login</button>
```

and <**h**:...> renders the input element:

```html
<input type="submit" value="Login" name="login:j_idt24">
```
Any idea?

**Comment by AlexanderBl4h** [comment]
@okroener Oliver, I would recommend to not use `<ui:fragment>`. Did you try it without? I have no idea, what is going wrong, but that could be a start.

**Comment by stephanrauh** [comment]
If you're building BootsFaves 0.8.0 from source, there's a simple answer: I broke the non-ajax functionality when I started to implement the new unified AJAX API. Thanks for the hint!

**Comment by AlexanderBl4h** [comment]
So `Yes, directly from the repository ...`, is irritating...

**Comment by stephanrauh** [comment]
@AlexanderBl4h Why? What's wrong with using ui:fragment?

**Comment by AlexanderBl4h** [comment]
Thought, that could be the problem in first instance. I am using the `rendered` attribute from `row and col` for this purpose - it is responsive anyway.

**Comment by stephanrauh** [comment]
@AlexanderBl4h I've edited one of your comments - hope you like it :).

**Comment by okroener** [comment]
Ok, as I understand its a bug, so nothing wrong with the code ...

**Comment by AlexanderBl4h** [comment]
@stephanrauh Mein Englisch ist leider nicht so perfekt, wie deins. :) Thanks!
@okroener Yes, it is a bug. :)

**Comment by stephanrauh** [comment]
@AlexanderBl4h Wenn mich nicht alles täuscht, chatten im Moment eh drei Deutsch miteinander. Und das auf englisch. Ich hätte aber auch noch Spanisch im Angebot :).

**Comment by okroener** [comment]
Das scheint so ... Buenas tardes :-)

**Comment by stephanrauh** [comment]
Ich bin gerade verwirrt. Helft mir mal auf die Sprünge. Kann ich im Rückgabewert der Action nur JSF-Seiten angeben, aber nicht z.B. Google.de? Oder habe ich einen Fehler eingebaut?

```xml
<b:commandButton value="non AJAX" 
							actionListener="#{imageGallery.chooseAnotherImage(image)}"
							action="#{AJAXBean.standardJSFAction}"
							 />
```
```java
public String standardJSFAction() {
    report("Standard JSF action called");
//    return "checkboxOnly.jsf";  // redirects to the target page
    return "checkboxOnly.jsf"; // does not redirect
}
```

**Comment by stephanrauh** [comment]
Hm, die Weiterleitung auf http://www.google.es funktioniert auch mit h:commandButton nicht. Unerwartet, aber anscheinend kein neuer Fehler...

**Comment by AlexanderBl4h** [comment]
Warum sollte die Weiterleitung aus der Anwendung heraus in der Methode als Rückgabewert zu definieren sein? Das ergibt keinen Sinn. Der Rückgabewert ist nur für interne Navigation, so wie ich es verstanden habe. Ich würde für solche Weiterleitungen einfach einen normalen Link nehmen. Und wenn es im Backend sein muss: http://stackoverflow.com/questions/5955130/jsf-page-redirecting-from-java-bean

**Comment by stephanrauh** [comment]
Ich hätte erwartet, dass es funktioniert, weil man gerne "orthogonale" Frameworks baut. Sprich: Konzepte, die an einer Stelle funktionieren, funktionieren auch an jeder anderen Stelle, wo man sie verwenden kann. In diesem Fall: ein b:commandLink akzeptiert sowohl interne als auch externe Navigation. Ein b:commandButton akzeptiert sowohl interne als auch externe Navigation - äh - nicht. So gesehen, ist es schon verwirrend, oder?

**Comment by okroener** [comment]
@AlexanderBl4h: thx it's working now!

**Comment by AlexanderBl4h** [comment]
Ehrlich gesagt, habe ich diese Navigation mit dem Rückgabetyp noch nie verwendet. Finde ich als Konzept irgendwie sinnlos, aber jedem das seine. Aber zu deinem Punkt: Es ist ja ein Unterschied, ob Frontend oder Backend. Aber verstehe dich auch. Aber der Usecase würde mich mal interessieren.

**Comment by AlexanderBl4h** [comment]
@okroener You are welcome! :) Do you use `<b:row>` with `rendered` now?

**Comment by stephanrauh** [comment]
As far as I can see, the non-AJAX API of b:commandButton now works flawlessly. What's missing is the ajax facet, such as
```xml
<b:commandButton value="f:event"                                                             
	actionListener="#{imageGallery.chooseAnotherImage(image)}"                               
	action="#{AJAXBean.standardJSFAction}">                                                  
	 <f:ajax listener="#{AJAXBean.standardJSFActionListener}" update=":messages"></f:ajax>   
</b:commandButton>                                                                           
```

I'll track progress on f:ajax is tracked in #134.

**Comment by stephanrauh** [comment]
@AlexanderBl4h Hm, Usecase... wir hatten im Projekt einfach für alles den CommandButton verwendet, weil wir keinerlei Logik im Frontend haben wollten. Und Ziel-URLs sind - im weitesten Sinne - auch Logik. Das ist jetzt aber eher "historisch gewachsen" und nicht "sorgfältig-darüber-nachgedacht-und-dann-entschieden".

**Comment by okroener** [comment]
@AlexanderBl4h: Ich verwende immer noch ui:fragment ...
