### ISSUE TITLE
b:buttonGroup, b:button and tooltips - last button has no round corners

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#164]
Currently when buttons in a button group have tooltips, the last button in the button group does not have rounded corners. Digging  a bit, I found that in bootstrap the definition for the last button in a button group is like '.btn-group .btn:last-child'. However this is not entirely correct, because BootsFaces renders a small script for tooltips after each component that has a tooltip set. The latter however doesn't always work. It is clearly visible in the examples that some of the tooltips are tooltips (like callouts) while others are plain titles - for example the datepicker's trigger button etc. etc.

It would be nice if the buttons don't lose their round corners when tooltip is set.

**Comment by stephanrauh** [comment]
That's a very surprising side effect. You've got sharp eyes!

**Comment by vsvetoslavov** [comment]
I noticed one more nasty effect with tooltips and button groups - if the tooltip is rendered in the same container (the default behavior), then buttons may get displaced because the `div` rendered between buttons affects the css styling a bit. Using a `data-container` seems to fix the problem.

**Comment by stephanrauh** [comment]
This issue seems to be fixed by both #165 and #166.

**Comment by stephanrauh** [comment]
The problem still exists because Bootstrap still accidentially counts the Javascript node as a widget node.

**Comment by stephanrauh** [comment]
Solved the problem by moving the JavaScript code into the button.
