### ISSUE TITLE
Tooltips not applied in some situations

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#165]
Currently on some components the tooltip is not shown as a tooltip, but as a title. This can be seen very clearly in the demo page of tooltips - http://www.bootsfaces.net/bootstrap/tooltips.jsf

My tests indicated that the following jquery script seems to fix the problem:
```javascript
$('[data-toggle="tooltip"]').tooltip();
```
This seems to make rendering a script for each component's tooltip unnecessary (thus also fixing the button group problem). Maybe some flag can be checked when a component needs a tooltip, in order for the script to be rendered. Of course all this is just a proposal how to achieve the goal of making tooltips work ;)

**Comment by vsvetoslavov** [comment]
Components where no tooltip is applied (taken from the demo page):
* datePicker - the trigger
* icon, iconAwesome
* inputText, inputSecret - the prepend facet, and no title nor tooltip in the input itself
* selectBooleanCheckbox
* selectOneMenu - no title nor tooltip
* slider

**Comment by stephanrauh** [comment]
In the case of b:inputText, things look a bit odd. Instead of adding the tooltip to the inputtext, where it belongs, it is added to the surrounding table. But of course it is activated for the input field, not for the table.

**Comment by stephanrauh** [comment]
As for the global activation of tooltips: introducing a global flag would also allow us to solve #107.

**Comment by stephanrauh** [comment]
I fixed the components without introducing a global flag.
