### ISSUE TITLE
Add container to tooltips

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#166]
Tooltips render divs which may cause trouble with button groups. For this and other reasons bootstrap provides the option to specify the "data-container" attribute (and 'body' as value for a starter). It will be very nice to have this attribute available - i.e. via tooltip-container attribute.

**Comment by stephanrauh** [comment]
I couldn't find out what the data-container attribute does precisely. Is it enough to always add data-container="body", or should the attribute be configurable?

**Comment by vsvetoslavov** [comment]
The data-container property specifies the container where tooltips are generated - and by tooltip here I mean the actual `<div>` tag that has `z-index`. See the container explained here: http://getbootstrap.com/javascript/#tooltips-options
The weird thing - I could only make it work via the data-container property - calling `.tooltip({container: 'body')` did not work for me. 
The data-container property is string - it is selector for the container element to use - ids may be passed like `data-container="#myContainer"`.

**Comment by stephanrauh** [comment]
Done. Every tooltip can optionally have a tooltip-container attributes that's translated to data-container. The default value is "body".
