### ISSUE TITLE
Mixed Bugs in staging

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#171]
Hi,
I noticed the following issues in staging:
* datepicker demo has bugs
    * toggle icon does not work and has misalignment issues (js ?)
    * multiple calendar does not work
* "More Sliders" menu entry throws ID not found: amodal search expression: amodal

Do you suspect any recent change for this?

**Comment by TheCoder4eu** [comment]
"More Sliders" demo has problems anyway, since a new build running on my local PC does not work anymore (I don't see the error I see in staging), I do not see the clock.
The error in staging might disappear if I restart the App server.

**Comment by stephanrauh** [comment]
The demo still works flawlessly on my machine. Disturbing.

**Comment by stephanrauh** [comment]
Actually, the error message is correct. There's no modal dialog in the demo. My new Search Expressions Engine checks the IDs more rigorously than its JSF counterpart.

**Comment by stephanrauh** [comment]
I fixed the "more sliders" demo. Now the command button opens a modal dialog.

**Comment by stephanrauh** [comment]
The multiple calendar demo now works, too.
