### ISSUE TITLE
Why does a <b:slider> render a <div col-4-md ...>?

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#172]
I got two simple `<b:slider>`. 

    <b:column styleClass="borderme">
        <b:slider mode="simpel" disabled="#{!adminSeminar.editierbar}" 
         value="# adminSeminar.seminar.maxVortraege}" max="15"
	 min="#{adminSeminar.seminar.vortraege.size()}">
        </b:slider>
    
        <b:slider value="9" />
     </b:column>
Those are displayed as:

![sliderbf](https://cloud.githubusercontent.com/assets/13524849/9561726/d6601d2a-4e51-11e5-8614-81c47603cb78.PNG)

As you can see, the slider do not fill the whole cointainer width (black border). 
In the generated sourcode, you can see: 
```html
<div class="col-md-1 col-xs-1 col-sm-1 col-lg-1">
<div class="col-md-4 col-xs-4 col-sm-4 col-lg-4">
```
Is that on purpose? If so, why? I do not get it. 

I'd like to display a short slider and manipulate the length via columns. Is there any quick fix?

**Comment by TheCoder4eu** [comment]
Add attribute to drive horizontal width.

**Comment by TheCoder4eu** [comment]
Testing

**Comment by TheCoder4eu** [comment]
Tests OK. Writing the doc.

**Comment by TheCoder4eu** [comment]
Doc ok
