### ISSUE TITLE
New component: accordion

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#173]
I would be nice to have an accordion in BootsFaces. It's an exotic element, but it can be useful, as MS Outlook and the PrimeFaces showcase demonstrate.

**Comment by stephanrauh** [comment]
@asterd Dario, what's the state of the art? Did you finish this component, or is it work in progress?

**Comment by asterd** [comment]
@stephanrauh the component is finished.. I have to create the documentation page, but the component is completed!
