### ISSUE TITLE
Bootfaces & PrimeFaces 5.2 JQuery Issue

### ISSUE THREAD

**Issue by okroener** [TheCoder4eu/BootsFaces-OSP#175]
Hello Altogether,

I wanted to try PrimeFaces together with BootsFaces. In this case, the charting elements.

When I want to use the DateAxis, I get an JavaScript error, the script just hangs. This happens when I add the following code in the managed bean:

```java
DateAxis xAxis = new DateAxis(); // lng.getString("weight_chart_dates"));
xAxis.setTickAngle(-50);
xAxis.setTickFormat("%b %#d, %y");
lineModel.getAxes().put(AxisType.X, xAxis);
```
When I remove this code, the Chart is displayed, but not in the right way.

Do you have any idea?

thx

Oliver

**Comment by TheCoder4eu** [comment]
Hi Oliver,
if you still have this issue with the last version of BootsFaces please reopen this issue or open a new one.
Thanks,
Riccardo
