### ISSUE TITLE
Core CSS is not compatible with the offical Bootstrap CSS

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#177]
BootsFaces 0.7.0 vs Bootstrap 3.3.5

See for example http://stackoverflow.com/questions/32521198/how-to-add-a-carousel-to-a-bootsfaces-page

**Comment by stephanrauh** [comment]
There are a few (but important) custom modifications:

https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/gradleResources/less/bs-navbar.less
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/gradleResources/less/bs-thumbnails.less
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/gradleResources/jq/ui/datepicker.js

**Comment by stephanrauh** [comment]
I documented the differences at http://bootsfaces.net/Staging/layout/resourcemanagement.jsf.
