### ISSUE TITLE
Add startbootstrap themes support

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#178]
Investigate Startbootstrap themes:

http://startbootstrap.com

**Comment by stephanrauh** [comment]
@TheCoder4eu I've added two of these themes to the showcase. So it's obvious the Start Bootstrap themes can be used with BootsFaces. Is that enough? Or should we include them with BootsFaces? In other words: can we close this ticket as solved with BootsFaces 0.8.1?
