### ISSUE TITLE
Input components don't render an asterik when required=true

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#179]
I observed this with b:inputText. Most like, the other components suffer from the same problem, too. If they render a label at all, that is :). Components to test and fix:

* b:inputText / b:inputSecret (solved)
* b:selectOneMenu (solved)
* b:selectMultiMenu (solved)
* b:slider (solved)
* b:datepicker (doesn't render a label)

**Comment by stephanrauh** [comment]
done.

**Comment by vsvetoslavov** [comment]
option to turn this on/off?

**Comment by stephanrauh** [comment]
@vsvetoslavov Is this an important requirement?

**Comment by vsvetoslavov** [comment]
Bootstrap provides input-addons - in my project I used these to provide visual feedback whether the field is mandatory. And before that I did pass through an asterisk feedback. So to me it totally makes sense.

**Comment by stephanrauh** [comment]
@vsvetoslavov That's an interesting and clever use of add-ons! Fancy to provide us a screenshot? I'm curious :).

In any case, I've solved your issue by using a CSS class to render the asterisk (see #190). You need to override the CSS class bf-required to suppress the asterisk. By default, it looks like so:
``` CSS
label.bf-required:after { content:" *"; }
```

**Comment by vsvetoslavov** [comment]
Instead of a screenshot - here's my code that does the magic
* I combined this with a bit of validation handling that I use because I then remove the "has-success" class.
* I actually wrote my own class in order to fit my requirements and preference, but this example uses the built-in "has-success" class. I made a copy of the "has-success" CSS style and changed some colors
```javascript
			//add "required" class to mandatory fields
			$('.bf-required').parents('.form-group').addClass('has-success');
			//add "has-error" class to fields that failed validation - also remove "has-success" class so it does not get in the way
			$('.error').parents('.form-group').addClass('has-error').removeClass('has-success');
```
