### ISSUE TITLE
b:panelGrid does not appear to work

### ISSUE THREAD

**Issue by wsaxton** [TheCoder4eu/BootsFaces-OSP#180]
Created a bare-bones web project with just booksfaces 0.7.0 and tried out the b:panelGrid.

    <?xml version="1.0" encoding="UTF-8"?>
    <html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:h="http://xmlns.jcp.org/jsf/html"
          xmlns:b="http://bootsfaces.net/ui">
        <h:head>
            <title>Title</title>        
        </h:head>
        <h:body>
            <b:panelGrid colSpans="2,10">
                <h:outputLabel value="Version:" />
                <b:inputText  span="10"  value="6.1"/>
            </b:panelGrid>
        </h:body>
    </html>

And I'm viewing the following in Chrome (Note the label is spanning the entire width of the div)

![panelgrid](https://cloud.githubusercontent.com/assets/11781393/10024516/8439dc84-6125-11e5-9d7d-4b997643e916.png)

**Comment by stephanrauh** [comment]
I think the result is OK. I get the same if the window is smaller than 1200 pixels. Just to be sure, let's compare the generated HTML code. My version is:

``` html
<body>
  <div id="j_idt5">
    <div class="row">
      <div class="col-lg-2">
        <label>Version:</label>
      </div>
      <div class="col-lg-10">
        <div id="j_idt7" class="form-group">
          <div class="col-md-10">
            <input id="input_j_idt7" name="input_j_idt7" type="text"
              class="form-control" value="6.1">
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
```

**Comment by wsaxton** [comment]
My apologies, I didn't realize the default size it use was "lg" (still learning bootstrap!) and there is a "size" attribute which allows me to scale it as appropriate.

**Comment by stephanrauh** [comment]
If every problem could be solved so easily :).
