### ISSUE TITLE
b:navbar does not support styleClass and class attribute does not work

### ISSUE THREAD

**Issue by wsaxton** [TheCoder4eu/BootsFaces-OSP#181]
HTML components use class attribute for setting the CSS class for components.  JSF components use styleClass to do the same.  b:navbar "class" attribute says its supports CSS classes, but it doesn't appear to work.  This should use styleClass anyway.

**Comment by stephanrauh** [comment]
It's true that b:navBar supports neither style nor styleClass. We should fix this. 

However, neither the BootsFaces documentation nor the BootsFaces tag library claim to support one of these attributes, so it shouldn't appear in the autocompletion list of your IDE. Maybe - just maybe - you or your IDE are confused by the class attribute every Java class has? Just a far shot.

**Comment by wsaxton** [comment]
Yes, thanks, its the IDE that thinks its an attribute.

**Comment by stephanrauh** [comment]
Solved in BootsFaces 0.8.0.

**Comment by stephanrauh** [comment]
I've uploaded a new developer snapshot, so you can test my changes. More details at #151.
