### ISSUE TITLE
Add advanced Bootswatch Themes support

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#182]
Add support for building BootsFaces with more Bootswatch Themes:

http://bootswatch.com/

cerulean,  darkly   flatly, journal,  paper, sandstone,  slate, superhero,  united,
cosmo, cyborg,  lumen, readable,  simplex, spacelab, yeti.

Features nice to have:
- switching theme
- specify theme per page/view

**Comment by stephanrauh** [comment]
I believe we've already implemented all this. What do you want to add?

**Comment by TheCoder4eu** [comment]
Yes, you are Right, I got confused with another Issue I had in Mind.
