### ISSUE TITLE
Can't add icon to dropMenu

### ISSUE THREAD

**Issue by georgemoralis** [TheCoder4eu/BootsFaces-OSP#184]
i have a nav menu that has to navlinks and a dropmenu. I can add icon to navlinks but not in dropmenu since that attribute is missing...

**Comment by stephanrauh** [comment]
Done. See the "birthday cake" symbol at http://www.bootsfaces.net/Staging/layout/navbars.jsf.
![image](https://cloud.githubusercontent.com/assets/3045767/10206633/37797342-67c8-11e5-833e-a06737c77255.png)

**Comment by georgemoralis** [comment]
that was fast thank you :)
