### ISSUE TITLE
dropmenu alignment

### ISSUE THREAD

**Issue by georgemoralis** [TheCoder4eu/BootsFaces-OSP#185]
having this

``` html
<b:navbarLinks pull="right">
                <b:navLink value="Dashboard" href="#" iconAwesome="tachometer"></b:navLink>
                <b:navLink value="Settings" href="#" iconAwesome="list"></b:navLink>
                <b:dropMenu value="My Account">
                    <b:navLink value="Action" href="#"></b:navLink>
                    <b:navLink value="Another action" href="#"></b:navLink>
                    <b:navLink value="Something else here" href="#"></b:navLink> 
                    <b:navLink></b:navLink>
                    <b:navLink value="Disconnect" iconAwesome="sign-out" </b:navLink>
                </b:dropMenu>
            </b:navbarLinks>
```

The dropdown menu is not visible .(alignment right)

Bootstrap has  dropdown-menu-left , dropdown-menu-right to overcome this issue .
http://getbootstrap.com/components/#dropdowns-alignment

**Comment by stephanrauh** [comment]
What about multi-level menus? We can add the CSS class `dropdown-menu-right` if the parent navBarLink is pulled right, but what about nested menus?

**Comment by georgemoralis** [comment]
have to check with bootstrap how to handle that be i suppose they renders on the other side (left-to-right) as well

**Comment by georgemoralis** [comment]
yah i verified it

When used dropdown-menu-right to align menu at right , nested menus are also draws at the left side of the dropdown (caret is still at the right side)

**Comment by stephanrauh** [comment]
I would like to post-pone this to BootsFaces 0.9 because I consider nested menus a more exotic use case.

**Comment by geopossachs** [comment]
In the current version, v1.5.0-SNAPSHOT by pull left the navbarLink is located at left and the dropMenu is also aligned left. By pull right, the navbarLink is located at right and the dropMenu is also aligned right.

If you need to toggle the alignment of the dropMenu you can change it by the bootstrap css class via the content-class attribute


 ```
<b:navbarLinks pull="left">
    <b:navLink value="Dashboard" href="#" iconAwesome="tachometer"></b:navLink>
    <b:dropMenu value="My Account" content-class="dropdown-menu-right">
        <b:navLink value="Action" href="#"></b:navLink>
        <b:navLink value="Another action" href="#"></b:navLink>
        <b:navLink value="Something else here" href="#"></b:navLink> 
        <b:navLink></b:navLink>
        <b:navLink value="Disconnect" iconAwesome="sign-out"></b:navLink>
    </b:dropMenu>
    <b:navLink value="Settings" href="#" iconAwesome="list"></b:navLink>
</b:navbarLinks>

<b:navbarLinks pull="right">
    <b:navLink value="Dashboard" href="#" iconAwesome="tachometer"></b:navLink>
    <b:dropMenu value="My Account" content-class="dropdown-menu-left">
        <b:navLink value="Action" href="#"></b:navLink>
        <b:navLink value="Another action" href="#"></b:navLink>
        <b:navLink value="Something else here" href="#"></b:navLink> 
        <b:navLink></b:navLink>
        <b:navLink value="Disconnect" iconAwesome="sign-out"></b:navLink>
    </b:dropMenu>
    <b:navLink value="Settings" href="#" iconAwesome="list"></b:navLink>
</b:navbarLinks>
 ```    

We could add an new attribute _pull_ to b:dropMenu. 
But I currently see no direct bug, which would have to be fixed.

**Comment by stephanrauh** [comment]
I agree. Probably the bug has been solved during the last four years. Let's close it.
