### ISSUE TITLE
icon awesome size attribute in components that support iconAwesome

### ISSUE THREAD

**Issue by georgemoralis** [TheCoder4eu/BootsFaces-OSP#186]
some components (like navlinks) support iconAwesome attribute . It would be nice if they also supported the size attribute for the icon

**Comment by TheCoder4eu** [comment]
In Button and CommandButton this happens already since as you specify a different button size you get a different font size and hence a bigger icon.
I have to verify the DropButton.

For the Links, we should decide if it makes more sense to increase the font size together with the icon size or let increase the icon size only.

**Comment by stephanrauh** [comment]
These components may benefit from the feature:
![image](https://cloud.githubusercontent.com/assets/3045767/16469339/b7c43d98-3e50-11e6-8dd9-f567981f09fc.png)

**Comment by stephanrauh** [comment]
If we implement this feature, we should also implement
```
attribute_list iconAwesome {
    icon-flip                                                             "Flip the icon: can be H (horizontal) or V (vertical)."
    icon-rotate                                                           "Rotate 90 degrees the icon: Can be L,R."
    icon-size                                                             "Icon Size: legal values are lg, 2x, 3x, 4x, 5x."
    icon-spin                Boolean                                      "Boolean value: if true the icon will spin."
}
```

**Comment by stephanrauh** [comment]
I've started to implement the feature. Todos left:
- test
- documentation

**Comment by stephanrauh** [comment]
Done. You can see the result at http://www3.bootsfaces.net/Showcase/forms/commandButton.jsf, http://www3.bootsfaces.net/Showcase/layout/navLinks.jsf and http://www3.bootsfaces.net/Showcase/forms/buttons.jsf.
