### ISSUE TITLE
Provide some control mechanism on what resources are included

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#187]
Currently each Bootsfaces (BF) component describes what resources it needs and only those resources are provided in the request. However this makes it hard to use the Bootstrap(BS) part of BF - i.e. add BS classes to divs, spans etc. This is because the resources need for handling these classes are not necessarily included into the request. It would be nice if there was some mechanism to turn off the separate resources feature and make BF include the entire BS in the request or make BF not add the BS resources at all. The latter approach would allow manually including the entire BS.

**Comment by stephanrauh** [comment]
I suppose BootsFaces 0.8.0 is going to offer what you need. Please check http://bootsfaces.net/Staging/layout/resourcemanagement.jsf and report us back. Thanks!
