### ISSUE TITLE
javax.faces.FacesException: Expression error: Object named: net.bootsfaces.component.Button not found.

### ISSUE THREAD

**Issue by NetoDevel** [TheCoder4eu/BootsFaces-OSP#188]

**Comment by stephanrauh** [comment]
@NetoDevel I've got a couple of questions:
* Which version of BootsFaces? 
* Where did you get it from? (i.e. Maven Central or bintray vs. direct download)
* Is the Button the only component showing this error?

**Comment by stephanrauh** [comment]
Possibly related to http://stackoverflow.com/questions/32799225/javax-faces-facesexception-expression-error-named-object-net-bootsfaces-layou

**Comment by NetoDevel** [comment]
@stephanrauh My error is related to issue # 189, I believe we can close this.

**Comment by stephanrauh** [comment]
Also see http://pt.stackoverflow.com/questions/90162/bootsfaces-erro-javax-faces-facesexception-erro-de-express%C3%A3o

**Comment by stephanrauh** [comment]
Another guy reported a similar error on StackOverflow, so I'd like to investigate the topic further. @NetoDevel José, can you upload or mail us a complete project showing the error? You've provided a couple of snippets on StackOverflow, but they ran fine in my project, so I suspect there's something wrong with the project setup.

**Comment by NetoDevel** [comment]
@stephanrauh my project is up in worskpace work tomorrow which send email to contact?

**Comment by stephanrauh** [comment]
Send it to webmaster1 at beyondjava.de (replacing the " at " by an @ sign, of course). Thanks in advance!

**Comment by NetoDevel** [comment]
I created a repository for the hotfix # 189, if you can can make the pull request or direct push on the master, we can leave it as an example for integrating spring boot and bootsfaces! follow the link below:
https://github.com/NetoDevel/springboot-bootsfaces
 @stephanrauh

**Comment by stephanrauh** [comment]
I've managed to reproduce your bug. It seems to be the same old story I've already reported about in my article http://www.beyondjava.net/blog/updating-to-mojarra-2-2-11-may-break-your-spring-boot-application/. 

Go back to Mojarra 2.2.10, and everything works. If so, please report back, so we can answer the two open questions on StackOverflow.

BTW, I guess you'd better get rid of your application's dependency to org.glassfish:javax.faces:2.1.21. I don't believe you need it. But if you need it for some reason, it should be the same version as the other JSF jars.

**Comment by NetoDevel** [comment]
thank you for return are few that help, we can use my repository as an example of the bootsfaces + spring boot configuration?You could make the fork there? and create a pull request? with correction?

@stephanrauh
