### ISSUE TITLE
support spring boot?

### ISSUE THREAD

**Issue by NetoDevel** [TheCoder4eu/BootsFaces-OSP#189]

**Comment by stephanrauh** [comment]
I'm sorry, but we won't support Spring Boot. That's not our decision. One of the base libraries - Mojarra - officially does not support Spring Boot. Manfred Riem told me that it's the job of the Spring Boot team to keep their framework compatible to JSF. As a matter of fact, the current version of Mojarra is incompatible to Spring Boot (although the Spring Boot team is currently working on a fix, or at least considering such work). Now, if even the base library isn't always compatible to Spring Boot, how can we, the BootsFaces team, guarantee Spring Boot compatibility?

@TheCoder4eu Riccardo, do you agree? If so, please close the ticket.

**Comment by NetoDevel** [comment]
@stephanrauh There is some version of mojarra that is compatible?I take much to turn in my application :(

**Comment by stephanrauh** [comment]
@NetoDevel Try Apache MyFaces. There's a blog reporting to run JSF successfully on Spring Boot using Apache MyFaces.

**Comment by TheCoder4eu** [comment]
From what I read in various posts and articles Spring Boot compatibility is not guaranteed (may work with specific versions).

**Comment by stephanrauh** [comment]
@NetoDevel José, I'd like to add a question: did you try the latest version of Mojarra (2.2.12)? According to https://github.com/spring-projects/spring-boot/issues/3216#issuecomment-148243684, the bug has been solved.
