### ISSUE TITLE
Double use of the label attribute causes problems

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#19]
The label attribute of <b:inputText> - and probably other components too - is used twice, which may cause problems. Consider the following code:
```XML
<label for="#{age.clientId}">Enter your age:</label>
<b:inputText id="age" value="#{user.age}" binding="#{age}"
	size="20" required="true"
	label="Age" >
	<f:validateLongRange for="age" minimum="1" maximum="200" />
</b:inputText>
<h:message for="age" style="color:red" />
 ```
For some reason I do not want to use the formgroup label. Instead, I prefer to provide my own label. However, the label attribute is used by the JSF error messages, so it's a good idea to provide the label attribute to the inputText. Unfortunately it's rendered like this:
![image](https://cloud.githubusercontent.com/assets/3045767/5154280/5e13cc8e-7253-11e4-840f-b5e987584820.png)

I'd like add an option to suppress the automatic generation of the label. Setting this option removes the "age" marked red while keeping the green ones.

**Comment by TheCoder4eu** [comment]
Already done in v0.6.0 .
