### ISSUE TITLE
New component: b:message

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#193]
There's no b:message yet. Plus, the h:message tag doesn't seem to work. To reproduce the bug, look at the last example of InputText.xhtml of the showcase.

**Comment by Kristover** [comment]
sefrzsfez

**Comment by AlexanderBl4h** [comment]
@stephanrauh Stephan: 

Acutally that is not completly true.

	<h:form>
		<h:inputText id="a" required="true" value="#{bean.a}"
			requiredMessage="a missing" />
		<h:message for="a" />
		<b:messages for="a" />
		<h:inputText id="b" required="true" value="#{bean.a}"
			requiredMessage="b is also missing" />
		<h:message for="b" />
		<b:messages for="b" />
		<b:commandButton value="submit" action="#{bean.test}" ajax="true"
			update="@form" />
	</h:form>

You may have a look at this one: http://showcase.omnifaces.org/components/messages
Those examples are pretty nice. 

To point out the errors:

It seems to be the case, that the for attribute gets completly ignored. Just run my example, you can see that those jsf messages are working as expected.

**Comment by stephanrauh** [comment]
Using the `for` attribute of `<b:messages>`> to simulate the singular `<b:message />` is a clever ploy indeed!

To bad we didn't implement the `for` attribute, either :). 

Thanks for pointing out we've missed an important attribute!

**Comment by stephanrauh** [comment]
Done. BootsFaces 0.8.1 has a b:message component, and I've both documented and tested it.

**Comment by AlexanderBl4h** [comment]
It would be helpful, if you can reference the commit in an issue. Just use "fix #193" or something like this. See more details right [here](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by stephanrauh** [comment]
Most of the time I do add the issue number, but sometimes I forget. Bear with me!

**Comment by TheCoder4eu** [comment]
@AlexanderBl4h btw, your suggestion is included in our guidelines:
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/CONTRIBUTING.md

**Comment by AlexanderBl4h** [comment]
Poor Stephan. I'm sorry. :)

**Comment by stephanrauh** [comment]
Yeah. Sigh. :).
