### ISSUE TITLE
Problems with JSF 303 Bean Validation API

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#194]
Using b:inputText with an integer value and JSR 303 Bean Validation causes a ClassCastException. To reproduce the bug, look at the last example of InputText.xhtml of the showcase and uncomment the JSR303 annotations of UserBean.

**Comment by exabrial** [comment]
Just curious... what JEE server are you running this on?

**Comment by stephanrauh** [comment]
I noticed the bug on my MacBook running a simple Tomcat 8. But I don't think this particular bug is caused by the application server. But then, I don't understand it at all - I can't remember to have seen special support for JSR 303 in PrimeFaces yet. But I didn't investigate the error yet.

**Comment by stephanrauh** [comment]
The error seems to have been solved in the meantime. I've added a demo to the showcase focusing on JSR 303/349 annotations. The demo runs flawlessly.
