### ISSUE TITLE
process attribute not available to commandButton

### ISSUE THREAD

**Issue by georgemoralis** [TheCoder4eu/BootsFaces-OSP#195]
Seems that process command is not available to commandButton (according to docs http://www.bootsfaces.net/Staging/forms/commandButton.jsf) .

i am using latest 23 September snapshot

My code
```java
<b:commandButton 
                            value="New Entry"
                            ajax="true"
                            process="@this :form:entries" 
                            update=":form:newDialogPanelGrid" 
                            icon="ui-icon-plusthick"
                            actionListener="#{parameterMB.createTriggered()}" 
                            oncomplete="PF('NewDialogWidget').show()"
                            />
```
That code works with primefaces commandButton but denies to work with bootfaces :(

**Comment by stephanrauh** [comment]
This evening I've added an example of partial processing to the documentation page. Obviously, it does work. Maybe the developer snapshot was too old. I've updated it, too. 

If it still doesn't work on your machine, maybe you should check the process string. Actually, `:form` looks a bit odd to me: I thought you don't need it. But it's possible that BootsFaces doesn't cope with expressions that are legal in standard JSF and / or PrimeFaces. If so, please report us.

**Comment by stephanrauh** [comment]
@georgemoralis I didn't hear from you for a week. I take it that's a good sign: your problem is solved, and I can close the ticket safely. Is that fine by you?

**Comment by georgemoralis** [comment]
i just think my issue is more related to https://github.com/stephanrauh/BootsFaces-Examples/issues/1

**Comment by nahummor** [comment]
Hi, I encountered a similar problem,i'm using Netbeans 8.1 jsf 2.2 bootsfaces 0.8.0 maven.
when i use b:commandButten the attribute process does not appear in the attribute list.
in the b:column the attribute colLg , colMd , colSm and colXs don't work'
instead, I use class="col-lg-2".

**Comment by stephanrauh** [comment]
@nahummor I just added the process attribute to the taglib. Now it should work with Netbeans, too. I've also added the b:column attributes a couple of days ago. You can test it with the latest developer snapshot of version 0.8.1. See #151 on how to get it. Fancy to give it a try and tell me if it works?

**Comment by nahummor** [comment]
Hi,thanks for the quick response,
the process attribute is working,
the  attribute colLg , colMd , colSm and colXs don't work, instead, I use class="col-lg-2".
every click on commandButton Glassfish show this Warning:   Unable to save dynamic action with clientId 'j_id6' because the UIComponent cannot be found

**Comment by stephanrauh** [comment]
Just ignore the warnings. Or switch to a newer version of OmniFaces. As far as I remember, Bauke fixed this nuisance with OmniFaces 2.2 in August 2015. See http://www.bootsfaces.net/integration/OmniFaces.jsf and https://github.com/omnifaces/omnifaces/issues/135.

**Comment by stephanrauh** [comment]
As for the attributes: I've installed Netbeans 8.1. this morning. My local copy of BootsFaces 0.9.0-SNAPSHOT does show the `colLg*`attributes:
![image](https://cloud.githubusercontent.com/assets/3045767/12215411/f975088e-b6bb-11e5-9e40-5530b3fdaa94.png)
I understand it looks different on your machine?

**Comment by nahummor** [comment]
this is what i see, but colLg colMd colSm and colXs dont work.
you see class attribute instead colLg ?
![image](https://cloud.githubusercontent.com/assets/16607408/12216971/7ac21f8c-b6fb-11e5-96ce-b2763254058b.png)

**Comment by stephanrauh** [comment]
OK, so I've probably been looking for the wrong error. I thought you've got a problem with the autocompletion.

Actually, I don't think using the class attribute is correct. I don't know why Netbeans shows it in the autocomplete list. The `class` attribute is not part of our taglib file. The correct attribute is `styleClass`. That's because `class` is a reserved word in Java. You can't use it as a variable name.

**Comment by stephanrauh** [comment]
Oh, and you are right. We've declared the attribute as "colLg" in the taglib file, but read "col-lg" in the Java code. That's an ugly one. I need to investigate a while to find a nice solution.
```java
			int colxs = A.toInt(attrs.get("col-xs"));
			int colsm = A.toInt(attrs.get("col-sm"));
			int collg = A.toInt(attrs.get("col-lg"));
```

**Comment by stephanrauh** [comment]
I've fixed `<b:column />` and uploaded a snapshot to Maven Central (0.8.1-SNAPSHOT). 
The bug affects every component. I'll continue to work on the bug later.

**Comment by nahummor** [comment]
It works ,thanks.

**Comment by stephanrauh** [comment]
I consider this ticket closed.
Also see #239. That's an enhancement inspired by your ticket.
