### ISSUE TITLE
New Editor component

### ISSUE THREAD

**Issue by srbala** [TheCoder4eu/BootsFaces-OSP#196]
Bootstrap based editor component would nice for BootsFaces.

Some of the library to consider are ...

http://summernote.org/#/
https://jhollingworth.github.io/bootstrap-wysihtml5/
https://mindmup.github.io/bootstrap-wysiwyg/

**Comment by stephanrauh** [comment]
The editor won't make it into the next version, but after that, it's a good idea.

**Comment by stephanrauh** [comment]
I suppose it's easy to implement the editor component with pure JavaScript and `<b:remoteControl>`. Let's close the ticket.
