### ISSUE TITLE
New component: b:inputTextarea

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#201]
Like mentioned on StackOverflow (http://stackoverflow.com/questions/33572953/how-does-bootsfaces-support-textarea-and-radio-buttons), it would be nice to add an b:inputTextarea component to BootsFaces.

**Comment by stephanrauh** [comment]
Finished both implementation and documentation.

**Comment by JonathanLalou** [comment]
Hi,

The <b:inputTextarea> seems not to retrieve the value of the managed bean in the XHTML file.
Eg:
```
<b:inputTextarea id="comments" value="#{myManagedBean.comments}" />
```
and 
```
public abstract class MyManagedBean {
   private String comments= "fooBar";
}
```
Expected behaviour: the input text area should be initied with the value "fooBar"
Actual behaviour: the input text area is empty.

Nevertheless, on the opposite direction, when the component is filled in, then the managed bean is well updated.

**Comment by stephanrauh** [comment]
I've fixed and tested the error (see http://bootsfaces.net/Staging/forms/inputTextarea.jsf). 

@JonathanLalou Thanks for pointing this out!

**Comment by JonathanLalou** [comment]
Thanks Stephan !

**Comment by stephanrauh** [comment]
@JonathanLalou You're welcome! If you need a developer snapshot on Maven Central, just tell me.

**Comment by JonathanLalou** [comment]
Yes please, upload a snaphot to sonatype or central repos ! :)
Thanks a lot in advance

**Comment by stephanrauh** [comment]
Done. See #151 on how to get the latest developer snapshot.

**Comment by JonathanLalou** [comment]
Great. Thanks

**Comment by JonathanLalou** [comment]
Hi Stephan,

I tested it and I confirm the issue is fixed.
Once again, thanks for your work.

**Comment by stephanrauh** [comment]
@JonathanLalou +1! :)
