### ISSUE TITLE
Enhancement proposition : < b:tabView> with dynamic attribute

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#209]
Hi,

Is it possible to give to < b:tabView> the possibility of lazy load inactive tabs ?

Thanks in advance
Regards

**Comment by stephanrauh** [comment]
That's a difficult one. It's a great idea, but allow me to postpone this to a future version. Of course, you can speed up the process by providing ideas how to solve the challenge or - even better - by sending us a pull request. Interested?

**Comment by jepsar** [comment]
I think I can submit a PR. I've got a working version, but that needs a bit more testing... I had to wrap the component in a `div` which now holds the `clientId` instead of the `ul` with the tab links.

**Comment by stephanrauh** [comment]
It seems we've implemented this feature in BootsFaces 1.2.0. See #807 for more details. Also see [the showcase section on dynamic tabs](https://showcase.bootsfaces.net/bootstrap/tab.jsf#dynamic_tabs).
