### ISSUE TITLE
Improve tag <b: column>

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#21]
In accordance with the rules of bootstrap I suggest to add this simple condition to tag <b:column>

if one of column will declared with size 0 we should apply the rule hidden-xx.
Follow an example to clarify : 
  
```HTML
<b:column col-md="10" col-lg="9" col-sm="0"> .... </b:column>
```
Should became : 

```HTML
<div class="col-md-10 col-lg-9 hidden-sm">  .... </div>
```

![schermata da 2014-09-23 18 02 04](https://cloud.githubusercontent.com/assets/5601887/4375377/b8e77af8-433b-11e4-9745-8ccc1ec5f78b.png)

**Comment by stephanrauh** [comment]
Solved by pull request #97.
