### ISSUE TITLE
Adding error messages to label of inputText 

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#210]
According to:

http://bootsfaces.net/Staging/forms/inputTextarea.jsf

Textareas are supporting a) a label at the top of a textarea and b) to render the label according to a FacesMessage. 

Would you mind, to add this to a normal inputText, too?

**Comment by AlexanderBl4h** [comment]
I saw, BootsFaces 0.7.0 does support this, too. My bad! But it does not work properly. :-1:

**Comment by stephanrauh** [comment]
I've found and fixed a couple of implementation errors concerning this topic today. However, the basic functionality works for error messages, as can be seen here: http://www.bootsfaces.net/forms/inputText.jsf.
