### ISSUE TITLE
b:selectBooleanCheckbox duplicates ID

### ISSUE THREAD

**Issue by LupusUmbrae** [TheCoder4eu/BootsFaces-OSP#212]
Switching from 0.7.0 to 0.8.0 i've found that the ID's for checkboxs are no longer unique, the div's containing them have the same ID. It looks like the actual input elements ID should be prefixed with input much like the input text elements

I have the following xhtml:
```
<h:form id="graphconfig">
 ....
    <b:selectBooleanCheckbox caption="Show Title" id="title-show" />
```

And the output HTML is:

```
<div id="graphconfig:title-show" class="checkbox">
  <label>
    <input name="graphconfig:title-show" type="checkbox">
  </label>
</div>
```

If we compare it to the input text's HTML:

```
<div id="graphconfig:title" class="form-group">
  <div class="input-group">
    <span class="input-group-addon">Label</span>
    <input id="input_graphconfig:title" name="graphconfig:title" type="text" class="form-control bf-no-message">
  </div>
</div>
```

We can see that a similar change has happened to the input text but the input element is now prefixed with `input_`

**Comment by stephanrauh** [comment]
Whow - that's probably the quickest bug report ever. We haven't even managed to announce that we've published BF 0.8.0 yet :).

**Comment by stephanrauh** [comment]
Actually, there's no duplicate id. The `name` of the input field is identical to the `id` of the surrounding `div`. That may be confusing, but it won't confuse your browser.

**Comment by LupusUmbrae** [comment]
Good point, apparently i can't read ;)

**Comment by stephanrauh** [comment]
I added the id nonetheless to the input field, because otherwise the `for` attribute of the associated label points to the wrong HTML tag.

**Comment by stephanrauh** [comment]
@LupusUmbrae The interesting thing about this issue is that it allowed me to find a variety of bugs - even if the bug you originally reported was a false positive :). Thanks!
