### ISSUE TITLE
Add more attributes to b:switch

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#219]
A couple of attributes can simply be passed through to the switch, without much logic required:
* onText
* offText
* onColor
* offColor
* indeterminate
* inverse
* size
* animate
* disabled
* readonly
* labelText
* handleWidth
* labelWidth

**Comment by stephanrauh** [comment]
Done and documented.

**Comment by mannan4net** [comment]
I am unable to found the update attribute in <b:switch> as in showcase the update attribute is being used. Version 0.9.1.
![switch demo](https://cloud.githubusercontent.com/assets/21006926/17643039/321e4a96-617b-11e6-964d-f55ffb051f66.JPG)
![switch issue](https://cloud.githubusercontent.com/assets/21006926/17643040/3425e2e0-617b-11e6-8fab-670016cc90d4.JPG)

**Comment by stephanrauh** [comment]
The `update` attribute is there, but it didn't find its way into the taglib file, which is used by your IDE to provide autocompletion and additional checks. I've fixed this. We'll track progress in #487.
