### ISSUE TITLE
b:navCommandLink does not pass f:param

### ISSUE THREAD

**Issue by 148349** [TheCoder4eu/BootsFaces-OSP#223]
navCommandLink doesn't seem to be passing parameters passed as f:param

For example, given that I'm in src.xhtml:
```xml
<b:navBar brand="Brand" brandHref="#" inverse="true">
    <b:navbarLinks>
        <b:navLink value="Home" href="#"></b:navLink>
        <b:navLink value="Link" href="#"></b:navLink>
        <b:navCommandLink value="Command link" action="dest.xhtml">
                <f:param name="userId" value="5" />
         </b:navCommandLink>
    </b:navbarLinks>
</b:navBar>
```
I could technically use the "outcome" attribute of navLink and pass the f:param the same way, but that'd change the URL (I'm using this in Liferay portlet) and that behaviour is rather undesirable.

**Comment by stephanrauh** [comment]
Sigh :). I'm reluctant to add the old-school parameter passing mechanism to BootsFaces. It's so clumsy.

BTW, does the `b:navCommandLink` work with Liferay? It changes the URL, to. 

What about AJAX? I've added it a couple of days ago in the developer preview version (BootsFaces-0.8.1-SNAPSHOT). The new AJAX API introduced with BootsFaces 0.8.0 allows you to pass arbitrary parameters like so:
```xml
<b:navCommandLink value="Command link" update="contentRegion" onclick="someBean.showUserDetails(5)" />
 </b:navCommandLink>
```

See #151 on how to get the developer snapshot version.

**Comment by 148349** [comment]
I thought navigation using AJAX was considered clumsier than passing parameters via f:param. Updating original tracker for clarity.

**Comment by Coolius70** [comment]
Using outcome works (version 0.9.1)

							<b:navLink outcome="workpackageDetails" value="" icon="pencil">
								<f:param name="workpackageId" value="#{o.id}" />
