### ISSUE TITLE
b:selectOneMenu ignores itemDisabled

### ISSUE THREAD

**Issue by LupusUmbrae** [TheCoder4eu/BootsFaces-OSP#229]
I've noticed that the bootsfaces selectOneMenu doesn't behave the same as the standard jsf html with respect to `itemDisabled`

In the following code:
```
<b:selectOneMenu id="yscale" onclick="yscaleChanges()">
    <f:selectItem itemLabel="Linear" itemValue="linear" />
    <f:selectItem itemLabel="Power" itemValue="pow" />
    <f:selectItem itemLabel="Logarthimic"
                itemValue="log" />
    <f:selectItem itemLabel="Ordinal" itemValue="ordinal" itemDisabled="true" />
</b:selectOneMenu>
```

The `Ordinal` item is still selectable, but if i switch to:

```
<h:selectOneMenu id="yscale" onclick="yscaleChanges()">
    ....
    <f:selectItem itemLabel="Ordinal" itemValue="ordinal" itemDisabled="true" />
</h:selectOneMenu>
```

The  `Ordinal` item is not selectable.

The difference seems to be in the HTML where the bootsfaces selectOneMenu outputs:

```
<select id="graphconfig:yscale" name="graphconfig:yscale" class="form-control bf-no-message" onclick="yscaleChanges();">
  ...
  <option data-label="Ordinal" value="ordinal">Ordinal</option>
</select>
```

The JSF HTML looks like: 

```
<select id="graphconfig:yscale" name="graphconfig:yscale" size="1" onclick="yscaleChanges()">
  ....
  <option value="ordinal" disabled="disabled">Ordinal</option>
</select>
```

In my case i can use the JSF HTML selectOneMenu and add the class from bootsfaces to give it the correct style, but thought it worth reporting the issue.

It looks like the `renderOption` in [SelectOneMenuRenderer.java](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/selectOneMenu/SelectOneMenuRenderer.java#L487) doesn't handle the disabled attribute

**Comment by stephanrauh** [comment]
Interesting - I didn't even know about this feature. But sure, why not. I'll add it.

**Comment by stephanrauh** [comment]
Done and documented at http://www3.bootsfaces.net/Staging/forms/selectOneMenu.jsf. If you want to test it, I've uploaded a new developer snapshot at Maven Central (see #151).

**Comment by LupusUmbrae** [comment]
Thanks :+1:
