### ISSUE TITLE
Create A Single Page Application Using BootsFaces

### ISSUE THREAD

**Issue by mostfa-ayad** [TheCoder4eu/BootsFaces-OSP#234]
hello  
can i make SPA using bootsFaces ?
it will be nice if done

**Comment by stephanrauh** [comment]
Yes, you can! I've explorerd two options:
* Use BootsFaces AJAX to navigation without ever changing the URL or re-initializing the JavaScript libraries. That what I did here: https://github.com/stephanrauh/lunch-tool. Note that the AJAX menus require BootsFaces 0.8.1, which should be published soon.
* Use the router of AngularJS to navigate. This example uses AngularFaces to implement the SPA naviation: https://github.com/stephanrauh/Presentations/tree/master/BootsFacesPresentation

Enjoy!

**Comment by stephanrauh** [comment]
I've written an article on http://www.beyondjava.net about BootsFaces SPA. It still needs some proofreading, so I'll publish it tomorrow evening. Stay tuned!
