### ISSUE TITLE
f:setPropertyActionListener indicate double call

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#235]
Hello All,

When I use f:setPropertyActionListener inside b:commandButton then action method is called twice. The setter method is called only once, that is indicated by f:setPropertyActionListener.
I checked it only with b:dataTable.
The full code: 
```xml
<b:dataTable... >
  <h:form >
    <b:commandButton action="..." >
      <f:setPropertyActionListener .../ >
    </b:commandButton >
...
```

This issue exists with ajax and normal requests too.
Please check it.

Thanks,
Mihaly

**Comment by lyahim** [comment]
When I tried to make a workaround use actionListener and action combination.
< b:commandButton action="..." actionListener="#{setter(value)}" ...>

Both the action method and the setter method called twice.

Mihaly

**Comment by stephanrauh** [comment]
Two questions:
* That sounds like a non-AJAX call?
* Is the command button inside the datatable? Or is it below?

**Comment by lyahim** [comment]
1) The AJAX and non-AJAX call work similar.
2) Yes, there are a delete button on each rows end.

**Comment by lyahim** [comment]
I paste a code what work with <b>h</b>:commandbutton:
'<h:form>
				<b:dataTable>
<h:column>
						<f:facet name="header">
							<h:outputText value="" />
						</f:facet>
						<h:commandButton disabled="#{!sessionInfoBean.root and user.userName eq 'admin'}" value="#{msg['common.delete']}"
						action="#{userListBean.deleteUser}" styleClass="btn btn-default">
							<f:setPropertyActionListener value="#{user}" target="#{userListBean.selectedUser}" />
							<p:ajax update="@form" />
						</h:commandButton>
					</h:column>
</b:dataTable>
			</h:form>'

**Comment by stephanrauh** [comment]
Thanks! I'll have a look at the problem later.

BTW, you don't need to separate the < from the tag when you're commenting. Just add ```xml before your source code, and you've got a nice source code formatting and less work. See https://guides.github.com/features/mastering-markdown/ (and browse for "code").

**Comment by lyahim** [comment]
Thanks, I tried, but with only simple quote mark.

**Comment by stephanrauh** [comment]
The single backward quote is for inline code. The three quote are for multiline code.

**Comment by stephanrauh** [comment]
I've fixed the bug and uploaded a developer snapshot to Maven Central. See #151 on how to get it.
