### ISSUE TITLE
b:navCommandLink ajax support

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#236]
Hello All,

Is it possible to use b:navCommandLink with ajax? I would like something similar:
```xml
<li>
							<h:commandLink action="#{loginBean.logout}">
								<p:ajax oncomplete="location.reload();" />
							#{msg['login.logout']}</h:commandLink>
						</li>
```

**Comment by stephanrauh** [comment]
Sure. I didn't run the snippet, but this should do the trick:
```xml
<li>
	<b:navCommandLink onclick="ajax:loginBean.logout()" 
                                           oncomplete="location.reload()"
                                           value="#{msg['login.logout']}" />
</li>
```
Maybe you have to add `ajax="true"`, but I doubt that.

The f:ajax or p:ajax syntax *should* work too, but we don't support it officially. Which is to say: we support it, but with low priority.

**Comment by lyahim** [comment]
The full snippet
```xml
<b:navBar>
  <b:navbarLinks>
    <b:dropMenu>
      <li>
                            <h:commandLink action="#{loginBean.logout}">
                                <p:ajax oncomplete="location.reload();" />
                            #{msg['login.logout']}</h:commandLink>
                        </li>
    </b:dropMenu>
  </b:navbarLinks>
</b:navBar>
```

I tried your code, but unfortunately the backing bean didin't called :(
And navCommandLink doesn't have oncomplete attribute.

**Comment by stephanrauh** [comment]
As of BootsFaces 0.8.2, this code works:
```xml
 <b:navCommandLink value="Action"  actionListener="#{navigationBean.listener}" action="#{navigationBean.test}" />
 ```
However, you're right, we haven't added the `oncomplete` attribute yet. In your case, I believe it would be better to use a server-side redirect 
```java
FacesContext.getCurrentInstance().getExternalContext().redirectTo("your login-page.jsf");
```
