### ISSUE TITLE
Can´t display command button value on button

### ISSUE THREAD

**Issue by TikoCisneros** [TheCoder4eu/BootsFaces-OSP#240]
I use Bootsfaces 0.8 with PrimeFaces 5.3, I only copy and paste the example code from the BootsFaces website. But the value of command button never be displayed.
![sin titulo](https://cloud.githubusercontent.com/assets/7831088/12266937/c026a506-b913-11e5-9b29-31c9b75c46e1.png)

**Comment by snipsh0t** [comment]
I have exactly the same problem, but I have a workaround: using messages from property files works.
This only shows the icon (so does not work):
```html
<b:commandButton look="primary" value="test" action="/jsf/test.jsf" iconAwesome="plus" />
```
This works ok:
```html
<b:commandButton look="primary" value="#{messages['message.test']}" action="/jsf/test.jsf" iconAwesome="plus" />
```

**Comment by stephanrauh** [comment]
That's a very odd error. You guys don't happen to use NetBeans 8.0.2? Because the other day we had exactly the same error report. After updating to NetBeans 8.1 the commandbutton worked again. Can you please read issue #227 and follow the advice I gave there (building the file from Maven without IDE support and things like that)? After that, please report back whether it worked for you or not.

Thanks in advance!
Stephan

**Comment by snipsh0t** [comment]
My project runs in an embedded jetty, I use eclipse as IDE, but always use standard maven to build my project so the IDE should not be of any influence. I do not have the problem on 0.7, only on 0.8

**Comment by stephanrauh** [comment]
Just a far shot: can you post the generated HTML code? Maybe there's something giving me a clue.

**Comment by snipsh0t** [comment]
Here's a simple test file: 
[test.xhtml](https://github.com/TheCoder4eu/BootsFaces-OSP/files/88169/test.xhtml.txt)

And the generated file: [view-source_test.jsf](https://github.com/TheCoder4eu/BootsFaces-OSP/files/88165/view-source_test.jsf.txt)
The result page looks like this:
![image](https://cloud.githubusercontent.com/assets/16675199/12280750/a69c92f8-b990-11e5-844e-1e112a9159d6.png)

**Comment by stephanrauh** [comment]
I typed Tiko's source code into a file and ran it. It looks fine. Plus, the generated code looks almost like the HTML code of @snipsh0t. The only error I observed (and fixed) is that the title is generated twice. Something strange seems to be going on. 

Let's try something I've never tried before. Would you mind to debug the source code for me? I'd do it myself, but as long as I can't reproduce your bug, my debugging doesn't help you.

Do you use Maven? If so, you can easily debug the source code. Maybe that helps. Open the class net.bootsfaces.component.commandButton.CommandButtonRenderer. The interesting lines are line 116:
```Java
		Object value = commandButton.getValue();
```
and lines 129ff:
```Java
			Object ialign = commandButton.getIconAlign(); // Default Left

			if (ialign != null && ialign.equals("right")) {
				value = value != null ? value + " " : null;
				writeText(rw, value, null);
				IconRenderer.encodeIcon(rw, component, icon, fa);
			} else {
				IconRenderer.encodeIcon(rw, component, icon, fa);
				value = value != null ? " " + value : null;
				writeText(rw, value, null);
			}
```

Basically, the variable `value` should contain a string, and it should be your commandButton's caption. Is it? Like so?
![image](https://cloud.githubusercontent.com/assets/3045767/12309356/782ccc52-ba4a-11e5-9a98-5e07ed6374b6.png)


Just for the record: here's my JSF page:

```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:b="http://bootsfaces.net/ui">
<h:head>
  <title>BootsFaces Basic Page</title>
</h:head>
<h:body>
  <b:container>
    <b:row>
      <b:column>
        <h1>Hello, World!</h1>
      </b:column>
    </b:row>
    <b:button value="Hola" look="info"></b:button>
    <h:form>
      <b:commandButton value="I'm disabled" disabled="true" ajax="true" iconAwesome="thumbs-down" look="info"
        title="Disabled!" />
    </h:form>
  </b:container>
</h:body>
</html>
```

And that's the generated HTML code:
```html

<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link type="text/css" rel="stylesheet" href="/BootsFacesWeb/javax.faces.resource/theme.css.jsf?ln=primefaces-bootstrap" />
<link type="text/css" rel="stylesheet"
  href="/BootsFacesWeb/javax.faces.resource/eNpLKk6zSi4u1k9JTUsszSnRT84vStUDCtQkoUmU5OfnlGQWYJUD8rHryUjNBZsGAOlRJ1c.css.jsf?ln=omnifaces.combined&amp;v=1452721667000" />
<link type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
<script type="text/javascript"
  src="/BootsFacesWeb/javax.faces.resource/eNrLCixNLaq0yioEUbqGeoaGesZ6WcU1WSjipZkwqdzMPLB0YllihV5aYnJqsVVWcRpIyDEvvTQnscgr2CoRwkISdIMoLE3UNdAz1DPAqlw3N7W4ODE9tRhDH1QB2Dbd5PyiVPwqUjKLUpNLMsuwmASzIj4V7Iuk4jSg6_VL8vNzSjILkESSwF4CAOxDalQ.js.jsf?ln=omnifaces.combined&amp;v=1452721679000"></script>
<!--[if lt IE 9]><script src="/BootsFacesWeb/javax.faces.resource/js/html5shiv.js.jsf?ln=bsf"></script><script src="/BootsFacesWeb/javax.faces.resource/js/respond.js.jsf?ln=bsf"></script><![endif]-->
<script type="text/javascript">
	if (window.PrimeFaces) {
		PrimeFaces.settings.projectStage = 'Development';
	}
</script>
<title>BootsFaces Basic Page</title>
</head>
<body>
  <div id="j_idt5" class="container">
    <div id="j_idt6" class="row">
      <div id="j_idt7" class="col-md-12">
        <h1>Hello, World!</h1>
      </div>
    </div>
    <button id="j_idt9" name="j_idt9" type="button" class="btn btn-info">Hola</button>
    <form id="j_idt10" name="j_idt10" method="post" action="/BootsFacesWeb/hola.jsf"
      enctype="application/x-www-form-urlencoded">
      <input type="hidden" name="j_idt10" value="j_idt10" />
      <button type="submit" id="j_idt10:j_idt11" name="j_idt10:j_idt11" class="btn btn-info disabled" title="Disabled!"
        disabled="disabled" onclick="BsF.ajax.callAjax(this, event,'j_idt10','j_idt10', null);;;return false;"
        title="Disabled!">
        <span><i id="j_idt10:j_idt11" class="fa fa-thumbs-down"
          onclick="BsF.ajax.callAjax(this, event,'j_idt10','j_idt10', null);;;return false;"></i></span> I'm disabled
      </button>
      <input type="hidden" name="javax.faces.ViewState" id="j_id1:javax.faces.ViewState:0"
        value="-8907144459948907170:-1167872041537738339" autocomplete="off" />
    </form>
  </div>
</body>
</html>
```

**Comment by snipsh0t** [comment]
Ok, got some debugging results:
```commandButton.getValue() returns null.```
On line 1017 in the CommandButton 
```String value = (String) getStateHelper().eval(PropertyKeys.value);```
The mentioned PropertyKeys.value is of type CommandButton, the one stored in the StateHelper map is of type UICommand.PropertyKeys.value, apparently they're not equal ;-)

**Comment by snipsh0t** [comment]
btw it's not difficult to find in the ComponentStateHelper the reason why using messages works:
```ValueExpression ve = component.getValueExpression(key.toString());```
the toString() method obviously makes the 2 different objects behaving equal

**Comment by stephanrauh** [comment]
You may be up to something. I've removed the offending getter and setter, and I've uploaded a snapshot version of 0.8.1 on Maven Central (see #151 on how to get it). Note this is a very experimental version - I've modified every component this evening. I believe it's a good change, but you never know.

Enjoy!

**Comment by stephanrauh** [comment]
Still, I wonder why it worked on my machine, but not on yours. Do you use MyFaces or Mojarra? Which version?

**Comment by snipsh0t** [comment]
Thanks, you fixed the issue!
The Mojarra dependency might be a reason, I now see I still use Mojarra 2.1.26, which means I don't match the specified requirements for Bootsfaces 0.8. Haven't got any problem earlier though, sorry about that.

**Comment by stephanrauh** [comment]
I very happy to hear that this nasty bug has finally been resolved! Thanks for your help!

As for the requirements... well, I just saw they contratict themselves...

"JSF 2.0, 2.1 and 2.2 are supported. Oracle Mojarra 2.2+ or Apache MyFaces 2.2+"

IMHO we should support everything starting from 2.0 and above. There are many conservative companies out there who are reluctant to update their proven infrastructure.
