### ISSUE TITLE
datatable in form

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#241]
Hello All,

When I use this code:

```xml
<h:form>
<b:dataTable>
...
</b:dataTable>
</h:form>
```
I get the following javascript error and the wrapper cannot shown(pager, search etc) :
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: "dataTable id"

Best Regards,
Mihaly

**Comment by TheCoder4eu** [comment]
@lyahim did you have a look to the issue #285 as XaeroDegreaz suggested?
Did this help you solve your issue?

**Comment by lyahim** [comment]
Hello,
It works correctly with 0.8.1

Br,
Mihaly

**Comment by stephanrauh** [comment]
Great! Let's close this issue!
