### ISSUE TITLE
missing div on b:selectBooleanCheckbox

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#243]
Hello All,

When I use b:selectBooleanCheckbox with label in form, the generated code not contains the `<div class="form-group">` part. Is it expected behaviour?

Best Regards,
Mihaly

**Comment by stephanrauh** [comment]
I guess you're right. I looks like a mistake. Now the input group (if there's any) is inside the form-group. Is that correct?

Since my bug fix, the generated code looks like so:
```html
<div class="form-group" type="checkbox">
  <label class="bf-no-message" for="input_j_idt117:j_idt119" type="checkbox">checkbox 2</label>
  <div id="j_idt117:j_idt119" class="checkbox" type="checkbox">
    <label class="bf-no-message" type="checkbox"><input name="j_idt117:j_idt119" id="input_j_idt117:j_idt119"
      type="checkbox"></label>
  </div>
  <input name="j_idt117:j_idt119_helper" value="on" checked="true" style="display: none" type="checkbox">
</div>
```
