### ISSUE TITLE
b:inputText locale="de" creates  java.lang.NumberFormatException

### ISSUE THREAD

**Issue by underflyer** [TheCoder4eu/BootsFaces-OSP#246]
Hi all,

we have been using bootsfaces-0.7.0 before.
now with bootsfaces-0.8.0 something changed in the behaviour of b:inputText.
```xml
<h:form>
<b:inputText id="mValue" immediate="true" value="#{bean.value}">
  <f:convertNumber minFractionDigits="2" maxFractionDigits="2" locale="de" />
  <f:facet name="append">
   <h:outputText value="€" />
  </f:facet>
</b:inputText>
...
</h:form>
```
This creates an Inputtext where the current Value is being converted from e.g. "0.0" into "0,00".
That's OK.
But on "submit" this `< h:form>`
an Exception is thrown: 
java.lang.NumberFormatException: For input string: "0,00"

so it seems, that the value is not being converted back from `locale="de"` into system.

best Regards

**Comment by stephanrauh** [comment]
I believe I've found the bug. However, I got a different error message, so I need your help to confirm my bug fix. I've uploaded a new developer snapshot to Maven Central. See #151 on how to get it.

BTW, I guess you're using MyFaces? That might explain the different error message.

**Comment by underflyer** [comment]
Hi, 

you're right, I'm using MyFaces. Sorry I didn't mention that. I guess next time a little more Stacktrace would be more helpful.

Your new Snapshot bootsfaces-0.8.1-20160115.072412-13 fixed the error. 
There are some Log-Entries on "submit" in the Server.log now:
... Event is null - probably that's a bug in AJAXRenderer, roughly line 100
....Event is null - probably that's a bug in AJAXRenderer, roughly line 100

So for me this bug seems to be fixed. Great Job. 
I want to thank you and your team for this great Project. 

Best regards
 Dirk

**Comment by stephanrauh** [comment]
Thanks for testing and reporting us back! 

Don't worry about the log messages. They are a left-over from a debugging session. At the time, the error message made sense, but in the meantime, I've added some functionality to the AJAX decoder. So the situation I considered suspicious at the time isn't an error, but a situation that's allowed to happen.
