### ISSUE TITLE
SPAs should have bookmarkable URLs

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#249]
A couple of days ago, I've written an article about how to write a Single Page Application (SPA) with BootsFaces. However, my approach doesn't include bookmarkable URLs and the back-button history. Let's think about a way to support this class of applications better. First idea: define a `<b:include`> tag that adds the name of the included file to the URL as a fragment, and evaluates this fragment if the current request is a non-AJAX request.

Also read https://medium.com/@stilkov/why-i-hate-your-single-page-app-f08bb4ff9134#.yay9gnbl5.

**Comment by TheCoder4eu** [comment]
I agree, bookmarkable URLS are very useful. I'll have a look at the linked article and think about it.

**Comment by stephanrauh** [comment]
In 2019, everybody who needs a SPA uses React.js, Vue.js or Angular. Let's close this ticket.
