### ISSUE TITLE
DataTable attribute for default sorting column

### ISSUE THREAD

**Issue by XaeroDegreaz** [TheCoder4eu/BootsFaces-OSP#254]

**Comment by XaeroDegreaz** [comment]
Some people at work were asking again about being able to sort things on a specific column when the page loads, so i thought I'd go ahead and fix this one myself. PR is up and ready to merge at your whim :)

**Comment by stephanrauh** [comment]
By the look of it, we've integrated your feature but forgot to close this issue. Be that as it may: default sort order is an official feature of BootsFaces 0.9.0 now.

**Comment by Kokscola** [comment]
Can you give an example how to set a default sorting column?
