### ISSUE TITLE
Tab demo doesn't work with AJAX

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#260]
The response text contains an error message ("wrong markup in line 47").

**Comment by zhedar** [comment]
Which Tab Demo did you mean? [This one?](https://github.com/stephanrauh/BootsFaces-Examples/blob/master/AJAX/src/main/webapp/index.xhtml)

**Comment by stephanrauh** [comment]
No, the first demo of the TabView showcase page: http://www3.bootsfaces.net/Showcase/bootstrap/tab.jsf
Currently, it's a non-AJAX demo. But when I tried to make the first button an AJAX button, the demo didn't work. I didn't check since then - maybe the error has been solved in the meantime.

**Comment by stephanrauh** [comment]
As it turns out, the error is caused by adding source code to the fourth tab, and trying to format it using SyntaxHighlighter. This works fine in non-AJAX mode but results in nested CDATA sections in the AJAX response.

**Comment by stephanrauh** [comment]
Now I've successfully converted the demo to AJAX. I consider this ticket closed.
