### ISSUE TITLE
AJAX request don't cope with non-AJAX responses

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#261]
Sometimes JSF answers an AJAX request with non-AJAX HTML. For instance, if an error occurs on the server side. This bug can be reproduced with the tab bug (issue #260).

**Comment by zhedar** [comment]
Is this still a separate issue or was it caused by the usage of a CDATA element in the component tree only?

**Comment by stephanrauh** [comment]
I've fixed the demo, but the problem persists. Throwing an NPE in an AJAX call results in a JavaScript error message at best, but there's no feedback to the user. I've started to investigate the topic this evening.

**Comment by stephanrauh** [comment]
The problem is harder than I expected. I hope to be able to solve it in JavaScript, but the message that arrives there is rather non-descript:
```xml
<error-name>class javax.faces.el.EvaluationException</error-name>
<error-message><![CDATA[]]>
```

**Comment by stephanrauh** [comment]
Maybe we should simply recommend using the `FullAjaxExceptionHandler` of OmniFaces. This reduces the problem to adding a documentation page :).

**Comment by zhedar** [comment]
I won't see any problem with that. OmniFaces is a defacto standard JSF framework anyway, so most of the users who would use BootsFaces probably already use it already. I guess we can't and shouldn't fix all of JSF's flaws.

**Comment by stephanrauh** [comment]
So true... but I don't think OmniFaces is a de-facto standard. 7000 downloads per month are impressive, but it's only a small fraction of the JSF programmers in total. But they have earned to be the de-facto-standard :).

**Comment by stephanrauh** [comment]
Finished the documentation. Let's close this ticket.
