### ISSUE TITLE
New component: b:focus

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#265]
This component is intended to set the input focus to a particular input field.

**Comment by zhedar** [comment]
I personally dislike the way this component was realized in PrimeFaces sometimes, because you need an extra reference:

    <p:focus context="panel"/>

Maybe it's still the best solution, but intuitively I always want to add to the actual component I want the focus to be on. I'm however not sure, if it would be possible to add it to another component like this instead:

    <h:inputText ...> 
       <b:focus/>
    </h:inputText ..>

Any thoughts on this?

**Comment by stephanrauh** [comment]
100% d'accord. Our (still undocumented) b:focus component currently uses the `target` attribute, but I think we can allow for both options.

**Comment by asterd** [comment]
Yes! I think is a good idea.. I'll working on it asap..
Il 25 mar 2016 21:06, "Stephan Rauh" <notifications@github.com> ha scritto:

**Comment by zhedar** [comment]
Concerning the configuration it's probably the best to take the referenced `target` component as a focus, if the attribute was set explicitly. If it's just plain `<b:focus/>` without a target, take the parent then?

**Comment by asterd** [comment]
Yes.. It is just my idea... I have to extend current behaviour to get
parent if target is not specified
Il 25 mar 2016 23:32, "Philipp Gruhn" <notifications@github.com> ha scritto:

**Comment by stephanrauh** [comment]
@asterd  Dario,if you want to take over, just re-assign the ticket to you.

@zhedar Philipp, yes, that's my idea - now that the `target` attribute has seen the light of the world, I don't see any point in removing it. Maybe it would be a good idea to add the same attribute the PrimeFaces guys use to avoid confusion. But that'd be an option. Using the parent attribute is (or will be) the approach recommend by the BootsFaces team.

**Comment by zhedar** [comment]
This seems to be implemented, should we change the milestone to 0.8.2?

**Comment by asterd** [comment]
Yes, sure.. I've only to add doc page..
