### ISSUE TITLE
New component: b:defaultCommand

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#266]
This component is intended to define which component is addressed when the user hits the "return" key.

**Comment by zhedar** [comment]
To track progress on this: This seems to be implemented in https://github.com/TheCoder4eu/BootsFaces-OSP/pull/313 by @asterd .

**Comment by stephanrauh** [comment]
@asterd I didn't see a documentation page. Would you mind to add a documentation page to our showcase?

**Comment by asterd** [comment]
@stephanrauh  doc added.. can i close this issue?

**Comment by stephanrauh** [comment]
Yes, we can! :)

**Comment by stephanrauh** [comment]
BTW, it's pretty cool that the default command supports multiple forms. I wasn't even aware this is possible. Good work! Thanks!
