### ISSUE TITLE
New feature: input mask for input fields

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#267]
This could be realized by a jQuery plugin, such as https://github.com/RobinHerbots/jquery.inputmask.

**Comment by AlexanderBl4h** [comment]
Hi Stephan,

am I overseeing this feature in 0.9.1? I can not find it. :( I am really using 0.9.1. No snapshot, nothing.

**Comment by stephanrauh** [comment]
No, it's simply not there yet. But you're free to contribute it :). The idea being that the input mask should be added to b:inputText and b:inputTextArea (as opposed to creating a new component). I believe our inputText is flexible enough to support input masks.

**Comment by AlexanderBl4h** [comment]
Oh dear. I looked really forward to see that! Yeah, can you give me some time? :) I am really running out of it. I got confused by `stephanrauh modified the milestone: v1.0.0, v0.9.1 on 10 Jul`,.

**Comment by stephanrauh** [comment]
There's no hurry. Originally, we wanted to release BootsFaces 1.0 before the JavaOne conference, but we've decided to delay it.

**Comment by stephanrauh** [comment]
Also see http://stackoverflow.com/questions/42101088/how-to-add-mask-for-component-input-text-bootsfaces/42122975#42122975.

**Comment by jepsar** [comment]
Though Robin Herbots plugin looks good, it is quite large and probably only a little part of it is needed. How about https://github.com/estelle/input-masking ? Looks good enough to me.

**Comment by stephanrauh** [comment]
Good hint. At first glance, I don't see any reason not to use Estelle's library.

**Comment by jepsar** [comment]
I've been playing with Estelle's library for a while, and it does not feel solid. I've seen some glitches in updating the placeholder.

> The idea being that the input mask should be added to b:inputText and b:inputTextArea (as opposed to creating a new component)

Doesn't this mean that input mask resources need to be loaded, even when they are not used? Let me have a look what the minimal set of js files from Robin's library will weigh.

**Comment by jepsar** [comment]
The JS file was about 75kB.

See PR https://github.com/TheCoder4eu/BootsFaces-OSP/pull/791

I did not add it to the `b:inputTextArea`. Would that be useful? I don't think so.

**Comment by stephanrauh** [comment]
@jepsar The feature works on my local machine, but not on our showcase (http://www3.bootsfaces.net/Showcase/forms/inputText.jsf). The only difference I've spotted so far is that the JavaScript code is not included with the minified code generated by the `CombinedResourceHandler` of OmniFaces. Can you have a look at the problem?

Otherwise, thanks for the good work! I think we're almost there!

**Comment by jepsar** [comment]
@stephanrauh I'll have a look tonight. The embedded JavaScript is also not rendered. I simply build using the `pom.xml` where I've updated the BootsFaces dependency to `1.1.2-SNAPSHOT`. Probably something Gradle related in the showcase.

**Comment by jepsar** [comment]
@stephanrauh As expected, I missed a dependency in `gradle.build`. I now used Gradle to build and the resulting war contained the correct jar (including the mask plugin).
See PR https://github.com/TheCoder4eu/BootsFacesWeb/pull/47

**Comment by TheCoder4eu** [comment]
@stephanrauh the PR is merged.

**Comment by TheCoder4eu** [comment]
The example is working in the devel showcase.
Thanks @jepsar and @stephanrauh !
