### ISSUE TITLE
Incompatibility between ButterFaces and BootsFaces

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#270]
Twitter user Jonathan LALOU ‏(@John_the_Cowboy) reports that adding the ButterFaces dependency to the Maven pom.xml prevents @bootsfaces' `<b:navBar>` from expanding its `<b:dropMenu><b:navLink>` submenus.

**Comment by JonathanLalou** [comment]
Hi,

More details:
* deployment under Jetty Maven plugin
* versions
```xml
        <jetty.version>9.3.0.v20150612</jetty.version>
        <jsf.version>2.2.6</jsf.version>
        <butterfaces.version>1.10.0</butterfaces.version>
        <omnifaces.version>1.12.1</omnifaces.version> <!-- same issue with omnifaces 1.8-->
        <bootsfaces.version>0.9.0-SNAPSHOT</bootsfaces.version>
 ```
* the dependency was added in Maven, but no widget from Butterfaces is called in XHTML files anyway.

**Comment by stephanrauh** [comment]
I managed to reproduce the error, at least partially. Need to fix the resource ordering algorithm.

**Comment by stephanrauh** [comment]
We've dropped ButterFaces support after running out of team members.
