### ISSUE TITLE
DataTable duplicates filter inputs, and paginator when updated via AJAX

### ISSUE THREAD

**Issue by XaeroDegreaz** [TheCoder4eu/BootsFaces-OSP#272]
Bootsfaces 0.8.1

```xml
.......
<b:commandButton
	value="Apply"
	action="#{indexPage.updateAgentsToBeReviewed()}"
	update="agentsToBeReviewedDatatable"
	ajax="true"
	styleClass="btn-block" />
..........

<b:dataTable
	id="agentsToBeReviewedDatatable"
	styleClass="table table-striped table-bordered"
	value="#{indexPage.annotationsToBeReviewed}"
	var="annotation">
	<h:column>
		<f:facet name="header">Team</f:facet>
		#{annotation.team.name}
	</h:column>
	<h:column>
		<f:facet name="header">Agent</f:facet>
		#{annotation.agent.agentName}
	</h:column>
	<h:column>
		<f:facet name="header">Calls</f:facet>
		<h:form>
			<b:commandButton
				value="Get Calls"
				action="#{indexPage.updateCallQueue(annotation.agent)}"
				ajax="true"
				update="callQueueColumn" />
		</h:form>
	</h:column>
</b:dataTable>
```

![image](https://cloud.githubusercontent.com/assets/312459/12561038/9c2e798a-c363-11e5-9a37-00a23608e684.png)

It will actually continue to duplicate even more every time you refresh the DataTable itself.

If you refresh the parent of the DataTable it renders properly, though.

**Comment by stephanrauh** [comment]
@XaeroDegreaz I know it's nasty to ask you, but now that you've started to improve the data table and to send us a pull request, are you interested in investigating the error yourself?

**Comment by XaeroDegreaz** [comment]
It's not nasty at all. I'll look into it, and after looking inside the renderer I think I have an idea of how to fix it :)

**Comment by stephanrauh** [comment]
Great, thanks! BTW, I'm still waiting for your pull request. I can integrate your changes myself, but if you send us a pull request, GitHub automatically adds you to the hall of fame of contributors.

**Comment by XaeroDegreaz** [comment]
Sorry I've been at work. I will put the pull request in when I get home, however I don't think it's fully completed. For instance, I still need you guys to send me your formatter at a minimum :D

**Comment by XaeroDegreaz** [comment]
It would serve as an easier way to talk about the changes though and refine them.

**Comment by stephanrauh** [comment]
Take your time. Just wanted to make sure your PR doesn't get lost.

As for the code formatter: I simply use the standard formatter of Eclipse 4.x. @TheCoder4eu Riccardo, what about you? Which formatter do you use? Seems we've never talked about it.

In any case: don't worry about it. If we don't like the formatting, it's just one keystroke to reformat it :).
