### ISSUE TITLE
Message / Messages escape attribute (for Links etc)

### ISSUE THREAD

**Issue by underflyer** [TheCoder4eu/BootsFaces-OSP#273]
Hi,

Within a FacesMessage it should be possible to show a clickable Link
currently "& lt;" and "<" will be rendered as "& lt;" and "<" in b:Messages and b:message
So an Attribute like "escape" would be fine:
```xml
<b:messages escape="true"/>
```
EXAMPLE:
```xml
"Info:  Click <a href="surprise.jsf" >here</ a> for your Solution"
```
Best Regards

**Comment by underflyer** [comment]
Hi,
does these Labels "user Support"/Question mean it is already possible?

**Comment by stephanrauh** [comment]
No, we don't support the escape attribute yet. But I think it's a good idea. I've changed the label.

**Comment by stephanrauh** [comment]
When I started to implement the feature, I stumbled over this StackOverflow article:

http://stackoverflow.com/questions/3356546/embedding-a-link-or-other-html-in-a-jsf-message

By the look of it, standard JSF messages don't support the `escape` attribute. I'll implement it nonetheless.

**Comment by stephanrauh** [comment]
Done and documented.

**Comment by stephanrauh** [comment]
You can see the effect of the new attribute at http://www3.bootsfaces.net/Staging/forms/messages.jsf. Try "info" in the topmost example. In the example below, there's always a difference between escaping and non-escaping.
