### ISSUE TITLE
label - renderLabel

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#276]
Hello All,

I would like to ask you, why are there renderLabel property to input elements?

Thank you,
Mihaly

**Comment by TheCoder4eu** [comment]
Hi,
in some situations you woud prefer the Label not to be rendered.
Have a look in the doc in the Reference section:

http://www.bootsfaces.net/forms/inputText.jsf

The default is false.
"Allows you to suppress automatic rendering of labels"

**Comment by lyahim** [comment]
Thank you.

**Comment by stephanrauh** [comment]
I'd like to add a parameter in the `web.xml` to make the default configurable. How do you guys like the idea?

**Comment by lyahim** [comment]
If somebody not want to use label why set the label attribute?

**Comment by stephanrauh** [comment]
In JSF, the label attribute has yet another meaning. We used this attribute in BootsFaces to display a Bootstrap label. But the original meaning of the label is it's used in error messages. Consider this code:
```xml
<h:inputText value="..." label="First name" id="firstname" required="true"/>
<h:message for="firstname">
```
The corresponding error message is "First name: field is required" (or something like that). The bottom line being that the text "First name" of the error message is precisely the value of the `label` attribute of the `<h:inputText />`.

**Comment by lyahim** [comment]
Hello Stephan,

I thinking about this topic, and I have an other question. What do you use the title attribute?

Thank you,
Mihaly
