### ISSUE TITLE
datepicker label

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#277]
Hello All,

Is it possible to add label attribute to datepicker?

Mihaly

**Comment by stephanrauh** [comment]
Sure. I've implemented and documented the new label attributes in the 0.9.0 branch. In case you want to test the feature: see #151 on how to get the developer snapshot.

**Comment by lyahim** [comment]
And now I noticed now, the form-group div wrapper is missing too.
