### ISSUE TITLE
f:convertNumber doesn't generate error message

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#280]
Hello All,

I would like to use f:convertNumber to validate some inputText fields, but it doesn't work.
The original JSF `h:inputText` sends back an error message if the submitted value cannot be converted to number. For example:
```xml
<h:inputText value="#{lessonEditBean.editedLesson.discount}" required="true">
    <f:convertNumber integerOnly="true" />
</h:inputText>
```
Your component sends back the following response:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
  <error>
    <error-name>class javax.faces.component.UpdateModelException</error-name>
    <error-message><![CDATA[/private/lesson_edit.xhtml @24,75 
        value="#{lessonEditBean.editedLesson.discount}": Cannot convert asd of type class 
        java.lang.String to class java.lang.Integer]]>
    </error-message>
  </error>
</partial-response>
```

Thank you,
Mihaly

**Comment by lyahim** [comment]
f:convertDateTime is similar

**Comment by stephanrauh** [comment]
I have to admit I wasn't even aware of these converters. In my eyes, this class of user error should either be handled by the backend bean (and the bean validation API in particular), or by client-side JavaScript code. However, it's valid JSF, so we should support it. Thanks for the hint!

**Comment by stephanrauh** [comment]
Seems we've already solved the issue some time ago. See http://www3.bootsfaces.net/Showcase/forms/converters.jsf for a working demo.
