### ISSUE TITLE
Multiple DataTables on the page cause error when paginating or filtering

### ISSUE THREAD

**Issue by XaeroDegreaz** [TheCoder4eu/BootsFaces-OSP#285]
@stephanrauh @TheCoder4eu 

#279 Introduced a bug :(

I'm looking into the below stack trace, and seeing how the JSF tries to figure out the forms. Perhaps I've invoked the `BsF.ajax()` call incorrectly?

This affects all pages with multiple DataTables on them whether or not they are using the new attributes.

In any case, I'd recommend either backing out the merge request #281 if you want to release any artifacts, or postponing any releasing of artifacts until I can complete one of these and get you to merge it into master:

* **Limit the scope of the breakage (mask the bug)**, e.g. do not break pre-#279 multiple DataTable pages by only performing the `BsF.ajax()` calls when the `dataTableProperties` attribute is set. Explain that this iteration of the attribute is a feature-in-progress and only works with a single DataTable per-page.
* **Add some JavaScript error handling** for these calls so that they fail gracefully, but still outline that the persistence map is still a WIP.

```
Uncaught clientError: Sourceform could not be determined, either because element is not attached to a form or we have multiple forms with named elements of the same identifier or name, stopping the ajax processing

jsf.js.jsf?ln=javax.faces&stage=Development:8735
```

I'm continuing to investigate, and will get a quick-fix PR put together ASAP in order to mask the bug. Sorry for my carelessness, I can't believe I didn't test this sooner.

**Comment by XaeroDegreaz** [comment]
Ok, pull request is in, but I'd request that this issue not be closed, as this is still an open bug and I'll still be searching for the actual solution to the root problem.

The fix makes sure the error doesn't bubble up and break normal functionality with searching and stuff.

**Comment by XaeroDegreaz** [comment]
Ok, so I've had some more time to play with this bug.

I first encountered it when testing the snapshot on a project at work that had multiple tables on the page. I've since masked that, but when I tried on a personal test project at home, the bug never actually happened!

I think there must be some funny difference in a form on the page or something. So while testing having forms on the page, and DataTables in form, I encountered the same bug as #241.

The rendering fix inside #272 uses a JQuery selector to select the wrapper that is generated for the DataTable. That wrapper gets its ID attribute from the TRUE DataTable ID. So when it's in a form it looks like `FormID:DataTableID`. The `:` is an invalid character in a JQuery selector so it blows up. In order to combat that I had to escape it so that it was valid according to the accepted answer in [this post](http://stackoverflow.com/questions/16077280/uncaught-error-syntax-error-unrecognized-expression-unsupported-pseudo).

I'm not entirely certain if this fixes the situation with the project at work, but I will verify that when I have a chance.

I know I type a lot, but I find it important to document everything :)

**Comment by stephanrauh** [comment]
I've merged your pull request to the master branch of BootsFaces (i.e. BootsFaces 0.8.2-SNAPSHOT). I've also uploaded the new developer snapshot to Maven Central (see #151). If this solves the bug, feel free to close this issue. In any case, please report back.

Thanks in advance
Stephan

**Comment by XaeroDegreaz** [comment]
I tested it with my work project and still haven't figured out what's causing it to fail in that particular project. There has to be something 'special' about that project. Has to be something with an errant form or something.

I've spun up several different personal projects testing multiple tables and there are no issues.

I'll keep investigating. In the meantime, if you want to just assign this ticket to me, or close this one and I can open another PR in the future if I find out the root cause to be something on the framework side.

**Comment by XaeroDegreaz** [comment]
I'm going to close this issue as the core issue `Multiple DataTables on the page cause error when paginating or filtering` has been solved.

I have been unable to replicate the failures in new projects since the fix, and there must be some special circumstance with the codebase with which I initially discovered this issue.

Any other projects out there that experience this bug will fail gracefully, and there will be errors in the JavaScript console. If you're somehow able to replicate this bug in a project, I guess you can reopen this ticket or create a new issue with exact information as how to produce the bug, and I'd be happy to fix it.
