### ISSUE TITLE
datepicker error message show id

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#287]
Hello All,

When datepicker validation failing the message generated wring because its shown the component id instead of label.
I think the buggy code is on DatePicker.java

/*     */   public String getLabel(FacesContext context)
/*     */   {
/* 562 */     Object o = getAttributes().get("label");
/* 563 */     if ((o == null) || (((o instanceof String)) && (((String)o).length() == 0))) {
/* 564 */       ValueExpression vex = getValueExpression("label");
/* 565 */       if (null != vex) {
/* 566 */         return (String)vex.getValue(context.getELContext());
/*     */       }
/*     */     }
/* 569 */     return getClientId(context);
/*     */   }
/*     */ }

Best Regards,
Mihaly

**Comment by stephanrauh** [comment]
I think you're right. I'd like to refactor the component, anyways. `getAttributes().get("label");` doesn't conform to the JSF coding conventions, and in some corner cases, JSF doesn't support this coding style. However, as a first step, I've fixed the bug. Would you like to test it? I've uploaded a developer snapshot to Maven Central (see #151 on how to get it). Feel free to reopen the ticket if something's wrong.

**Comment by lyahim** [comment]
Hello Stephan,

I've checked the changes, and looks good.
Where can I reopen a ticket?

**Comment by stephanrauh** [comment]
Hi Mihaly,

if you can reopen the ticket, there's a button below the comment field (see screenshot). Sometime people do reopen our tickets, so I believed this option is available to everybody. If you, you can always ask us to open it again :).

![image](https://cloud.githubusercontent.com/assets/3045767/12986485/ce4ab87e-d0f7-11e5-8e29-c6dd0901328e.png)

**Comment by lyahim** [comment]
I have no right to reopen an issue :( Not shown the button.
