### ISSUE TITLE
Quickstart is not working

### ISSUE THREAD

**Issue by leolux** [TheCoder4eu/BootsFaces-OSP#289]
I tried to follow the instructions of the quickstart guide [1] But my webapp produces the following exception on startup:

1100: Error loading theme, cannot find "css/bsf.css" resource of "bsf" library
javax.faces.FacesException: Error loading theme, cannot find "css/bsf.css" resource of "bsf" library
	at net.bootsfaces.listeners.AddResourcesListener.processEvent(Unknown Source)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)
	at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2169)
	at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2142)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:301)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:245)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:107)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)

I am running tomcat 8 and all the latest libraries for JSF, BootsFaces and Primefaces. I didn't include the library OmniFaces because I don't need it in general and because it wasn't mentioned in the quickstart guide [1]. 

Is there something missing in the quickstart?

[1] http://www.bootsfaces.net/quickstart.jsf

**Comment by stephanrauh** [comment]
Maybe you have to add the theme context parameters?

```xml
<context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>default</param-value>
</context-param>
```

Possibly also
```xml
<context-param>
    <param-name>BootsFaces_THEME</param-name>
    <param-value>cerulean</param-value>
</context-param>
```

**Comment by leolux** [comment]
I am still getting the same error. Btw I am using tomcat8. Even if I add weld-servlet-2.3.2.Final.jar to my webapp the same error occurs. 

This is the content of my web.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd" id="WebApp_ID" version="3.1">
  <display-name>webapp</display-name>
  <welcome-file-list>
    <welcome-file>faces/index.xhtml</welcome-file>
  </welcome-file-list>
  <servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
  </servlet-mapping>
  <context-param>
    <param-name>javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
    <param-value>false</param-value>
  </context-param>
  <context-param>
    <param-name>com.sun.faces.enableMissingResourceLibraryDetection</param-name>
    <param-value>true</param-value>
  </context-param>
  <context-param>
    <param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
    <param-value>true</param-value>
  </context-param>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.jsf</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.faces</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.xhtml</url-pattern>
  </servlet-mapping>
  <context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
  </context-param>
  <context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>default</param-value>
  </context-param>
  <context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>bootstrap</param-value>
  </context-param>
  <session-config>
    <tracking-mode>COOKIE</tracking-mode>
    <tracking-mode>URL</tracking-mode>
  </session-config>
</web-app>`

Here is my faces-config.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd"
	version="2.2">
	<application>
		<resource-bundle>
			<base-name>JSF Hello World</base-name>
			<var>labels</var>
		</resource-bundle>
		<resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
	</application>
</faces-config>`

And I have the following libraries in WEB-INF/lib:
- BootsFaces-OSP-0.8.1-dist-default.jar
- jsf-api-2.2.11.jar
- jsf-impl-2.2.11.jar
- jstl-1.2.jar
- omnifaces-2.2.jar
- primefaces-5.3.jar
- weld-servlet-2.3.2.Final.jar

The quickstart guide tells me that starting with BootsFaces is as simple as adding the jar to the libraries and adding the namespace xmlns:b="http://bootsfaces.net/ui" to a JSF page. But this results in  
> cannot find "css/bsf.css" resource of "bsf" library

Any idea what I might have to change?

**Comment by stephanrauh** [comment]
It's nothing to do with your issue - but I suggest you remove the /faces/* URL pattern from your web.xml. It's one of the thing almost every tutorial and textbook tells you to do. But in my eyes, this is an additional indirection making it difficult to understand the code. But of course it's up to you - it's just my personal opinion.

**Comment by stephanrauh** [comment]
As for your issue: it's true, the file "css/bsf.css" isn't part of the library. Actually, it shouldn't be accessed at all. The correct path is "css/default/bsf.css".

**Comment by stephanrauh** [comment]
Oh, I see: there's an annoying typo in our showcase. The correct section of the `web.xm` is:

```xml
    <context-param>
        <param-name>BootsFaces_THEME</param-name>
        <param-value>default</param-value>
    </context-param>
    <context-param>
        <param-name>BootsFaces_USETHEME</param-name>
        <param-value>true</param-value>
    </context-param>
```

**Comment by stephanrauh** [comment]
@leolux I'd like to keep the issue open until you confirm my hint solved your issue. So, please report us back, no matter whether my hint works for you or not :). 

Thanks in advance!
Stephan

**Comment by leolux** [comment]
Your are right! When I remove the /faces/* URL pattern from your web.xml and update the web.xml as you described, the error (cannot find "css/bsf.css") is gone.

But the application hangs on startup without producing any error message in the server console. When the client (browser) connects to index.html the server doesn't respond until the client gives up. This bug must get introduced by BootsFaces because the application works again as soon as I remove the dependency:

`<dependency>
    <groupId>net.bootsfaces</groupId>
    <artifactId>bootsfaces</artifactId>
    <version>0.8.1</version>
    <scope>compile</scope>
</dependency>`

**Comment by stephanrauh** [comment]
Actually, if there server doesn't react at all, there's little reason why it should produce an error concerning the css file :).

I suggest you tackle the problem from a different angle. Try one of our demos. Our showcase is a very complex demo (https://github.com/TheCoder4eu/BootsFacesWeb). There are also much smaller demos at https://github.com/stephanrauh/BootsFaces-Examples. Most of them are simple Maven project. Try to get one of the demos up and running. When you've managed that, we can compare your project and our demo project to learn what went wrong.

**Comment by leolux** [comment]
I think that this issue can be closed now. The only problem left is that the application doesn't startup correctly but this should be the responsobility of the server.
