### ISSUE TITLE
datepicker ajax support

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#298]
Hello All,

Is it possible to add ajax support to datepicker?

Thanks,
Mihaly

**Comment by stephanrauh** [comment]
Sure. Currently, we've got so many open ticket that we have to start to prioritize things. How fast do you need the AJAX support?

**Comment by lyahim** [comment]
At now I can solve with Remotecommand.

```xml
<b:datepicker id="dateSelect" value="#{calendarBean.selectedDate}" placeholder="1900-01-01" 
						dateFormat="#{appBean.defaultDatePattern}">
						<p:remoteCommand name="rc" update="calendars" actionListener="#{calendarBean.changeDate}" />
						</b:datepicker>
						<script>
							$("#calendarForm\\:dateSelect").attr('onchange','rc()');
						</script>
```

**Comment by stephanrauh** [comment]
Hey, that's a pretty cool workaround! And a clear case for using PrimeFaces along with BootsFaces :).

Nonetheless, we won't forget your issue. It's just good to know we don't have to solve it today :).

**Comment by stephanrauh** [comment]
I'll close this ticket in favor of #572. BTW, we've called the component b:dataPicker deprecated because we'd like to get rid of the dependency to jQueryUI. You can use b:dataTimePicker instead. So I'm not sure we'll add AJAX to the deprecated component. The new component offers full support of AJAX.

**Comment by ErickPezoa** [comment]
What version do we need to have the component b:dataTimePicker?

**Comment by stephanrauh** [comment]
Both 1.0.2 and the upcoming 1.1.0 should be ok.
