### ISSUE TITLE
<b:inputText value="#{anInteger}">: Exception thrown on non-numeric input 

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#30]
Consider the following code:
```XML
<h:outputText value="Integer 1 (BootsFaces)"/>
<b:inputText id="v1" value="#{settingsBean.value1}" />
<h:message for="v1"/>
<h:outputText value="Integer 2 (MyFaces)"/>
<h:inputText id="v2" value="#{settingsBean.value2}" />
<h:message for="v2"/>
<b:commandButton value="Apply" ></b:commandButton>
```
Both values are int fields:
```Java
@RequestScoped
@ManagedBean
public class SettingsBean {
	private int value1; // getter and setter omitted 
	private int value2; // for sake of brevity
}
```
Submtting a letter in the MyFaces field will produce a FacesMessage:
![image](https://cloud.githubusercontent.com/assets/3045767/5329252/cb64c2c8-7da4-11e4-951c-c6c56ad9e5ae.png)

However, submitting a letter in the BootsFaces field results in a much more ugly exception:
* input:
![image](https://cloud.githubusercontent.com/assets/3045767/5329256/ea2370b0-7da4-11e4-8233-fd3abd3a9e6e.png)

* result:
![image](https://cloud.githubusercontent.com/assets/3045767/5329261/09942746-7da5-11e4-9675-e91161863b39.png)

**Comment by TheCoder4eu** [comment]
should be the missing Override of getConvertedValue() in InputText Renderer.

**Comment by TheCoder4eu** [comment]
Tested, this fixes the bug.
