### ISSUE TITLE
popover support???

### ISSUE THREAD

**Issue by fwelland** [TheCoder4eu/BootsFaces-OSP#300]
So after a bit of trial and error and some investigation, I found that popovers didn't work in BootsFaces 0.8.1.   

Further, they seemed to be commented out in the gradle build file in BootsFaces-OSP/gradleResources.   

Why and how do I address this?    

NOTE1:  
I did comment out the exclusions in the build file for gradleResources -- that seems to help address issue -- but not clear why that js and a couple of others are omitted in first place

NOTE2:  
Are there some instructions for how to use the gradle build files?    The web site says run clean assemble.    That doesn't crash but results JAR is incomplete; and there doesn't seem to be deps to cause stuff in gradleResouces to build as well.

**Comment by stephanrauh** [comment]
@TheCoder4eu Riccardo, this seems to be your field of expertise.

**Comment by TheCoder4eu** [comment]
I added support for Popovers wit the last less refactoring.
