### ISSUE TITLE
dataTable i18n

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#301]
Hello All,

Could you set in future i18n feature for dataTable?

Link to help:
https://www.datatables.net/plug-ins/i18n/

Best Regards,
Mihaly

**Comment by stephanrauh** [comment]
Sure! In the meantime, have a look at this StackOverflow issue: http://stackoverflow.com/questions/35517215/bootsfaces-datatable-change-default-values/35528829#35528829

**Comment by lyahim** [comment]
Thank you.

**Comment by asterd** [comment]
In development version, dataTable already supports i18n with the attributes lang and customLangUrl. Lang supports only a restricted set of languages, customLangUrl instead, adds the ability to specify an external dataTable language file.

**Comment by asterd** [comment]
3963916 add this enhancement
