### ISSUE TITLE
selectOnemenu ajax update

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#302]
Hello All,
I try to update a selectOneMenu with other one with ajax.
the code is:

``` xml
<b:selectOneMenu id="cSelect" onchange="ajax:passEditBean.changeClient()" update="lSelect" required="true">
    ....
</b:selectOneMenu>
<b:selectOneMenu id="lSelect">
  ....
</b:selectOneMenu>
```

The result is the following:

![image](https://cloud.githubusercontent.com/assets/3195083/13198540/db7ade96-d80b-11e5-9075-826dd738e18c.png)

The ajax response is:

``` xml
<?xml version="1.0" encoding="UTF-8"?><partial-response id="j_id__v_0"><changes><update id="passForm:lSelect"><![CDATA[<div class="form-group"><label for="passForm:lSelect" class="bf-no-message">???pass_edit.lesson???</label>
<select id="passForm:lSelect" name="passForm:lSelect" class="form-control bf-no-message" title="???pass_edit.lesson???"><option data-label="Kérem válasszon" value="">Kérem válasszon</option><option data-label="Típus 1" value="1" selected="true">Típus 1</option><option data-label="típus2" value="2">típus2</option></select></div>]]></update><update id="j_id__v_0:javax.faces.ViewState:1"><![CDATA[fDilWxUAxJcYO7cVx9EQF8+nI+p5cAoX8rHZ15MrvMX29WiO]]></update></changes></partial-response>
```

Do I something wrong or is it a bug?

Thank you,
Mihaly

**Comment by stephanrauh** [comment]
After reformatting, the AJAX response looks like so:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<partial-response id="j_id__v_0">
  <changes>
    <update id="passForm:lSelect"><![CDATA[
      <div class="form-group">
        <label for="passForm:lSelect" class="bf-no-message">???pass_edit.lesson???</label>
        <select id="passForm:lSelect" name="passForm:lSelect" class="form-control bf-no-message" title="???pass_edit.lesson???">
          <option data-label="Kérem válasszon" value="">Kérem válasszon</option>
          <option data-label="Típus 1" value="1" selected="true">Típus 1</option>
          <option data-label="típus2" value="2">típus2</option>
        </select>
      </div>
    ]]>
    </update>    
    <update id="j_id__v_0:javax.faces.ViewState:1"><![CDATA[fDilWxUAxJcYO7cVx9EQF8+nI+p5cAoX8rHZ15MrvMX29WiO]]></update>
  </changes>
</partial-response>
```

**Comment by lyahim** [comment]
Yes, It looks the response update the id="passForm:lSelect" which is the 'select' not the whole div wrapper. For example inputText wrapper div has the id and the input has a modified id.

**Comment by stephanrauh** [comment]
By the look of it, the attributes "update", "process" and "ajax" were missing in the taglib. I've added them to make them available for NetBeans user and for the autocompletion of your IDE.

**Comment by stephanrauh** [comment]
Also see PR #296 .

**Comment by stephanrauh** [comment]
I've uploaded a developer snapshot to Maven Central containing a bugfix. As usual, see #151 on how to get the snapshot. Would you mind to test the bug?

Thanks in advance!
Stephan

**Comment by lyahim** [comment]
I will checking

**Comment by lyahim** [comment]
Hello Stephan,
I don't see any changes in snapshot. Is it possible couldn't make the deploy?

Mihaly

**Comment by zhedar** [comment]
@lyahim This may be a bit late, but you may either have to delete the 0.8.2-Snapshot files in your local Maven-Repository or explicitly force Maven to update the dependencies. Maybe that's why the snapshot seems stale to you?

**Comment by stephanrauh** [comment]
I've just retested the issue. We've solved the bug in the meantime. I'll close the issue.
