### ISSUE TITLE
Better attribute names for b:navBar

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#303]
I'm a bit unhappy with some of the attribute names of b:navBar. They are far from being intuitive, at least in my eyes:
* fixed="top"
* fixed="bottom"
* fixed="non-sticky" (but is it at the top or the bottom?)
* static="true" (can that be combined with the fixed attribute?

What about renaming them like so?
* position="top" or "bottom" or "inline" (default being "top")
* sticky="true" or "false" (default being true)

@asterd @TheCoder4eu How do you like the idea?

**Comment by asterd** [comment]
I agree with you that the attribute names are a bit unclear. I've used a new value for the fixed attribute because i would not modify the navbar attribute list. But your proposal sounds me good! Non-sticky is only for the bottom at this moment, so using a new attribute can be a very good idea.

**Comment by stephanrauh** [comment]
Finished and documented a basic implementation. Todos left:
* better documentation
* testing

**Comment by stephanrauh** [comment]
Seems like I've written the documentation, but forgot to close the issue. Herewith, I declare it closed.
