### ISSUE TITLE
Multi-theme Gradle build produces identical themes

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#307]
On a short test, it looked like the multi-theme Gradle build introduced with PR #304 produces identical themes.

**Comment by stephanrauh** [comment]
Dario, it's been a busy week for me, so I forget the current state of things... did you already solve this problem?

**Comment by asterd** [comment]
Hi, i understand! I've already solved.. Or better: i have restored the
original build gradle with only one addition to provide conditional theme
compilation from an external java client.. So the build is basically the
old one but now there is a java program that call the script multiple times
with different theme as parameter..
Il 05 mar 2016 23:21, "Stephan Rauh" <notifications@github.com> ha scritto:

**Comment by TheCoder4eu** [comment]
Hi Dario, can we close the issue?

**Comment by asterd** [comment]
Hi! Yes you can close it!
Il 12 mar 2016 16:38, "TheCoder4eu" <notifications@github.com> ha scritto:
