### ISSUE TITLE
Unable to find resource bsf, css/flatly/icons.css

### ISSUE THREAD

**Issue by RenanSant** [TheCoder4eu/BootsFaces-OSP#308]
icons.css is in the wrong directory: css/icons.css

**Comment by TheCoder4eu** [comment]
What version of BootsFaces are you using?
icons.css is common to all Themes, can you give us a snippet to verify your issues?

**Comment by TheCoder4eu** [comment]
Hi, I had no answer, can we assume you solved the issue or can you give us a snippet to verify your issue?

**Comment by chiux119** [comment]
Hi, there. I'm having the same problem. I'm using version 0.8.1. 
On the web app I'm working on when I try to navigate to a new page I get an error that says
Unable to find resource bsf, css/default/icons.css

I checked the jar file and icons.css is in css, but not css/default.

**Comment by stephanrauh** [comment]
I managed to reproduce and find the problem. BTW, there's a similar issue at #328 , so I'll close this issue. Please follow #328 to track progress.
