### ISSUE TITLE
<b:tabView /> forgets the active tab on page submit or reload

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#31]
&lt;b:tabView&gt; shows the first tab after each page reload. I suggest to store the active tab in the view scope to fix this.

**Comment by xystra** [comment]
0.6.6 when a commandbutton is clicked within one of the tabs and the view refreshes, the active tab is reset to 0, not the tab you were originally in.

**Comment by stephanrauh** [comment]
I tried and failed to reproduce the problem with BootsFaces 0.6.7. Both h:commandButton and b:commandButton show the last active tab after an page submit. I tested both Mojarra 2.2.11 and MyFaces 2.2.7. I close the issue until you send us a reproducer project.

**Comment by stephanrauh** [comment]
It's important to put the entire tabView into the same form as the commandButton. Otherwise, the active tab index - which is stored in an invisible input field - is not sent to the server. Probably this caused your problem. I'm going to mention this in the documentation.

**Comment by stephanrauh** [comment]
Added the documentation.

**Comment by xystra** [comment]
So something like this will not work?

```
<div class="main-content">
<b:tabView activeIndex="0" styleClass="nav-tabs-custom-colored">
    <ui:include src="tab1.xhtml" />
    <ui:include src="tab2.xhtml" />
    <ui:include src="tab3xhtml" />
</b:tabView>
</div>
```

and

```
<ui:composition>
    <b:tab title="#{tabTitle}">
<div class="widget widget-table">
        <div class="widget-header">
<h3><i class="fa fa-table"></i> <h:outputText value="#{title}"/></h3>
</div>
 <div class="widget-content">
<h:form>
 <div class="row">
 <div class="col-md-6">
 <b:inputText value="#{bean.externalValue}" label="External Value"
required="true" converter="toUpperCase"/>
 </div>
 <div class="col-md-6">
 <b:selectOneMenu value="#{bean.referenceCodeId}" id="refCode" label="IBIS
Value">
            <f:selectItems value="#{bean.commonData}" var="common"
itemLabel="#{common.description}" itemValue="#{common.code}"/>
        </b:selectOneMenu>
 </div>
</div>
 <div class="row">
 <div class="col-md-12">
 <b:commandButton action="#{bean.addMapping()}" value="Add Mapping"
styleClass="btn-primary" iconAwesome="plus" />
 </div>
</div>
<p/>
<hr width="100%" size="1"/>
<p/>
</h:form>

...

```

**Comment by stephanrauh** [comment]
No, I'm afraid it won't. That's how HMTL works: there's a form, and when you submit something, you submit this form. Everything outside is ignored. We could send an AJAX request to the server each time a tab is clicked, but this produces a lot of network traffic, so I'm reluctant to do something like that.

**Comment by xystra** [comment]
How about providing a setter for the active tab in the TabView class? This way I can set it within my bean?

**Comment by stephanrauh** [comment]
It's already there. It's the activeIndex attribute which can be bound to an EL expression. What's missing is the other way round: the tabs don't send their state to the server unless they are in a form.

**Comment by xystra** [comment]
I don't see getter/setter for the activeIndex in the TabView? Am I missing something?

**Comment by stephanrauh** [comment]
Exactly. See http://www.bootsfaces.net/bootstrap/tab.jsf. The example uses a fixed index number, but it should be possible to use a EL expression, too.

**Comment by xystra** [comment]
This is what I'm doing..

JSF:
```HTML
<b:tabView activeIndex="#{general.getActiveIndex(1)}" styleClass="nav-tabs-custom-colored">
```

Bean:
```Java
   public static enum Section
   {
        SECTION_1,
        SECTION_2,
        SECTION_3
   }

   public int getActiveIndex(final int section)
   {
      return activeIndex.get(Section.values()[section]);
   }
```

Bean handling form submit from within tabs
```Java
   @Override
   public void setActiveTabIndex()
   {
      GeneralInfoBean.setActiveIndex(Section.SECTION_1, 1);
   }
```

It's still defaulting to 0 all the time. When I debug the setter is being called and the correct value is being set, but I never get a breakpoint on the getter which should be called from the EL expression..

**Comment by stephanrauh** [comment]
I had the same problem with another component earlier this day, but I hoped it was just a typo. I'll have a look at if. It might be a general problem.

**Comment by xystra** [comment]
did you manage to reproduce this one?

**Comment by stephanrauh** [comment]
Yes, I did. I re-implemented b:panel, and now it works. I ran a few tests, and it seems to be true: it's not a good idea to call UIComponent.getAttribute() to read the attributes of JSF components. Most of the time, the approach works, but the combination of EL expressions and numeric or boolean values seems to fail in a reproducible way. In other words: I'll re-implement b:tabView, too.

**Comment by stephanrauh** [comment]
Now the activeIndex property can be bound to an EL expression. Until the user clicks a tab, that is: in that case the user's choice overrides the bean's choice.
