### ISSUE TITLE
List Element arround Navlinks

### ISSUE THREAD

**Issue by ScreamingTree86** [TheCoder4eu/BootsFaces-OSP#310]
Hi,
is it right that every Navlink in a Container Column has a bullet point in front of it because it will be set in a list element. 
Is it possible to get rid of this? Because it looks kind of weird.

![asdasd](https://cloud.githubusercontent.com/assets/6475837/13316080/88994dd8-dbae-11e5-8cdf-d75a18b48943.PNG)

**Comment by TheCoder4eu** [comment]
Hi, you are right, I wanted to add an attribute to avoid the List element to be rendered, but it won't be the default.

**Comment by stephanrauh** [comment]
@ScreamingTree86 @TheCoder4eu As far as I understand, `<b:navLink />` is not intended to be used alone. It's always surrounded by a container like `<b:listLinks />`. The latter prevents the bullet points from being rendered.

Did the problem occur because you tried to use `<b:navLink />` without embedding it in such a container?

**Comment by ScreamingTree86** [comment]
@stephanrauh 
Okay from the showcase it is not clear to always use <b:listLinks /> with navlinks. The showcase only says that the examples there use listlinks. 
Anyway, i did not use <b:listLinks /> because i use only single navlinks in my sites and no link lists ;). I removed the dot by css maipulating the element.

**Comment by stephanrauh** [comment]
So a `b:navLink` is basically an `h:link` that's can be embedded in a `b:listLinks ` container, but can also be used as a solitary component. In that case, it doesn't make sense to render it as a `<li />`tag. Now BootsFaces uses a `<span />` for solitary navLinks.

**Comment by stephanrauh** [comment]
Documented the feature in the showcase (http://www3.bootsfaces.net/Showcase/layout/navLinks.jsf).
