### ISSUE TITLE
Buttons default look missing

### ISSUE THREAD

**Issue by ScreamingTree86** [TheCoder4eu/BootsFaces-OSP#311]
Hi,
i use the b:button and b:commandButton. I miss the look attribute to get the default white grey gradient. 
But the Button i get is completely white like there is rendered nothing 

`<b:button id="toggler" value="Spalten" style="float:right;" size="sm" iconAwesome="calculator"/>`
generates
`<button id="form:circulationsTable:toggler" name="form:circulationsTable:toggler" type="button" style="float:right;" class="btn btn-sm btn-default">...</button>` 

and looks like this 
![asdasdasdwads](https://cloud.githubusercontent.com/assets/6475837/13320913/5e00b7c8-dbcc-11e5-837f-83b80f2c6114.PNG)

**Comment by stephanrauh** [comment]
Did you add the default theme as described in http://www.bootsfaces.net/layout/themes.jsf? Or rather, like so - we've already fixed the documentation bug, but we didn't publish the updated documentation yet:
```xml
    <context-param>
        <param-name>BootsFaces_THEME</param-name>
        <param-value>default</param-value>
    </context-param>
    <!-- The default is false, when set to true the bootstrap-theme.css will be loaded -->
    <context-param>
        <param-name>BootsFaces_USETHEME</param-name>
        <param-value>true</param-value>
    </context-param>
```

**Comment by ScreamingTree86** [comment]
Ah okay. I missed that. It was notquite clear that i habe to set a default theme.
But thank you for your help. Now everything works well :)
