### ISSUE TITLE
calendar not working

### ISSUE THREAD

**Issue by squillace91** [TheCoder4eu/BootsFaces-OSP#317]
trying to include 

http://www.primefaces.org/showcase/ui/data/schedule.xhtml

but for some reason it does not show up. Date picker happens the same.

**Comment by stephanrauh** [comment]
Would you mind to upload your source code? Currently we have very little time because of the Javaland conference, so we'd appreciate every help you can give us. Thanks!

**Comment by TheCoder4eu** [comment]
@squillace91 did you try with latest versions?

**Comment by TheCoder4eu** [comment]
Since we didn't hear anything from you I assume the problem is solved.
Reopen the Issue if you still have issues.
