### ISSUE TITLE
AjaxRenderer question

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#318]
Hello All,

What does mean this message: Event is null - probably that's a bug in AJAXRenderer, roughly line 100

This button action send:
```xml
<b:commandButton  icon="glyphicon-plus" look="success"
			action="#{payoffListBean.createNewPayoff}"/>
```

Thank you,
Mihaly

**Comment by stephanrauh** [comment]
Well... when I wrote the AJAX renderer, I thought this particular `else` branch must never be reached. However, it turn out to be a perfectly legal condition, so I removed the message in BootsFaces 0.8.2. The version we've published on Maven Central still contains the warning, but you can safely ignore it.
