### ISSUE TITLE
not rendering hidden-md

### ISSUE THREAD

**Issue by VonTalavang** [TheCoder4eu/BootsFaces-OSP#321]
Hello
i do this in the xhtml
```
<b:container fluid="true">
            <!--  header -->
            <b:row styleClass="show-grid header" 
                   >
                <b:column 
                    col-xs="12" 
                    col-sm="0" 
                    col-md="0" 
                    col-lg="0"
                    style="text-align: center;"
                    >
```

but when i rendered... i got this
`<div id="j_idt9" class="col-xs-12 hidden-sm hidden-lg " style="text-align: center;">`

somewhere in the rendering process... the style "hidden-md" wasnt rendered.

i have to added manually with a styleclass later.

PD: awesome work in this project (not sarcasm)

**Comment by stephanrauh** [comment]
@asterd Do you want me to test your bug fix? Otherwise, feel free to close the bug.
