### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by cpfeiffer** [TheCoder4eu/BootsFaces-OSP#322]
Could you please clarify under which license bootsfaces is distributed? As of 2016-03-10, http://www.bootsfaces.net/ does not indicate a license, and the repository contains both 
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/LICENSE (GPL) and https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/LICENSE.LESSER (LGPL). Some files specify a license (e.g. https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/dropButton/DropButton.java LGPL).

Thanks.

**Comment by stephanrauh** [comment]
The general idea is to publish BootsFaces under a dual licence. You can chose between the GPL v3 or the LPGL v3 - whichever suits you best. 

What about you: do you prefer a more liberal license?

**Comment by cpfeiffer** [comment]
Thanks for the clarification! Maybe you can document this either in README.md or on bootsfaces.net?

We (GEBIT Solutions) are fine with LGPLv3, but if you want to get more widespread adoption you would probably use something like Apache License 2 or MIT (like bootstrap itself).

**Comment by TheCoder4eu** [comment]
Hi, in fact we are thinking about switching to Apache License 2, to increase adoption as you suggested.
This will make hopefully the License situation more clear.

**Comment by cpfeiffer** [comment]
That's probably a great move! +1

**Comment by TheCoder4eu** [comment]
We relicensed the Project starting from the 0.9.0 release
to switch to the more permissive Apache Version 2.0 license.
BootsFaces versions prior to v0.9.0 are available under a dual license: GPLv3 or LPGLv3.You can choose, which of those licenses you want to apply.
