### ISSUE TITLE
b:badge - property not found exception on method with parameter

### ISSUE THREAD

**Issue by neskartu** [TheCoder4eu/BootsFaces-OSP#329]
Hi all,

yesterday I took my first steps with Bootsfaces. After a little bit playing with some of the components, I got an exception (PropertyNotFoundException) with the badge component, when I tried to use a method with a parameter like so:

```xml
<b:badge value="#{applicationController.getLoggedInUser(role.id)}" />
```

So far I used this in an `<h:outputText />` and it worked well. I tried it also with a `<b:label>` and it worked too.

Greetings.

**Comment by stephanrauh** [comment]
I've added a null check, but other than that, the problem seems to have been solved already by one of the previous commits. I'll close this ticket.
