### ISSUE TITLE
Select inputText element by id with JQuery

### ISSUE THREAD

**Issue by rpinquie** [TheCoder4eu/BootsFaces-OSP#330]
Hi,

I have an inputText element as follows:
`<h:form>
<b:inputText id="author" " label="Author" style="width:300px;" disabled="true"/>
</h:form>`

when I try to hide this element using JQuery: `$("#author").hide();` it doesn't work and I don't have any error message in the console.

Is there a new way to select element by id in BootsFaces 0.8?

**Comment by asterd** [comment]
Hi,

when you put an item inside a form, it's id is decorated with the form id (for example, in your situation the inputText id became "formid_author". To prevent this behaviour you have to set the form attribute "prependId" to false. In this way, your inputText gets the correct id and you can refer from javascript without problems.

So, the correct code is:

```
<h:form prependId="false">
    <b:inputText id="author" " label="Author" style="width:300px;" disabled="true"/>
    <script type="text/javascript">
         $("#author").hide(); // now it works!
    </script>
</h:form>
```

**Comment by rpinquie** [comment]
Thanks a lot Asterd.
