### ISSUE TITLE
<b:dataTable /> does not trigger <p:ajax> events

### ISSUE THREAD

**Issue by farooq7124** [TheCoder4eu/BootsFaces-OSP#332]
Dear team,

Is there any AJAX api for <b:dataTable /> as we have for primefaces as

<p:ajax event="page" oncomplete="userDetailTableWidget.clearSelection();" />

![image](https://cloud.githubusercontent.com/assets/12643480/13902837/ce1a037a-ee82-11e5-920f-23dec9235fd7.png)

Thanks,
Mohammed Farooq

**Comment by stephanrauh** [comment]
I'm afraid we won't be able to support the particular event you've highlighted in your screenshot. The current minimalist implementation of the dataTable doesn't support editable rows (at least not the way PrimeFaces does). But in general: yes, there are quite a few events that should be AJAX-aware. 

However, you should note that the dataTable is rendered on the client, so updating parts of the dataTable probably won't work (unless we find a simple, fast and reliable way to re-initialize the JavaScript widget).

**Comment by stephanrauh** [comment]
Recently, we've added this feature to the datatable. We're using a different API, because we're not PrimeFaces, but I think you'll be happy with our API just as well. Also see the last example of https://showcase.bootsfaces.net/forms/DataTable.jsf.
