### ISSUE TITLE
b:selectBooleanCheckbox requiredMessage

### ISSUE THREAD

**Issue by underflyer** [TheCoder4eu/BootsFaces-OSP#333]
Dear Team,

b:selectBooleanCheckbox does not support requiredMessage. It is possible to set it as required=true. but no RequiredMessage can be set.
Enhancement?

Best Regards

**Comment by stephanrauh** [comment]
I'm not sure how the `required` attribute is expected to work with the `selectBooleanCheckbox`. Defining the checkbox as mandatory amounts to forcing the user to check it. If it is uncheck, the validation constraint is violated. Is that the usecase you have in mind?

**Comment by underflyer** [comment]
Hi,

jep that's my usecase. 
An Example: "[ ] I accept the Guidelines of this Forum."
if not Checked on Submit: RequiredMessage("Please accept the guidelines to proceed") ....

like In german webshops etc: normal procedure for AGB and privacy etc.

**Comment by stephanrauh** [comment]
OK. It's a bit unusual, but seems to make sense. 

BTW, I sort of hate those "AGB" checkboxes - mind you, have you ever really read them? More often that not, it's hard not to accept them, no matter what contract you accept... *sigh*

**Comment by underflyer** [comment]
true, but if Web-Developer does not implement such Checkboxes in there Page there some specialized lawyer how will send expensive "Abmahnungen"/"Dea".
So
you do not have to read it, but you have to accept/click it "manually".... sigh

**Comment by stephanrauh** [comment]
Until we've published the bug fix, I recommend to use a Bean Validation API annotation as workaround:

```xml
	@AssertTrue(message = "Greetings from the JSR303 Bean Validation API: This checkbox must always be checked!")
	private boolean cbxError = false;
```

**Comment by stephanrauh** [comment]
Implemented the checked with a non-configurable error message.
