### ISSUE TITLE
Rerender of b:dataTable duplicates elements  

### ISSUE THREAD

**Issue by JWGmeligMeyling** [TheCoder4eu/BootsFaces-OSP#335]
I try to update a `<b:dataTable>` using a `<f:ajax execute="@form" render="data-table-basic"/>`. While new entries are added to the data table correctly, its control elements appear twice. Not sure if this is actually a bug or the intented behaviour for dataTable, as I am very new to JSF and Bootsfaces. Little help would be appreciated a lot though :smile: I am on BootsFaces 0.8.1 / Chrome.

**Comment by stephanrauh** [comment]
No, it's not the way it should be :). But it's hard to avoid: the BootsFaces datatable is a client side widget, and every time you update the form, it is initialized again. BTW, I couldn't reproduce your error. Could you send us a reproducer?

In any case, in BootsFaces 0.8.2 you can use the `widgetVar` to destroy the datatable before updating the page:
```xml
<b:dataTable value="#{carPool.carPool}" var="car" id="bcarPool"
                      widgetVar="tblWidget">
...
</b:dataTable>
<b:commandButton onclick="tblWidget.DataTable().destroy();event.stopPropagation();ajax:carPool.initRandomCarPool();" 
    update="@form"/>
```
In BootsFaces 0.8.1 you have to find out a jQuery expression that finds your dataTable. For instance, you can use `$('.dataTable').DataTable().destroy()`.

Be that as it may, that BootsFaces dataTable is a client-side widget, which means it doesn't play nicely with JSF AJAX.

**Comment by stephanrauh** [comment]
If you want to give the new version a try, I've uploaded a developer snapshot to Maven Central (see #151 on how to get it)

**Comment by JWGmeligMeyling** [comment]
Thanks for your efforts, I will try the developer snapshot!
