### ISSUE TITLE
navbar not displaying correctly

### ISSUE THREAD

**Issue by jpiersanti** [TheCoder4eu/BootsFaces-OSP#336]
Hello guys,

First of all, thanks for such an awesome jsf library. I really like it.

I am writing because I am having a small issue(?) with the navbar: I am using the same code as you guys have in the webapp: https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/applayout/navbartop.xhtml

but when I see the site using a mobile device the navbar is not looking "reduced" as in your website. It is always looking like in a long screen. Am i missing something? I am including my test page, in case you can see my mistake straightforward.

I have tried even with a container surrounding the navbar and nothing, all the time the same: navbar looks always like in a lg screen.

Any clue?

Thanks!!

`
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
< html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<f:view locale="#{language.localeCode}">
< h : head>
	<title>my title</title>

 
   
</ h:head >

< h : body style="padding-top: 60px;">
< script>
  $.blockUI.defaults.overlayCSS.opacity=0;
  $.blockUI.defaults.message="#{msg['quiniela.pleaseWait']}";
< / script> 
 < b : container>
 < b : navBar brand="BootsFaces"
    brandHref="#{request.contextPath}/index.jsf" inverse="true"
    fixed="top">
    
      <b:navbarLinks>
        <b:navLink />
        <b:navLink />
        <b:dropMenu value="Getting Started">
          <b:navLink value="Requirements" outcome="/requirements"
            icon="check" />
          <b:navLink value="Download" outcome="/download" icon="save" />
          <b:navLink value="Quick Start" outcome="/quickstart"
            icon="play-circle" />
          <b:navLink value="PrimeFaces"
            outcome="/integration/PrimeFaces" icon="tasks" />
          <b:navLink value="OmniFaces" outcome="/integration/OmniFaces"
            icon="tasks" />
          <b:navLink value="ButterFaces" outcome="/integration/ButterFaces"
            icon="tasks" />
          <ui:remove>
            <b:navLink value="undocumented components"
              outcome="/undocumented" icon="question-circle" />
          </ui:remove>
        </b:dropMenu>

        <b:dropMenu value="Layout">
          <b:navLink value="Basic Layout and Grid System"
            outcome="/layout/basic" iconAwesome="table" />
          <b:navLink value="Simplified Grid System"
            outcome="/layout/simplifiedLayout" iconAwesome="table" />
          <b:navLink value="Themes" outcome="/layout/themes" />
          <b:navLink value="RTL (right-to-left) support"
            outcome="/layout/rtl" iconAwesome="table" />
          <b:navLink value="CSS files, JS files and CDNs"
            outcome="/layout/resourcemanagement" />
          <b:navLink value="Sidebars (NavLinks and NavCommandLinks)"
            outcome="/layout/navLinks" icon="list" />
          <b:navLink value="Menus (Navbars)" outcome="/layout/navbars"
            iconAwesome="ellipsis-h" />
          <b:navLink value="Navigation and AJAX" outcome="/layout/navigationAndAJAX"
            iconAwesome="ellipsis-h" />
          <b:navLink value="Panels" outcome="/layout/panels"
            iconAwesome="list-alt" />
          <b:navLink value="Grids" outcome="/layout/panelgrids"
            iconAwesome="th-large" />
          <b:navLink value="Icons" outcome="/layout/icons"
            iconAwesome="photo" />
          <b:navLink value="Image" outcome="/layout/Image"
            iconAwesome="photo" />
          <b:navLink value="Jumbotron" outcome="/layout/jumbotron" />
          <b:navLink value="Wells" outcome="/layout/wells" />
        </b:dropMenu>
        <b:dropMenu value="Forms">
          <b:navLink value="AJAX" outcome="/forms/ajax" />
          <b:navLink value="BlockUI" outcome="/forms/blockUI" />
          <b:navLink value="Search Expressions"
            outcome="/forms/searchExpressions" />
          <b:navLink value="Custom Search Expressions"
            outcome="/forms/customSearchExpressions" />
          <b:navLink value="Buttons" outcome="/forms/buttons" />
          <b:navLink value="Button Groups and Toolbars"
            outcome="/forms/buttonGroups" />
          <b:navLink value="Command Button"
            outcome="/forms/commandButton" />
          <b:navLink value="DataTable (experimental)"
            outcome="/forms/DataTable" />
          <b:navLink value="Fetch Bean Infos (Validations)"
            outcome="/forms/FetchBeanInfos" />
          <b:navLink value="Input Text" outcome="/forms/inputText" />
          <b:navLink value="Input Secret" outcome="/forms/inputSecret"
            iconAwesome="user-secret" />
          <b:navLink value="Textarea" outcome="/forms/inputTextarea" />
          <b:navLink value="Checkbox" outcome="/forms/checkBox" />
          <b:navLink value="Switch" outcome="/forms/switch" />
          <b:navLink value="Combobox (SelectOneMenu)"
            outcome="/forms/selectOneMenu" />
          <b:navLink value="Multiple Choice Combobox (SelectMultiMenu)"
            outcome="/forms/selectMultiMenu" />
          <b:navLink value="Poll" outcome="/forms/poll"
            iconAwesome="refresh" />
          <b:navLink value="Messages" outcome="/forms/messages"
            iconAwesome="refresh" />
        </b:dropMenu>
        <b:dropMenu value="Bootstrap Widgets">
          <b:navLink value="Alerts" outcome="/bootstrap/alerts"
            icon="warning-sign" />
          <b:navLink value="Carousel" outcome="/bootstrap/carousel" />
          <b:navLink value="DropButton" outcome="/bootstrap/dropButton" />
          <b:navLink value="Labels and Badges"
            outcome="/bootstrap/labelsbadge" icon="tag" />
          <b:navLink value="Modals" outcome="/bootstrap/modal" />
          <b:navLink value="Thumbnails" outcome="/bootstrap/thumbnails"
            icon="picture" />
          <b:navLink value="Tab" outcome="/bootstrap/tab"
            icon="folder-close" />
          <b:navLink value="Tooltip" outcome="/bootstrap/tooltips"
            iconAwesome="comment" />
        </b:dropMenu>
        <b:dropMenu value="jQueryUI Widgets">
          <b:navLink value="Slider" outcome="/jquery-ui/slider"
            icon="tasks" iconAwesome="sliders" />
          <b:navLink value="More Sliders" outcome="/jquery-ui/slider2"
            icon="tasks" />
          <b:navLink value="DatePicker" outcome="/jquery-ui/datepicker"
            icon="calendar" />
        </b:dropMenu>
      </b:navbarLinks>
      <b:navbarLinks pull="right">
        <h:form style="display:inline" styleClass="form-inline">
          <b:selectOneMenu value="#{theme.currentTheme}"
            style="width:180px;margin-top:8px"
            onchange="$('.theme-selector-button').click()">
            <f:selectItem itemValue="default" itemLabel="default" />
            <f:selectItem itemValue="cerulean" itemLabel="cerulean" />
            <f:selectItem itemValue="cosmo" itemLabel="cosmo" />
            <f:selectItem itemValue="cyborg" itemLabel="cyborg" />
            <f:selectItem itemValue="darkly" itemLabel="darkly" />
            <f:selectItem itemValue="flatly" itemLabel="flatly" />
            <f:selectItem itemValue="journal" itemLabel="journal" />
            <f:selectItem itemValue="lumen" itemLabel="lumen" />
            <f:selectItem itemValue="paper" itemLabel="paper" />
            <f:selectItem itemValue="readable" itemLabel="readable" />
            <f:selectItem itemValue="sandstone" itemLabel="sandstone" />
            <f:selectItem itemValue="simplex" itemLabel="simplex" />
            <f:selectItem itemValue="slate" itemLabel="slate" />
            <f:selectItem itemValue="spacelab" itemLabel="spacelab" />
            <f:selectItem itemValue="superhero" itemLabel="superhero" />
            <f:selectItem itemValue="united" itemLabel="united" />
            <f:selectItem itemValue="yeti" itemLabel="yeti" />
            <f:selectItem itemValue="freelancer" itemLabel="Freelancer (custom)" />
            <f:selectItem itemValue="grayscale" itemLabel="Grayscale (custom)" />
          </b:selectOneMenu>
          <b:commandButton styleClass="theme-selector-button" value="select"
            action="#{theme.selectTheme}" style="display:none" />
        </h:form>
      </b:navbarLinks>

      <b:navbarLinks pull="right">
        <b:navLink outcome="/examples/index" value="Examples" iconAwesome="desktop" />
      </b:navbarLinks>
   
  < / b :navBar>
 < / b :container>
		
	< b :container >
	blah
	< / b:container>
	
              
< / h:body>
< / f:view>
< / html>
`

**Comment by asterd** [comment]
Hi, wich version of Bootsfaces are you using? i've tried your page (without any modification) in my environment and this is the result: 

<img width="574" alt="schermata 2016-03-30 alle 08 40 02" src="https://cloud.githubusercontent.com/assets/734776/14133874/1b5f4668-f653-11e5-903e-d6ebe7f4be89.png">
<img width="579" alt="schermata 2016-03-30 alle 08 39 48" src="https://cloud.githubusercontent.com/assets/734776/14133873/1b5eff0a-f653-11e5-9d2f-c66882a8c779.png">

**Comment by jpiersanti** [comment]
Hello,

Thanks for your quick response! I am using bootsfaces 0.8.1. If I browse to that page using a mobile browser I see it all expanded, in the same way as my pc monitor :(

I've check the mobile phone's settings (just in case) and it's using "Android" as agent so I guess it should appear as you picture shows but somehow it doesn't :-(

Regards,

**Comment by asterd** [comment]
Hello,

can you post a screenshot of the mobile rendering? just to understand well which is the behaviour..

Regards

**Comment by jpiersanti** [comment]
Hello there, 

Please find attached a screenshot of my mobile device's browser. As you can see, the navbar appears extended as in a long screen. I have attached also how is the navbar appearing in the same browser when viewing the bootsfaces page (this is the way I expect to see both).

Regards,


![screenshot_20160331-214210](https://cloud.githubusercontent.com/assets/18153638/14188573/89f27ea6-f789-11e5-90ad-6524f6d2e8e8.png)



![screenshot_20160331-213442](https://cloud.githubusercontent.com/assets/18153638/14188514/2ecc470a-f789-11e5-8a76-8ce4e0866405.png)

**Comment by stephanrauh** [comment]
Might be something to do with the viewport. Not long ago, someone told me we forgot an important setting in the page header.

**Comment by jpiersanti** [comment]
hey man, thank you very much! 

I added this header and it worked:

<meta name="viewport" content="width=device-width, initial-scale=1" />

Thanks again!!

**Comment by stephanrauh** [comment]
Maybe you closed the issue to early. Now that we know how to fix the bug - how should the BootsFaces team react? Basically, I see two options:

- simply document the header an hope that every developer reads the documentation.
- Modify BootsFaces in such a way that it automatically renders the viewport, unless you explicitly advise it not to render the meta tag.

What's your opinion?

**Comment by jpiersanti** [comment]
Oops,sorry about that... I closed it too early.

What I would do is to modify BootsFaces so it displays the viewport by default as I mentioned, adding also the parameters to customize the width (being device-with the default value) and scale (being 1 the default) or disable the header if needed.

Thank you very much for your support.

**Comment by stephanrauh** [comment]
@asterd @TheCoder4eu What's you opinion? Currently I'd suggest to generate the header by default, and to add a context parameter in the web.xml to disable it. However, I don't know how to do it. I don't want to write a `HeadRenderer` because that would break compatibility with PrimeFaces and with Liferay.

**Comment by zhedar** [comment]
I think we should document it, because that's something I discovered as well yesterday. Either way, if we decide to set it by default, it should be documented anyway, because this may have unintended side effects for some users.
That's also why I think it's probably best not to set it, I'm not sure how it would be overriden, if it was set manually.

**Comment by asterd** [comment]
I agree that viewport must be setted by default, and if we want to automate this without the use of an HeadRenderer, maybe we have to use the AddResourceListener class with a method that can set-up only one time, a meta section on the header.. Sure it is not the best and cleanest solution.. But it might work..  If you agree with this approach, i can try to implement it..

**Comment by stephanrauh** [comment]
Maybe that's an option that works. It might be possible to add a component to the JSF header using the AddResourcesListener. I've already done it with the `InternalIE8CompatiblityLinks` widget. The difference is that our new widget generates code (the meta tag). 

Following the idea of @zhedar , I suggest we only add the component if the context parameter is there. Alternatively, it should be possible to add the parameter on a per-view basis. That would be adding the widget manually:
```xml
<h:head>
   <b:adjustViewPortForMobileDevices />
</h:head>
```

**Comment by jpiersanti** [comment]
Hello guys, may I add another comment on this? 

@stephanrauh  the, option you just mentioned looks also good to me. 

From what I could observe from adding the header, is that if I need the header ... it looks like I would also need it in all the pages so all the pages are displayed in the same way. 

The scenario where some pages has the viewport for mobile and some other doesn't could be an exceptional case... that's why it would make sense (to me, at least ) to allow the possibility to disabled it in the pages where is not needed (if any)... or also globally in the web.xml (if not needed at all) as suggested in another post...

Regards,

**Comment by stephanrauh** [comment]
True. Being able to configure this particular option on a per-view basis doesn't make sense.

**Comment by asterd** [comment]
Bootstrap, that is the base of our ui, was born to manage in a clever manner the responsiveness of a site. I think that a user who choose our project, expect that it works good on mobile by default (we have also to consider that responsiveness is a requirement today - think to the new google ranking's rules). And the meta tag viewport is the base for that. Indeed, i think that the basic setting (<meta name=viewport content="width=device-width,initial-scale=1">) maybe does not create problems in most cases. So, i think the best thing to do is to setting up by default this tag in all page header, with the possibility to disable by  a context parameter, and if you want to customize this setting, you can specify you custom meta tag that take precedence over the base setting. I don't know how to implement this.. but i can study a way to do that.. what's your opinion?

**Comment by jpiersanti** [comment]
What about creating a component Header extending https://docs.oracle.com/javaee/6/api/javax/faces/component/html/HtmlHead.html ?

It would be used as <b:head></b:head>, instead of the <h:head> and it would behave as its parent + the behavior proposed in the thread by default (adding the viewport by default + any parameter to disable it, etc).

Regards,

**Comment by stephanrauh** [comment]
This approach works, but it breaks compatibilty to PrimeFaces and Liferay.

**Comment by stephanrauh** [comment]
Added a documentation page for the viewport feature.
