### ISSUE TITLE
Update build and getting started instructions

### ISSUE THREAD

**Issue by zhedar** [TheCoder4eu/BootsFaces-OSP#343]
Both the Readme and the cheat.sheet are slightly out of date. This was once mentioned in https://github.com/TheCoder4eu/BootsFaces-OSP/pull/299, but seems to be forgotten again.
We should aim this for the next release, so it may affect adaption in a positive way. (A clean house invites you to stay, but what if the windows are stained, so you can't look inside?)

This issue is a reminder to update those files and to track that progress.

Here's a quick and incomplete list of ideas:
- [x] add a small getting started section in the readme
- [x] make the cheat.sheet a .md file, link it directly in the readme, making it viewable nicely in the browser
- [x] check the cheat.sheet for changed names, e.g. there is no gradle.build file any more
- [x] BUILD-MAVEN.txt is empty, give it some love
- [ ] think about contributing rules, they looked a bit restrictive at first sight, but aren't really followed if I recall correctly
- [x] include the licensing information as soon as #322 is solved

**Edit:** Already overhauled the cheat.sheet, WIP: see [here](https://github.com/zhedar/BootsFaces-OSP/blob/docs/cheat-sheet.md).

**Comment by zhedar** [comment]
As of a new GitHub layout, the license is included into the top nav bar, so we probably don't need to include it in the readme.

However, to resurrect this: Any thoughts on the current [contribution guidelines](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/CONTRIBUTING.md)?

**Comment by stephanrauh** [comment]
@zhedar @asterd @TheCoder4eu In one of the Angular2 repos I've found a checklist: "I'm reporting a bug / I'm asking for a new feature / I'm asking for support / other". Unfortunately, I didn't find it again, so I can't give you a hint how to implement this. But I think it might be useful.

**Comment by stephanrauh** [comment]
We've finished most of the ticket. Let's close it.
