### ISSUE TITLE
0.8.2-SNAPSHOT bypassing validators?

### ISSUE THREAD

**Issue by jpiersanti** [TheCoder4eu/BootsFaces-OSP#344]
Hello guys,

I was using version 0.8.2-SNAPSHOT in order to test the growl component and it's working fine. Thething is now all the validations are being by-passed.

It's just not taking into consideration any @notnull @max @min annotation from the javax.validation API.

0.8.1 works just fine.

Should I change the version of any other library?

Regards,

**Comment by asterd** [comment]
Hi,

no, sadly is a bug of the snapshot version.
I hope to close it in short time.

**Comment by stephanrauh** [comment]
I've pushed a new version of the developer snapshot to Maven Central. The bug should be fixed by now. See #151 on how to get the developer snapshot.
