### ISSUE TITLE
validated tooltip-position field if tooltip is used inside form.

### ISSUE THREAD

**Issue by jpiersanti** [TheCoder4eu/BootsFaces-OSP#348]
Hi Guys,

I have observed that whenever I put a tooltip for a component inside a form, while using at the same time "b:messages" to display global validation message the b:messages display an error saying that "tooltip-position needs to be top, bottom, left or right".

If I add the attribute the message goes away, perhaps there should be a default value for the tooltip-position?

Regards,

**Comment by stephanrauh** [comment]
Both documentation and implementation indicate that the default already is "bottom". Can you send us a reproducer? And would you mind to tell us which version of BootsFaces you are using?

**Comment by jpiersanti** [comment]
Hello there, 

I am using version 0.8.1. I will place here the reproducer by the end of the day.

Regards,

**Comment by zhedar** [comment]
This issue has since been fixed and should be absent in 0.8.2.
[0.8.1 didn't had the default value setting](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/v0.8.1/src/main/java/net/bootsfaces/render/Tooltip.java), if `position` was null. (However I don't get how it could actually be null after `generateTooltip`).
[0.8.2. introduced another null check](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/render/Tooltip.java) in `generateTooltipInternal`, before the warning was printed.
@jpiersanti Are you able to test this with the 0.8.2 Snapshot?

**Comment by jpiersanti** [comment]
Hi Guys,

Here is how to reproduce the issue:

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:c="http://java.sun.com/jsp/jstl/core"
	
      xmlns:b="http://bootsfaces.net/ui">
    <h:head><meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Titke</title>
        <meta name="author" content="The Author"></meta>

       
    </h:head>
    <h:body>
    <b:container>
   
     <h:form id="form1">
    <b:panel title="test" look="primary" id="panel1" collapsible="false">
  
    
    	
    	<b:row>
    		<b:column col-md="12" tooltip="textTooltip">
    			<b:inputText rendered="true"  required="true" type="number"  />
    		</b:column>
    	</b:row>
    
    	 <b:row>
    		<b:column col-md="12">
    			<b:messages  globalOnly="true" showSummary="false" showDetail="false"/>
    		</b:column>
    	</b:row>
   
    	 
    	<b:row>
    		<b:column>
    			<b:column>
    				<b:commandButton value="Accept"  update="@form"></b:commandButton>
    			</b:column>
    		</b:column>
    	</b:row>
    	
   
    </b:panel>
     </h:form>
    </b:container>
    </h:body>
    </html>`

However I have found that if I put the row containing the mesages tag BEFORE the row of theinputText it also works fine (I need the message to be on top of the button, so I ended up putting the tooltip-position as well).

Hope this help. I will try with 0.8.2-SNAPSHOT and let you know if it still happens.

**Comment by jpiersanti** [comment]
Hello again,

With 0.8.2-SNAPSHOT is working fine, there is no issue.

Regards,

**Comment by zhedar** [comment]
I couldn't reproduce this in my tooltip refactoring branch as well, so I guess I won't introduce a regression :)
Thanks for the snippet!

**Comment by jpiersanti** [comment]
You are welcome ;-) 

At least could you confirm that the snippet fails with the 0.8.1 version? Just in case I missed something,

Regards,

**Comment by zhedar** [comment]
Yes, I was able to reproduce it with 0.8.1, but it's definitely gone now.
