### ISSUE TITLE
ReflectiveOperationException incompatible with java 6

### ISSUE THREAD

**Issue by elpaisa22** [TheCoder4eu/BootsFaces-OSP#349]
When I try to run a Java 6 web application with the latest version of BootsFaces (0.8.0), server logs an error because class "ReflectiveOperationException" is not found and none page is displayed. Maybe you can change the exception class by another compatible with Java 6

**Comment by zhedar** [comment]
`ReflectiveOperationException` indeed requires Java 7, it can be safely replaced by a generic `Exception` though,  because we won't do anything with it than log it directly and `Method.invoke`, which throws the Exceptions, is also available in JDK 6.

**Comment by zhedar** [comment]
Somehow [detection of wrong JDK usage is broken](http://stackoverflow.com/questions/21683738/enforcing-java-6-source-compatibility-in-maven-and-or-eclipse).
Therefore I added the [animal-sniffer maven plugin](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/index.html) to check for wrong usages of new methods. That should provide an easy eay to check our code for Java 6 compatibility by running `mvn animal-sniffer:check`.

**Comment by elpaisa22** [comment]
@zhedar That's great! Thank you. 

I think there is still one thing with Java 6, the class "net.bootsfaces.utils.BsfUtils" has this annotation:   "@SafeVarargs", but removing that, it compiles with maven perfectly.

Thanks again and I would like to congrat to you for yor project, it's a great idea and the components looks awesome!

**Comment by zhedar** [comment]
Oh, I stumbled upon that method with this annotation just yesterday. It's only used in one place, so I probably just remove it and replace it by `new ArrayList<Node>(Arrays.asList(rootNode)`.

Thanks for your feedback! The bad news is, animal-sniffer didn't complain about that... So testing to compile with an actual JDK6 seems to be the safest way to check for compliance.
