### ISSUE TITLE
Find a way to configure render-labels globally

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#354]
My latest push, which converted most widgets to a form that can be automatically generated, broke the feature that you can configure the render-labels attribute globally in the web.xml.

So we should find a better way to implement it. Alternatively, we could add this functionality to the XText generator.

**Comment by asterd** [comment]
why do you say that? I've seen that in the code of inputText, the renderLabel is managed and also in the Renderer.. so, where is the problem? can you explain me please?

**Comment by stephanrauh** [comment]
Yesterday I've removed some of the code dealing with the default value of render-label. But I don't want to removed the feature, so I opened the ticket to make sure I verify if I've introduced an error, and to find a better solution if I did.

**Comment by stephanrauh** [comment]
Implemented and tested.
