### ISSUE TITLE
Improve the visible and hidden attribute

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#356]
When I implemented the `visible` attribute, I implemented something I believed to be better than the Bootstrap approach. As a result, it's impossible to hide an element on small displays only. But our showcase menu could benefit from such a feature.

I suggest to add this syntax:
* visible="md" means: visible on every screen that's at least medium size
* visible="<md" means: visible on screens smaller than medium size
* visible="<=md" means: visible on screens smaller than or equals to medium size
* visible=">md" means: visible on screens larger than medium size
* visible="sm...md" means: visible on screens between medium and small screens (inclusive)
* and so on.

Of course, the new symbolic names (`medium-screen`) should be supported, too.

The `hidden` attribute should be improved in a similar way.

**Comment by asterd** [comment]
As far as i understand, this behaviour seems to be the same of col-*-* that you mentioned in issue #355. So, basically, you want to add the visible, hidden, and col-*-* attributes to almost every component, with a shared behaviour that we can code inside the CoreRenderer isn't it?

**Comment by stephanrauh** [comment]
Sure, the tickets are related. And yes, you've got my intention correctly. Recently I've learned that you don't have to wrap every component into a column div. You can define the column span directly with the component. And if Bootstrap supports this, BootsFaces should support this, too.

**Comment by stephanrauh** [comment]
Already implemented for:

- `<b:label />`
- `<b:dropMenu />`
- `<b:navLink />`
- `<b:navCommandLink />`

**Comment by stephanrauh** [comment]
This ticket has mostly been solved by working on #393.
