### ISSUE TITLE
examples-dashboard.xhtml  bug？

### ISSUE THREAD

**Issue by sjljsw** [TheCoder4eu/BootsFaces-OSP#363]
The left side menu after b:column use. Is what all don't show .

my run examples is  surce code.

**Comment by zhedar** [comment]
I'm afraid I can't seem to understand, what exactly you mean. Do you mean the [Dashboard example](http://www3.bootsfaces.net/Examples/dashboard.jsf)?
What is not working as expected? What happens instead?

**Comment by sjljsw** [comment]
@zhedar  Don't show included under the label of the elements 。

b:column
