### ISSUE TITLE
b:panelGrid should support every screen size

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#364]
Currently, `<b:panelGrid columns="2">` generates two equals-sized columns. However, these columns are always generated for the `lg` size. There should be a way to influence that.

**Comment by asterd** [comment]
@stephanrauh if i have understand you point correctly, i think that the "size" attribute of panelGrid already influence that isn't it?

**Comment by stephanrauh** [comment]
@asterd  Oh, you're right, it seems like a guy named Stephan implemented this feature in 2014. But I don't think I did it in a good way. In a way, it's logical to use an attribute called `size`, but it doesn't match the general approach, which is to append postfixes like `-sm`or `-md`. I want the library to be "orthogonal", which means you have to learn only a few general concept and can combine these concepts freely. In other words: I want the library to be boring. It should work just the way you expect it to work intuitively. I'm not sure I reached this goal by adding the `size` attribute.

@asterd , @zhedar , @TheCoder4eu What's your opinion?
