### ISSUE TITLE
Unable to save dynamic action with clientId because the UIComponent cannot be found when CombinedResourceHandler is used

### ISSUE THREAD

**Issue by zhedar** [TheCoder4eu/BootsFaces-OSP#365]
It seems like the usage of OmniFaces' `CombinedResourceHandler` causes a lot of warnings known from #325 to appear again. We shouldn't need the `CombinedResourceHandler` to display Glyphicons anymore, but in our showcase we still recommend the usage of the handler.
We should probably change that recommendation as long as this bug is around.

This probably wasn't seen much, because the handler is currently deactivated in the showcase.

**Comment by ggam** [comment]
The showcase and its explanations has been updated to OmniFaces 2.6 so I think this can be closed.

Note however that currently Gliphicons don't work with CombinedResourceHandler (#688).

**Comment by stephanrauh** [comment]
This particular bug haunted us for a long time, so let me double-check: can you confirm the messages are gone in development mode?
