### ISSUE TITLE
Breaking change: process is @this by default, used to be @all

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#371]
I noticed this with the `b:image` attribute, but it may be a broader problem. When I uploaded the chess demo to AngularFaces.net, the default value of the `process` attribute was `@ all`. Now it seems to be `@this`. It seems like something has changed this spring.

**Comment by stephanrauh** [comment]
This is a deliberate change I've forgotten to document. The idea was to align the default values of the `process` attribute with PrimeFaces. b:commandButton and b:commandLink default to `@form`, while every other component defaults to `@this`. Unfortunately, I´m not sure this is the default behavior of PrimeFaces - but I don't think it's a good idea to change that again.

http://stackoverflow.com/questions/25339056/understanding-process-and-update-attributes-of-primefaces

**Comment by tandraschko** [comment]
Default on components is @all, the default on p:ajax is @this.

**Comment by stephanrauh** [comment]
@tandraschko @TheCoder4eu @asterd @zhedar  Should we align the behavior of BootsFaces with PrimeFaces? I'd like to do that, but that would mean to introduce two breaking changes in a row. On the other hand, if BF 0.8.6 follows 0.8.5 only one or two weeks later, we might get away with it without annoying too many people. What do you think?

**Comment by zhedar** [comment]
So if we're aligning with PrimeFaces, we would actually have the some behaviour as pre 0.8.5? I guess most used with bigger applications haven't upgraded that fast, so that probably won't lead to big problems.

The JSF spec only mentions `f:ajax`'s `execute`, which defaults to `@this`, but this is a bit of a different concept, so there's nothing we could follow directly. 👎 

I'm not sure about this though. Is there a downside to process `@all` components on default? Does it impact performance or bandwidth?

**Comment by stephanrauh** [comment]
Default to process="@all" has little to none effect on performance. Basically, what's sent to the server is the user's input, which rarely exceeds a single kilobyte per request. The only drawback is that it violates the HTML specification, which insists on sending only one form at a time to the server. But that's a silly restriction we can safely ignore.

**Comment by tandraschko** [comment]
process != form parameters!
Always every form input will be posted to the server, it doesn't matter what you set on process.

In PF there is a special option called "partialSubmit=true", which only sends the inputs to the server which will be processed.

**Comment by stephanrauh** [comment]
Done.
