### ISSUE TITLE
b:image not working in 0.8.5 as described. "RES_NOT_FOUND"

### ISSUE THREAD

**Issue by Robblle** [TheCoder4eu/BootsFaces-OSP#375]
After updating from BootsFaces 0.8.1 to 0.8.5 all my <b:image> images stopped working.
I'm trying to display a picture with the following line:
`<b:image name="logo" value="img/logo.png" />`

I tried using standard HTML code 
`<img name="logo" src="img/logo.png"/>`
and PrimeFaces code
`<p:graphicImage id="logo" value="img/logo.png"/>`
and both seem to be working just fine.

Browser: Google Chrome 50.0.2661.94
OS: Windows 7 Home Premium

**Comment by asterd** [comment]
Hi, in 0.8.5 image tag mimic the h:graphicImage so with the pair name and library, you can load an image from a specific library. Instead, if you want to load an url, you have to use value, exactly as p:graphicImage do.

So, <b:image library="img" name="logo.png" /> load the image in resouces/img/logo.png
<b:image value="img/logo.png" /> loads image in img/logo.png 

Have you try this way?

**Comment by Robblle** [comment]
I just tried these two variants and both are not working. Can you give me an example, please?
```
<b:image name="test" value="resources/img/logo.png"/>
<b:image name="test" value="/resources/img/logo.png"/>
```

**Comment by asterd** [comment]
your image is in the resources folder under webcontent or webapp (context-root) folder? if yes, you can do this way:

<b:image library="img" name="logo.png" />
otherwise 
<b:image value="/resources/img/logo.png" /> 

but if is in resources the first example is the best.
Let me know if it works!

**Comment by Robblle** [comment]
I got it working with `<b:image name="img/logo.png"/>`. Everything else didn't work. The showcase entry for images should be updated accordingly.

**Comment by stephanrauh** [comment]
Let's resurrect this issue. I'd like to investigate if we've changed anything between 0.8.1 and 0.8.5. If so, we should examine whether the change is an error, and either fix it or document the new behavior. It seems to be a breaking change, after all.

**Comment by zhedar** [comment]
We should also consider to support [resource library contracts](http://www.mkyong.com/jsf2/resources-library-in-jsf-2-0/), like `h:graphicImage` does since JSF 2.0. We should probably add a library to `b:graphicImage` to make it similar to `h:graphicImage`.

**Comment by asterd** [comment]
The b:image already support resource library contracts. It was an addition that i've done some time ago. Maybe is only an issue with the attributes "name" that is target as "mandatory". If you use the tag as described on the site, or with the resource library contracts, it works (maybe) :)

**Comment by zhedar** [comment]
But the `b:graphicImage` currently lacks the `library` attribute, atleast in the documentation. How have you implemented it?

**Comment by asterd** [comment]
Yes, is a documentation lack. The component has the library attribute...

**Comment by stephanrauh** [comment]
The source code of the imageRenderer has changed considerably since 0.8.0. Some I can't rule out we've introduced an incompatibility. I'll have a look at it tomorrow.

**Comment by stephanrauh** [comment]
The documentation was wrong. It claimed the `name` attribute was mandatory. In this case, BootsFaces tried to load the file from a resource library instead of using the `value` attributes. I've changed the precedence of the attributes. Now, `value` is used first. Plus, BootsFaces shows a warning if both sets of attributes are set.

**Comment by stephanrauh** [comment]
I've uploaded a snapshot version of 0.8.6 to Maven Central.
