### ISSUE TITLE
Feature Request - Load menu items from bean

### ISSUE THREAD

**Issue by rogeriovalente** [TheCoder4eu/BootsFaces-OSP#377]
Hi, I'm looking for a feature that allow me to create a dropMenu from backing bean, loading the navLink property from that.
On primefaces I use a panelMenu component and set the model property with values loaded from a MenuModel property in backing bean.

In menu.xhtml I have the simple code below
`<p:panelMenu model="#{menuBean.menuApp}" />`

And the MenuBean class is responsible to create a MenuModel object that is showed to the user.
I need this because the menu is different based on the user's type, and all the application menu and users permissions are stored on database.

Thanks.

**Comment by zhedar** [comment]
While this might be something we might consider, you can always put the full menu in your facelet and just render the parts your user has access to. So if your menu isn't overly complex, you can do that right now.
Although that would depend on your access rights model, how easy this would be to apply. If you have a simple role model, you may do a role check in the `rendered` condition of the menu items or even a whole sub menu and therefore won't show it to a user which doesn't have the right role.

**Comment by stephanrauh** [comment]
Sounds like a general problem:

- adding columns to a datatable dynamically
- adding input fields to a b:panel or b:panelGrid dynamically
- and much more

**Comment by stephanrauh** [comment]
You can create BootsFaces menus dynamically with `c:forEach`. As far as I remember, current versions even support `<ui:repeat>`. Let's close the ticket because there's workaround.
