### ISSUE TITLE
Improve component: <b:selectOneMenu /> 

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#38]
Currently, selectOneMenu only supports f:selectItem (note the singular). f:selectItems (plural) need yet to be done.

**Comment by TheCoder4eu** [comment]
This is an enhancement we can deliver quickly or we can leave it for next version?

**Comment by stephanrauh** [comment]
I delivered it quickly :).

Copyright hint: The current implementation of f:selectItems rendering is an adapted version of the PrimeFaces 5.1 counterpart. This should be OK by the license provided we mention PrimeFaces.
