### ISSUE TITLE
modal backdrop wrong place

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#380]
Hello All,

At now the black screen under the modal dialog is generated on the end of page.
That's not good when the dialog in form(for example) can what update. The black box cannot disappear. The div has this classes: modal-backdrop in
Please fix if you can.

Thank you,
Mihaly

**Comment by stephanrauh** [comment]
I think it's better if you changed your page, or reduce the `update`region. Currently, I can't think of the use case that makes it necessary to update something outside the modal without hiding the modal. But if you need to do this, use an update statement that updates only the input fields or the div that needs to be updated.
