### ISSUE TITLE
b:button icon and value

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#382]
Hello All,

If I try to use a button without label, because I want to show only an icon have to add value="" attribute. Can you modify this component if icon exists and value attribute null to hide title?

Thank you,
Mihaly

**Comment by zhedar** [comment]
While investigating this, I found that ` <b:button icon="download"/>` (same with iconAwesome) already seems to work like intended:
![bildschirmfoto 2016-05-19 um 00 38 56](https://cloud.githubusercontent.com/assets/6633403/15377208/1d4a7226-1d5a-11e6-9d74-523502cc6947.png)

Or what else did you mean by title?

**Comment by TheCoder4eu** [comment]
I think the answer solved the Issue. Closing.
