### ISSUE TITLE
button onclick event

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#383]
Hello All,

If I create an onclick event on the button always generated a windows.location.href part, like onclick="$('.my-menu').toggle();window.location.href='/studioadmin.web/private/calendar.xhtml';"

Is it correct behaviour?

Thank you,
Mihaly

**Comment by stephanrauh** [comment]
* Would you mind to show us the complete JSF snippet? For instance: I can only guess you're talking about `<b:button />` - as opposed to `<b:commandButton />?.
* Setting `outcome="@none"` should solve the problem (at least for `<b:button />`).

**Comment by stephanrauh** [comment]
@lyahim Mihaly, I didn't hear from you yet. Did me comment help you?

**Comment by lyahim** [comment]
Hello Stephan,

Sorry I missed your last comment. I'm checking it.

Mihaly

**Comment by lyahim** [comment]
Hello Stephan,

I've update to 0.8.6 and at now I don't find that behaviour.
I think you fixed somewhere between 0.8.1 and 0.8.6, maybe can close this issue.

Thank you,
Mihaly

**Comment by stephanrauh** [comment]
@lyahim Closing tickets is one of my favorite tasks. It's a close second to helping developers by solving issue. In any case: Thanks for reporting us back!
