### ISSUE TITLE
New features for b:dataTable

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#389]
Alexander suggested to add these datatable features:
- [ ] Hidden Columns (https://datatables.net/examples/basic_init/hidden_columns.html)
- [x] Searchable Columns (see the link above) (done)
- [ ] Row Grouping (https://datatables.net/examples/advanced_init/row_grouping.html)
- [ ] rowClasses (provided by JSF)
- [ ] Hover (CSS)
- [ ] Compact  (CSS)
- [x] Scroll - vertical (https://datatables.net/examples/basic_init/scroll_y.html) (done)
- [ ] Index column (https://datatables.net/examples/api/counter_columns.html)
- [x] Disable features like paging, ordering.... (done)
- [x] Row Selection (and fire actions for instance deleting a row in front- and backend) (done)

**Comment by TheCoder4eu** [comment]
Hi @stephanrauh , I'd extract the features we do not have time to deliver in this release in another Issue and close thisone. What do you think?

**Comment by stephanrauh** [comment]
Good idea!

**Comment by stephanrauh** [comment]
I'll close this ticket in favor of the follow-up ticket #659.
