### ISSUE TITLE
datepicker shows wrong format 

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#392]
Hello All,

I changed library version from 0.8.1 to 0.8.6 and after that the datepicker shows date in invalid format.

`
<b:datepicker id="birthDate" label="#{msg['client_edit.birth_date']}" value="#{clientEditBean.dateForPicker}" placeholder="1900-01-01" readonly="false"
							dateFormat="yyyy-MM-dd" required="false">
`
Plase check this.

Thank you,
Mihaly

![datepicker](https://cloud.githubusercontent.com/assets/3195083/15635021/d57c4f3c-25d3-11e6-9a8f-d1c2c80e16f7.PNG)

**Comment by zhedar** [comment]
It should work if you use a `lang` setting, which maybe differs from `en`. I fixed that bug in a local stash somewhere, but didn't check it in yet. I guess time was getting spare after all. See https://github.com/TheCoder4eu/BootsFaces-OSP/issues/144#issuecomment-216715144 .

**Comment by TheCoder4eu** [comment]
@lyahim , did the solution suggested by zhedar work?

**Comment by lyahim** [comment]
Hello,
Yes, this works.

Best Regards,
Mihaly

**Comment by stephanrauh** [comment]
Can we do anything to prevent developers to run into this trap?

**Comment by zhedar** [comment]
@stephanrauh 
Like I said, I've already prepared a fix, but need to get it out of my stash and test it a bit further. I will probably look into this now. I just hesistated a bit, because we had plans to replace the datepicker and therefore I didn't continue to work on it.

**Comment by TheCoder4eu** [comment]
@zhedar , thanks, go ahead, since a big sponsor of changing the DatePicker was Dario, I think it's better to postpone changing DatePicker to 1.0 .

**Comment by TheCoder4eu** [comment]
Anyway, I'll improve the docs accordingly, after your fix.

**Comment by zhedar** [comment]
Done. It was just a small fix, essentially we overwrote all our custom settings, when there was a js file with defaults for the chosen language.

**Comment by TheCoder4eu** [comment]
That is : doing the right thing in the wron place, thanks! :+1:
