### ISSUE TITLE
Add the "responsive" attributes to every visible BootsFaces component

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#393]
Bootstrap doesn't force you to wrap each and every widget in a `<b:column />`. So BootsFaces shouldn't do that, either.

**Comment by stephanrauh** [comment]
Components with "responsive" attributes:
* b:accordion 
* b:alert
* b:button
* b:column
* b:commandButton
* b:dateTimePicker
* b:dropButton
* b:dropMenu
* b:inputSecret
* b:inputText
* b:label
* b:panel
* b:socialShare

**Comment by TheCoder4eu** [comment]
IMHO b:Slider already fits this requirement. Plus you have the option to limit its width with regard to the container where he is included.
