### ISSUE TITLE
Logical 'End' Marker to Carousel Component

### ISSUE THREAD

**Issue by matembaq** [TheCoder4eu/BootsFaces-OSP#397]
Currently, the carousel traverses its carouselItems and goes back to the first time without a 'logical end' marker to stop it. How do you limit the movement of the controller NOT to go past the last carouselItem? 

This 'marker' could be optionally used (or even detected on the client-side) in order to present/render view components for action 'options' specific to the 'logical end' of the carousel - e.g. when a carousel is used to simulate a wizard conduct validations or present user options based on user inputs (without server-side interaction)

**Comment by stephanrauh** [comment]
Just saw that we've already implemented this feature. Simply set `wrap="false"`.

**Comment by stephanrauh** [comment]
I've added the flag in the wizard example of our showcase.

**Comment by stephanrauh** [comment]
As for your other request: it's possible to skip slides using the JavaScript API. I didn't test it yet, but this approach should work:

Add an invisible input field to your form, update it with the
     index of the next slide and call `$('.wizardPseudoClass').carousel($('invisibleFieldId').val());`:</p>

```xml
        <h:inputText id="nextSlideId" type="hidden" value="#39;{wizardBean.nextIndex}" />
        <b:commandButton value="next step"
                  update="@form:**:messages @previous"
                  execute="@form"
                  onclick="ajax:bean.onclick(); return false;"
                  look="success"
                  oncomplete="$('.wizardPseudoClass').carousel($('nextSlideId').val());;$('.wizardPseudoClass').carousel('pause'); return false;"/>
```

**Comment by zhedar** [comment]
@stephanrauh Woah, good job spotting the `wrap` attribute, I've totally overseen that will looking at this previously. Maybe we can even disable the next button in the showcase, if the last slide is shown. But I'm not sure, if it is that easy, didn't have a look into data-wrap's internals yet.

**Comment by stephanrauh** [comment]
I'll close this issue. Please report back if my suggestion to skip carousel items does not work.
