### ISSUE TITLE
InputBox JAAS form login not working

### ISSUE THREAD

**Issue by michaelende** [TheCoder4eu/BootsFaces-OSP#398]
Hello everybody,

i try to use the bootsfaces framework in my project.
I would like to use the input box of bootsfaces for my JAAS Form login.

the JAAS Form login has some restriction.
1. id of username field must named as j_username
2. id of password field must named as j_password.

if i use your input box for the username or the password it doesn’t work, because the rendered input box has not the defined id.

the renders output is like this example
```xml
<div id=„j_username“...>
<inputbox id=„input_j_username“…./>
</div>
```
it is possible to fix it, the the id set to the original tag and not to the div container?
```html
<div id=„div_j_username“...>
<inputbox id=„j_username“…./>
</div>
```

many thanks

**Comment by stephanrauh** [comment]
Setting the id to the original tag causes other problems. In particular, developers are confused why their AJAX requests don't work as expected (if they work at all). But we can add two new attributes `fieldId` and `name`, which solves your problem like so:
```xml
<b:inputText id="userNameDivID" fieldId="j_username" name="j_username">
```

**Comment by stephanrauh** [comment]
I've implemented the two new attributes to `<b:inputText />` and `<b:inputSecret />` and published a new developer snapshot on Maven Central. See #369 on how to get it.

**Comment by stephanrauh** [comment]
@michaelende Would you mind to test the feature and to report back if it works for you?

Thanks,
Stephan

**Comment by michaelende** [comment]
hi, now its working,Thanks for your very very fast fix.
