### ISSUE TITLE
button.js isn't included automatically

### ISSUE THREAD

**Issue by cooper-lyt** [TheCoder4eu/BootsFaces-OSP#400]
b:commandButton  insert to page , but  button.js  not include;

now must Manual add: <h:outputScript library="bsf" name="js/button.js"/>

**Comment by TheCoder4eu** [comment]
Hi,
what version of BootsFaces are you using?

Can you provide a simple code example to see if we can reproduce the problem? 

Thanks

**Comment by pavankd** [comment]
HI cooper-lyt,
           could you please share the button.js download link

**Comment by zhedar** [comment]
As far as I see, we don't use any of the features [button.js](http://getbootstrap.com/javascript/#buttons) provides, therefore we won't include it automatically.

@pavankd
The file is already shipped with BootsFaces. You can always include it with `<h:outputScript library="bsf" name="js/button.js" target="head"/>`.

@pavankd @cooper-lyt 
Would you mind to explain, where you need that for exactly? Maybe we should implement some extra button features then.

**Comment by pavankd** [comment]
@zhedar 
I am bulid a SPA application.i am trying to call the page using ajax.when i clicked on button for second its loading the page. following is my code.
<h:form>
<b:commandButton value="Next" size="sm" iconAlign="right"
iconAwesome="fa-angle-double-right" immediate="true" 
onclick="ajax:groupBean.setCgRegistrationPage('/pages/cGroup/CGFForm.xhtml')"
update="@(.pl_cgReg)" ajax="true" type="button" />
</h:form>

as @cooper-lyt  side the button.js is note included .thought it is issue with commandbutton ajax.

I tired is but its not working

**Comment by zhedar** [comment]
So you mean adding that js file isn't solving #399? It shouldn't have to do with that probably anyway.

**Comment by cooper-lyt** [comment]
sorry am late

             <b:commandButton look="success" styleClass="btn-block" id="login" value="login"
                                         ng:data-loading-text="lodding..." onclick="$(this).button('loading');" action="#{identity.login}"/>
                
data-loading-text need "button.js"

**Comment by zhedar** [comment]
So this basically makes the button unclickable twice. Maybe that's really something we would want to add. Sometimes you just need to submit something again (e.g. if the first request didn't work because of reasons), so I'm not a 100% sure about that yet.

@asterd @stephanrauh @TheCoder4eu What do you think about that?

**Comment by cooper-lyt** [comment]
i think  if put a "b:commandButton" or "b:button"  then button.js should included automatically

**Comment by zhedar** [comment]
@cooper-lyt 
Currently, we're only including files we really need. Because it won't make any sense to bloat up traffic and loading times with files never used. But if we decide to include a loading-related feature, we will probably include it by default.

**Comment by cooper-lyt** [comment]
Thank you for your work .

**Comment by stephanrauh** [comment]
Let me add one or two thought to the remark of @zhedar.

Actually, with the current HTTP protocol, our minimal-traffic policy is a bad idea. BootsFaces would be a lot faster if we joined and minified all the JS and CSS libraries. However, with the coming http/2 standard, things will change. We've been discussing the topic a lot and decided to bet on the future. 

If you don't follow us, you can either use the CombinedResourceHandler of OmniFaces, or you can use your own minified version of Bootstrap.

**Comment by stephanrauh** [comment]
@zhedar That's a topic I'm currently trying to solve at work. Our application is slow, and our users are impatient. Adding insult to injury, they've learned that a double click never hurts. In other words, they don't cope with the average internet application. So I've started to implement a double-click protection. 

Actually, that's the same as implementing a "busy bee" waitcursor. It's one of these problems you'll never ever get right. At work, we've decided to show the waitcursor and block the UI until the request is finished. Trying to send a second JSF request before the first JSF request is finished usually doesn't work. Quite the contrary, JSF detects something's wrong and shows an error message.

@cooper-lyt Did you already discover our blockUI feature? That's a different approach to your problem, but maybe you like it, too.

**Comment by cooper-lyt** [comment]
BlockUI is stridency,  like ask can't

 i need this ,ask don't

**Comment by stephanrauh** [comment]
@cooper-lyt @pavankd The attribute `data-loading-text` has been deprecated in Bootstrap 3.3.7 and removed in Bootstrap 4.0. So, even if it looks like a clever idea, we won't add support for it. As a work-around, follow the approach suggested by @zhedar:
- add `<h:outputScript library="bsf" name="js/button.js" target="head"/>` manually
- add `onclick="$(this).button('loading');" ` to the button.
