### ISSUE TITLE
Modals overlayer not hide?

### ISSUE THREAD

**Issue by cooper-lyt** [TheCoder4eu/BootsFaces-OSP#406]
`use` javascript dismiss a Modals ,  overlayer not hide!

code:

**open button:**
```xml
  <b:commandButton value="新建店面" ajax="true" update="@(.ttttt)"
                             look="link"
                             oncomplete="$('.modalEdit').modal();">
                <f:param name="officeId" value=""/>
  </b:commandButton>
```

**dismiss button:**
```xml
<b:commandButton ajax="true" value="确定" 
                               oncomplete="if (#{facesContext.maximumSeverity==null} 
                                          || #{facesContext.maximumSeverity.ordinal lt 2})
                                          {
                                             $('.modalEdit').modal('hide')
                                          }"
                                action="#{officeHome.save}" look="success"/>
```

version: 0.8.6

**Comment by stephanrauh** [comment]
The expression `#{facesContext.maximumSeverity==null ... }` is evaluated when the dialog is drawn. I suspect that's too early for you. I can only guess: the modal dialog contains input field, which may be valid or not. You don't want the dialog to be closed until the user input is sensible. That's what the `oncomplete` attribute should care for. Unfortunately, the attribute is evaluated before the user sees the input field. So the JavaScript code always evaluates to `false`. You can verify that in the F12 tool of your browser (or the ALT-CMD+I tool if you're using a Mac)

**Comment by cooper-lyt** [comment]
@stephanrauh   
the dialog is closed , only overlayer not  hide

**Comment by cooper-lyt** [comment]
i found the problem
my ajax commandButton not have  property "update"! 

add update="@this"  overlayer is hide,

please  close the issues

**Comment by zhedar** [comment]
Seems like this is something, that can happen anytime. Glad you found the error.
