### ISSUE TITLE
Carousel animation

### ISSUE THREAD

**Issue by angelorm** [TheCoder4eu/BootsFaces-OSP#408]
In Bootstrap the carousel comes with a standard slide animation but apparently on Bootsfaces doesn't work from what I've seen. Is there a way to add some or is it something in the works?
Not sure if it's a bug or if I'm being dumb.

**Comment by stephanrauh** [comment]
It's strange I didn't notice. I was sure there is a smooth slide transition. Thanks for making me aware of this!

**Comment by stephanrauh** [comment]
Added the dependency to bsf/js/transition.js fixes the problem. I've added the dependency to BootsFaces 0.9.0, which is due in the next couple of weeks (see http://www3.bootsfaces.net/Showcase/bootstrap/carousel.jsf for the working preview). Until then, you can add the dependency yourself by adding this line to your JSF page:

```xml
<h:outputScript library="bsf" name="js/transition.js" />
```
