### ISSUE TITLE
Bootswatch (lumen) is shaking since BootsFaces 0.8.6

### ISSUE THREAD

**Issue by mydeadlyvenoms** [TheCoder4eu/BootsFaces-OSP#412]
After upgrading to BootsFaces 0.8.6 the Bootswatch lumen theme started to shake in vertical direction (on hover). I think this can be a pretty annoying bug especially if one is using buttons within a table.

You may have to switch the theme multiple times since sometime the old css seems to be used.

[BootsFaces Example (please make sure you are using the lumen theme)](http://showcase.bootsfaces.net/forms/buttons.jsf)

If you check the original theme, everything seems to be ok:

[Bootswatch Example](https://bootswatch.com/lumen/)

**Comment by zhedar** [comment]
You are right, it looks like the button should look like it is pressed down and therefore the parent expands to the bottom on mouse hover, making it look shaking.
According to the title, this is a new issue introduced with 0.8.6? Did you see it before as well?

Also our themes in the showcase seem to be broken a bit. For example, if you select readable first, then lumen, the style is a bit... mixed.

**Comment by mydeadlyvenoms** [comment]
Yes this appeared after migrating to 0.8.6.
I guess it has to to with the fact, that the look of lumen changed with this release.
Yep I also noticed this behavior.

**Comment by zhedar** [comment]
Yeah probably, also #390 should make this a bit harsh to work around, because you can't really overwrite those css properties yourself, which should be the easiest fix. 
What should work, if you really need that right now is to define an inline style which overwrites `.btn:hover`'s `margin-top` and `border-bottom-width` attributes and set's them to 0 px each.

Meanwhile I will look into the theming and see if we can overwrite that centrally.

However, this change will remove the button pressing "animation", but who needs that anyway?

**Comment by zhedar** [comment]
Ok, it wasn't exactly 0 pixels, but I got it working by overriding that setting for every theme. Due to http://www3.bootsfaces.net/Showcase/forms/buttons.jsf it seems to work.

**Comment by mydeadlyvenoms** [comment]
@zhedar the "bugfix" is not online or is it? 
[http://www3.bootsfaces.net/Showcase/forms/buttons.jsf](http://www3.bootsfaces.net/Showcase/forms/buttons.jsf) is still shaking when I use the lumen theme.

**Comment by zhedar** [comment]
I guess that's because we still got a bug with the theme switching. But that should be gone after you selected the theme and then refresh the whole site. The theme should be loaded properly then.

**Comment by mydeadlyvenoms** [comment]
Unfortunately this doesn't solve the problem..

**Comment by zhedar** [comment]
I had to reload the page without submitting the original request though. Entering http://www3.bootsfaces.net/Showcase/forms/buttons.jsf again would do the same.

**Comment by mydeadlyvenoms** [comment]
Got it, now it works. 👍  Thanks you
