### ISSUE TITLE
How to use Tabs with Templating or how to add action to tab

### ISSUE THREAD

**Issue by pavankd** [TheCoder4eu/BootsFaces-OSP#413]
Hi ,
        Please help me in following scenario ,
        i want to use tabs with template.
        like when i click on tab it must load tab specific template. without javascript.
        or
       how to add action to tab

**Comment by stephanrauh** [comment]
I don't understand the first question. What do you want to do precisely? Which templates do you want to load?

As for the second question: `<b:tabView />` supports the BootsFaces AJAX API. It seems we've yet to implement the jQuery event, but even today it should be possible a bind an AJAX call to `onClick`.

**Comment by pavankd** [comment]
In My project we will used template for page layout with header,content,footer and maintemplate .so indeed to add tabs in the content part load corresponding xhtml to specific tab.
how to do this?

**Comment by zhedar** [comment]
@pavankd I'm going a bit StackOverflow on this and may ask: What have you tried so far?

**Comment by pavankd** [comment]
@zhedar So fare i tried SPA but i am unable to load forms properly eg : onclick="ajax:navigationbean.setPage('/pages/registrationForm.xhtml')" to command button or navlink,its not loading properly, Form is activation only after the second click and my application has lot of inner pages with forms.

i followed this link to create my application : http://www.beyondjava.net/blog/single-page-applications-with-bootsfaces/

**Comment by stephanrauh** [comment]
That's a cool link indeed :).

Seriously, I suspect you try to do something that's a bit unorthodox. I understand you've got a page with a template. This page contains a tab. Is this correct?

Now comes the twist: by selecting another tag withing the page, you want to replace the template. Correct?

But that would mean to replace the *entire* page with another page. TabViews, in contrast, are usually used to replace the *content area* of the tab. They are not used to replace the surroundings of the tabView. Of course, it's perfectly possible your use case make sense - far be it from me to me to judge over this! - but I'd like to point out it's not the traditional use case of tabs.

So, I've got two questions:
* Did I get you right?
* Do you really want to replace the template when another tab is selected? Is there no other option to achieve your goal?

**Comment by zhedar** [comment]
That may even not related to tabs, but may even be a general problem, as it looks much like #399.

@pavankd Could you try, if it works with BootsFaces 0.8.1?

**Comment by TheCoder4eu** [comment]
@pavankd  , does it work with last releases?

**Comment by primeO** [comment]
How to close the tab in bootsfaces cant find any sources of it in demo link
