### ISSUE TITLE
b:selectOneMenu doesn't support placeholder

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#419]
b:selectOneMenu has a `placeholder` attribute, but it's never evaluated. Is it possible to implement it? Otherwise, let's remove it.

**Comment by zhedar** [comment]
I would vote to simply remove it. There's the `noSelectionOption=true" bit for that, which does the job in a select-fashioned way.

**Comment by stephanrauh** [comment]
I've removed the attribute.
