### ISSUE TITLE
b:selectMultiMenu doesn't implement neither placeholder nor tooltip correctly

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#420]
b:selectMultiMenu has code implementing both tooltip and placeholders, but neither seems to work.

**Comment by zhedar** [comment]
The tooltip works in the Showcase, atleast for me. How did you discover that?

**Comment by stephanrauh** [comment]
Obviously, tooltips sometimes work :). But look at my new "Tooltips" paragraph of http://www3.bootsfaces.net/Showcase/forms/selectMultiMenu.jsf, just above the attributes section. Did I define the tooltip in a wrong way?

**Comment by zhedar** [comment]
Ah, damn. In the title it states `b:selectMultiMenu` correctly, but the post said `b:selectOneMenu`, which works just fine. You're right, that's broken somehow. But I couldn't spot the error right away, so it must be something more specific to the component.

**Comment by stephanrauh** [comment]
Oh, the pleasures of copy and paste never cease to enchant me...

**Comment by zhedar** [comment]
I guess this has to do with the more complex layout of our `multiSelectMenu`, or even the fact, that the title is set on the button again. However, fiddling around with this I sadly hadn't any success yet to show the real tooltip in any way :(

**Comment by stephanrauh** [comment]
The tooltip is now there. The problem was that the wrong id was initialized. Now there are two ids - one for the outer div containing the tooltip, and a inner div for the `select` element.

**Comment by zhedar** [comment]
Great find, that's actually the only thing I haven't tried ... :D
Looks like you referenced the wrong issue in 112e096, did you?
The fix seems to be in ad925c9f17c624117fa4427cf9da4b58403508a7.

**Comment by stephanrauh** [comment]
Yeah, I remember to have confused a commit yesterday... the commit being correct, but I couldn't find it in the commit history of the issue. Guess that's what you've found.
