### ISSUE TITLE
Do we need b:outputLabel?

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#423]
Several times I've missed `<b:outputLabel />`. The idea being that it's a simple text which serves as a label for an input field. By default, this should be the next element in the JSF tree (or the first child of the next `<b:column>` of the JSF tree). The extra value of  `<b:outputLabel />` should be that it acquires the error classes of BootsFaces as soon as the input field shows a validation error. The standard ´<h:outputLabel>` isn't aware of the BootsFaces CSS style classes.

@zhedar, @asterd, @TheCoder4eu: any thoughts on the topic?

**Comment by zhedar** [comment]
I've always used `p:outputLabel`, so I've never really had the chance to miss the features `h:outputLabel` hasn't. We probably should also consider to highlight required fields (with an asterisk or customizable).

I think this is a valuable addition, if we want BootsFaces to be used independently. Also, if you missed it a couple of times already, it probably is wort to implement.

**Comment by stephanrauh** [comment]
Let's close the ticket. It's been three years open without anybody complaining about that.
