### ISSUE TITLE
ui-widget font-size

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#424]
When integrating with **primefaces**, **ui-widget** is reducing font size to **0.85em**, causing uneven font size in a page.

**Comment by zhedar** [comment]
I've noticed that one too, also very recently if I'm not mistaken. Did it happen to you while updating specific versions of PrimeFaces or BootsFaces?

There's a certain discrepancy between to CSS styles, but I dont know, if we can really do something about it. If we change that just to fit PrimeFaces, we might break some application's styles on the way.

However, you can always overwrite that setting in your own CSS files with something like 

    .ui-widget, .ui-widget .ui-widget {
        font-size: 90% !important;
     }

**Comment by chsreedhar** [comment]
I tried with above CSS, it effects the other basic tags font size like h1, to h6
It disturbs the bootstrap basic tags.

**Comment by stephanrauh** [comment]
This bug has been fixed in 1.0.2.
