### ISSUE TITLE
Glyphicons not loaded with CombinedResourceHandler

### ISSUE THREAD

**Issue by m1rc0** [TheCoder4eu/BootsFaces-OSP#425]
Hi there,

when using the CombinedRosourceHandler from OmniFaces the Gylphicons are not loaded.

> Failed to load resource: the server responded with a status of 404 (Not Found) (08:47:55:324 | error, network)  at http://localhost:8080/fonts/glyphicons-halflings-regular.ttf

**Comment by mydeadlyvenoms** [comment]
Also fonts are not being loaded then, for example the font which comes with the lumen theme.

**Comment by zhedar** [comment]
I currently couldn't find it in the documentation, but in the past we used to exclude Glyphicons from the `CombinedResourceHandler`. You may want to try that:

    <context-param>
        <param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_EXCLUDED_RESOURCES</param-name>
        <param-value>bsf:css/icons.css</param-value>
    </context-param>
    <context-param>
     <param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_DISABLED</param-name>
     <param-value>false</param-value>
    </context-param>

@mydeadlyvenoms You can probably try the same with the fonts, that aren't loaded.

**Comment by m1rc0** [comment]
@zhedar works like charm. Thank you very much.
