### ISSUE TITLE
b:switch - JavaScript and AJAX API doesn't seem to work properly

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#429]
When I tried to add AJAX to the `onclick` handler of `b:switch`, I noticed that the click even is only fired when the mouse points to the white area of the switch. Chances are the other JavaScript handlers are out of order, too.

**Comment by TheCoder4eu** [comment]
@stephanrauh do you have a sample code to reproduce the issue?

**Comment by TheCoder4eu** [comment]
@stephanrauh do you have a sample code to reproduce the issue? Or it is solved in v1.0?

**Comment by stephanrauh** [comment]
We've got quite a few working demos using `<b:switch />`, so I suppose the issue was either false alarm or it has been solved in the meantime.
