### ISSUE TITLE
InputText size "extra small" (xs) is missing

### ISSUE THREAD

**Issue by ScreamingTree86** [TheCoder4eu/BootsFaces-OSP#431]
Hi,
i use the inputText component at some places with the field size xs. But since the update to 0.8.6 this field sizes seems to be missing. The inputfileds get rendered with medium size. Was it kicked form the source? It is still in the references:

> 	The size of the input. Possible values are xs (extra small), sm (small), md (medium) and lg (large) .

For buttons xs is still there.

**Comment by stephanrauh** [comment]
The `field-size` is still in the source code, and it works in the showcase: http://showcase.bootsfaces.net/forms/inputText.jsf. But it's not part of Bootstrap. By the look of it, neither `input-xs` nor `input-md` have ever been part of Bootstrap. @TheCoder4eu Should we add the missing sizes, or should we correct the documentation?

http://stackoverflow.com/questions/22920589/bootstrap-3-input-xs-smaller-than-sm

**Comment by ScreamingTree86** [comment]
Ah okay. I see `input-md` and `input-xs` is generated in the html but the classes do not exist. `input-md` just uses the default height of `.form-control`. 

Strange,i thought there where sometime xs sized input forms...

**Comment by stephanrauh** [comment]
Let's close the issue. It would be a nice feature, indeed, but I think we run into trouble if we start fixing missing features of Bootstrap. Those things tend to backfire with the next update.
