### ISSUE TITLE
per-column filter input placeholder does not respect lang attribute of its b:datatable

### ISSUE THREAD

**Issue by susanne69** [TheCoder4eu/BootsFaces-OSP#434]
Hi,

I am using Bundle-Version: 0.8.6, Bundle-Date: 20160522-21:44:31.
My b:datatable has the attribute lang set to **"de"**,the per-column filter input fields show as **placeholder** the **English** translation though.

Kind regards,
susanne69

**Comment by zhedar** [comment]
You're right, the search fields placeholders seem to be `Search [FIELDNAME]` and therefore aren't localized:
![bildschirmfoto 2016-06-22 um 21 13 36](https://cloud.githubusercontent.com/assets/6633403/16280123/704d73fe-38be-11e6-9d2a-662a79eb97df.png)

Maybe we forgot to include them in the localization files or it even is a bug of the datatables component itself. After having a quick look at https://datatables.net/manual/i18n it rather seems that those fields may not be included.

**Comment by susanne69** [comment]
That might be the reasonable solution not to show the placeholder if not specified or not attempted to be altered.

Thank you for having a look at it.

**Comment by stephanrauh** [comment]
Yes, the word "search" is "hard coded" in the `DataTableRenderer`. So we should find a nice, flexible and future-proof solution. Among other things, the correct translation in German is "nach [FELDNAME] suchen". So we need some extra flexibility with regard to the word order. Plus, we need i18n files specific to BootsFaces. But I don't see how we can support more than half a dozen languages.

**Comment by zhedar** [comment]
Actually it would be "[FELDNAME] durchsuchen", wouldn't it? Probably we could also recycle the search field translation and append the field's name to it. We may check if this introduces any problems with some languages, but may still be viable.

**Comment by stephanrauh** [comment]
@susanne69 Yes, that may be a solution that suits the needs of most developers:
* add an option to suppress the placeholder completely
* add an option to replace the word "Search" by something user-specific.
That still means the application doesn't react properly to the browsers locale, but I suppose hardly anybody will notice.

**Comment by zhedar** [comment]
Another solution would be to drop to literal part completely and use a symbolic term for search. However, I'm not sure, how that works out. See http://stackoverflow.com/questions/12036038/is-there-unicode-glyph-symbol-to-represent-search

**Comment by stephanrauh** [comment]
@zhedar Dunno. If the column was a city, the placeholder would be "Stadt durchsuchen". Which sounds like leaving the house and looking everywhere in the city :). 

Be that as it may, the i18n file could look like so:
```
bootsfaces.datatable.search="nach %1 filtern"
```
The %1 being a placeholder that may be moved around freely.

**Comment by stephanrauh** [comment]
@zhedar The symbolic search approach sounds promising. We could simply use `fa-search`.

**Comment by stephanrauh** [comment]
I've implemented the solution using symbols instead of texts.
