### ISSUE TITLE
Allow the column filters of b:dataTable to be above the columns

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#436]
This is a feature I've already implemented, but for some reason, it doesn't work yet. So I've deactivated it in order to publish a nice release. It would be nice to find the bug - probably somewhere in the JavaScript code.

**Comment by susanne69** [comment]
Sorry, I do not know whether to interfere here but deactivating multi-column-search-position makes the whole search thing, general search input and per-column input, not appear. The defaultResultsPerPage is also not honored anymore. I guess there are still dependencies to it in the Javascript and not dealt with. Rather leave it activated since it is just the default value. If it was set as attribute it worked fine.

I appreciate that that you react so promptly but sometimes it's better to sleep over possible ways to fix it; the genius in us can recover over night :) I really get surprised by mine but only after I serve a coffee ;).

Cheers

**Comment by stephanrauh** [comment]
Well, even after having my morning coffee the search features still work in the showcase. Your error description sounds like a JavaScript error indeed. You'll see that when you open your browsers JavaScript console. Would you mind to show us your datatable code snippet?

**Comment by susanne69** [comment]
I do not use any custom script in the page. Data are displayed perfectly.
I can share my b:datatable page but its is straight forward.

**Comment by susanne69** [comment]
OK, found it. I used orderable = "false" for one b:dataTableColumn. the column definition is added but a comma is missing before:
... language: { url: '/mavenproject1/javax.faces.resource/jq/ui/i18n/dt/datatable-de.json.jsf?ln=bsf' } columns: [null,null,null,null,{'orderable': false}],});

If I do not use it then it works.
New bug for orderable?

**Comment by susanne69** [comment]
Not for a bug for **orderable**  but **language** because if I omit lang="de" and use orderable = "false" then it seems just fine.

**Comment by stephanrauh** [comment]
Great, thanks! I think I've found the bug. Your diagnosis made that very simple.

**Comment by stephanrauh** [comment]
I hope now I'm caught every permutation :). Fancy to try the new snapshot?

**Comment by susanne69** [comment]
Sure. I do need to change the dependency though, right? I tried **0.9.1-SNAPSHOT** but it refuses to be transferred. Is it called differently?

**Comment by stephanrauh** [comment]
I've described in in #369. Snapshots are treated a little different than ordinary releases. You (or I, FWIW) can upload them as often as you want. Basically, all you have to do is to clear your Maven cache and und the pom.xml again. If you use Eclipse, there's a check box "force update of releases / checkbox" in the "update maven project" dialog. But I often simply delete the files from the .m2 folder to be really sure they are downloaded again.

**Comment by stephanrauh** [comment]
Oh, and I did the bug fix in 0.9.0. This ticket is targeted at the next version because it's a new feature. Somehow we've mixed to related, but different things in this ticket. :).

**Comment by susanne69** [comment]
I still get only 0.9.0-20160624.212046-9 :/

**Comment by susanne69** [comment]
... clear m2 worked out :) Thank you.

**Comment by susanne69** [comment]
Perfect, bulletproof. It survives all my combinations I have complained about.

**Comment by stephanrauh** [comment]
I'm glad to hear this!

**Comment by TheCoder4eu** [comment]
Is this issue to close?

**Comment by susanne69** [comment]
Yes, please close it.

 

Von: TheCoder4eu [mailto:notifications@github.com] 
Gesendet: Samstag, 29. Oktober 2016 17:22
An: TheCoder4eu/BootsFaces-OSP <BootsFaces-OSP@noreply.github.com>
Cc: susanne69 <susanne@baltsch.de>; Comment <comment@noreply.github.com>
Betreff: Re: [TheCoder4eu/BootsFaces-OSP] Allow the column filters of b:dataTable to be above the columns (#436)

 

Is this issue to close?

**Comment by TheCoder4eu** [comment]
Thanks @susanne69 .
