### ISSUE TITLE
b:messages "for" attribute appears to do nothing

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#437]
I have two b:messages components set up on my page. One has a "for" attribute of "form1", for example, and the other has "form2". If I make a FacesMessage with a clientId of "form1", both b:messages receive the message. Same thing happens if I do "form2". Same thing happens if I put complete gibberish, whether in the FacesMessage or in the "for" attribute. It appears that the "for" attribute does nothing at all. Using h:messages works exactly as intended with no other changes. Literally changing the b to an h solves the problem -- I just no longer have the nice styling of bootsfaces.

I am on 0.8.6

**Comment by MitchTalmadge** [comment]
Just tested with b:message, and it works exactly how it should.

**Comment by MitchTalmadge** [comment]
Looks like b:message does support multiple messages. Kinda misleading. I was under the impression that b:message displayed only one message (like h:message) and b:messages displayed multiple (like h:messages).

**Comment by stephanrauh** [comment]
To my surprise, your analysis is correct. I didn't know there's a for attribute for `h:messages`, so I didn't implement it in `b:messages`. I also wasn't aware that both Mojarra and PrimeFaces show only one message with `h:message` and `prime:message`. Looks a bit off to me, because the source code leaves me with the impression that the message is selected at random, not by severity.

**Comment by MitchTalmadge** [comment]
Honestly, the whole h:messages system is confusing to me. I'll leave this to your best judgement of how it should work. I just kind of assumed that b:messages would display multiple messages if they were available, and b:message would show only one (based on severity).

**Comment by stephanrauh** [comment]
I always assumed that `h:message` is responsible for a single field, and `h:messages` is responsible for displaying the rest. But after reading the source code I have to admit I was wrong. You can use the components that way, but there are other ways to use them, too.

**Comment by MitchTalmadge** [comment]
That's probably the most proper way to do it. The limitation of not having a "for" attribute for the b:messages has driven me to use individual b:message tags on each of the fields, which is actually working out much nicer for me, as the user can see the error right on top of the associated fields. So honestly, I was misleading myself. Still, a "for" attribute would be nice.

**Comment by stephanrauh** [comment]
I've implemented a `for` attribute that's a bit more flexible than its standard counterpart. Have a look at http://www3.bootsfaces.net/Showcase/forms/messages.jsf (browse for "the for attribute").

**Comment by MitchTalmadge** [comment]
Wow, amazing work! And quick too :) Very impressed with the results. Works just how I'd want it to, and more.

**Comment by stephanrauh** [comment]
Great! 

I suppose I'll add an attribute `onlyMostSevere`to `<b:message />`, so developers can decides themselves if they want to see one or more messages.

**Comment by MitchTalmadge** [comment]
That sounds like a great idea. Thanks again for all the support!

**Comment by stephanrauh** [comment]
Have a look at http://www3.bootsfaces.net/Showcase/forms/messages.jsf.

**Comment by MitchTalmadge** [comment]
Perfect :) Thanks so much
