### ISSUE TITLE
Allow to specify body for some components as alternative of the value/text attributes

### ISSUE THREAD

**Issue by jpiersanti** [TheCoder4eu/BootsFaces-OSP#438]
Hello All,

This is not an issue but a suggestion. I find useful to allow some components like b:label and all similar text decorator to be used in this way:

```
<b:label   severity="info">
<h:outputText value="text1" />
<h:outputText value="#{bean.someNumber}" >
    <f:convertNumber type="percent"/>
</h:outputTex>
</b:label>
```

as an alternative of the usual way, using the text attribute for the case of label.

Do you think this could be a good improvement? Or is there a way of achieving the same result already?

Regards,

**Comment by stephanrauh** [comment]
@jpiersanti Which other BootsFaces components might benefit from this? Fancy to start collecting a list?

**Comment by jpiersanti** [comment]
Hello @stephanrauh,

I would say that b:label, b:navLink, b:navCommandLink and b:badge could benefit from an alternative ways to add text information.

**Comment by stephanrauh** [comment]
This has been reported a second time as #693. I'll close this ticket in favor of the other ticket.
