### ISSUE TITLE
CRUD Datatable

### ISSUE THREAD

**Issue by michaelende** [TheCoder4eu/BootsFaces-OSP#439]
Hello,

this is a question and not a Bug.
it is possible to add a Button in a table which call a modal form with the selected object of the table row?

i missing a action attribute in the b:button tag.

many thanks
Michael

```
    <b:dataTable value="#{masterdataManager.listAllAccounts()}" var="acc"
                 styleClass="table table-striped table-bordered"
                 style="width:100%" fixedHeader="true" responsive="true">

        <h:column>
            <f:facet name="header">
                <h:outputText value="ID"/>
            </f:facet>
            <h:outputLabel value="#{acc.id}"/>
        </h:column>
        <h:column>
            <f:facet name="header">
                <h:outputText value="Username"/>
            </f:facet>
            <h:outputLabel value="#{acc.name}"/>
        </h:column>
        <h:column>
            <f:facet name="header">
                <h:outputText value="Password"/>
            </f:facet>
            <h:outputLabel value="#{acc.password}"/>
        </h:column>
        <h:column>
            <f:facet name="header">
                <h:outputText value="Role"/>
            </f:facet>
            <h:outputLabel value="#{acc.role}"/>
        </h:column>
        <h:column>
            <f:facet name="header">
                <h:outputText value="Action"/>
            </f:facet>

            <h:form>
                <b:button look="warning" pt:data-target="#amodal" pt:data-toggle="modal"
                          onclick="return false;" iconAwesome="pencil"  />
                <b:commandButton iconAwesome="trash" action="#{masterdataManager.deleteAccount(acc)}"/>
            </h:form>
        </h:column>
    </b:dataTable>

    <b:modal id="amodal" title="Edit Account" styleClass="modalPseudoClass" >
        <p>Modal body</p>
        <f:facet id="footer" name="footer">
            <b:button id="close" value="close" dismiss="modal" onclick="return false;"/>
            <b:button id="ok" value="Ok" look="primary" dismiss="modal" onclick="return false;" />
        </f:facet>
    </b:modal>
```

**Comment by stephanrauh** [comment]
If you don't want to start with a lot of JavaScript, you probably have to use a commandButton and AJAX. Clicking it sets the current account (similar to the "trash" button of your example). The commandButton also has to update the content of the modal. Finally, open the modal dialog using JavaScript and the `oncomplete`attribute.

Does this help you?

**Comment by michaelende** [comment]
Thanks for the support. I make it as you discript.
But when I click the save-button on the EditForm (Modal) it dont call the action in the managedBean.
Have you any Idea or a solution for this problem?

```
<b:modal id="editAccountModal" title="Edit Account" styleClass="modalPseudoClass">
            <h:form id="editAccountForm">
                <b:inputText value="#{accountView.selectedAccount.id}" label="ID" readonly="true"/>
                <b:inputText value="#{accountView.selectedAccount.name}" label="Username"/>
                <b:inputText value="#{accountView.selectedAccount.password}" label="Password"/>
                <b:selectOneMenu value="#{accountView.selectedAccount.role}" label="Role:">
                    <f:selectItems value="#{accountView.getRoles()}" var="r" itemValue="#{r}" itemLabel="#{r}"/>
                </b:selectOneMenu>

                <b:button id="close" value="close" dismiss="modal" onclick="return false;"/>
                <b:commandButton action="#{accountView.update()}" dismiss="modal" value="save" look="primary"/>
            </h:form>
        </b:modal>
```

**Comment by stephanrauh** [comment]
I guess your commandButton would be better off with AJAX, but of course, it should work even so if you don't mind reloading the entire page. The `dismiss` attribute is specific to Bootstrap, but not to BootsFaces. We don't support it (yet?). It's simply ignored because we usually close the modal via JavaScript using the `oncomplete` callback. `dismiss` is a valid attribute of `<b:button />`, but that's a different component.

I'm also not sure if you are allowed to add the parenthesis in the `action` attribute. 

Putting it all together, you may try

```xml
<b:commandButton update="@(.whatever)" onclick="action:accountView.update()" oncomplete="$('#editAccountModal').modal('hide');" look="primary" />
```

**Comment by michaelende** [comment]
thanks for the quick response, but it doesn't work:-(. 
It is possible to add a example with crud datatable with modal forms for editing and creating items in the showcase / demo application region?

**Comment by LuisToro** [comment]
Hello, I have problems with updating <b: datatable> with id. The structure of the code is as follows:

` <ui:define name="body">
                <b:container>
                    <h:form id="TipoDiscapacidadListForm">
                        
                        <b:dataTable id="datalist"
                                     value="#{tipoDiscapacidadController.listTipoDiscapacidad}"
                                     var="item"
                                     select='false'
                                     selectionMode="single"
                                     row-highlight='true'
                                     ajax="true"
                                     lang='es'>`

                               . . .  /* Columns  *\ . . . 

                          `</b:dataTableColumn>

                        </b:dataTable>
                        
                    </h:form>
                     <ui:include src="Edit.xhtml"/>

                                    . . .`

In the edit.xhtml

In the edit I use `<b:modal>` with a `<b:>commandbutton/>`

`<b:commandButton value="#{bundle.Editar}" look="caution" ajax="true" update="TipoDiscapacidadEditForm:panelEdit,:TipoDiscapacidadListForm:datalist,:growl" actionListener="#{tipoDiscapacidadController.update()}" action="#{tipoDiscapacidadController.closeEditModal()}" />`

I get the following error. Any help is appreciated.

Invalid search expression: TipoDiscapacidadListForm:datalist The subexpression datalist doesn't exist, or it can't be resolved.

**Comment by LuisToro** [comment]
I solve it !

`<b:commandButton/>` inside `<b:modal/>`

`<b:commandButton value="#{bundle.Editar}" look="caution" ajax="true" update="TipoDiscapacidadEditForm:panelEdit,:growl" actionListener="#{tipoDiscapacidadController.update()}" action="#{tipoDiscapacidadController.closeEditModal()}" />`


In the controller:

```
public void closeEditModal(){
        RequestContext context = RequestContext.getCurrentInstance();
        context.update("TipoDiscapacidadListForm:datalist");
        context.execute("$('.modalPseudoClassEdit').modal('hide');");
        
    }
```


Thx.

**Comment by stephanrauh** [comment]
I'm pretty sure the latest enhancements (version 1.0.2) of our b:dataTable solved this issue. The root cause was that the row id wasn't added to the button. Feel free to leave a comment on this issue if I'm mistaken and the bug still exists.
