### ISSUE TITLE
b:panel doesn't render styleClass attribute

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#44]
The panel component doesn't render the styleClass attribute:
```XML
<b:panel title="hello world" styleClass="helloWorldClass">
  ...
</p>
<prime:commandButton update=".@(helloWorldClass" />
```
The command button can't update the panel, because the class attribute is missing.

**Comment by stephanrauh** [comment]
Done. Riccardo, would you mind to check whether the build file has to be modified? I added a styleClass value to the RPanel enum. Do the yui-compressor rules have to be adapted?

**Comment by TheCoder4eu** [comment]
The yuicompressor just minifies JS and CSS.
I just had to add the styleClass attribute for b:panel.
