### ISSUE TITLE
b:accordion is showing footer facet buttons

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#442]
Hi,
(and again thanks for your great job for this API)

Is it normal that b:accordion is showing facet ? 
For exemple, collapsed panels are showing buttons from footer facet.

Is it the awaiting behavior ?

Regards

**Comment by stephanrauh** [comment]
No, that wasn't the intended behaviour. Actually, it was puzzling me for quite some time now, but I needed your hint to recognize we didn't nest the `divs` correctly. I've uploaded a developer snapshot of BootsFaces 0.9.0 to Maven Central. See #369 on how to get it.
