### ISSUE TITLE
b:navLink inside ui:repeat rendered with span instead of li

### ISSUE THREAD

**Issue by kirys** [TheCoder4eu/BootsFaces-OSP#443]
When navlink is used inside a ui:repeat it render with span.
example in this case:
```
	<b:listLinks>
		<b:navLink header="Statistiche" />
		<b:navLink href="#{request.contextPath}/a/s/stats/index.xhtml" value="Sommario" />
		<b:navLink href="#{request.contextPath}/a/s/stats/anni.xhtml" value="Andamenti annuali" />
		<b:navLink></b:navLink>
		<b:navLink header="Dettaglio annuo"/>		
        <ui:repeat value="#{mercurialSession.years}" var="anno">
			<b:navLink href="#{request.contextPath}/a/s/stats/anno.xhtml?y=#{anno}" value="#{anno}" />
		</ui:repeat>		

		<b:navLink></b:navLink>
	</b:listLinks>
```

**Comment by stephanrauh** [comment]
Oops - you're right, I missed that when I allows the navLink to be a solitary link.

**Comment by MitchTalmadge** [comment]
I noticed this bug as well but forgot to report it -- oops :P Glad someone else caught it. I used a c:forEach tag to get around the bug. It works just as well.

**Comment by kirys** [comment]
glad to be of help ^_^

**Comment by stephanrauh** [comment]
There are subtle differences between `ui:repeat` and `c:each`. The (older) `c:each` component is resolved earlier, which may cause problems under certain circumstances.

**Comment by zhedar** [comment]
@stephanrauh In this case, `c:forEach` should be a valid use though. As long as you don't bind any `ui:repeat`s to the var of the iterating JSTL tag, you should be fine. The reason why this works is, that `c:forEach` won't be a component itself unlike `ui:repeat`.

**Comment by stephanrauh** [comment]
I've fixed this issue both for Mojarra and MyFaces. It should even work with the `p:repeat` component of PrimeFaces.
