### ISSUE TITLE
<b:selectOneMenu> validation: "bf-error" CSS pseudo class not applied on error

### ISSUE THREAD

**Issue by mistahboz** [TheCoder4eu/BootsFaces-OSP#449]
When using validation (such as `required="true"`) on `<b:selectOneMenu>` the CSS pseudo class "bf-error" is not applied to the `select` tag on validation fail.

**Comment by stephanrauh** [comment]
Please have a look at #593 and http://www3.bootsfaces.net/Showcase/forms/selectOneMenu.jsf#errorClasses. I believe this is a duplicate of this error, so we'll track progress in #593. If I'm wrong, just answer in this issue: We're still listening to it. 

Thanks for your understanding (and your patience - for some reason, this issue slipped my attention!)
Stephan

**Comment by stephanrauh** [comment]
I've just closed #593. I assume this bug is solved now, too.
