### ISSUE TITLE
b:datepicker should have z-index 3 or higher

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#45]
Most datepickers of the example page work fine, except for the first one:

![image](https://cloud.githubusercontent.com/assets/3045767/5691605/8a8e8e90-98d0-11e4-9bb4-4e86a1d8e3a5.png)

Setting the z-index of the div to 3 or higher fixes the problem:

```xml
<div id="ui-datepicker-div" 
      class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" 
      style="position: absolute; top: 325px; left: 390.5px; z-index: 3; display: none;">
```

I suggest to add the z-index to bsf.css, something like 

```css
.ui-datepicker-div { z-index:3; }
```

**Comment by TheCoder4eu** [comment]
Oh, yes I did notice that some times ago, but always forgot to fix this.
I'll see what can be the best integer to apply (although we can always raise it in the future);

**Comment by TheCoder4eu** [comment]
Not so trivial to solve, datepicker had the z-style applied as element style(inline).

**Comment by stephanrauh** [comment]
Also see https://github.com/TheCoder4eu/BootsFaces-OSP/issues/82.
