### ISSUE TITLE
Feature Request - b:link, b:commandLink

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#453]
It'd be really nice to see `b:link` and `b:commandLink` components to replace the `h:link` and `h:commandLinks`. I've been resorting to using `b:navCommandLink` and `b:navLink` which work, but they feel hacky, as I feel those are meant for navbars.

I'm curious to hear opinions on this.

**Comment by stephanrauh** [comment]
What's the difference between `b:link` and `b:navLink`? Should it generate different HTML code?

**Comment by MitchTalmadge** [comment]
The main reason for this is that I always felt like I'd break something if I used a _nav_Link somewhere outside of a _nav_bar. It never occurred to me that I could use it as a regular link anywhere else; so intuition is my greatest argument. 

Other than that, here is the difference between an `h:link` and a `b:navLink`:

`h:link`
```xml
<a href="/root/index.xhtml">test</a>
```

`b:navLink`
```xml
<span id="editAssetModalForm:j_idt113">
    <a href="/root/index.xhtml" role="menuitem" tabindex="-1">test</a>
</span>
```

Notice that the b:navLink has a <span> tag where the h:link does not, and that the b:navLink includes a `role="menuitem"` which may confuse ARIA clients. 

It's not a huge deal, but something to consider. Again, the main reason is because of confusion. I can't imagine I'm the only one who was confused by this.

**Comment by TheCoder4eu** [comment]
Mitch let us ponder a little bit more on this. we are going to release soon.

**Comment by stephanrauh** [comment]
Done and documented.
