### ISSUE TITLE
BootsFaces search expressions do not work in f:ajax render

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#458]
For reference of where I discovered this:
https://gitter.im/TheCoder4eu/BootsFaces-OSP?at=577e2e84b79455146f57326c

I cannot seem to use BootsFaces' own search expressions (`@parent`, etc) inside of the `f:ajax`'s `render` attribute. [This page](http://showcase.bootsfaces.net/forms/searchExpressions.jsf;jsessionid=9zv4ZHgZEhf-6JQs54E6qtV5-U2iNUPNWlKCPH4p.wildfly01) says that 

"For these components, the search expressions should also work with traditional <f:ajax /> facets (although we discourage the use of these AJAX facets - in most cases you don't need them)."

To be fair, I have only tested this with an `f:ajax` component inside of an `h:commandButton`, and the quote above is talking about BootsFaces' ajax enabled components. Therefore, if this was not intended to be a feature, I'm okay with that. It would be a great feature, though.

**Comment by stephanrauh** [comment]
Unfortunately, it's impossible to modify the standard expression resolver of Mojarra and MyFaces. It's deeply ingrained in the implementation. Unlike many other features of JSF, there's no API allowing to modify it. So my remark only applies to the BootsFaces components.

Currently @tandraschko and I try to bring the search expressions to JSF 2.3. It will be a reduced subset of both the PrimeFaces and the BootsFaces search expressions. In particular, JSF 2.3 will only support search expression delivering a single result. There won't be such a thing as `@after`.
