### ISSUE TITLE
h:commandLink, b:commandButton, etc. do not work inside of b:dataTableColumn

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#459]
For reference of where I discovered this:
https://gitter.im/TheCoder4eu/BootsFaces-OSP?at=577e2e84b79455146f57326c

It appears that `h:commandLink`, `b:navCommandLink`, `b:commandButton`, and `h:commandButton` do not work inside of `b:dataTableColumn`. I had to resort back to the `h:column` and `f:facet` tags to make them work. The problem is that they do not call their `action` attribute methods at all.

**Comment by stephanrauh** [comment]
I've fixed this bug some time ago. The last demo of https://showcase.bootsfaces.net/forms/DataTable.jsf shows b:commandButtons in a b:dataTable.
