### ISSUE TITLE
BootsFaces ajax breaks when in the same form as an h:inputFile

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#460]
I have discovered that when a BootsFaces ajax component is in the same form as an `h:inputFile`, the component will not fire its action with ajax anymore. Here's an example:

This form contains nothing more than an `h:inputFile` and a `b:commandButton` with `ajax` set to `true`:

``` xml
<h:form enctype="multipart/form-data">
    <h:inputFile/>
    <b:commandButton action="#{testController.action}" ajax="true" value="Submit"/>
</h:form>
```

The `action` method contains literally nothing more than `System.out.println("test");`

When I click submit... Nothing happens.

Now I change `ajax` to `false`. I click submit, and `test` is printed in the console. The page is also refreshed.

Now I change `ajax` back to `true` and remove the `h:inputFile` (leaving the `enctype` set to `multipart/form-data`). I click submit, and `test` is printed in the console, without a page refresh.

**Comment by zhedar** [comment]
Maybe you can have a look at https://github.com/TheCoder4eu/BootsFaces-OSP/issues/376. It's actually quite the same issue if I remember correctly. It's still a strange issue though. We may need to inspect this in the future.

**Comment by MitchTalmadge** [comment]
Please attempt to reproduce this again using my snippet above. If you guys can't reproduce it, I'll spend some time and make a self contained example that will hopefully be of help. Thanks!
