### ISSUE TITLE
b:datatable per-column filtering returns no rows if current page # was greater than filter result has

### ISSUE THREAD

**Issue by susanne69** [TheCoder4eu/BootsFaces-OSP#462]
Hello again,
I have moved to 0.9.0. 
The per-column filtering in b:datatable returns no rows if current page # was greater than result has.

Imagine 3 rows and 1 row per page. The column has values A,B and C.
I am on page #1 and filter for 'C' filter shows correctly one row with C.
The filter is removed again and I move to page 3.
I am filtering again for 'C' and no row is returned. Only if I click on page #1 the lost row shows up from the dark. Poor row.

Kind regards,
Susanne

**Comment by stephanrauh** [comment]
I'm not sure if we can solve this bug. It seems to be a bug of the underlying JavaScript widget (https://datatables.net/). But of course I'd like to have a look myself before reporting a bug on their bugtracker.

**Comment by stephanrauh** [comment]
BTW, you may want to move to 0.9.1. It's not a big update - basically compatibility to Java 6/7 and a few minor bugfixes.

**Comment by stephanrauh** [comment]
Good news: I've just tried to reproduce the bug. It's gone away. I suppose the datatables.net team has noticed the bug themselves.
