### ISSUE TITLE
More than one b:datatableColumn with order attribute set cause script error

### ISSUE THREAD

**Issue by susanne69** [TheCoder4eu/BootsFaces-OSP#463]
Hi, me again,

When there is more than one b:datatableColumn with order attribute set a script error is caused.
A part of your table variable definition look as follows
searching: true,**order: [3,'asc'],[4,'asc'],**stateSave: true,

I guess [4,'asc'], is not wanted here. 

I think your script should be bulletproof despite wrongly set attributes e.g. like ignoring the second order attribute and give out a script warning.

Kind regards,
Susanne

**Comment by stephanrauh** [comment]
Is throwing a `FacesException` too harsh? I'm afraid the JavaScript warning is easily missed.

CU
Stephan

**Comment by susanne69** [comment]
Yes, it is better to be obvious. FacesException is perfect.

Cheers,
Susanne

**Comment by stephanrauh** [comment]
I still think it's a good idea, but our team has run out of team members. Let's close the ticket reluctantly.
