### ISSUE TITLE
Question regarding wizard with carousel

### ISSUE THREAD

**Issue by m1rc0** [TheCoder4eu/BootsFaces-OSP#465]
Hi there,

it's probably a stupid newbie question, but I hope you can and may help me.

I want to create a wizard according to the example in your docs. On the last page of the wizard I'd like to give a summary of what was entered, but honestly I don't know what to process. 

I used my previous example here (https://github.com/m1rc0/BootsFacesExample) to show what I mean.

Thank you very very much

**Comment by stephanrauh** [comment]
Did you push your example already to GitHub? All I can see is a sketch of an SPA, but there's no wizard.

**Comment by m1rc0** [comment]
Uh, I'm so sorry. Now its there. 

Thank you very much

**Comment by stephanrauh** [comment]
Adding AJAX to the command buttons solves your problem. I've added a `styleClass` to the result panel in order to be able to use `update="@(.result)"`, and I've added an AJAX call to the `onclick` handlers:

```xml
<b:carouselItem style="width:400px;height:230px">
    <b:panel title="Step 3" look="success" >
        <b:panelGrid columns="2" styleClass="result">
            <h:outputText value="First Name"/>
            <h:outputText value="#{backingBean.newThing.name}"/>
            <h:outputText value="Street"/>
            <h:outputText value="#{backingBean.newThing.description}" />
        </b:panelGrid>
        <b:commandButton look="success" value="Save" actionListener="#{backingBean.saveThing()}"/>
    </b:panel>
</b:carouselItem>
<b:carouselControl direction="right" >
    <b:commandButton value="previous step" role="button"
                     update="@(.result)"
                     onclick="$('.wizardPseudoClass').carousel('prev');$('.wizardPseudoClass').carousel('pause');ajax:backingBean.dummyAction();"
                     look="info" />
</b:carouselControl>
<b:carouselControl direction="left">
    <b:commandButton value="next step" role="button" style="position:absolute;right:0px"
                     update="@(.result)"
                     onclick="$('.wizardPseudoClass').carousel('next');$('.wizardPseudoClass').carousel('pause');ajax:backingBean.dummyAction();"
                     look="success" />
</b:carouselControl>
```

```java
@Named
@SessionScoped
public class BackingBean implements Serializable {
    public void dummyAction() {}
    ...
```

**Comment by stephanrauh** [comment]
BTW, your bean lacks its `serialVersionUID`.

**Comment by m1rc0** [comment]
Hey @stephanrauh. It works like charm. Thank you very much. 

Is there a way to donate you guys a coffee? :)

**Comment by stephanrauh** [comment]
@m1rc0 You'll have to send the coffee to five different guys living in three different countries. Not to mention the different favorite flavors :).
