### ISSUE TITLE
Make <div> a first-class citizen of JSF

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#47]
Divs play a crucial role in Bootstrap, but they aren't part of JSF's DOM tree. This mismatch often leads to difficulties. AngularFaces has the same problem, so I invented a way to make divs and spans first-class citizens of JSF. I'd like to donate the code to the BootsFaces project. 

First-class divs would be an option that has to be activated in the web.xml, so it's the programmers' choice if they want to use the feature or not.

Demonstration of the problem:
```XML
<b:panelGrid colSpans="3,9">
  <h:outputText value="street"/>
  <b:inputText value="#{address.street}" />
  <h:outputText value="zipcode/city"/>
  <div>
     <b:inputText value="#{address.zip}" />
     <b:inputText value="#{address.city}" />
  </div>
</b:panelGrid>     
```

The idea is to display the two field zipcode and city in a single column, so that they align nicely with the wider fields, such as the street names. Unfortunately, JSF converts both the opening &lt;div&gt; and the closing &lt;/div&gt; to text nodes. As a result, the form looks, well, confused.

It's possible to solve the problem in JSF using &lt;h:panelGroup display="block"&gt; instead of &lt;div&gt;. But that's verbose and ugly. Adding insult to injury, hardly anybody knows this trick.

**Comment by TheCoder4eu** [comment]
Did you try to use a ```<b:row>``` instead of a ```<div>``` ?

**Comment by TheCoder4eu** [comment]
A  ```<b:container>``` instead of a ```<div>```  could be appropriate.

**Comment by AlexanderBl4h** [comment]
Why do you think, that should working? As far as I understand, <b:inputText> spans the whole container. A component to 'group' other components such as `<b:inputText>` would be nice.

**Comment by stephanrauh** [comment]
Thanks for your upvote! I'll raise the priority of this ticket.

**Comment by jbmb** [comment]
if you want the `div` to become part of the component tree, you could use the `xmlns:jsf="http://xmlns.jcp.org/jsf"` namespace (pass-through element):
`<div jsf:id="someId">...</div>`
Is that not sufficient?

**Comment by stephanrauh** [comment]
That didn't work when I tried (see http://www.beyondjava.net/blog/jsf-2-2-html5-cheat-sheet/). Does it work for you?

**Comment by stephanrauh** [comment]
The feature has been implemented, but it has not been documented yet.

**Comment by stephanrauh** [comment]
While documenting the feature, I noticed it needs some polishing. Currently, it's marked as "experimental".

**Comment by stephanrauh** [comment]
Probably it's not perfect, but I've polished the feature enough to call in done and implemented.
