### ISSUE TITLE
Improve the selection feature of the b:dataTable 

### ISSUE THREAD

**Issue by TomKrauss** [TheCoder4eu/BootsFaces-OSP#473]
The `b:dataTable` supports a `select` attribute, which, when set to `true`, allows the user to select rows in the table.

You cannot however yet access the selected row - there is no API todo so.
Furthermore, if you try to add an `onselect` AJAX Handler (e.g.: `onselect="ajax:myBean.selected()"`), this handler does not work, but you get a **JavaScript error** (event is not defined), when selecting a row in the table.

Last but not least, it would be nice, if one could optionally select **multiple** rows instead of only single rows.

**Comment by stephanrauh** [comment]
Both features have been implemented in the meantime. See https://showcase.bootsfaces.net/forms/DataTable.jsf and scroll to the demo below "Unified AJAX and JavaScript API".
