### ISSUE TITLE
Improve b:tree documentation

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#476]
Improve docs with the processing of check and uncheck the items (not automatic)
implement the methods (processValueChecked and processValueUnchecked) from TreeNodeEventListener interface .
use these methods like below:

```
	public void processValueChecked(TreeNodeCheckedEvent arg0) {
		Node node = (DefaultNodeImpl) arg0.getNode();
		node.setChecked(true);

		TreeModelUtils.updateNodeById(getCategoriasModelTree(), node.getNodeId(), node);
	}
```
See #456 .

**Comment by asterd** [comment]
Done!
