### ISSUE TITLE
No target in b:navLink

### ISSUE THREAD

**Issue by dqdb55** [TheCoder4eu/BootsFaces-OSP#478]
Hi, 
I would like to open something in new window after clicking b:navLink. Is it possible to do it in bootsfaces with b:navlink? I think that I need something similar to target attribute (target="_blank") in primefaces' p:link.

Thanks for help.

**Comment by stephanrauh** [comment]
Can you solve the issue with JavaScript? I didn't try with BootsFaces yet, but I'm sure you can add JavaScript either to the `onclick` handler or to the `href` attribute to have this HTML code generated:

```HTML
<a href="javascript:window.open('http://www.google.com', '_blank');" >Google</a>
```

**Comment by stephanrauh** [comment]
I just observed that we didn't implement any of the JavaScript callback functions with `<b:navLink />`.  So I guess we'll add both the `target` attribute and the JavaScript callbacks.

**Comment by dqdb55** [comment]
onclick="window.open('http://google.com', '_tab');" 
is working pretty well.

Thanks for the tip.

**Comment by stephanrauh** [comment]
It's always a pleasure to help! However, I'm a bit surprise the `onclick` bit works. I'll have to double-check this. Some time ago, someone reported that `onclick` doesn't do anything, and the source code indicates the same. `onclick` should work with `b:navCommandLink`, but it seems we've forgotten to implement it with the non-AJAX `b:navLink`. Can you confirm or deny this?

Thanks in advance
Stephan

**Comment by dqdb55** [comment]
This code:

<b:navLink value="Mail" onclick="window.open('http://mail.page.com', '_tab');" rendered="#{userUtil.isUserInAdminRole()}"/>

- is opening new tab in browser (Firefox)
- is refreshing current page (which is not necessary, a bit strange, but it's not a big problem in my case).

If I press the link (navLink) with Ctrl button then 2 tabs will be opened -> this is another problem but not really important for me now.

I advice to double-check this component.

Best regards

**Comment by stephanrauh** [comment]
This feature was so simple to implement that I decided to collect the low-hanging fruit now even if it was planned for version 1.1.
