### ISSUE TITLE
b:navCommandLink - different cursor when outcome & action is used

### ISSUE THREAD

**Issue by dqdb55** [TheCoder4eu/BootsFaces-OSP#479]
When I use b:navCommandLink's "outcome" attribute - there is a "hand" cursor.
When I use b:navCommandLink's "action" attribute - there is a "pipe" cursor. In "action" attribute there is a backend bean method called and navigation string is returned by this method.
 
I think that hand cursor should be shown in both cases.

I tested using version 0.9.1 and Firefox 47.

**Comment by stephanrauh** [comment]
Interesting. We should be able to fix this with a CSS style. BTW, if you need a quick workaround, you can probably add such a CSS class yourself (style="cursor:pointer") to the b:navCommandLink.

**Comment by dqdb55** [comment]
Your workaround with style="cursor:pointer" is working. Thanks.

**Comment by MitchTalmadge** [comment]
I noticed the same thing. If nobody is gonna take this one, I'll do it 👍

**Comment by stephanrauh** [comment]
It's yours :).

**Comment by MitchTalmadge** [comment]
I'll be sure to put it in the commit next time

**Comment by zhedar** [comment]
Putting it in the PR body text works aswell, that's why I would have expected the title to do the same.
