### ISSUE TITLE
form has height 0

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#48]
Just saw this one on the staging showcase - one of the CSS rules you've changed recently seems to be important:

![image](https://cloud.githubusercontent.com/assets/3045767/5696902/e08b97fa-99e0-11e4-9411-4f55721a8914.png)

**Comment by TheCoder4eu** [comment]
For some reason inputText lost its enclosing form-group div...

**Comment by stephanrauh** [comment]
Oops - sounds like an unexpected effect of a change of mine.

**Comment by TheCoder4eu** [comment]
Have a look here:

https://github.com/TheCoder4eu/BootsFaces-OSP/commit/16eb146567400db678191d92cfbe29f98912d6ac#diff-ac3e1dc8a2df5358e9a98650782985c7

InputTextRenderer rows 89-91
the form-group now is rendered only if label is not null.

**Comment by stephanrauh** [comment]
Surprising effect... as far as I can see, form-group does nothing but adding a margin of 15px. Yet still, dropping it reduces the height of the form to zero pixels!

I reactivated the form-group and added it to b:selectOneMenu, too.
