### ISSUE TITLE
b:SelectOneMenu Converter

### ISSUE THREAD

**Issue by bernardomk** [TheCoder4eu/BootsFaces-OSP#480]
Hi,

I have a SelectOneMenu with filled with a Collection using f:selectItems. I added a single f:selectItem to have a message: "Please Select One" as this is gonna be a master / detail cascade.

The problem is that it is passing a String or Integer or whatever and I have not been able to set a converter to the b:SelectOneMenu.

Is this a bug or am I doing something wrong?

Thanks in advance!

**Comment by stephanrauh** [comment]
Your bug might be solved by the pull request I've accepted yesterday. I didn't test it yet as thoroughly as I wanted to, but  the first impression is positive. Do you want to give it a try yourself? Grab BootsFaces-0.9.2-SNAPSHOT from Maven Central (see #369 on how to get it).

**Comment by bernardomk** [comment]
Hey,

Don't think it's a bug, look:

<f:selectItem itemLabel="Select One" itemValue="" **noSelectionOption="true"** />

Setting noSelectionOption to true solved the problem! Still, no converter needed!

**Comment by stephanrauh** [comment]
I've used both `f:selectItem` and `f:selectItems` in a single radio button (see http://www3.bootsfaces.net/Showcase/forms/RadioButton.jsf). That's a different component, but it uses the same method to collect the `selectItems`, so this should also work with comboboxes. However, I didn't try converters yet.
