### ISSUE TITLE
Add AJAX to b:dateTimePicker

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#482]
As @ScreamingTree86 points out, we've forgotten to add AJAX to `<b:dateTimePicker />`. BootsFaces 1.0 should fix that.

**Comment by asterd** [comment]
Done and documented with 9e9b7e0 . Maybe @stephanrauh you must have a look to check is all ok, please!

**Comment by stephanrauh** [comment]
I guess I should run a QA session on it, but it's definitely far better than before.

**Comment by MitchTalmadge** [comment]
Using 0.9.2, I can't seem to get ajax to do anything at all. Was this tested?

**Comment by asterd** [comment]
Hi @MitchTalmadge, the source code on GitHub was aligned with the support of Ajax in DateTimePicker (9e9b7e0 and 3532a41). I don't know if the pre-build jar contains this commit... but also in BootsfacesWeb (source code) the documentation is aligned with an example of ajax call.

**Comment by MitchTalmadge** [comment]
@asterd It appears that ajax does work for popup and basic type fields, but not at all for inline. Also, the ajax appears to only fire when I click on the field, but not when I click on the dates inside the popup. For example, if I click on the field, which makes the popup appear, then ajax is fired. If I click a date inside the popup, even though the date changes inside the field, ajax is not fired. If I click away from the field, and then click on it again, ajax is now fired and the correct date is sent.

**Comment by MitchTalmadge** [comment]
Found the problem; ajax is only happening on the `onclick` javascript event. To get it to work with the date change event, I just added `ondtchange="ajax:true"` to the dateTimePicker. I would have assumed that `ajax="true"` was all I needed for both onclick and ondtchange, so maybe that can be an improvement in the future?

**Comment by TheCoder4eu** [comment]
@MitchTalmadge thanks for your PR!

**Comment by TheCoder4eu** [comment]
@stephanrauh , I guess the PR solved the Issue? Or there was something left?
