### ISSUE TITLE
Add support for horizontal forms

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#485]
I think it would be useful to add support for [horizontal forms](http://getbootstrap.com/css/#forms-horizontal) to input components. My idea:
- the user has to add the `form-horizontal` to a container, we can't add it for him... (just like #475)
- add an `horizontal` attribute the input elements ( `b:inputText`, `b:selectOneMenu` and so on)
- if the attibute is present, the rendered label gets the `control-label` class
- if the attribute is present the `input` element (or the `div` with the class `input-group` if present) has to be enclosed in a `div` which has the column classes. The user can add the classes from another attribute of the input components, `horizontalStyleClass` or something like that
- if the input has also the `size` attribute, the size class should be added to the form group ([link](http://getbootstrap.com/css/#forms-control-sizes))

**Comment by stephanrauh** [comment]
I'd like to find a more simple solution. In particular, the "we can't add it for them" bit puzzles me. But I didn't find a better solution yet, so I vote for your proposal.

**Comment by MitchTalmadge** [comment]
What about creating a b:form component that simply extends a regular h:form and has the option to make it horizontal?

Horizontal form support would be great. I used to use them, but since the BootsFaces components aren't entirely compatible, I decided to just ditch them all together.

**Comment by stephanrauh** [comment]
Sounds like a good solution. We'd have to check where `@form` still works. If it does, we should do it this way.

**Comment by NicolaIsotta** [comment]
I guess this can be closed @stephanrauh since horizontal and inline forms are supported in version 1.0

**Comment by stephanrauh** [comment]
That's correct. BTW, supporting of horizontal and inline forms introduced a couple of errors which have been fixed in 1.0.1-SNAPSHOT, which will be published soon.
