### ISSUE TITLE
b:command button does not work in datatable.

### ISSUE THREAD

**Issue by jwsj** [TheCoder4eu/BootsFaces-OSP#486]
When click the button in datatable, refresh the page and not execute method action.
Below my code :

```xml
<h:form id="frm">
		<f:metadata>
			<f:event type="preRenderView"
				listener="#{CboController.getListarCbo}" />
		</f:metadata>

		<b:dataTable id="tabela" value="#{CboController.listaCbo}" var="tab"
			lang="es">

			<b:dataTableColumn label="Código">
				<h:outputText value="#{tab.codCbo}" />
			</b:dataTableColumn>

			<b:dataTableColumn label="Descrição">
				<h:outputText value="#{tab.descCbo}" />
			</b:dataTableColumn>

			<b:dataTableColumn label="Ação">
				<b:commandButton value="alt" icon="alterar-dados" ajax="true"
					action="#{CboController.redirectEdit()}">
				</b:commandButton>

			</b:dataTableColumn>
		</b:dataTable>

	</h:form>
```

**Comment by stephanrauh** [comment]
For some reason, every button has the same `name` and `id`.

**Comment by stephanrauh** [comment]
Turns out, it's a weird caching problem.

**Comment by stephanrauh** [comment]
I've uploaded a developer snapshot fixing the bug to Maven Central. See #369 on how to get it. Note that I didn't fix every bug yet. If you use input fields in your dataTable, you'll want to replace `b:dataTableColumn` by the standard `h:column`.  If you're using NetBeans or IntelliJ, your IDE probably will complain about the `label` attribute, but apart from that, thing should work better than before.

To dos left before we can close the issue:
* There seems to be a special treatment of the `submittedValue` attribute in `h:column`. We should find it and make the special treatment available to `b:dataTableColumn`.
* Talking of which: why do we need a `b:dataTableColumn` in the first place? Let's try to find a way to get rid of it. Every JSF component in the table is considered a column.

**Comment by stephanrauh** [comment]
Finished the last remaining bugs, added a demo to the sneak preview showcase (http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf) and uploaded a new developer preview version of BootsFaces to Maven Central.
