### ISSUE TITLE
<b:switch missing update attribute

### ISSUE THREAD

**Issue by mannan4net** [TheCoder4eu/BootsFaces-OSP#487]
Hello Team,
While using switch component I am facing the below issue as the update attribute is missing, screen shot is attached for reference.
![switch demo](https://cloud.githubusercontent.com/assets/21006926/17642765/47409294-6171-11e6-99bb-d0012536858f.JPG)
![switch issue](https://cloud.githubusercontent.com/assets/21006926/17642766/48b892b6-6171-11e6-9958-7b4a121697f3.JPG)

**Comment by stephanrauh** [comment]
Luckily only the taglib was affected, so it's only an IDE problem (which is annoying enough). Now it's fixed.

**Comment by stephanrauh** [comment]
In the meantime, I've uploaded the bugfix to the developer preview section of Maven Central. See #369 on how to get it.
