### ISSUE TITLE
b:switch alignment issue

### ISSUE THREAD

**Issue by jbhardwaj12** [TheCoder4eu/BootsFaces-OSP#488]
css class checkbox is applied on Switch component from core.css, this adds 10 px of top and bottom margin which causes misalignment in form. 

![image](https://cloud.githubusercontent.com/assets/11051205/17684632/cb698d20-6322-11e6-9812-549289294aeb.png)

**Comment by stephanrauh** [comment]
Might be caused by deriving the switch from the checkbox.

**Comment by MitchTalmadge** [comment]
Yep I had to use some of my own css to fix this:
```
.checkbox label.bf-no-message {
    padding-left: 0 !important;
}

.checkbox {
    margin-top: 0 !important;
    margin-bottom: 0 !important;
}
```

If I remember correctly, the switch doesn't have its own wrapper class that I could use for these modifications, so I had to use the checkbox class itself which is less than ideal, but works.

**Comment by TheCoder4eu** [comment]
Fixed the issue (now the component has a 0 margin)
