### ISSUE TITLE
CommandButton inside a Datatable not working

### ISSUE THREAD

**Issue by mannan4net** [TheCoder4eu/BootsFaces-OSP#489]
Hi Team I am trying to add a row dynamically into the datatable it is perfectly working fine, but if I want to remove a particular row having a button for in each row the actionListenor not called and unable to remove a row. However the same example with jsf working fine, but I need the datatable from bootsfaces framework.
```xml
<b:row>
<b:column col-md="12">
<b:commandButton look="success" icon="glyphicon-plus" value="" process="@this" ajax="true" immediate="true" 
update="addedItem" actionListener="#{CGHSRegistrationBean.addSocietyMaintenanceCharges}" />                                    
</b:column> 
</b:row>
<b:row>
<b:column>
<b:dataTable searching="false" paginated="false" id="addedItem" ajax="true" save-state="true" value="#{CGHSRegistrationBean.rd.societyMaintenanceChargeses}" var="item" >
<b:dataTableColumn id="a" label="Remove Row">
<b:commandButton value="k" icon="=glyphicon-minus" process="@this" ajax="true" immediate="true" update=":CGHSReg addedItem" 
actionListener="#{CGHSRegistrationBean.removeSocietyMaintenanceCharges(item)}"/>
</b:dataTableColumn>
<b:dataTableColumn id="b" label="Maitenance Head"><b:inputText value="#{item.maintenanceHead}" /></b:dataTableColumn>
<b:dataTableColumn id="c" label="Maitenance Charges"><b:inputText value="#{item.maintenanceCharges}" /></b:dataTableColumn>
</b:dataTable>
</b:column>
</b:row>
```   
The first table is from jsf and the second is from bootsfaces.
![bootsfaces datatable issue vs jsf datatable](https://cloud.githubusercontent.com/assets/21006926/17734157/16dcdc6e-6498-11e6-9393-381fd8bda284.JPG)

**Comment by stephanrauh** [comment]
You're lucky - I've fixed this bug last weekend. Please try the latest Snapshot of BootsFaces-1.0.0 and report back whether it fixes your problem or not.

See #369 on how to get the snapshot.

**Comment by mannan4net** [comment]
Thanks master, I will diffidently check and update to you.

**Comment by mannan4net** [comment]
Hi Master I am unable to use the mentioned snapshot, hence not able to check the fix., Or please let me know the development/beta version of 1.0.0 of bootsfaces url to download.

**Comment by stephanrauh** [comment]
The fault is on my side. For some reason, I've confused the version numbers. The correct version number is 0.9.2-SNAPSHOT (located at https://oss.sonatype.org/content/repositories/snapshots/net/bootsfaces/bootsfaces/0.9.2-SNAPSHOT/).

**Comment by Koster2013** [comment]
I tested it with version 0.9.2. It doesn't work. The commandbutton work only outside the datatable...

**Comment by Koster2013** [comment]
That works for me :)

```
<h:column>
					<f:facet name="header">Download</f:facet>
					<b:commandButton value="button" 
						action="#{homeView.download}">
					</b:commandButton>
				</h:column>
			</b:dataTable>
```

**Comment by stephanrauh** [comment]
I'm a bit confused. What does work and what does not? Reading your posts, I understand using `b:dataTableColumn` doesn't work, while using the some command button with `h:column` does work. Did I get you right?

**Comment by LuisToro** [comment]
Work for me too.!! Thx stephanrauh. I have a question, when release the next stable version?

**Comment by stephanrauh** [comment]
Soon. Maybe even end of this month, although we've still got a lot of open bugs and little time to close them. But still, it's time to publish a new release.
