### ISSUE TITLE
Add documentation of b:socialShare

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#492]
It seems this page is still missing.

**Comment by dqdb55** [comment]
Hi Stephan
Where can I find an example of how to use b:socialShare? Is this component finished?

**Comment by stephanrauh** [comment]
Yes, the component is finished. But for some reason, we forgot to document it.

@asterd Can you send us an example how to use the component? Thanks in advance!

**Comment by asterd** [comment]
@stephanrauh documentation done! I've also update the component with some bug fix.

**Comment by dqdb55** [comment]
And where can I find this documentation? I am not sure where should I look for it...

**Comment by stephanrauh** [comment]
http://www3.bootsfaces.net/Showcase/bootstrap/SocialShare.jsf
That's a link to our developer showcase, so it's little wonder you didn't find it. It's sort of unofficial. More to the point, it's a sneak preview of the upcoming version. AFAIK, we didn't modify the social share buttons in the current developer version, so the sneak preview should also apply to the BootsFaces version you're already using.

**Comment by dqdb55** [comment]
Thanks for info.
I've spent 2 hours with no results. I don't know what is missing in docs or
whether somewhere is a bug or not but I was not able to run this
component...

**Comment by dqdb55** [comment]
I use version

0.9.1

**Comment by dqdb55** [comment]
Previously I tried to find info about this component here:
http://showcase.bootsfaces.net/ , but with no results.

**Comment by stephanrauh** [comment]
The documentation won't make it to the official showcase until we've published the next version of BootsFaces. However, I'm sure the component already works as described in the developer preview showcase.

**Comment by stephanrauh** [comment]
I just checked with version 0.9.1: layout is a bit odd, and the option to disable the data protection button doesn't work. Maybe that's what stopped you from getting the component work. The text of the data protection button is white - probably not the best choice on many web sites.

But the functionality is there:
```xml
<b:socialShare shares="twitter,linkedin" 
               showLabel="true" show-count="false"
               text="BootsFaces rocks!" block-message="Click to unblock the share buttons" />
```
![image](https://cloud.githubusercontent.com/assets/3045767/18609689/6173a860-7d08-11e6-825d-a88821adc543.png)
