### ISSUE TITLE
Add "after" facet to inputs

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#493]
It would be useful to have an "after" facet in all the components who generate a form-group. The contents of this facet (for example, a `<b:message/>` or an `help-block`) should be rendered inside the form-group, but after the input/select/input-group.

**Comment by stephanrauh** [comment]
Would you mind to show us an example demonstrating your use case? We can add the facet, but the documentation looks nicer if we can explain why we added it :).

**Comment by stephanrauh** [comment]
related to #511.

**Comment by NicolaIsotta** [comment]
Actually, in my case, this is related to horizontal forms (#485) . I'd like to achieve a layout where error messages and/or description test can be shown next to an input.
Just an easy example taken from web:
http://i.stack.imgur.com/ToPRZ.png

**Comment by stephanrauh** [comment]
related to #614. In fact, #614 is the more general solution.

**Comment by stephanrauh** [comment]
Solved by #682 and #685.
