### ISSUE TITLE
carousel not starting to slide automatically on asynchronous page navigation

### ISSUE THREAD

**Issue by mweber96** [TheCoder4eu/BootsFaces-OSP#495]
If a SPA contains a page with a b:carousel and you're switching the pages via AJAX without a complete page refresh then the carousel won't start sliding automatically. However, it will continue sliding if you manually slid to another carouselitem.

Like mentioned by Stephan Rauh on my stackoverflow question [SPA approach not working if page contains b:carousel](http://stackoverflow.com/questions/39128418/spa-approach-not-working-if-page-contains-bcarousel) the carousel needs to be started manually with JavaScript.

An example is provided via the repository I posted on my stackoverflow question: [Repository related to stackoverflow question](https://github.com/mweber96/stackoverflow39128418)

I hope this issue is able to contribute to this outstanding project!

**Comment by stephanrauh** [comment]
Yes, this ticket is a valuable contribution to the project, even if we didn't manage to address it yet. Thanks!

**Comment by TheCoder4eu** [comment]
@mweber96 
If I understand well , with AJAX the page does not load, instead the DOM is changed replacing content.
The Carousel does the following on Page loading:

```
    $('[data-ride="carousel"]').each(function () {

      var $carousel = $(this)

      $carousel.carousel($carousel.data())

    })
```
It starts a carousel if it has a `data-ride="carousel"` attribute.
In your case this `on('load', function () )` is not triggered.

This is not a bug, but simply requires the developer making an additional effort.
Unfortunately, tracking a DOM change is not a trivial task, you should use a 
http://developer.mozilla.org/en/docs/Web/API/MutationObserver

you can find an example here:

http://stackoverflow.com/questions/3900151/is-there-a-jquery-event-that-fires-when-a-new-node-is-inserted-into-the-dom
