### ISSUE TITLE
Some problem when I use BootsFaces

### ISSUE THREAD

**Issue by ragrok** [TheCoder4eu/BootsFaces-OSP#498]
Hi, guys. I encounter some problem when I use BootsFaces.  
### First is how to make label and input on same line
- Like this :

``` xml
<b:container fluid="true">
        <h:form styleClass="form-horizontal">
            <b:row>
                <b:column styleClass="form-group">
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                </b:column>
                <b:column styleClass="form-group">
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                    <b:label col-md= "3" text="">Pri.Applicant</b:label>
                    <b:inputText col-md= "3">
                    </b:inputText>
                </b:column>
            </b:row>
            <b:row>
                <b:column col-md="6">
                    <b:panel title="Panel title">Panel content</b:panel>
                    <b:panel title="Panel title" look="primary">Panel content</b:panel>
                </b:column>
                <b:column col-md="6">
                    <b:panel title="Panel title" look="success">Panel content</b:panel>
                    <b:panel title="Panel title" look="info">Panel content</b:panel>
                </b:column>
                <b:column col-md="6">
                    <b:panel title="Panel title" look="warning">Panel content</b:panel>
                    <b:panel title="Panel title" look="danger">Panel content</b:panel>
                </b:column>
            </b:row>
        </h:form>
    </b:container>
```
- page render:
  ![page render](https://cloud.githubusercontent.com/assets/16792321/18240680/cdc72682-737f-11e6-9b61-e527cb41749e.png)
### Second is how to redirect or forward to next page when I click navLink tag.
- Java code 

``` java
1. CtrlLoginBean.java
 public void redirectInbox(){
        LOGGER.debug("come in redirectInbox");
         Util.redirect(Constants.STATIC_URL+"/inbox.xhtml");
    }

    public String returnInboxUrl(){
        LOGGER.debug("come in redirectInbox");
        return Util.returnUrl(Constants.STATIC_URL+"/inbox.xhtml");
    }
2. Util.java
public static void redirect(String web) {

        try {
            Util.LOGGER.debug("redirect to []", web);
            ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
            context.redirect(returnUrl(web));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static void forward(String web) {
        try {
            Util.LOGGER.debug("forward to []", web);
            ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
            context.dispatch(context.getRequestContextPath() + web);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static String returnUrl(String web) {
        Util.LOGGER.debug("redirect to []", web);
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        return context.getRequestContextPath() + web + Constants.AFTER_REDIRECT;
    }
```
-  nav.xhtml page code

``` xml
<h:form styleClass="navbar-form navbar-right">
        <b:navBar brand="Project name" brandHref="#" inverse="true"
            fixed="top" fluid="true">
            <b:navbarLinks pull="right">
                <b:navLink value="Inbox" >
                  <f:facet name="Inbox">
                    <b:button action="#{login.redirectInbox}"></b:button>
                  </f:facet>
                </b:navLink>
                <b:navLink value="Settings" action="#{login.returnInboxUrl}" ></b:navLink>
                <b:navLink value="Profile" href="#{login.returnInboxUrl}"></b:navLink>
                <b:navLink value="Help" href="#"></b:navLink>
            </b:navbarLinks>
            <div class="form-group" style="width:30%;float:right;margin-top:10px;">
                <b:inputText  fieldSize="sm" >
                  <f:facet name="append">
                  <h:outputText value="Search" />
            </f:facet>
                </b:inputText>
            </div>
        </b:navBar>
    </h:form>
```

**Comment by ragrok** [comment]
###　Datatable can't display search box and other feature
-  customer.xhtml
```
<b:container fluid="true">
		<h:form>
			<b:row>
				<b:column>
					<b:dataTable value="#{userBean.listUserInfo}" var="userInfo"
						searching="true" page-length="5" page-length-menu="5,10,20">
						<h:column value="#{userInfo.id}" />
						<h:column value="#{userInfo.age}" />
						<h:column value="#{userInfo.email}" />
						<h:column value="#{userInfo.school}" order="asc" />
						<h:column value="#{userInfo.telephone}" label="Engine Power (hp)" />
					</b:dataTable>
				</b:column>
			</b:row>
		</h:form>
	</b:container>
```
-  Page render
![qq 20160906092805](https://cloud.githubusercontent.com/assets/16792321/18259322/6208fa2e-7415-11e6-9260-d779783df255.png)
-  Other Information you can check [my project](https://github.com/ragrok/spring_jsf_mybatis) at github.

**Comment by stephanrauh** [comment]
Sorry for answering so late. I remember to have answered you, but obviously, something went wrong, so my answer didn't make it to GitHub.

First of all: that's two different topics. I'd prefer to see two different tickets for it. That makes our life easier.

As for the input fields: did you already try the `label` attribute of `b:inputText`? If you set `inline="true"` and - depending on your web.xml - `render-label="true"`, it does exactly what you want to achieve. Unfortunately, until BootsFaces 0.9.1, we generate HTML code that doesn't precisely match the Bootstrap template, so there are some layout glitches. In particular, you can't define the `col-xx-yy` attribute of the label and sometimes the labels aren't vertically aligned precisely with the input field. We plan to fix that with the next BootsFaces version (probably 1.0).

**Comment by stephanrauh** [comment]
As for the data table: it looks like the JavaScript code initializing the data table is never run (or fails). However, I couldn't see how the data table is used in your project (at least not by just reading the source code). Did you modify the project in the last seven days, since your opened the ticket? Did you maybe even solve the problem?

**Comment by ragrok** [comment]
Sorry, now I want to refactory my simple demo, previous issues have't enough time to solved. when I refactory front interface and encounter them, I will spend some time to solve it.

**Comment by ragrok** [comment]
I hope BootsFaces achieve more and more BootStrap features. Components Based Development join popular front framework is very cool.

**Comment by stephanrauh** [comment]
More and more Bootstrap features... yeah, sure, what's missing?

**Comment by ragrok** [comment]
Haha, It means project have more and more customer component and BootStrap Layout and widget.

**Comment by stephanrauh** [comment]
Development is starting to slow down because our toolbox is fairly complete now. We still add components, but they start to cover more exotic use cases. As for the customer components: well, I guess you're the customer, so you've just offered to implement new components :).

(Jokes aside, if you want to add a component, your pull request is always welcome).

**Comment by ragrok** [comment]
Haha,this is interesting joker.In fact, I am javaweb developer.In recent times, I learning jsf life-cycle and try to making customer component, so, add customer components isn't a difficult things.

**Comment by ragrok** [comment]
This article [java-uis-state-of-javaserver-faces-jsf-in-2016](http://www.beyondjava.net/blog/java-uis-state-of-javaserver-faces-jsf-in-2016/#summary) make me very affect.I know so many people consist on their be 
interesting things. Good lucking, @stephanrauh .

**Comment by stephanrauh** [comment]
In the meantime, we've solved the first issue. We didn't include it in the official showcase, but you can see how to implement horizontal or inline layouts here: http://www3.bootsfaces.net/Showcase/forms/horizontalForms.jsf
https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/forms/horizontalForms.xhtml

**Comment by stephanrauh** [comment]
It took me a while to understand the second question. 

- If you're using `<b:navCommandLink>`, you can navigate by defining an `action`. This is a method of the Java bean which returns the URL of the JSF page to navigate to.
- Likewise, if you're using `<b:navLink>`, you can navigate by defining the `href`. The value of the attribute is the URL of the JSF page to navigate to. Of course, this URL can be evaluated in a Java bean method on the server side.
- Alternatively, the `redirect()` method should work, too. I don't recommend it, but under certain circumstances its useful, too. For instance if you want to use typesafe navigation with Deltaspike (see http://www.beyondjava.net/blog/type-safe-navigation-in-jsf/).


b:navLink value="Settings" action="#{login.returnInboxUrl}" >
