### ISSUE TITLE
Add Initial PatternFly support

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#499]
PattenFly is a UI framework for enterprise web applications:

http://www.patternfly.org/

it is developed by RedHat and is based on Bootstrap.

This Task is intented in introducing initial support to PatternFly treating it as a "Special" Theme.

**Comment by TheCoder4eu** [comment]
Testing

**Comment by asterd** [comment]
Cool! you want also to add support to its custom components? I see that they have a lot of custom components (some of them we already have of course).. but maybe we can evaluate some additional items isn't it?

**Comment by stephanrauh** [comment]
First impression: looks promising! I've updated the Maven files today :).

**Comment by TheCoder4eu** [comment]
Thanks @asterd , I see you implemented Spinner and Touchspin!
Sorry for the late answer, I think it would be nice to support their components too(not all), there are just a bunch missing. (See Excel)

**Comment by TheCoder4eu** [comment]
Final Tests started for basic PatternFly support.

**Comment by TheCoder4eu** [comment]
Updated PatternFly version to v3.13.0

**Comment by TheCoder4eu** [comment]
Final Tests for basic PatternFly support: wip.

**Comment by TheCoder4eu** [comment]
Closing the Issue because the minimum Goals for initial support to PatternFly treating it as a "Special" Theme are achieved.
