### ISSUE TITLE
Netbeans cannot find "value"-attribute on DataTableColumn

### ISSUE THREAD

**Issue by rubiktubik** [TheCoder4eu/BootsFaces-OSP#510]
Hi i'am using Bootsfaces 0.9.1
I can use every component without problem except
the `<b:DataTableColumn/>` in a `<b:dataTable/>` Netbeans shows me the
following message:

> The attribute value is not defined in the component dataTableColumn

I included the `xmlns:b="http://bootsfaces.net/ui"` tag and use this component as follows:

```html
<b:dataTable value="#{customerBean.allCustomers()}" var="customer" lang="de">
        <b:dataTableColumn value="#{customer.firstName}" label="Vorname"></b:dataTableColumn>
        <b:dataTableColumn value="#{customer.secondName}" label="Nachname"></b:dataTableColumn>
        <b:dataTableColumn value="#{customer.phoneNumber}" label="Telefon"></b:dataTableColumn>
        <b:dataTableColumn value="#{customer.email}"></b:dataTableColumn>
        <b:dataTableColumn value="#{customer.address.street} #{customer.address.houseNumber}, #{customer.address.city.zipCode} #{customer.address.city.name}" label="Adresse"></b:dataTableColumn>
</b:dataTable>
```

The weird thing is that in the browser everything works as expected! Only Netbeans shows the error!

Do i found a bug or i'am doing something wrong?

**Comment by stephanrauh** [comment]
Sound like a faulty taglib file. Most of the time I use Eclipse, which is less strict. The JSF framework itself doesn't evaluate the taglib attributes, they are only used by the IDEs.

**Comment by rubiktubik** [comment]
thank you for the quick answer! You mean its a bug in netbeans?

**Comment by stephanrauh** [comment]
Actually, it's a feature. Netbeans tries to enforce correct JSF code. However, it's one of those annoying features that tend to stand in your way. JavaScript frameworks like Angular or Polymer add attributes to existing HTML tags all the time. I suspect Netbeans forbids these attributes, too. It would be nice if there was an option to disable this feature. However, I haven't found this feature (but maybe I didn't look thoroughly enough).

**Comment by stephanrauh** [comment]
I've added the "value" attribute to the taglib and uploaded a developer preview BootsFaces-0.9.2-SNAPSHOT to Maven Central. See #369 on how to get it.
