### ISSUE TITLE
DateTimePicker sets hour to 12

### ISSUE THREAD

**Issue by Najarana** [TheCoder4eu/BootsFaces-OSP#512]
Whatever time i choose the hour is always set to 12am when trying to send the date to my backingbean

**Comment by stephanrauh** [comment]
@asterd Dario, does this ring a bell? Can you reproduce this error, or have you encountered it before?

**Comment by Najarana** [comment]
Found the bug in DateTimePicker. This seems to have been already fixed in 0.9.2-SNAPSHOT but in 0.9.1 there was a line `cal.set(11,12)` which obviously meant that hour field was always set to 12.

**Comment by stephanrauh** [comment]
That's great news! Thanks for reporting us back!
