### ISSUE TITLE
b:datepicker not work with custom validator and attrs

### ISSUE THREAD

**Issue by sergio11** [TheCoder4eu/BootsFaces-OSP#516]
Hi,

First, thank you for the great work you have done with this library.
I am using the datepicker component into the modal. I am developing a custom validator for validate if the date is on the range.

```
<b:datepicker 
    id="birthday"
    mode="popup-icon"
    col-md="12"
    tooltip="La fecha de nacimiento" 
    tooltip-position="bottom"
    required="true">
       <f:convertDateTime pattern="dd/mm/yy" />
        <f:validator validatorId="dataRangeValidator" />
        <f:attribute name="minDate" value="01/01/1980" />
        <f:attribute name="maxDate" value="#{now}" />
</b:datepicker>
```

When deploying the app I get the following error:
![errorbootfaces](https://cloud.githubusercontent.com/assets/6996211/19169455/e558c276-8c14-11e6-8799-f4c25cfc1628.PNG)

If I remove the <f:attribute> components, not crash.

I am using Bootsfaces 0.9.2-SNAPSHOT.
thanks.

**Comment by stephanrauh** [comment]
¡Hola Sergio!,

I've found and solved two bugs that look almost, but not quite, like your bug report. I've also compiled a new BootsFaces-0.9.2-SNAPSHOT to Maven Central. Would you mind to give the new version a try and report us back? 

If the problem hasn't been solved, please give us a more complete "reproducer". For instance, you didn't mention how the `dataRangeValidator` is defined.

By the way, I'm a bit surprised that the `f:attribute` bit works. As far as I know, we didn't document it.

Finally, I'd like to mention that we intend to declare the `b:datePicker` deprecated in favor of the `b:dataTimePicker`. The latter is a date picker that doesn't need jQueryUI, so it meets the requirements of many developers better (one library less!).

**Comment by sergio11** [comment]
Hi,
thanks for answering.
I downloaded the dependency again. It does not appear mistake, but the switch is disabled when I insert the attr element.
I can not select any date nor change of month.

![error](https://cloud.githubusercontent.com/assets/6996211/19249145/27f90e7a-8f34-11e6-9a07-a547ee1ae9b0.PNG)

I also attached the code validator:

```
FacesValidator(value = "dataRangeValidator")
public class DateRangeValidator implements Validator {
    
    private final static String PARAM_MIN_DATE = "minDate";
    private final static String PARAM_MAX_DATE = "maxDate";
    

    @Override
    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        
       DateTimeConverter converter = (DateTimeConverter) ((UIInput)component).getConverter();
       Date valueDate = (Date) value;
       Map<String, Object> attrs =  component.getAttributes();
       if(attrs.containsKey(PARAM_MIN_DATE)){
           String minDateString = (String)attrs.get(PARAM_MIN_DATE);
           Date minDate = (Date) converter.getAsObject(context, component, minDateString);
           if(minDate.after(valueDate)){
               String message = "La fecha " + converter.getAsString(context, component, value) + " es anterior al límite " + minDateString;
               FacesMessage facesMessage = new FacesMessage(message);
               facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
               throw new ValidatorException(facesMessage);
           }
       } else if(attrs.containsKey(PARAM_MAX_DATE)){
           String maxDateString = (String)attrs.get(PARAM_MAX_DATE);
           Date maxDate = (Date) converter.getAsObject(context, component, maxDateString);
           if(maxDate.before(maxDate)){
               String message = "La fecha " + converter.getAsString(context, component, value) + " es posterior al límite " + maxDateString;
               FacesMessage facesMessage = new FacesMessage(message);
               facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
               throw new ValidatorException(facesMessage);
           }
           
       }
     
    }
    
}
```

I feel very good about the new DateTimePicker. 
I think that the less jQuery UI is better.

thanks and greeting.

**Comment by TheCoder4eu** [comment]
@sergio11 could you try our last repository version? Did you see some Javascript errors?

**Comment by TheCoder4eu** [comment]
We are closing this Issue, if you still experience this problem please open a new one.
