### ISSUE TITLE
Site Down from couple of hours 

### ISSUE THREAD

**Issue by subodhcjoshi82** [TheCoder4eu/BootsFaces-OSP#517]
Hi Please fix the issue ASAP  this site http://showcase.bootsfaces.net/Examples/ is down from Last 4hours 

> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /Examples/.
> 
> Reason: Error reading from remote server

**Comment by stephanrauh** [comment]
Showcase and examples are up and running again. Thanks for reporting the error!
