### ISSUE TITLE
Unnecessary dataTable summary info

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#518]
This isn't urgent or anything, but I figured I'd bring it up. When disabling pagination on a `b:dataTable`, it still says "Showing x to y of x entries" at the bottom. Is this necessary? Example:

![image](https://cloud.githubusercontent.com/assets/8848080/19207346/49dc4a0e-8cad-11e6-8f0e-e53a69a1f94e.png)

Wouldn't all the results be displayed all the time? I can't decide if it'd be best to leave or remove the text, so I'm just curious what others think.

**Comment by zhedar** [comment]
Agreed. We probably shouldn't show that, if no pagination is used. Maybe we should even make it a toggleable option to show the entrycount?

**Comment by zhedar** [comment]
As far as I saw there is no direct way in the JS api to do that. However, we could always hide the `datatable_info` element of the current datatable via css. Not the most elegant solution, but it may work.

**Comment by mtvweb** [comment]
Option is there. Workaround: custom-options = "info:false"

**Comment by stephanrauh** [comment]
Thanks for giving us the hint, @mtvweb ! Now both the paginator and the info are hidden. I didn't implement an option to show the one while hiding the other. If someone needs that, a CSS statement will probably do the trick.

**Comment by mtvweb** [comment]
This change breaks my project. 👎 

I would prefer a separate option for the info to have more flexibility. My project uses a table with a limited range of lines to show them all without pagination, but I need the information about the contained lines.

Also I use some tables in forms, showing a few lines with pagination, but without information to decrease the amount of information in it. i.E. a table with a **_pageLength = 5, pagination = true, info = false._** In this case it is enough to have a page indicator showing that there is another page with lines.

**Comment by stephanrauh** [comment]
After merging your PR #620, your project should be alive and kicking again :).
