### ISSUE TITLE
commandButton ajax "onStart"

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#519]
Is there an equivalent of "onStart" or something similar for commandButtons? (opposite of onComplete) My goal is to create a loading wheel when ajax starts, and make the wheel go away when ajax ends. I am able to do this with f:ajax, but I can't figure it out with b:commandButton's ajax. I can't use onClick because it overwrites the ajax code that would be generated by BootsFaces

**Comment by MitchTalmadge** [comment]
onFocus kinda works, but if I click down on a button and release somewhere else, the loading wheel never goes away because the ajax isn't triggered.

**Comment by MitchTalmadge** [comment]
I came up with a hacky solution:

`onfocus="focused = true;" onmouseup="if(focused) loading_start(); focused = false;"`

**Comment by stephanrauh** [comment]
It seems we've omitted this feature because we didn't see the use case yet. Maybe this JavaScript snippets helps you. It intercepts every AJAX request, so you have to check the source of the request, too.

```javascript
jsf.ajax.addOnEvent(function (data) {
		if (data.status === 'begin') {
			requestOngoing = true;
			onCompleteCallbacks = [];
		}
		if (data.status === 'complete') {
			destroyScopes(data);
		}
		if (data.status === 'success') {
			handleAjaxUpdates(data);
			requestOngoing = false;
		}
	});
```

**Comment by MitchTalmadge** [comment]
@stephanrauh That worked great! Thanks so much, I had no idea you could do that.

**Comment by TheCoder4eu** [comment]
@stephanrauh we can close this issue?

**Comment by stephanrauh** [comment]
Let's add the solution described above to the documentation before closing the ticket.

**Comment by stephanrauh** [comment]
Just finished documenting the low-level AJAX API.
