### ISSUE TITLE
hidden-md never shows up

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#523]
Using `<b:column colMd="0">`, `hidden-md` never appears in the classes. In fact, quite the opposite happens, and `col-md-12` shows up. (Only if colMd is the only attribute. If colXs is specified, for example, then `col-xs-#` will appear and not `col-md-12`.) xs, sm, and lg work fine.

**Comment by stephanrauh** [comment]
It seems setting using zero is an undocumented feature. I fixed the bug nonetheless. I just hope I didn't break too many programs relying on the bug :(.

BTW, the additional `col-md-12` seems to be important. It's added to every size, not only `md`. So I added it to `col-md="0"´, too.

**Comment by stephanrauh** [comment]
@TheCoder4eu @asterd Please have a look at my bugfix. I want to be sure I didn't break anything. Thanks!

BTW, I've documented these features at the `basic.xhtml`.
