### ISSUE TITLE
using the var name "resource" in a dataTable does not work

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#524]
If you use a var named "resource" in a dataTable, it will not work. The datatable will render, but trying to use the var will just give you completely incorrect (empty) data. Must be some kind of internal conflict. I found this because one of my entities are called resource :P

**Comment by stephanrauh** [comment]
That's an interesting bug (and one I can confirm). I suppose that's because `resource` is a reserved name in EL 2.0+. It's usually used to find a file:

```xml
<h:graphicImage value=”#{resource[‘images:Planets.gif’]}”/>
```

I don't think BootsFaces can do something about that, so I'll close the bug. Thanks a lot for reporting it nonetheless!

**Comment by MitchTalmadge** [comment]
Oops, forgot about that. Thanks!
