### ISSUE TITLE
f:setPropertyActionListener does not work inside a b:dataTable

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#525]
Hello, I trying to use the f:setPropertyActionListener inside a b:dataTable, but it DOES NOT call the target bean function. If I put the f:setPropertyActionListener out of the b:dataTable so it works perfectly, but I need it inside to set the current line (object) to the bean, and after that exclude it. 
Is it a bug? Are there another ways to do it? Please help me.

Thank you very much,
Ruan Felisky.
[sources.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/530012/sources.zip)

**Comment by ruanfelisky** [comment]
I realized that I can use the h:column instead of b:dataTableColumn, but it would be nice if we could use the second one too. Anyway, the h:column works in this case and I could solve my problem :)

**Comment by TheCoder4eu** [comment]
Hi Ruan,
happy you found a solution that suits your needs.
We'll investigate this corner case.

**Comment by stephanrauh** [comment]
@ruanfelisky Just for the sake of completeness: I know it's a far shot, but I've fixed quite a few bug concerning rows in a data table, so there's a faint chance I've already solved your problem. Would you mind to test the current BootsFaces-1.0.0-SNAPSHOT? See #369 on how to get it.

Thanks in advance,
Stephan

**Comment by ruanfelisky** [comment]
Hi @stephanrauh ,

I've just tested the BootsFaces-1.0.0-SNAPSHOT and the problem regarding the f:setPropertyActionListener is solved! 

Thank you very much!
Ruan

**Comment by TheCoder4eu** [comment]
Solved in v1.0.0
