### ISSUE TITLE
set width b:datatablecolumn is not working

### ISSUE THREAD

**Issue by NetoDevel** [TheCoder4eu/BootsFaces-OSP#527]
```
 <b:dataTableColumn label="Ação" style="width:50px !important">
        <center>
                 <b:commandButton icon="time"></b:commandButton>
        </center>
</b:dataTableColumn>
```

**Comment by stephanrauh** [comment]
Just implemented the attributes `style` and `style-class`. They influence both the look of the content column and the header cell. If both `style` and `header-style` or `content-style` are provided, the more specific style wins. The same applies to `style-class`, `header-style-class` and `content-style-class`. I've also uploaded a new developer preview - see #369 on how to get it.
