### ISSUE TITLE
Missing JavaScript handler on non-AJAX NavLinks and NavCommandLinks

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#534]
Due to a side effect of another bug fix, the `onclick` attribute of `b:navLink` and `b:navCommandLink` isn't rendered if the attribute `ajax` is set to false.

**Comment by stephanrauh** [comment]
Done.

**Comment by MitchTalmadge** [comment]
Your fixes solved my problems, thank you!

**Comment by stephanrauh** [comment]
Always glad to help!

**Comment by jottyfan** [comment]
Same on my side. All panels do toggle now, the result of an ajax=false navCommandLink is no longer a partial response but a complete html page. Good work, thanks! Looking forward to have a release 0.9.2 soon (please don't let us wait for 1.0.0 struggle with that annoying bug).
