### ISSUE TITLE
Problem with <b: panelGrid>

### ISSUE THREAD

**Issue by sergio11** [TheCoder4eu/BootsFaces-OSP#535]
Hi,

I wanted to show two panels in each row. I set the **panelGrid as 6,6** for medium desktop resolution but I do not get the desired result.

Here I show the result (the screen is larger than it looks):

![panel_grid_error](https://cloud.githubusercontent.com/assets/6996211/19836125/d5c06a68-9e97-11e6-9e87-727af4ae342d.PNG)

Here I put the code:
```
<b:row id="results" style="margin-top: 1rem">
    <b:messages />
        <b:panelGrid rendered="${not empty searchTopicBean.topicsSelected}" colSpans="6,6" size="md">
             <ui:repeat var="topic" value="#{searchTopicBean.topicsSelected}">
                    <b:panel span="6" title="Result for topic #{topic}" collapsible="false" look="info">
                         <b:row>
                           <p:chart type="donut" model="#{chartBean.donutCharts.get(topic)}" style="width:70%;height:300px;margin: 0 auto;" />
                          </b:row>
                          <ui:remove>
                              <b:row>
                                 <p:chart type="pie" model="#{chartBean.pieCharts.get(topic)}" style="width:70%;height:300px;margin: 0 auto;" />
                              </b:row>
                          </ui:remove>
                    </b:panel>
             </ui:repeat>
        </b:panelGrid>
  </b:row>
```

I am using bootsfaces 0.9.2-SNAPSHOT and Primefaces 5.3.

Thanks and greetings

**Comment by stephanrauh** [comment]
I'm afraid we can't solve this problem. It's caused by `ui:repeat`. From the data structure point of view, the panel grid contains only a single component. BootsFaces doesn't recognize that `ui:repeat` represents two components. Maybe you can solve this by using `c:forEach`, but of course, this approach has other disadvantages.
