### ISSUE TITLE
Datepicker date pattern localized

### ISSUE THREAD

**Issue by sescde** [TheCoder4eu/BootsFaces-OSP#538]
I'd like to use datepicker. I added the following code:

```xml
<div>
  <p:outputLabel for="spieldatum" value="Spieldatum:" styleClass="control-label" />
  <b:datepicker value="#{antrag.spieldatum}" locale="de" id="spieldatum">
  </b:datepicker>
</div>
`

If I click on the datepicker and select a date, I get it formatted as "dd.mm.yy" but I want it to look like "dd.mm.yyyy".
Is there any chance to change the display pattern? I found no parameter so far.

**Comment by sescde** [comment]
Found a hint in #392 
attribute **dateFormat** is not documented on http://showcase.bootsfaces.net/jquery-ui/datepicker.jsf
Where can I get a full overview of usable attributes of datepicker?

**Comment by zhedar** [comment]
Sorry for the late answer, but until now I wasn't really able to provide a full answer. However, I will look into this as my next priority.

Additionally to the attibutes documented in the showcase there are also `minDate`, `maxDate`, `dateFormat`, `lang` and `disabled`.

As we're using the api of the underlying jqueryUI DatePicker [here's more info](https://api.jqueryui.com/datepicker/) about the eventual input format.

**Comment by stephanrauh** [comment]
To dos:

- add both attributes `locale` and `date-format` to the bootsfaces.jsfdsl
- document them in the showcase
- run tests

@sescde Answering your question, you're right: the `date-format` takes the format of the `SimpleDateFormat` as a parameter. If it's omitted, the locale defines the format. By default, `DateFormat.SHORT` is used, with a minor modification: if the month and the year takes a single digit in the default format, it's replaced by the two-digit version.

**Comment by stephanrauh** [comment]
We've deprecated the `<b:datePicker>` in favor of the `<b:dateTimePicker>`. So let's close the ticket.
