### ISSUE TITLE
Get rid of <url-pattern>/javax.faces.resource/*</url-pattern>

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#54]
Not sure if it's possible at all - but we should investigate how we can get of the <url-pattern>/javax.faces.resource/*</url-pattern> line in the web.xml. Judging from the issues, it's a major source of mistakes.

**Comment by TheCoder4eu** [comment]
Not sure if it is possible too, it is needed by the custom UnmappedResourceHandler (à la OmniFaces)...
But we can document this better( I have an open issue for that).
Anyway in my test app with just the jar, in my web.xml I just have:
```   <context-param>
        <param-name>BootsFaces_USETHEME</param-name>
        <param-value>true</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>/page/*</url-pattern>
    </servlet-mapping>
```

and it works perfectly...

**Comment by stephanrauh** [comment]
I added the documentation to the quickstart.jsf page of BootsFacesWeb.

I'd still like to solve the root problem, but for the moment, you can safely post-pone it to the next version.

**Comment by stephanrauh** [comment]
It seems we don't need the ```UnmappedResourceHandler``` at all if the ```url-pattern``` is configured correctly. Maybe it's an issue with multiple ```url-pattern```s. My suggestion is to use this configuration:
``` XML
   <context-param>
        <param-name>BootsFaces_USETHEME</param-name>
        <param-value>true</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.jsf</url-pattern>
     </servlet-mapping>
```
