### ISSUE TITLE
Ajax b:navLink triggers a Bootstrap CSS issue

### ISSUE THREAD

**Issue by traxtech** [TheCoder4eu/BootsFaces-OSP#540]
Hi!

I have a problem with Ajax b:navLink.

**Expected:** Ajax b:navLink have a mouse pointer cursor
**Actual:** Ajax b:navLink have a mouse text cursor
**Preliminary analysis:** Bootstrap have a CSS issue, it requires links to have an href value to render correctly the mouse cursor. When using b:navLink with Ajax, no href is rendered, and it triggers the bootstrap issue.
**Possible solution 1:** When rendering an Ajax b:navLink, set href="#" (may trigger some weird issues ?)
**Possible solution 2:** add a bit of CSS for this specific case

**Comment by stephanrauh** [comment]
Interesting. I didn't notice that yet. Probably you're right: Bootstrap doesn't expect `navlinks` without `href`, so it doesn't cope with them. I vote for solution 2. As a workaround, simply add `style="cursor:pointer"` to your navLink.

**Comment by stephanrauh** [comment]
I wonder if this affects every component featuring AJAX?

**Comment by stephanrauh** [comment]
I've uploaded BootsFaces-1.0.0-SNAPSHOT containing a bug fix to Maven Central. See #369 on how to get it. Please test it and report back if you're not satisfied. If you're unhappy with my bug fix, we'll reopen the issue.

Thanks in advance
Stephan
