### ISSUE TITLE
how to set lang pt-br in datatable?

### ISSUE THREAD

**Issue by NetoDevel** [TheCoder4eu/BootsFaces-OSP#542]
I'm trying to put my datatables in the Portuguese language, and I'm not getting.

**Comment by mfasouza** [comment]
Hi NetoDevel, you can put a JSON into project resource folder
(Example: WEB-INF/resource/lang/pt-br.json)
Load the JSON with resource function of JSF in the CustomLagURL 
(Example: <b:dataTable customLangUrl="#{resources['lang/pt-br.json']}">. 
This site https://datatables.net/plug-ins/i18n/ has JSON files of language. I'm sorry by my english, it's bad!

**Comment by ruanfelisky** [comment]
Hi NetoDevel, you can also download it from cdn, like in this example bellow:

<b:dataTable value="#{myBean.values}" var="test" customLangUrl="//cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json">

**Comment by NetoDevel** [comment]
@mfasouza and @ruanfelisky 

downloaded the translation, what to do?
the lang attribute datatable the bootsface, I place the json?
You could make a simple demonstration?

Thank you

**Comment by mfasouza** [comment]
@NetoDevel the example of @ruanfelisky  you don't need download/save the file! Beacuase the tag
**<b:dataTable customLangUrl="//cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json">**
will find the file in the cloud and translate the dataTable for you..

Well, about my suggestion. You have a physical file and you can set how you want the table labels..
In your **web.xml** you can define a local repository :
_<context-param>
  		<param-name>javax.faces.WEBAPP_RESOURCES_DIRECTORY</param-name>
  		<param-value>/WEB-INF/resources</param-value>
</context-param>_
And your pages, you use the tag **<b:dataTable customLangUrl=#{resource['/pt-br.json']}**

**Comment by stephanrauh** [comment]
Actually, you don't need to set the context parameter unless you really want to hide the translation file in the WEB-INF folder. By default, resources searched in the `resources` folder of your context root. In Maven project, this is usually `src/main/webapp/resources`.

**Comment by stephanrauh** [comment]
I've added some documentation in our showcase. See the developer preview at http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf and scroll down to "Internationalization". The example below is a live demo using both the built-in files of BootsFaces and file hosted on a CDN.

I'll close the issue. Feel free to report back if our hint didn't help you. We keep listening to this issue even if it's closed.

**Comment by NetoDevel** [comment]
Thank's @stephanrauh , @mfasouza , @ruanfelisky  
worked perfectly
