### ISSUE TITLE
SelectBooleanCheckbox into b:dataTable column don't work.

### ISSUE THREAD

**Issue by mfasouza** [TheCoder4eu/BootsFaces-OSP#544]
Hi everyone, I sorry about my english, it's horrible.
I trying to use a SelectBooleanCheckbox into a column of <b:dataTable> but your value (checked or not) doesn't apply in my @ManagedBean(@ViewScoped) when my form is submited. The components are within a <h:form>.
Perhaps (I don't know!) the cause is id of compents into of dataTable are changed when Tree Components is mounted, and the binding of values falis.
I testing with <b:row> and <b:column> and the value is applied into @ManagedBean.

Exists a other alternative of apply the values of <b:SelectBooleanCheckbox> (cheked) in @ManagedBean ?
 And .. I try using Map<Long,Boolean> and not work.

I'm sorry again and thanks!

**Comment by stephanrauh** [comment]
Please check out BootsFaces-1.0.0-SNAPSHOT or BootsFaces-0.9.2-SNAPSHOT. See #369 on how to get that preview version.

I've fixed several similar bugs of the data table, so chance are your bug has been fixed, too. Don't forget to report back so we can close this issue.

**Comment by stephanrauh** [comment]
@mfasouza Now that we've published BootsFaces 1.0.0, I have to update my request: would you mind to test BootsFaces 1.0.0? Did we solve your bug in the meantime?

Best regards,
Stephan

**Comment by mfasouza** [comment]
Hi, I will update the library and return with results of test.

**Comment by mfasouza** [comment]
Hi @stephanrauh ! The problem is **solved**!
Thank you,
