### ISSUE TITLE
label for the component <b: dateTimePicker />

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#545]
Is it possible to automatically render the label for the component <b: dateTimePicker />?
I haven't found this option in this component, like in the others.

**Comment by ruanfelisky** [comment]
The property "fieldSize" is also unavailable in dateTimePicker, in my projetc I set fieldSize="sm" for all components, but in this case I can't.

**Comment by asterd** [comment]
Hi @ruanfelisky, the label attribute already exist in DateTimePicker, but to enable the rendering of the label, you must specify the attribute render-label="true". 
Instead, the fieldSize attribute left. I've added it in my last commit (829108f)

**Comment by ruanfelisky** [comment]
Hi @asterd,

Thank you very much for your attention.

Just one question, which version is the label attribute working?
I'm in 0.9.1 and it doesn't work, even when I set the property render-label="true".

In all other components it works perfectly.
