### ISSUE TITLE
Allow the column filters of b:dataTable to be above the columns

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#546]
This is a feature already implemented, but for some reason, it doesn't work yet. So I've deactivated it in order to publish a nice release. It would be nice to find the bug - probably somewhere in the JavaScript code.

Refers to #436 .

**Comment by stephanrauh** [comment]
A couple of days ago we've implemented this feature in another feature. So I now know it can be implemented. Let's have a second look at it.

**Comment by stephanrauh** [comment]
Putting the filter fields above the table header did the trick. I've added a working example to the showcase, tool
