### ISSUE TITLE
Missing attributes disabled and readonly in b:dateTimePicker

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#547]
Hi!

Is it possible to implement the attributes "disabled" and "readonly" in the b:dateTimePicker component?
(like in the b:inputText)

Thanks in advance.
Ruan

**Comment by stephanrauh** [comment]
Oops, we forgot that? I'm also certain we can add both features!

**Comment by ruanfelisky** [comment]
Ok, thank you @stephanrauh !

**Comment by asterd** [comment]
Hi @ruanfelisky, in my latest commit (9fdd7c9) I've added the disable and readonly attributes to DateTimePicker component. The only thing to take in mind, is that the readonly attribute doesn't work for the picker with mode="inline". The disabled attribute instead, works good also for that mode.

**Comment by ruanfelisky** [comment]
Ok, thank you @asterd.

**Comment by stephanrauh** [comment]
The feature still works :). Let's close it!
