### ISSUE TITLE
Contradicting resource dependencies

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#55]
bsf.js is imported into the header by the b:datePicker, but the body by b:commandButton. Which version is correct?

![image](https://cloud.githubusercontent.com/assets/3045767/6046000/981424f8-ac9e-11e4-8cde-b2b24dbc724b.png)

**Comment by TheCoder4eu** [comment]
I aligned to head, just to be safe.
