### ISSUE TITLE
/fonts/glyphicons not found 404

### ISSUE THREAD

**Issue by wilima** [TheCoder4eu/BootsFaces-OSP#554]
Hello, I have problem, that my app is not able to load /fonts/ dir from BootsFaces, everything else is fine, where can be a problem?

https://www.dropbox.com/s/s0xrek0204jynxc/Screenshot%202016-11-17%2023.47.17.png?dl=0

Thanks.

**Comment by zhedar** [comment]
Which version of BootsFaces are you using?
Dou you have OmniFaces' `CombinedResourceHandler` activated?

**Comment by wilima** [comment]
9.2 SNAPSHOT, my faces-config is basicaly empty.



    <application>
        <resource-bundle>
            <base-name>resources.commonStrings</base-name>
            <var>commonStrings</var>
        </resource-bundle>
        <resource-bundle>
            <base-name>resources.topicStrings</base-name>
            <var>topicStrings</var>
        </resource-bundle>
        <resource-bundle>
            <base-name>resources.userStrings</base-name>
            <var>userStrings</var>
        </resource-bundle>
    </application>
</faces-config>

**Comment by zhedar** [comment]
Meh, I hoped for this to be rather quickly identified. However, would you be able to provide a small reproducer? You could also try version 1.0.0, which was released recently (but is quite chatty currently, is there was still a debug output left in :( ).

**Comment by wilima** [comment]
I am pretty sure, that it just worked a few days ago... I will try to find somethings.

**Comment by wilima** [comment]
Version 1.0.0 same problem.

**Comment by wilima** [comment]
Created small example and icons works here, so it will be problem in my project.

**Comment by zhedar** [comment]
Maybe you didn't use glyphicons in your example but did in your project? Did you try that as well?

**Comment by wilima** [comment]
The problem is in <b:dataTable> column header. I created empty dataTable and icons appear.

**Comment by wilima** [comment]
I just had to redeploy (clean and build) whole project (every part of EE app). Thanks :)

**Comment by zhedar** [comment]
Oh wow. These errors are the worst. Glad you sorted that out. Happy coding!
