### ISSUE TITLE
logs with : running on BootsFaces 1.0.0-SNAPSHOT for v1.0.0

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#555]
Hi,

A little cosmetic bug : 
12:24:15,219 INFO  [net.bootsfaces.listeners.AddResourcesListener] (ServerService Thread Pool -- 67) This application is running on BootsFaces 1.0.0-SNAPSHOT

Despite of 
```
<dependency>
	<groupId>net.bootsfaces</groupId>
	<artifactId>bootsfaces</artifactId>
	<version>1.0.0</version>
</dependency>
```

Regards

**Comment by zhedar** [comment]
Yeah, I've noticed this as well. We tend to forget that all the time, we should find a reliable way to get rid of manually changing this version string and instead pull it from the manifest or something like that.

**Comment by zhedar** [comment]
We can't undo that for 1.0.0, but I would aim for an early 1.0.1 release anyways, so that won't be that big of an issue.
But I'm leaving this issue open, so that we're reminded of automating this.

**Comment by TheCoder4eu** [comment]
Last commit should solve the problem for next releases
