### ISSUE TITLE
<p:dateTimePicker> locale problem

### ISSUE THREAD

**Issue by dajevtic** [TheCoder4eu/BootsFaces-OSP#556]
Setting a locale other than the default causes a JavaScript error.
After investigating the problem i noticed that class DateTimePickerRenderer renders the locale attribute twice, which causes the problem.
Removing one rendering of the locale attribute (line (BsfUtils.isStringValued(dtp.getLocale()) ?					"locale: [" + dtp.getLocale() + "], " : "") +) solved the issue for me...

Running on <version>1.0.0</version>

**Comment by zhedar** [comment]
You're right. We're rendering the locale twice. The fix should be quite easy, but I will have another look at that, because I don't want the `displayFormat` messed up by a quick fix in any case.

**Comment by zhedar** [comment]
Thanks for the hint, I applied some minor refactorings by the way in a prior commit.

**Comment by stephanrauh** [comment]
@zhedar So it's solved in the current source code version?

**Comment by zhedar** [comment]
@stephanrauh Yep, I fixed it by checking and applying @dajevtic's suggestion in 452697d.

**Comment by stephanrauh** [comment]
@dajevtic I've just uploaded the latest version of BootsFaces to Maven Central. See #369 on how to get it. Please run a test and report us back.

Thanks in advance,
Stephan

**Comment by dajevtic** [comment]
I can confirm that the new version solves this issue.
Thank you, guys! Keep up the great work...
