### ISSUE TITLE
Radiobutton problem

### ISSUE THREAD

**Issue by LuisToro** [TheCoder4eu/BootsFaces-OSP#557]
Hello Team BootsFaces,

I got this error when use radiobutton. I use BootsFaces-OSP-1.0.0.jar

Severe:   Error Rendering View[/xhtml/reportes/Create.xhtml]
java.lang.NullPointerException
	at net.bootsfaces.component.radiobutton.RadiobuttonRenderer.encodeBegin(RadiobuttonRenderer.java:61)

is this a bug?

THX

**Comment by zhedar** [comment]
Did you specify a `value` for your `radioButton`?

If not, can you provide an example?

**Comment by LuisToro** [comment]
Sorry, the error was generated because I did not put the `value`.

Thanks for your prompt response.
