### ISSUE TITLE
b:message styleClass is not working

### ISSUE THREAD

**Issue by NetoDevel** [TheCoder4eu/BootsFaces-OSP#562]
i am trying use attribute styleclass in b:message component and is not working

`<b:messages for="quantidadeTipoAtendimento" style-class="requiredBMessage" id="msgQtd"/>`
or
`<b:messages for="quantidadeTipoAtendimento" styleClass="requiredBMessage" id="msgQtd"/>`

**class css**

```
.requiredBMessage {
       padding: 6px;
       margin-top: 5px;
       width: 200px;
}
```

**Comment by stephanrauh** [comment]
I've fixed this with version 1.0.1. I've pushed the snapshot to Maven Central, so you can already test the bug fix. See #369 on how to get the 1.0.1-SNAPSHOT.
