### ISSUE TITLE
Panel Icon in header

### ISSUE THREAD

**Issue by steelxtreme** [TheCoder4eu/BootsFaces-OSP#564]
Hi bootsfaces community, I guess your doing a great job. 

Is there a way to add an icon in panel header? , I want to write a dashboard like, but accordion just wraps panel components. or just css rules?

king regards

**Comment by stephanrauh** [comment]
Sorry for the late answer - I confused your question with a feature request. However, I believe BootsFaces supports this feature out-of-the-box. Did you already discover the header facet?

<img width="361" alt="bildschirmfoto 2016-12-05 um 21 46 15" src="https://cloud.githubusercontent.com/assets/3045767/20901775/66dea678-bb34-11e6-9803-e486873a7e07.png">

```xml
<b:panel>
   <f:facet name="heading">
            <i class="fa fa-battery-three-quarters" style="padding-right:20px" />
            <h:outputText
              value="Battery charge left: 75% " />
            <b:badge style="margin-left:10px; background-color:#5cb85c" value="good"  />
   </f:facet>
   <h:outputText value="Panel Content"/>
</b:panel>
```

Please report back if that's what you need. Until you we hear from you, I'll close the issue.

King :) regards 
Stephan

**Comment by steelxtreme** [comment]
Thanks for the help, i didn't know about header facet.
