### ISSUE TITLE
Required field b:selectOneMenu doesn't change the color

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#565]
Hi!

When I set the attribute required="true" for a b:inputText and I don't fill this field, besides presenting the message, the field also becomes red. But when using a b:selectOneMenu, it dosen't change the color, it continues black.

Did I forget something?

Basically my code is this bellow:

<b:inputText label="Placa" value="#{myBean.placa}" required="true" requiredMessage="Placa deve ser informada" />

<b:selectOneMenu label="Marca" value="#{myBean.marca}" required="true" requiredMessage="Marca deve ser informada" >
    <f:selectItem itemLabel="Selecione a marca" itemValue="" noSelectionOption="true" />
    <f:selectItems value="#{myBean.marcas}" var="mr" itemLabel="#{mr.descricao}" itemValue="#{mr}" />
</b:selectOneMenu>

<b:selectOneMenu label="Modelo" value="#{myBean.veiculo.modelo}" required="true" requiredMessage="Modelo deve ser informado" >
    <f:selectItem itemLabel="Selecione o modelo" itemValue="" noSelectionOption="true" />
    <f:selectItems value="#{myBean.modelos}" var="md" itemLabel="#{md.descricao}" itemValue="#{md}" />
</b:selectOneMenu>

![image](https://cloud.githubusercontent.com/assets/4307334/20603530/0e16377a-b249-11e6-82b4-e996768a9d56.png)

**Comment by stephanrauh** [comment]
I suppose you're referring to the color of the label? The field is rendered black in each of your three examples.

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug.

**Comment by ruanfelisky** [comment]
Hi, that's right, sorry, it's the label.
Tks.

**Comment by stephanrauh** [comment]
OK, I've solved the issue. The input field and the surrounding div both need ids, so I used the wrong it to determine whether there's a FacesMessage or not. I've uploaded the current Snapshot to Maven Central, so you can test it. See #369 on how to get it.

**Comment by ruanfelisky** [comment]
I've tested the current Snapshot and it's ok!
Thank you.
