### ISSUE TITLE
How to manage b:tree display in height ?

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#567]
Hi,

Creating a Forum page i'm trying to limit the display size of a b:tree in it's height dimension if you put many Nodes. But i didn't see any solution yet ?
- no scrollSize attribute like for b:dataTable
- trying to use a p:scrollPanel does modify the render aspect of b:tree : all nodes look disabled BUT the scroll is ok
- limitating Panel container is useless

Have you any good tips please ?

Many thanks in advance.

**Comment by Kristover** [comment]
Hi,

i 've found a temporary solution by using styleClass of p:scrollPanel and forcing lost styles.
(it seems that the bootstrap style is lost by primefaces theme, but not sure)

regards

**Comment by stephanrauh** [comment]
I should have answered earlier. I thought this is a difficult task, but it turned out to be simple. Just add a `style="height:100px;overflow-y:scroll` to the `<b:tree />`. I've added an example at http://www3.bootsfaces.net/Showcase/bootstrap/tree.jsf.
