### ISSUE TITLE
Event onselect does't work in b:dataTable

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#570]
Hi BootsFaces team!

I'm using the component b:dataTable in many pages, and in a particular one I set select="true" and selectionMode="single" in order to use the selection feature, and I need to call an ajax request when the user select a record in the datatable. So I tried to use the event "onselect" and/or "ondeselect" but it seems that both events don't work, it just does't call my method.

I'm showing my code below. Am I forgetting something?

```xml
<b:dataTable id="atividadesTable" 
                       value="#{cadastroAtividadeBean.atividadesFiltradas}" 
                       var="atividade" customLangUrl="#{resource['/json/pt-br.json']}"
                       searching="false" select="true" selectionMode="single"
                       onselect="ajax:cadastroAtividadeBean.selecionarAtividade()"
                       process="@this">
    <b:dataTableColumn value="#{atividade.descricao}" label="Descrição" />
</b:dataTable>
```

```java
public void selecionarAtividade() {
    System.out.println("print something");
}
```

Thanks in advance!
Ruan

**Comment by stephanrauh** [comment]
Also see http://stackoverflow.com/questions/40723698/get-selected-item-in-bootsfaces-bdatatable.

**Comment by stephanrauh** [comment]
As a first step to solving your problem, I've added some crucial information to the JavaScript code. Now you can check the `indexes` array in order to learn which row has been selected. You can also check the `typeOfSelection` parameter to learn whether a row, a column or an individual cell has been selected.

**Comment by ruanfelisky** [comment]
Hello @stephanrauh, thanks for the information.

I've been thinking, my idea would be to pass the object corresponding to the row selected by parameter, as in the example below:

```xml
<b:dataTable value="#{myBean.activities}" var="activity" 
     searching="false" select="true" selectionMode="single"
     onselect="ajax:myBean.selectActivity(activity)" >
     <b:dataTableColumn value="#{activity.description}" label="Description" />
</b:dataTable>
```

```java
public void selectActivity(Activity activity) {
    // Do anything with the object activity
}
```

Is it possible with the current version of Bootsfaces (1.0.0)?

Thanks!

**Comment by mtvweb** [comment]
Ajax call is generated by the first AjaxRenderer of DataTableRenderer as an "onclick" event to the surrounding <script> tag instead as part of the "select.dt" code. Tried to fiddle out why this happens, but without success

**Comment by stephanrauh** [comment]
@ruanfelisky After giving it some thought, your idea sounds like the natural way to do it. Currently, I've got no idea how to implement it, but I'm sure I'll figure it out.

**Comment by stephanrauh** [comment]
@mtvweb Maybe I've already solved the problem you're describing. Please have a look at the fourth table at http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf. Judging from what I see in the developer tools, "select.dt" should be active. Does it look different in your browser? If so, please try the current 1.0.1-SNAPSHOT and tell me if the problem's still there. (See #369 on how to get the snapshot). Thanks in advance!

![image](https://cloud.githubusercontent.com/assets/3045767/20851925/6aa6b5d2-b8e3-11e6-8474-86955ca66a72.png)

**Comment by stephanrauh** [comment]
@ruanfelisky The JavaScript widget of b:dataTable also allows you to select multiple rows (if selectionMode is not set to "single"). So maybe we have to modify the signature of the JSF bean method like so:

```java
public void selectActivity(Activity... activity) {
    // Do anything with the object activity
}
```

(notice the three dots)

However, I'm not sure. Maybe we should support both versions. The version without dots is called when a single row is selected, and the dotted version is always called (if a method matching the signature exists).

**Comment by mtvweb** [comment]
Right. I've build version from GitHub. Code seems to be correct. Only problem in the moment that the server method isn't called by Ajax. (Added a debug message on server side, but no output there). 

<img width="1309" alt="bildschirmfoto 2016-12-02 um 23 20 43" src="https://cloud.githubusercontent.com/assets/2180107/20852460/3b300fc6-b8e6-11e6-9297-c78eb912e728.png">

**Comment by stephanrauh** [comment]
After improving the documentation, I suggest closing this ticket. If anybody wants us to pursue the idea of passing a vararg in the case of selecting multiple lines, please open a new ticket.
