### ISSUE TITLE
tabindex not rendered in component b:dateTimePicker

### ISSUE THREAD

**Issue by mtvweb** [TheCoder4eu/BootsFaces-OSP#573]
A set  tab index for b:dateTimePicker is not generated in html code

**Comment by stephanrauh** [comment]
Actually, `tabindex` is not in the autocomplete list. Until we've solved this problem, please use JSF 2.2 pass-through attributes. This should do the trick.

Components that should support `tabindex`.
- [x] b:button
- [x] b:colorPicker
- [x] b:commandButton
- [ ] b:datepicker
- [ ] b:dateTimePicker
- [x] b:inputSecret
- [x] b:inputText
- [x] b:inputTextarea
- [x] b:selectBooleanCheckbox
- [x] b:selectMultiMenu
- [x] b:selectOneMenu
- [x] b:switch
- [x] b:touchspin

**Comment by stephanrauh** [comment]
I've fixed the issue in both b:datepicker and b:dateTimePicker, and I've added the attribute `tabindex` to the taglibs of `b:tree` and `b:navLink`. I've also uploaded the current developer snapshot version to Maven Central, so you can already test it. See #369 on how to get the snapshot version.

**Comment by mtvweb** [comment]
It works. Great work
