### ISSUE TITLE
ContextMenu in bootsfaces

### ISSUE THREAD

**Issue by danysion** [TheCoder4eu/BootsFaces-OSP#574]
We need implement a ContextMenu with right click in dataTable and that we can select a row with right click ( for example rigth click in a row , select a option and open a new modal with the selected row) .

This is the original question in stackOverFlow: 
http://stackoverflow.com/questions/40723698/get-selected-item-in-bootsfaces-bdatatable

Thanks for all !

**Comment by stephanrauh** [comment]
We've run out of team members. So let's close this ticket.
