### ISSUE TITLE
remotecommand method is not rendered correctly for Ajax call

### ISSUE THREAD

**Issue by mtvweb** [TheCoder4eu/BootsFaces-OSP#575]
Remote command is not rendering the javascript function correctly.
Id is rendered inside a json structure as subelement "x:"
```java
String c = call.toString().replace("callAjax(this,", "callAjax({x:{id:'" + clientId + "'}},");
```
Changing Line 82 of RemoteCommandRenderer.java to the following helps:
```java
String c = call.toString().replace("callAjax(this,", "callAjax({id:'" + clientId + "'},");
```
Server function is called and update is executed with this change

**Comment by stephanrauh** [comment]
I've fixed the bug and uploaded the current developer snapshot to Maven Central. See #369 on how to get it.

Todos left:
- [ ] document b:remoteCommand properly

**Comment by stephanrauh** [comment]
I've documented the component and added optional parameters. Let's close the ticket.
