### ISSUE TITLE
[b:tree] DefaultNodeImpl equals() not based on nodeId ?

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#578]
Hi,

Working on b:tree, i have found this equals() implementation upon node text :
```
public boolean equals(Object obj) {
		if(obj == null) return false;
		if(obj instanceof DefaultNodeImpl)
			return this.getText().equals(((Node)obj).getText());
		return false;
}
```
I think that this equals should compare nodeId values, no ?
It could imply some strange bugs later depending of tree content.

Regards

**Comment by stephanrauh** [comment]
I believe you're right. I've changed the equals method. BTW, the equals method is never used, except in the showcase example.
