### ISSUE TITLE
navbar css classes are repeated

### ISSUE THREAD

**Issue by jbhardwaj12** [TheCoder4eu/BootsFaces-OSP#58]
When using inverse="true" fixed="top" in navBar 
the output is generated incorrectly as div with class="navbarnavbar navbar-inverse navbar-fixed-top".
In generated code class navbar must not be repeated and generate output like 
class="navbar navbar-inverse navbar-fixed-top"

**Comment by TheCoder4eu** [comment]
Hi, our team noticed this and a fix has already been made:
https://github.com/TheCoder4eu/BootsFaces-OSP/commit/7d22393a4f60d7957a4ef6f31638e60ba4c44f4d

and this version ( v0.6.5 ) will be released soon
