### ISSUE TITLE
Disabling or hiding tabs of b:tabView

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#580]
Hi,

I'm trying to disable a tab from `b:tabView` but it is not working. Even if I set the `disabled` attribute to `true` in the `b:tab`, it is still enabled.

Besides, I would like to know if it is possible to implement the `rendered` attribute of `b:tab`? Because in my project depending on the active user I need to hide one or more tabs (or just disable it as quoted above).

Thank you very much!

**Comment by stephanrauh** [comment]
I've added both `rendered` and `disabled` to both the `b:tabView` and the individual `b:tab`. You can already test it using the 1.0.1-SNAPSHOT on Maven Central. However, I didn't find out yet how to stop the click from adding the class `active` to the disabled tab.

**Comment by ruanfelisky** [comment]
Hi @stephanrauh 

I've just tested the new attributes and they worked almost 100%. I only noticed two points (very similar):

1. When setting `disabled="true"` for the first `b:tab` it keeps active.
2. When setting `disabled="true"` for the `b:tabView` its first `b:tab` also keeps active.

**Comment by stephanrauh** [comment]
Maybe that's best solved with a little CSS, something like 
```css
<style>
.nav-tabs > li.active.disabled > a {
    margin-right: 2px;
    line-height: 1.428571429;
    border: 1px solid transparent;
    border-radius: 4px 4px 0 0;
    </style>
}```

**Comment by ruanfelisky** [comment]
The problem is not only visual, it's because all components inside the disabled `b:tab` keep enabled (`b:commandButton`, `b:inputText`, `b:dataTable`, etc). 

My wish is that all of these components remain disabled as well. But if that is not possible to implement, I think I can handle each component individually.

Example bellow:

```xml
<b:tabView>
    <b:tab title="Históricos" disabled="true">
        ...
    </b:tab>
    <b:tab title="Etapa">
        ...
    </b:tab>
</b:tabView>
```

![image](https://cloud.githubusercontent.com/assets/4307334/21205708/d708deca-c244-11e6-8c64-d6a2d53949cd.png)

**Comment by stephanrauh** [comment]
It's easy to implement a "disable recursively" feature, but I don't think it's a good idea. It may be OK for your use case, but at the same time, I'm sure it stands in the way of other developers.

What about adding a new attribute `disabledRecursively`? This attribute should be implemented in every container of BootsFaces, such as `b:panel`, `b:well`, and `b:dataTable`.

**Comment by stephanrauh** [comment]
@ruanfelisky I've just implemented that the content pane of an inactive tab is never shown. In the light of your last comment, this doesn't seem to be what you need. Do you need a tab which can be selected, but the content pane of which is deactivated? In that case, I'd suggest implementing the attribute `contentDisabled`.

**Comment by stephanrauh** [comment]
I guess this feature is good enough now to ship it.

**Comment by ruanfelisky** [comment]
Hi and sorry for the delay.

So when the `b:tab` is disabled (not the first, but the others), the user cannot access it, and consequently cannot see its content. Following this same logic when the first `b:tab` is disabled, maybe the active tab could be the second one automatically, and so on. Now, if all the tabs are disabled, in this case I don't know what exactly could be done, maybe the active `b:tab` might be the first but its contents be hidden, something like that.

Anyway I think the new attribute `contentDisabled` will be great and will work for me. If displaying content (even disabled) is a problem for my project, I can use the `rendered` attribute implemented in this issue that will perfectly fill that need.

Thank you.

**Comment by stephanrauh** [comment]
@ruanfelisky That's pretty much what I've implemented:
http://www3.bootsfaces.net/Showcase/bootstrap/tab.jsf#disabled

**Comment by ruanfelisky** [comment]
wow that's awesome! It's exactly what I need. Thank you very much guys!
