### ISSUE TITLE
b:remoteCommand broken after ajax update

### ISSUE THREAD

**Issue by mtvweb** [TheCoder4eu/BootsFaces-OSP#581]
After the heavy ajax update for data tables it seems that b:remoteCommand is not working any more. Even the showcase site isn't working well

**Comment by stephanrauh** [comment]
@mtvweb Are you referring to Version 1.0 or to the new snapshot version 1.0.1-SNAPSHOT?

**Comment by mtvweb** [comment]
Of course the snapshot version

**Comment by stephanrauh** [comment]
Oh. I'm puzzled. The remoteCommand demo works on my machine, but not on our preview showcase. Thing is, both servers use the same source code. The only difference is that the showcase runs on Gradle and Wildfly, while my machine runs on Maven and Tomcat 8.
![image](https://cloud.githubusercontent.com/assets/3045767/21031315/0a1ae912-bda3-11e6-926e-3ca7608946a8.png)

**Comment by stephanrauh** [comment]
@TheCoder4eu @zhedar @asterd Can one of you check out the current source code and tell me if the demo http://127.0.0.1:8080/BootsFacesWeb/forms/RemoteCommand.jsf works? 

Thanks in advance!
Stephan

**Comment by mtvweb** [comment]
Build it from source. Tested with Tomee 7.0.1 and 7.0.2. It seems that it is working with both versions using localhost:8080 but not through the ajp protocol with apache http using a http://localhost:80/ url and an apache configuration using ProxyPass / ajp://localhost:8009/

**Comment by mtvweb** [comment]
Forget about the port. Further testing works even with port 80 through apache proxy. May be sthg. else. It seems to be random.

**Comment by mtvweb** [comment]
It seems to me that tomee 7.0.1 fails most of the time  (I think it was working sometimes ago, but not sure) and tomee 7.0.2 seems to work most of the time. (not sure if it is working 100 percent. because I switched several times between the versions)

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug on Wildfly 10.0. It's really a strange bug: the `decode()` method of the `RemoteCommandRenderer` is never called.

**Comment by stephanrauh** [comment]
That was a difficult bug if there's one. Some JSF implementations submitted the wrong form.

I've uploaded the bug fix to Maven Central, so you can test it either using the snapshot version or by building the version from source.
