### ISSUE TITLE
Missing attributes id and fieldId in b:dateTimePicker

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#582]
Hello guys,

Is it possible to implement the attributes `id` and `fieldId` in `b:dateTimePicker`?
In my project I need to manipulate some of these fields and it would help me a lot.

Thanks in advance.
Ruan

**Comment by stephanrauh** [comment]
So the `id` would be the id of the entire widget (including the optional col-xx-yy divs) and `fieldId` would be the id of the actual input field?

**Comment by stephanrauh** [comment]
Oh, it seems we've forgotten to declare the id. Of course, it was there, but it wasn't offered by the autocompletion of Netbeans and IntelliJ.

**Comment by stephanrauh** [comment]
Done and documented.

**Comment by ruanfelisky** [comment]
The idea would be the same of `b:inputText` that has both `id` and `fieldId`.

Tks.

**Comment by stephanrauh** [comment]
Ok, so I guessed correctly. In the meantime, I've uploaded a new BootsFaces-1.0.1-SNAPSHOT, so you can test my bug fix.

**Comment by ruanfelisky** [comment]
I've tested the current Snapshot and it's ok!
Thank you.
