### ISSUE TITLE
Converters for String.class not called

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#583]
If the application has a `javax.faces.convert.Converter` annotated with `@FacesConverter(forClass = String.class)`, the `getAsString` method is not called.
I found the problem, in the `CoreRenderer` class, method `getValue2Render`, this `if` starting at line 462:

```
if(valueType == String.class) {
    return (String) val;
}
```

I think there are two possible solutions:
- Delete these three lines.
- Add a condition to the if, something like this:
                    
```
if(valueType == String.class && (null == fc.getApplication().createConverter(String.class))) {
    return (String) val;
}
```

**Comment by stephanrauh** [comment]
I've chosen the second option.

**Comment by stephanrauh** [comment]
A couple of minutes ago, I've uploaded a new snapshot version to Maven Central, so you can test my bugfix. As usual, see #369  on how to get the snapshot version.

Thanks in advance
Stephan
