### ISSUE TITLE
Can't throw event "blur" with b:selectMultiMenu

### ISSUE THREAD

**Issue by danysion** [TheCoder4eu/BootsFaces-OSP#584]
Good morning, I am having problems with the component b:selectMultiMenu and ajax events.
I only need that when I lose focus ( onBlur event or onChange) throw a simple call of my bean method, but when I try the code this doesn't work.
I saw that b:selectMultiMenu dont have property "ajax" and "onBlur" and finally the property "onChange" dont call my method.
This is part of my code:

```xml
<b:selectMultiMenu id="version" enable-filtering="true"
						styleClass="versiones"
						nonSelectedText="#{gecohMsg['container.combo.select']}"
						value="#{Expedients.facadeTableSelect.listVats}"
						nSelectedText="Seleccionados" numberDisplayed="1"
						includeSelectAllOption="true"
						enableCaseInsensitiveFiltering="true" lang="es"
						disabled="#{Expedients.versiones}" onchange="ajax:Expedients.showSua()">
						<f:selectItems value="#{Expedients.multiComboVat}" var="multiVat"
							itemLabel="#{multiVat.value}" itemValue="#{multiVat.code}" />
					</b:selectMultiMenu>
```

Thanks for all.

**Comment by stephanrauh** [comment]
Fun fact: our documentation even says that AJAX is broken since BootsFaces 0.7. It's high time to change that!

**Comment by stephanrauh** [comment]
Obviously we've forgotten to implement AJAX support. Actually, AJAX support seems to be difficult. The underlying JavaScript widget only supports a few jQuery events. `onblur` is not among them.

	* onSelectAll
	* onDropdownShow
	* onDropdownHidden
	* onSelectAll
	* onChange
	* onDropdownHide
	* onDeselectAll
	* onDropdownShown
	* onInitialized

**Comment by stephanrauh** [comment]
The underlying JS widget doesn't support `onblur`, so we can't provide that, either. However, the events listed above should already be supported by the current developer snapshot. I've uploaded it to Maven Central a couple of minutes ago.

**Comment by stephanrauh** [comment]
To dos left:

- [ ] testing
- [ ] testing
- [ ] testing

**Comment by stephanrauh** [comment]
I didn't test every event, but I've added and tested an example of AJAX with ondropdownhidden in our showcase.

**Comment by stephanrauh** [comment]
You can run a test using the BootsFaces-1.1.0-SNAPSHOT on Maven Central. See #369 on how to get it.
