### ISSUE TITLE
DateTimePicker fails with ajax update

### ISSUE THREAD

**Issue by mtvweb** [TheCoder4eu/BootsFaces-OSP#586]
DateTimePicker (Github master) destroys date value during ajax call immediately after rendering the page.

I've initialized a date on initialization for two date time picker controls. During the first rendering, before touching the picker with an user action. DateTimePicker sends back a date to the server with a wrong year. 

I have attached a small example showing this issue. I've tried to debug, rendering looks good. Seems to be the Ajax call, which may be to early, with an not fully initialized date value.

**Some output from the DateTimePickerRenderer:**

DTP:Thu Sep 01 19:41:26 CEST 2016
DTP sloc:de
DTP format:MM.YYYY
DTP displayformat:'MM.YYYY'
DTP inlineDisplayDate:'09.2016'
DTP:Fri Mar 31 19:41:26 CEST 2017
DTP sloc:de
DTP format:DD.MM.YYYY
DTP displayformat:'DD.MM.YYYY'
DTP inlineDisplayDate:'31.03.2017'

**Output from DTPBean:**

set1:Wed Mar 09 00:00:00 CET 7
set2:Wed Mar 09 00:00:00 CET 7

**Example files:**

[DTPBean.java.txt](https://github.com/TheCoder4eu/BootsFaces-OSP/files/655546/DTPBean.java.txt)
[dtptest.xhtml.txt](https://github.com/TheCoder4eu/BootsFaces-OSP/files/655547/dtptest.xhtml.txt)

**Comment by stephanrauh** [comment]
@mtvweb Your pull request solved the issue. Thanks!

**Comment by stephanrauh** [comment]
You can run a test using the BootsFaces-1.1.0-SNAPSHOT on Maven Central. See #369 on how to get it.
