### ISSUE TITLE
New attribute: contentDisabled

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#587]
As suggested by @ruanfelisky in #580, it might be useful to disable every component of a container. For instance, `<b:panel contentDisabled="true"><b:inputText /></b:panel>` would disable the input field.

- [x] b:accordion
- [x] b:buttonGroup
- [x] b:buttonToolbar
- [x] b:column
- [x] b:container
- [x] b:dataTable (current implementation also block search filters and the page length menu)
- [x] b:dropButton (indirectly by adding the ancestor lookup logic to navLink etc.)
- [x] b:dropMenu 
- [x] b:flyoutMenu
- [x] b:jumbotron 
- [x] b:kebab 
- [x] b:listLinks  
- [x] b:navBar 
- [x] b:navBarLinks 
- [x] b:panel
- [x] b:panelGrid
- [x] b:pillLinks
- [x] b:row
- [x] b:tab
- [x] b:tabLinks   
- [x] b:tabView
- [x] b:tree (not implemented because this doesn't seem to be useful)
- [x] b:well

Not implemented:
- [x] b:form (implementing this feature adds little value, but is very difficult because we'd have to add a Renderer, thus losing compatibility to other frameworks like PrimeFace or LifeRayFaces)

**Comment by stephanrauh** [comment]
@ruanfelisky I've started to implement this feature using the way Bootstrap suggests, using `fieldset`. That's a simple and pragmatic solution, although it may miss some of the non-native fields. So I've added some special code for b:datePicker, b:dateTimePicker and b:colorPicker.

There's a sneak preview at http://www3.bootsfaces.net/Showcase/layout/Accordion.jsf.

**Comment by ruanfelisky** [comment]
@stephanrauh very nice and useful! This feature will help me a lot!
Tks!

**Comment by stephanrauh** [comment]
Done and documented.
