### ISSUE TITLE
No Styling

### ISSUE THREAD

**Issue by cattleyalinda** [TheCoder4eu/BootsFaces-OSP#59]
Hi,
I'm new to bootsfaces. I'm tying out the starter template but the styling does not appear. I already added the jar file in the project. I followed the instructions in the Quick start regarding the Theme css support. 

What am I missing? 

thanks,
cattleyalinda

**Comment by stephanrauh** [comment]
Just a far shot: maybe the theme context parameter?


<context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>true</param-value>
</context-param>

**Comment by cattleyalinda** [comment]
i've already included that theme context parameter and yet the styling does not appear. I tried it in eclipse and netbeans. I created a web project and added the bootsfaces jar.

**Comment by cattleyalinda** [comment]
The project is a dynamic web project  with Glassfish 4 as server. Im using jdk 1.7. Ive added bootsfaces jar and the jsf 2.2 mojarra jar in the libraries. When the project is run only the text appears in the starter template. The styling and the menu does not show.

**Comment by TheCoder4eu** [comment]
Maybe you are viewing the xml of the page only, what is the URL of the page?
What is the url-pattern of the servlet-mapping in your web.xml ?

**Comment by cattleyalinda** [comment]
I used the default page, since I'm trying it out. 

http://localhost:8080/d/

Here's the web.xml

<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd" id="WebApp_ID" version="3.1">
  <display-name>d</display-name>
  <welcome-file-list>
   <welcome-file>index.jsp</welcome-file>
       <welcome-file>default.jsp</welcome-file>
  </welcome-file-list>
  <servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
  </servlet-mapping>
  <context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>true</param-value>
</context-param>
  <context-param>
    <description>State saving method: 'client' or 'server' (=default). See JSF Specification 2.5.2</description>
    <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
    <param-value>client</param-value>
  </context-param>
  <context-param>
    <param-name>javax.servlet.jsp.jstl.fmt.localizationContext</param-name>
    <param-value>resources.application</param-value>
  </context-param>
  <listener>
    <listener-class>com.sun.faces.config.ConfigureListener</listener-class>
  </listener>
</web-app>

**Comment by stephanrauh** [comment]
Hi,

Try to omit the /faces/ pattern. Better use •.jsf, like we do in the BootsFacesWeb project (i.e. the showcase).

Regards,
Stephan

**Comment by cattleyalinda** [comment]
it's still not working. maybe you can take a look at the workspace.

![bootsfaces](https://cloud.githubusercontent.com/assets/11058486/6265566/cee83f36-b7e4-11e4-8ab1-34317446966c.png)

**Comment by stephanrauh** [comment]
Try using the JSF tags h:head and h:body instead if the HTML tags (head and body).

**Comment by cattleyalinda** [comment]
Thanks for your patience.. but still its not resolved

**Comment by stephanrauh** [comment]
It's difficult to know the reason without seeing the code. Can you upload it to GitHub so we can see it?

**Comment by cattleyalinda** [comment]
I recreated the project and its working fine now. Thank you very much for your help and patience.

**Comment by vishwasreddy** [comment]
hello please i have the same issue in my project file is in jsp but internally we are converting the page in jsf as an extension .jsf please  help the project is in crucial stage

**Comment by stephanrauh** [comment]
@vishwasreddy Mind you, if someone asked you precisely that question, would you be able to help them?  I don't know anything about your project. Only I doubt it ever worked - JSP and JSF files are something completely different. By the way, please take the time to formulate your question in correct English, including punctuation marks.

**Comment by rigeen** [comment]
Hi, I´m using JSF 2.2 templates and I´d like to know how to apply bootsfaces correctly in these cases. I´ve been looking for  an example or documentation about it, but I don´t get it. Could somebody give me a hint?

**Comment by zhedar** [comment]
@rigeen I guess this isn't the correct issue, you may want to open another one (although, if this is a question, StackOverflow might be a better fit).
However, you didn't mention what your problem is exactly, so I'm just going to refer you to the [quickstart](http://www.bootsfaces.net/quickstart.jsf;jsessionid=RpNumLRWPcq0n3WxXoO0F6yqwBXvWlgvUBn6FsjZ.wildfly03) (you can scroll down beneath the maven dependency, if that isn't clear). There are also some simple [examples](http://showcase.bootsfaces.net/Examples/) and the [showcase](http://showcase.bootsfaces.net) is available as a [project](https://github.com/TheCoder4eu/BootsFacesWeb) itself. It uses facelet templating, so while I'm not sure what your problem exactly is, you can probably look up some examples there.

**Comment by rigeen** [comment]
Well, I have a jsf-primefaces project using two templates, one for the index page and the other one for the rest of pages. I´m not sure where to put the bootsfaces reference library and tags, as I only need the container tag and I don´t  want to modify the pages themselves. I put the reference library in the page  itself and works, but some css style properties touching primefaces components (as corrousel) and even the body itself don´t work as expected. That´s why I want to know, which is the right way to do this. Besides that, thanks for your advice.

**Comment by stephanrauh** [comment]
@rigeen 
* Put the BootsFaces.jar into the WEB-INF/lib folder. If you use Maven or Gradle, your build system does this automatically for you.
* Declare the BootsFaces namespace into every XHTML file which uses at least one BootsFaces component. In your case, that's the one page using `b:container`.
* It's always possible there's a conflict between PrimeFaces CSS and BootsFaces CSS. If you want us to do something about it, please open a new issue which describes which components are incompatible. But maybe it's easier to replace the PrimeFaces carousel by the BootsFaces carousel. Our components are created and tested with PrimeFaces, but the PrimeFaces guys don't add BootsFaces to their test projects, so chances are our components are more compatible than their components.
