### ISSUE TITLE
Improve autocomplete in Netbeans

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#601]
By default, Netbeans proposes `bnu` instead of `b` as the namespace prefix for bootsfaces components. I know it's not a real problem, but the solution is quite simple: adding `id="b"` attribute to the `<facelet-taglib>` element in the file `bootsfaces-b.taglib.xml`.

**Comment by stephanrauh** [comment]
Is it the id or the `id` or the `composite-library-name`, as suggested by http://stackoverflow.com/questions/23755485/customize-default-taglib-preffix?

**Comment by stephanrauh** [comment]
`composite-library-name` seems to be a false track, since it only deals with composite components. However, there also seems to exist an attribute called `short-name`. Let´s start with the id, because that's what the OmniFaces guys do, and usually, they have a pretty good grasp about how JSF works :).

**Comment by stephanrauh** [comment]
The JSFDSL generator needs to be updated, too. Nonetheless, I've published a developer snapshot on Maven Central. As usual, see #369 on how to get it. Does it solve the bug?

**Comment by stephanrauh** [comment]
Todo left:
- wait for @NicolaIsotta to confirm the solution works (or install Netbeans myself)
- add the id attribute to the taglib generation of the JSFDSL generator

**Comment by NicolaIsotta** [comment]
It's fixed in the snapshot version. Thanks @stephanrauh

**Comment by stephanrauh** [comment]
@NicolaIsotta Thanks for testing!

**Comment by stephanrauh** [comment]
I've updated the JSFDSL plugin: https://github.com/stephanrauh/JSFLibraryGenerator/tree/master/plugins
