### ISSUE TITLE
Document b:dataTableColumn data-order and data-search

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#604]
Document the two new properties added by PR #602

**Comment by stephanrauh** [comment]
@mtvweb Jens, I need your help. I've documented the `data-order` option. But currently, I don't have a clue how to document the `data-search` option. Can you give me a hint? What should the example look like?

**Comment by mtvweb** [comment]
Here's a possible example

```
<b:dataTableColumn 
       value="#{ bean.lastname }, #{ bean.firstname }"
	label="Name" 
	data-search="#{ bean.firstname } #{ bean.middlename } #{ bean.lastname }" />

<b:dataTableColumn 
       value="#{ bean.location }"
	label="Location" 
	data-search="#{ bean.location } #{ bean.longitude } #{ bean.latitude }" />

```

It only display first and last name, but searching is also possible by the middle name, even it is not displayed. Or in the second example you can also search by geo location.

**Comment by stephanrauh** [comment]
@mtvweb Using the car demo which shows the age of the car in months, I could also add the option to search for the (invisible) year of construction. Thanks for your inspiration!

**Comment by stephanrauh** [comment]
I've added the documentation of `data-search` to the showcase.
