### ISSUE TITLE
Render all label-col-xx classes in horizontal mode

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#605]
Right now, only one of the classes specified by the user is rendered: for example, if I have a `b:inputText` with `label-col-sm="4" label-col-md="3" label-col-lg="2"` the generated html contains this: `<label class="bf-no-message has-success col-md-3 control-label" [...] >`.
The issue is in the class `net.bootsfaces.render.Responsive`, method `getResponsiveLabelClass`: the strings for the `col-xx` classes should be combined in a StringBuilder.

**Comment by stephanrauh** [comment]
Good point. I've fixed that. Thanks!

**Comment by stephanrauh** [comment]
I've published a developer snapshot on Maven Central. As usual, see #369 on how to get it.
