### ISSUE TITLE
dateTimePicker: missing form-group class

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#606]
Quick example: in [the Bootsfaces showcase](https://showcase.bootsfaces.net/forms/DateTimePicker.jsf), the dateTimePicker with the label attribute are rendered inside a div, but it hasn't got the form-group class.
I guess the problem is in the `net.bootsfaces.component.dateTimePicker.DateTimePickerRenderer` class, the `else if` starting at line 181 is missing the line
```java
rw.writeAttribute("class", "form-group", "class");
```

**Comment by stephanrauh** [comment]
What a weird bug. Luckily, it was easy to fix. Thanks!

**Comment by stephanrauh** [comment]
I've published a developer snapshot on Maven Central. As usual, see #369 on how to get it.
