### ISSUE TITLE
b:message doesn't support composite components

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#607]
If a have a composite component with an implementation like this:
```
<cc:implementation>
	<b:inputText id="input" value="#{cc.attrs.value}" .../>
</cc:implementation>
```
And I add a message for the input element in a page:
```
<ezcomp:myinput id="field1" .../>
<b:message for="field1:input"/>
```
I get this exception:
```java
javax.faces.FacesException: Invalid search expression: field1:input The subexpression input doesn't exist, or it can't be resolved.
```
`h:message` works instead.

**Comment by stephanrauh** [comment]
Looks like a difficult one!

**Comment by stephanrauh** [comment]
For some reason unknown, `b:message` only checked its children and the root component for `field1:input`. Now I've added a bit more flexibility. `b:message` now also checks it's parent. In my test case, that's the form. Hope that works for you, too!

I've uploaded the new snapshot of BootsFaces to Maven Central. As usual, see #369 on how to get it.

**Comment by stephanrauh** [comment]
I'll close this issue so we can include it into the 1.0.2 version.

**Comment by NicolaIsotta** [comment]
It's working in the snapshot version.

**Comment by stephanrauh** [comment]
THX! We're currently preparing the 1.0.2 version, so I'm very glad you reported back in time.
