### ISSUE TITLE
v1.0.2 Ship List - Bugfix Release

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#608]
v1.0.2 Ship List - Bugfix Release

**New features:**
- #602 The `<b:dataTableColumn>` has two new attributes: `data-order` and `data-search`. both attributes deal with columns that are displayed differently from the internal represenation. For example, think of numbers, which might be displayed as Roman numbers. Or think of date. The american representation of dates doesn't match alphabetical sorting, so you have to tell the datatable the correct sort order.  `data-order` does just that. It allows you to define a function or a bean attribute defining the real order. Similarly, `data-search` allows you to find data by hidden key. For instance, you might display the data as `04/30/2000`, but allow users to enter the word "April", too.

**Bug fixes:**
- #607 Added more flexibility for the resolution of ids. The original error report was that `<b:message />` doesn't support composite components. However, probably the too-strict check caused problems in other situations, too, even if they complied to the JSF specification.
- #606 under certain circumstances, the `<b:dataTimePicker>` was rendered without its `form-group` CSS class.
- #605 BootsFaces 1.0.0 introduced horizontal forms, and the new attributes `label-col-xx-yy`. However, we forget that it's a common use case to combine multiple `label-col-xx-yy` attribute targeting different screen sizes. #605 allows you to do just that.
- #598 The search expression "**:id" used to return zero or one results. However, the wildcard indicates that multiple results are returned, not just the first. BootsFaces 1.0.2 fixes this.
- #597 That's a very strange bug: `<b:colorPicker>` didn't send data to the backend. Starting with BootsFaces 1.0.2, it works properly again.
- #596 One of the reasons why so many people report incompatibility with PrimeFaces was a CSS rule going rogue. It was meant to address a single component of BootsFaces. As a side effect, it affected every component of PrimeFaces, reducing its font size to 85%. We've fixed that. However, there are many incompatibilities remaining. Please check out the GitHub repository https://github.com/stephanrauh/PrimeFacesAlongWithBootsFaces which tries to solve the incompatibilities between PrimeFaces and BootsFaces (or Bootstrap in particular).
- #594 `<b:datePicker>` is one of our oldest components, but that doesn't mean it's perfect. This bug fixes that style and styleClass not were not rendered with inline b:datePickers.
- #593 BootsFaces adds CSS classes to indicate whether the input field has an error or a warning. This CSS class is added to both the label and the input field. Only it wasn't added to the input field of `<b:selectOneMenu>`. We've fixed that.
- #591 You couldn't order data table columns by data (or rather: the sort order was alphabetical, which is wrong in almost every country of the world). The new feature #602 fixes this. Kudos to @mtvweb!
- #586 `<b:dateTimePicker>` behaved very strangely when AJAX was activated. It sent requests before the user could even start to type. As a result, the date pickers showed wrong or empty values at page load. #586 addresses this bug. Kudos to @mtvweb who fixed this bug!
- #584 We were a bit surprised that ´<b:selectMultiMenu>` didn't support AJAX. We've fixed that. However, the component doesn't support the standard set of events because the underlying JavaScript component supports a slightly unorthodox set of events. We're sure you'll cope if you keep that in mind. Everything you really need is there, but sometimes the event names are different from what you might expect.
- #578 DefaultNodeImpl equals() tested the text instead of the id

**Miscellaneous:**

**Comment by stephanrauh** [comment]
I guess we can close this issue after shipping the version yesterday :).
