### ISSUE TITLE
dateTimePicker broken in 1.0.2

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#611]
Quick example: [the showcase](https://showcase.bootsfaces.net/forms/DateTimePicker.jsf). All the `dateTimePicker` with the `label` attribute are broken: pressing the button doesn't open the calendar.

Side note: I think the "Embedding a DateTimePicker in a form" section should be updated with the new `b:form`

EDIT: I just found out in #590 there's already a discussion about this problem. Anyway, I tested PR #610 and it works.

**Comment by NicolaIsotta** [comment]
The problem is the `id` of the `div`s. I made a quick test and PR #610 by @mtvweb fixes this

**Comment by stephanrauh** [comment]
So that's the error solved by the PR. I always tested the first datePicker example and forgot to have a look at the others. It's a pity the PR missed the 1.0.2 by a half a day.

**Comment by stephanrauh** [comment]
This should be fixed by now. See http://www3.bootsfaces.net/Showcase/forms/DateTimePicker.jsf. I've uploaded a new snapshot of 1.1.0 so you can test it yourself.
