### ISSUE TITLE
Tab view tab display none when  I click

### ISSUE THREAD

**Issue by FherPie** [TheCoder4eu/BootsFaces-OSP#612]
Hi everyone. First I l like  Bootfaces it is nice. Actually I am using Icefaces 3.3.0 and Bootfaces 1.0.1 experimentally.  I found a liitle trouble  it is here:
http://stackoverflow.com/questions/41554265/bootfaces-display-none-tab-in-tabview
Thanks in advance

**Comment by stephanrauh** [comment]
I'll repeat the answer I gave you on StackOverflow: 

I can think of at least two different reasons:

 - ICEfaces. BootsFaces is officially **not** compatible with ICEfaces. I know some people managed to get this combination of frameworks up and running, but it's difficult. Among other things, the automatic AJAX feature of ICEfaces doesn't bode well with BootsFaces. We work hard to produce as clean HTML code as possible, but ICEfaces requires immaculate, flawless HTML code. Last time I checked we didn't generate code ICEfaces could cope with.
 - Your template. You didn't show it, so it can contain any code.

I suggest you try to simplify the code and see when the error vanishes:

 - Get rid of the pill tabs. I don't think they cause the problem, but they are a deviation from the standard, so it's a good idea to check this, just in case.
 - Put your snippet on a page without your template.
 - Remove ICEfaces from your application. To do so, you probably need to create a new project or a copy of the project which you can simplify radically.

Oh, and check the JavaScript console (the F12 tool, or CMD+ALT+I on OSX). Maybe you spot an error message there. 

Once you've figured out what's the problem, please report back, so other developers can benefit from your experience. Thanks in advance! and: ¡Buena suerte!

**Comment by stephanrauh** [comment]
@FherPie You've accepted my answer on StackOverflow, so probably I've helped you to solve your problem. I'll close this ticket. If you've got any question or remark, don't hesitate to tell us - either here or on StackOverflow.

**Comment by FherPie** [comment]
Thanks!
