### ISSUE TITLE
Horizontal form only works in the most simple case

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#614]
The other day I've learned that every component that is to be aligned vertically must be included in the some `form-group`. That's hard to accomplish with JSF because each component is rendered individually. We need to find a solution nonetheless.

One important special case is adding the `b:message` tag into the same line as the label and the input field. 

Other use cases are:

- Putting a command button behind an input field.
- Putting input fields behind a checkbox or a radio button.

**Comment by NicolaIsotta** [comment]
#493 is related to this. As an alternative to the `facet`, have you considered modyfing the `encodeChidren` method?

**Comment by stephanrauh** [comment]
I suppose this issue is solved by #682 and #685.

**Comment by stephanrauh** [comment]
This issue has been solved by introducing `<b:form />`.
