### ISSUE TITLE
b:navLink can't be disabled

### ISSUE THREAD

**Issue by knoppt** [TheCoder4eu/BootsFaces-OSP#615]
Hi Bootsfaces Team,

I use Bootfaces 1.0.2 and I want to disable a b:navLink.
I set the attribute disabled="true", but its's still enabled!

```xml
<b:navLink value="test" style-class="pull-right"
                           outcome="test.xhtml"
                           disabled="true">
```

Could you fix it in next Version?

Best regards,
knoppT

**Comment by stephanrauh** [comment]
Looks like a useful new feature. Any suggestion how the link should be displayed if disabled? Gray? With or without underline?

**Comment by knoppt** [comment]
Hi,
thanks for answer! 
In my opinion, the disabled navLink should be gray whithout underline! 

Best regards,
knoppT

**Comment by stephanrauh** [comment]
I've implemented and documented the feature (see http://www3.bootsfaces.net/Showcase/layout/navLinks.jsf). You can test it using the latest developer snapshot BootsFaces-1.1.0-SNAPSHOT. See #369 on how to get it.
