### ISSUE TITLE
b:radioButton doesn't change value in Version 1.0.2

### ISSUE THREAD

**Issue by knoppt** [TheCoder4eu/BootsFaces-OSP#616]
Hi,

I changed Bootsfaces Version from 1.0.1 to 1.0.2! 

Now b:radioButton doesn't change value when submit @form! 

I use Bootsfaces showcase [http://showcase.bootsfaces.net/forms/RadioButton.jsf](http://showcase.bootsfaces.net/forms/RadioButton.jsf)

```xml
<b:panel title="Survey" look="primary">
   <p>What's your favorite band?</p>
     <b:radiobutton value="#{radiobuttonBean.favoriteBand}">
         <f:selectItems value="#{radiobuttonBean.bands}" />
         <f:selectItem itemValue="" itemLabel="None of the above" />
     </b:radiobutton>
     <b:commandButton value="submit your choice" action="#{radiobuttonBean.submitBand}"
                      look="primary" update="@form" />
     <b:message for="@form:@property(radiobuttonBean.favoriteBand)" />
 </b:panel>
```
The setter favouriteband was not invoked! 
In Version 1.0.1 it worked fine!

Thanks, best regards!

knoppT

**Comment by stephanrauh** [comment]
I've just tried to reproduce the bug. I don't see any error. So probably I've tested the wrong thing. do we talk about this part of the demo? When I tested it, the method `setFavorityBand(String x)` was called, and the message was shown:
![image](https://cloud.githubusercontent.com/assets/3045767/21912184/9efbdb8a-d924-11e6-8d42-4c1274aaee3f.png)

**Comment by knoppt** [comment]
Hi,

I tested it again and assert, that the bug only occurs when I put the b:radiobutton into a composite component!

Then the radioButton doesn't change the value in Version 1.0.2! 
In Version 1.0.1 everythings works fine! 

Outside a composite component it also works in Version 1.0.2! 

Here my code (radioButtonBean identical like showcase)!

example.xhtml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:stala="http://xmlns.jcp.org/jsf/composite/component">
<body>
	<h:form id="form">
		<stala:editPanel />
	</h:form>
</body>
</html>
```

editPanel.xhtml:
```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<composite:interface>
	</composite:interface>
	<composite:implementation>
	       <b:panel title="Survey" look="primary">
                   <p>What's your favorite band?</p>
                   <b:radiobutton value="#{benutzerController.favoriteBand}">
                         <f:selectItems value="#{benutzerController.bands}" />
                         <f:selectItem itemValue="" itemLabel="None of the above" />
                   </b:radiobutton>
                   <b:commandButton value="submit your choice"
                            action="#{benutzerController.submitBand}" look="primary"
                            update="@form" />
                    <b:message for="@form:@property(benutzerController.favoriteBand)" />
                </b:panel>
	</composite:implementation>
</ui:composition>
```
 
Thanks in advance,
knoppT

**Comment by knoppt** [comment]
The h:form is the party pooper! 

When I put the h:form into the composite component it works! 
But this is no solution!

Best regards, 

knoppT

**Comment by stephanrauh** [comment]
Might be an id resolution problem. Just a wild shot: try to add an id to `<stala:editPanel />`.

**Comment by knoppt** [comment]
I added id to stala:editPanel, but same result!

**Comment by stephanrauh** [comment]
Sigh... well, it was worth a try. I'll debug your code later.

**Comment by stephanrauh** [comment]
Oh. It was something unexpected. The child elements of a custom component are not stored in the `children` variable, but in the `facets` variable. Now it works. Please try again with the current developer snapshot BootsFaces-1.1.0-SNAPSHOT I've just uploaded. See #369 on how to get it.
