### ISSUE TITLE
<b:dataTable> Problems with input filters.

### ISSUE THREAD

**Issue by danysion** [TheCoder4eu/BootsFaces-OSP#617]
Good morning , i have two problems with the filters of my datatable.

•When i filter column of my datatable and go to other page and finally return to datatable page.Now i see that the filter is applicated but the filter input is clean , how can in this case hold the content of input filter?

•In another case to delete the data table, I delete all values ​​from the table but if the table was filtered, maintain the filter but with empty fields (similar to the previous case) How can I completely clean the table and its filters ?

Thanks for all.

**Comment by stephanrauh** [comment]
- As for the first case: do you navigate with or without AJAX?
- Good point. Currently, the filters are handled by the client side. There's no connection to the backend. Hence, there's no means to delete the filter. I'll have to think about that.

**Comment by danysion** [comment]
• I navigate with AJAX.
• Perfect, this maybe be necesarry because we need clear the input filters.

**Comment by stephanrauh** [comment]
Done. The datatable doesn't transmit the values of the filters to the server, but that's probably not necessary. It suffices to be able to implement one direction (setting the value from the server).
