### ISSUE TITLE
Improve b:button/b:commandButton size attribute description

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#618]
Not really a issue, but the current description of the `size` attribute is: `"Size of the Button, can be large, small, mini. If not specified, Standard size button is rendered."`
Actually, the size classes are ( `btn-` ) `lg`, `sm` and `xs`, so the description is misleading.
The renderers code is already correct (it just appends what it receives to `btn-`).

PS: is there any reason why the `value` attribute is required in `b:button` / `b:commandButton`? I think displaying buttons with icon only is a common use case.

**Comment by stephanrauh** [comment]
Fixed the non-issue. It was a left-over from Bootstrap 2. I also made `value` optional. Most likely, it was a copy-and-paste error when I created the BootsFaces.jsfdsl file.
