### ISSUE TITLE
b:dataTable not styled by patternfly

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#619]
I was trying the patternfly theme and I like its "professional" look; the `b:dataTable` component, though, is not styled [like it should](http://www.patternfly.org/pattern-library/content-views/table-view/#_).
I think this is caused by:

- file `datatables.min.css` which should not be included when patternfly is the chosen theme (a context-param to control its loading would be useful too)
- the `core.css` file for patternfly theme should include tables and datatables customization
As always, thanks for your work.

**Comment by NicolaIsotta** [comment]
I've just created a PR. This is how a b:dataTable appears now:
![datatable_patternfly](https://cloud.githubusercontent.com/assets/18428155/22431930/8b637914-e713-11e6-8ce8-f3e71fea8022.jpg)

**Comment by TheCoder4eu** [comment]
@NicolaIsotta your PR looks ok to me, thank you very much for this contribution!

**Comment by NicolaIsotta** [comment]
@TheCoder4eu unfortunately, the datatables customization by patternfly doesn't include the responsive plugin ([and they have no plans to do it](https://patternfly.atlassian.net/browse/PTNFLY-1967)), as you can see in the snapshot showcase. I've already prepared a PR which fixes the problem.
