### ISSUE TITLE
Add the Dashboard example

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#62]
Add the Dashboard example to the Examples Page

**Comment by TheCoder4eu** [comment]
Work in progress

**Comment by TheCoder4eu** [comment]
Testing

**Comment by TheCoder4eu** [comment]
Test OK

**Comment by TheCoder4eu** [comment]
Added to the Examples Page.

**Comment by fourtytwo** [comment]
But there is no code to the example. Or at least i cannot find it.

**Comment by zhedar** [comment]
@fourtytwo I guess [that's what you're looking for](https://github.com/TheCoder4eu/BootsFaces-examples/blob/master/src/main/webapp/dashboard.xhtml).
The examples were migrated to their own project.
