### ISSUE TITLE
Validation error style classes problem

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#621]
Sorry to bother you guys, but I'm pretty sure there's a problem with error style classes.
Here's the HTML from your showcase of a input text with failed validation:
![input_with_error](https://cloud.githubusercontent.com/assets/18428155/22100693/09bf4554-de31-11e6-9c50-81db20ebc624.jpg)
The issue is that the `has-error` class should be added to the `form-group` `div`, not to the `label` or `input` elements; source: http://getbootstrap.com/css/#forms-control-validation
Also, the `bf-error` class and its equivalents should be removed, or at least have no default css rules, because they override bs default styles.

**Comment by stephanrauh** [comment]
The Bootstrap style looks better, too.

I just wonder how to implement this without breaking backward compatibility. I'm sure many developers rely on the bf-* classes.

**Comment by stephanrauh** [comment]
@TheCoder4eu @zhedar @asterd Any thoughts on this? I'd love to collect your feedback before I start implementing something and breaking the applications of several thousand developers.

**Comment by TheCoder4eu** [comment]
@stephanrauh it depends on how they rely on the bf-* classes.
If they rely only on its presence, we just need to keep adding this classes as before removing the associated styles and applying in addition the Bootstrap classes correctly.

**Comment by TheCoder4eu** [comment]
@stephanrauh can we close this issue too?

**Comment by TheCoder4eu** [comment]
@stephanrauh can we close this issue?

**Comment by stephanrauh** [comment]
I'd like to keep this ticket open. I think we should support the Bootstrap approach, tool

**Comment by sergiowww** [comment]
I've been hung up on the same problem, the `has-error` class should be added to the `form-group` container. Neither the input field nor to the field's label should receive feedback classes, it is exactly what @NicolaIsotta said. I've cloned the project and I'll submit a PR as soon as I fix it, I don't know if this issue has been fixed, so please, if anyone have any news about it, keep us updated!
![error](https://cloud.githubusercontent.com/assets/8181382/24158956/909df24c-0e3c-11e7-978f-e3e5140f2812.png)
!

**Comment by stephanrauh** [comment]
OK, go ahead!

For the sake of backward compatibility, please make the error classes configurable:

- check the parameter `legacyErrorClasses` of the web.xml:
  `BsfUtils.getInitParam("net.bootsfaces.legacy_error_classes");`
- render the old (and wrong) style if the parameter is set to true
- render the new style if the parameter is empty or false

Thanks in advance!
Stephan

**Comment by sergiowww** [comment]
Copy that! Thanks!

**Comment by sergiowww** [comment]
The Pull Request is ready for approval!

**Comment by stephanrauh** [comment]
I've merged the PR. Todos left:

- [ ] document the feature
- [ ] double-check if the PR already covers every component able to display error messages

**Comment by stephanrauh** [comment]
The feature is still broken with:
- [ ] `<b:colorPicker>`

**Comment by TheCoder4eu** [comment]
@stephanrauh , did the commit 2ab0b09 fix also Slider and Slider2?
We can close this issue?

**Comment by stephanrauh** [comment]
It solved the bug partially. But it's good enough to close the issue.
