### ISSUE TITLE
Too aggressive css rule?

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#624]
Link: https://github.com/TheCoder4eu/BootsFaces-OSP/blob/028cd7d37fc292991e22812b494f69fa6ffe75c6/gradleResources/staticResources/css/bsf.css#L30
Is there a reason why this rule overrides bootstrap defaults? Inputs inside tables have a bad-looking bottom-margin becuase of it. Example:
![margin](https://cloud.githubusercontent.com/assets/18428155/22202801/25901a10-e16a-11e6-942a-69bc2bd8ba47.jpg)
Bootstrap default:
![without margin](https://cloud.githubusercontent.com/assets/18428155/22202852/6797c836-e16a-11e6-9b43-7ab82df4ff8f.jpg)

**Comment by stephanrauh** [comment]
I can only guess. When I wrote the inputText component, I implemented the markup in a wrong way, and this might have been an attempt to fix this. I think we can safely remove this line. Actually, the result of the offending line already puzzled me for a long time. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Everything seems to be ok after the change.

**Comment by stephanrauh** [comment]
@NicolaIsotta Is the odd vertical alignment of this demo caused by non-standard HTML code?

![image](https://cloud.githubusercontent.com/assets/3045767/22220336/989128f8-e1ae-11e6-9370-1af67b43d2a5.png)

**Comment by NicolaIsotta** [comment]
The markup is not really wrong, but to remove the bottom margin from the inputs I think you have to add the `form-inline` class to the `h:panelGrid`
