### ISSUE TITLE
b:touchSpin doesn't work when setting fieldId

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#625]
As the title. I've already prepared a PR to fix this. Also, the PR will fix the wrong `label` `for` attribute of `b:inputText`, `b:inputSecret` and `b:touchSpin` when using the `fieldId`.

**Comment by stephanrauh** [comment]
I'll have a thorough look at it tomorrow. I've browsed quickly over your source code. At first glance, it looks good. Thanks!

**Comment by stephanrauh** [comment]
OK, you PR looks good. Thanks!
