### ISSUE TITLE
b:image used with value only display warning when it shouldn't

### ISSUE THREAD

**Issue by LorenzoMcMaster** [TheCoder4eu/BootsFaces-OSP#627]
<b:image value="mypic.jpg" style="width: 250px" />
When setting JSF DEVELOPEMENT mode b:image always shows that warning:

[WARNING ] Please use either the 'value' attribute of b:image, or the 'name' and 'library' attribute pair. If all three attributes are provided, BootsFaces uses the 'value' attributes, ignoring both 'name' and 'library'.

**Comment by stephanrauh** [comment]
Strange bug. Thanks for reporting!
