### ISSUE TITLE
b:dataTable doesn't use browser language

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#628]
As the title, I've already prepared a PR which contains two other small fixes.

**Comment by stephanrauh** [comment]
@NicolaIsotta I've uploaded a new version of the snapshot to Maven Central, and I've added a demo on the showcase. But I don't know how to test the feature. There used to be a Google Chrome setting allowing me to switch the default language, but it's gone :(. Do you have an idea?

http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf (search for Internationalization)

**Comment by NicolaIsotta** [comment]
@stephanrauh 
Just put `<f:view locale="#{someBean.locale}"/>` somewhere in the xhtml.

Into 'someBean', which should be `SessionScoped`:

```java
private String locale; // getter and setter

@PostConstruct
public void postConstruct() {
    this.locale = FacesContext.getCurrentInstance().getViewRoot().getLocale().getLanguage();
}
```

Then, in DataTable.xhtml, add a `b:selectOneMenu` with `#{someBean.locale}` as the value and some `selectItems` with the possible languages.

**Comment by stephanrauh** [comment]
Adding the selectItem with `itemValue=#{localeBean.locale}' isn't exactly the same as the auto-detection you've implemented :). But you're right, I remember faintly that we used to add a locale setting to the root tag. But if I've got you right, simply omitting the `lang` and `lang-url` tags (or setting them to null) should do the trick. Which is what my demo does.

**Comment by NicolaIsotta** [comment]
Yes, if both the values are missing or null the Language is evaluated from the viewroot. Anyway, I think Firefox have the accepted-languages configuration if you need to test.

**Comment by stephanrauh** [comment]
Oh. It's an OSX problem. You can set the browser language of Chrome in Windows, but not in OSX. The Mac version always uses the system default language. Now my MacBook speaks Spanish to me, and the datatable does the same, too.

Probably it would have been simpler to install Firefox :).
