### ISSUE TITLE
Feature request: Ajax status indicator

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#633]
I think this can be a nice addition to:

https://showcase.bootsfaces.net/layout/Spinner.jsf

... or it could be a new component.
See also:

http://www.primefaces.org/showcase/ui/ajax/status.xhtml

http://stackoverflow.com/questions/7880843/show-loading-progress-when-making-jsf-ajax-request

**Comment by stephanrauh** [comment]
We've got something similar: http://showcase.bootsfaces.net/forms/blockUI.jsf. Does this match your requirements? What could we add or improve?

**Comment by jepsar** [comment]
I've read the documentation in the showcase. That is what I needed. Thanks.

Let me see how the customization works out. I don't want to change the screen that much, just show a spinning cog somewhere in a corner.

Maybe it would be nice to have component where you could use the body to set the loading message and CSS. For now a bit of script is fine with me (it will end up in a template anyhow).

**Comment by jepsar** [comment]
Additionally, maybe the documentation could be improved. This feature was hard to find. Maybe it could be referenced in https://showcase.bootsfaces.net/forms/ajax.jsf

**Comment by stephanrauh** [comment]
@jepsar I agree. I'm a bit unhappy with the documentation because it's hard to find anything unless you already know where it is. I'd like to add a search engine, but I haven't found the time yet to implement or integrate it.

**Comment by stephanrauh** [comment]
I've added the link to the documentation page. Is there anything else we can do to improve the feature?

**Comment by jepsar** [comment]
You can close this issue if you like. I haven't had time to play with the styling. If there are any problems there I'll create a new issue on Git.

Thanks!

**Comment by stephanrauh** [comment]
OK!
