### ISSUE TITLE
Improvement: poll interval attribute type could be more lenient

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#637]
Now it requires you to use a String. When you use EL to calculate a value on the fly, like `#{1000 * user.refresh}`, it will result in a Long which is not accepted. It would be nice if it accepts instances of String or Number (int value).

I'm on 1.0.2

**Comment by jepsar** [comment]
I'll submit a pull request

**Comment by stephanrauh** [comment]
I've merged the pull request. Todos left:

- [ ] testing
- [ ] updating the documentation
