### ISSUE TITLE
b:selectBooleanCheckbox doesn't support horizontal forms

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#643]
As the title says. I think I can prepare a PR, but there's another one pending and I'd prefer not to mix things up.

**Comment by stephanrauh** [comment]
Thanks for offering a PR! I hope we'll be able to review your PR soon. I'm sorry we're so slow. Sometimes work life can be very demanding.

BTW, it's possible to create two pull requests at the same time. I didn't do it myself yet, but as far as I remember, the general idea is to create pull requests from separate branches.

**Comment by NicolaIsotta** [comment]
@stephanrauh 
Here's the modified code of `SelectBooleanCheckboxRenderer`: http://pastebin.com/raw/Q3BQGk60
To use it, you have to add `IResponsiveLabel` interface to `SelectBooleanCheckbox` and `+responsiveLabel` to `widget selectBooleanCheckbox` in the jsfdl file.
Quick preview:
![preview](https://cloud.githubusercontent.com/assets/18428155/23863551/67f108f2-0810-11e7-95b4-683cbcbff820.jpg)

**Comment by stephanrauh** [comment]
I've integrated your patch into BootsFaces. At first glance, it looks great. Thanks! 

I've also uploaded a new snapshot version of BootsFaces to Maven Central. 

Todo left: 
- [ ] document the new feature in the showcase
