### ISSUE TITLE
selectOneMenu in navBar form aligned right

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#645]
Hi,
sorry to break rules of bug reporting but firstly i wanted to say i like BootsFaces a lot and looking forward to the next release.

BootsFaces 1.0.2

If I add a selectOneMenu to a navbar and align it to the right it seems to bleed outside of the navbar.  also i could not get b:selectOneMenu to fire ajax event in this situation so i fell back to h:selectOneMenu.
```xml
<b:navBar>
		<h:form styleClass="navbar-form navbar-right">
			<h:selectOneMenu id="something"
				value="#{myBean.something}">
				<f:selectItem itemLabel="No filter" itemValue="0" />
				<f:selectItems var="something"
					value="#{myBean.somethings}"
					itemLabel="#{something.name}"
					itemValue="#{something.id}" />
				<f:ajax listener="#{myBean.changeSomething}" />
			</h:selectOneMenu>
		</h:form>
        ..more navLinks
</b:navBar>
```

the problem is worse inside b:row and b:column.  the selectOneMenu floats right outside the navBar and gets covered over by any content in second column
```xml
<b:row>  
    <b:column col-md="9">  
        ...navBar inside here  
    </b:column>  
    <b:column col-md="3">  
        ....stuff here overlays the selectOneMenu  
    </b:column>  
</b:row>
```

**Comment by stephanrauh** [comment]
Never mind breaking the rules. Not for breaking them in such a kind way :). We're glad you like BootsFaces!

**Comment by stephanrauh** [comment]
As for the second case: Putting the navbar into a column is not what the makers of Bootstrap had in mind. So it's not surprising the navbar doesn't respect the nine columns width. I'd expect it to cover 100% of the available space (all 12 columns). Is that what you've seen?

As for the first bug: have a look at our showcase: https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/applayout/navbartop.xhtml. There, we use this code:
```xml
 <b:navbarLinks pull="right">
        <h:form style="display:inline" styleClass="form-inline">
          <b:selectOneMenu ...>
          </b:selectOneMenu>
        </h:form>
</b:/navbarLinks>
```

Does this approach solve your problem?

**Comment by chongma** [comment]
re: navbar in column
the navbar itself is perfectly aligned and functional.  it is only the selectOneMenu that goes off to the side.

i just tried your suggestion and it didn't work for me.  is that example live at a demo page so i can see it working?  i am using Chrome browser.

**Comment by stephanrauh** [comment]
This seems to be a peculiarity of Bootstrap. I suggest you simply override the default setting by adding `style="margin: 0"` to the form.

![image](https://cloud.githubusercontent.com/assets/3045767/24157638/38d92dec-0e5a-11e7-95eb-4842e21750ef.png)
