### ISSUE TITLE
b:dataTableColumn rendered

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#647]
The rendered attribute partially works for b:dataTableColumn although it is not documented.  it hides the column but breaks pagination

**Comment by stephanrauh** [comment]
Sounds like something we need to investigate.

**Comment by stephanrauh** [comment]
Both remarks seem to have vanished in the meantime. The documentation covers the `rendered` attribute, and when I ran a test, pagination worked fine.
