### ISSUE TITLE
prepend + append facets with buttons ko ?

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#649]
Hi,

Perhaps a regression on prepend and append facets.
It seems to be the continuation of issue #511

Bootfaces 1.0.2 : I encounter no rendering for text value and icon buttons. The css is also broken, because the button has not the same height than the associated component.
Tested with inputText.

Regards

**Comment by stephanrauh** [comment]
I can't find a bug. Have a look at [our showcase](http://www3.bootsfaces.net/Showcase/forms/inputText.jsf#prependingButtons). Both the prepended and the appended button are rendered fine. Can you explain in more detail what the error is, and how to reproduce it?

**Comment by stephanrauh** [comment]
I'll close the issue now. I'm ready to open it again if you send me a reproducer (i.e. a small but complete demo showing the bug).
