### ISSUE TITLE
b:commandButton and b:navBarLinks don't support custom icons

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#65]
Currently BootsFaces command buttons can display GlyphIcons and FontAwesome icons. NavBarLinks can't display icons at all. As user on StackOverflow asks: Wouldn't it be nice to display arbitrary icons?

Also see http://stackoverflow.com/questions/25648748/create-a-custom-icon-for-bnavlink.

**Comment by TheCoder4eu** [comment]
For navBarLinks we can have a look how to add a icon.

To add a custom icon, we could add a new attribute, but the user will be responsible for creating/using a class that shows the icon.

**Comment by stephanrauh** [comment]
I just saw there already ```<b:navBar />``` already can display a custom icon:
```xml
<b:navBar brandHref="/index.jsf" inverse="true" brandImg="MandelbrotEarth1.png" />
```

**Comment by stephanrauh** [comment]
I suggest to add to add an ```image="URL" attribute to the commandButton. Plus, AFAI the HTML button can contains nested elements, so we should allow our commandButton to do so, too. This way our users gain a lot of flexibility, allowing things like this:
```xml
<b:commandButton action=#{bean.method}">
   This text
   <img = "some/image.png" />
   surrounds an image.
</b:commandButton>

**Comment by TheCoder4eu** [comment]
I would favor nesting, which has the advantage to allow control on Image sizing.

**Comment by yersan** [comment]
I'm taking care about this issue

**Comment by stephanrauh** [comment]
@yersan Did you already commit the implementation to the master branch? It tried to nest an iconAwesome image within the command button, but it didn't work as expected (see the sixth button of http://www.bootsfaces.net/BootsFacesWeb/forms/commandButton.jsf).

**Comment by yersan** [comment]
Yes, I remember it that was merged into master by this pull request https://github.com/TheCoder4eu/BootsFaces-OSP/pull/123
It should work with nested <img> or <h:graphicImage>, but it seems that doesn't work with <b:iconAwesome>

Since I have worked with this issue before, I will check it to allow nested b:iconAwesome in the <b:commandButton>

**Comment by yersan** [comment]
@stephanrauh I can see that the src/main/webapp/forms/commandButton.xhtml page in BootsFacesWeb project has a wrong markup. 
It seems that accidentaly you have changed a `<b:commandButton>` by a `<h:commandButton>`. For this reason you cannot see the `<b:iconAwesome>` nested.

I have just changed it in my local computer and `<b:iconAwesome>` is nested in a `<b:commandButton>`. 
But using a `<b:iconAwesome>` has a quite different result than using icon attribute in  `<b:commandButton>`

I would expect to see the same result using this:
```xml
<b:commandButton icon="plus-sign" value="Non-Ajax Submit" id="cb" />
```
and this:
```xml
  <b:commandButton value="Non-Ajax Submit" id="cb" >
      <b:iconAwesome name="plus-sign" />
 </b:commandButton>
```

There is a blank space introduced by jsf value which results in a different image alignment in both cases.
It's not so much important but I'm going to review it.

**Comment by stephanrauh** [comment]
Let's close this issue. As far as I remember, Yeray has fixed the remaining issue.
