### ISSUE TITLE
b:alert icons with flatly theme

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#650]
i have not tested with other themes but i am currently using the flatly theme and when i use a b:alert it renders correctly but there is no icon.  there is a space where the icon should be.

might this also relate to problems i have experienced with font awesome?  a lot of the icons work but a lot are missing, e.g. when i use icon="calculator" or icon="newspaper" on a b:navLink it is just blank whereas some other ones render fine (calendar, credit-card).  i checked the version shipped with BootsFaces and looked at the list of icons and the ones i am trying to use should be present.

**Comment by chongma** [comment]
Submitted PR for adding a list of Font Awesome Icons at the bottom of the icons documentation.  Not sure this is necessary, and might even cause trouble with Font Awesome team, but I did it for testing.  All the icons seem to work ok in documentation project so still don't know why why some icons are missing in my project

**Comment by stephanrauh** [comment]
These lists have to be updated every once in a while. That's a potential source of trouble. On the other side, it looks useful to me. What about improving it even further? I.e. displaying the BootsFaces code to render the icon instead of displaying the class name?

While we're at it: the same list might be useful for the Glyphicons, too. Only Bootstrap 4 is going to drop Glyphicon support.

**Comment by stephanrauh** [comment]
I suppose this bug has something to do with your project setup. Let's close it. We can reopen it again if you manage to send us a reproducer (e.g. a tiny project on GitHub reproducing the bug).

**Comment by chongma** [comment]
is it possible that the icon attribute uses glyphicons and not font awesome?  that could explain why i only get a limited subset of icons.  when i just looked at the glyphicons list a lot of the icons are identical with the same name.  i will try to verify this.

**Comment by chongma** [comment]
BTW in particular i was using a b:navLink

**Comment by chongma** [comment]
just realised i should have been using icon-awesome attribute and not icon
