### ISSUE TITLE
b:dataTableColumn col-md etc

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#651]
Another thing I noticed that would be a really nice feature is if dataTableColumns could be hidden depending on the screen size to let tables fit better on different screen sizes. Eg col-md="true" col-sm="false".  not sure if that is possible?

**Comment by chongma** [comment]
quick update: after reading the documentation more thoroughly i found the `col-xx` attributes on `b:dataTable` in version 1.0.2.  this would be perfect to collapse the columns on smaller screen sizes. but it does not seem to work for me.  i added `col-sm="5" col-xs="3"` but it seemed to mess up the table formatting.  a `b:well` below the table mixed into the table and it did not collapse the table.  i will investigate further and find out if it is my fault or if there is a problem.

**Comment by stephanrauh** [comment]
@chongma Did you find a work-around? Or a solution?
