### ISSUE TITLE
how to add attributes to a dataTable?

### ISSUE THREAD

**Issue by mel-galvan** [TheCoder4eu/BootsFaces-OSP#657]
Hi, i'm a beginner using bootsfaces. I'm trying to create a dataTable with these options:

```xml
<b:dataTable value="#{dtFilterView.cars}" var="car" class="editableCarTable" paginated="false" scroll-size="400px" scroll-collapse="true">
...
</b:dataTable>
```

But when I click on a button which lets me edit each row, the next error is displayed:
DataTables warning: table id=j_idt5:j_idt7 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

I don't know if I'm making a mistake or what it's wrong...

**Comment by stephanrauh** [comment]
Try starting with the last example of https://showcase.bootsfaces.net/forms/DataTable.jsf. If that doesn't help, publish a more complete code snippet. Mind you: You've mentioned an error caused by clicking a button, but you didn't show us the source code of the button. 

Please report back, especially if you managed to solve the bug. We need the info to close the ticket.

**Comment by mel-galvan** [comment]
<b:dataTable value="#{dtFilterView.cars}" var="car" class="editableCarTable" multi-column-search="true" paginated="false" scroll-size="400px" scroll-collapse="true">
                            <b:dataTableColumn label="Id">
                                <b:inputText value="#{car.id}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.id}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Brand">
                                <b:inputText value="#{car.brand}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.brand}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Year">
                                <b:inputText value="#{car.year}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.year}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Color">
                                <b:inputText value="#{car.color}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.color}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Price">
                                <b:inputText value="#{car.price}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.price}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn>
                                <b:commandButton value="" icon="edit" ajax="true" update="@(.editableCarTable)" onclick="ajax:car.edit()"></b:commandButton>
                                <b:commandButton value="" icon="trash" ajax="true" onclick=""></b:commandButton>
                            </b:dataTableColumn>
                        </b:dataTable>

**Comment by mel-galvan** [comment]
`<b:dataTable value="#{dtFilterView.cars}" var="car" class="editableCarTable" multi-column-search="true" paginated="false" scroll-size="400px" scroll-collapse="true">
                            <b:dataTableColumn label="Id">
                                <b:inputText value="#{car.id}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.id}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Brand">
                                <b:inputText value="#{car.brand}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.brand}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Year">
                                <b:inputText value="#{car.year}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.year}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Color">
                                <b:inputText value="#{car.color}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.color}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Price">
                                <b:inputText value="#{car.price}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.price}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn>
                                <b:commandButton value="" icon="edit" ajax="true" update="@(.editableCarTable)" onclick="ajax:car.edit()"></b:commandButton>
                                <b:commandButton value="" icon="trash" ajax="true" onclick=""></b:commandButton>
                            </b:dataTableColumn>
                        </b:dataTable>`

**Comment by mel-galvan** [comment]
I've seen that documentation yet, but i don't know if using the custom-options attribute can help me to solve the problem. Here it's my whole code:
`<b:dataTable value="#{dtFilterView.cars}" var="car" class="editableCarTable" multi-column-search="true" paginated="false" scroll-size="400px" scroll-collapse="true">
                            <b:dataTableColumn label="Id">
                                <b:inputText value="#{car.id}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.id}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Brand">
                                <b:inputText value="#{car.brand}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.brand}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Year">
                                <b:inputText value="#{car.year}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.year}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Color">
                                <b:inputText value="#{car.color}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.color}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn label="Price">
                                <b:inputText value="#{car.price}" rendered="#{car.editable}" />
                                <h:outputText value="#{car.price}" rendered="#{!car.editable}" />
                            </b:dataTableColumn>
                            <b:dataTableColumn>
                                <b:commandButton value="" icon="edit" ajax="true" update="@(.editableCarTable)" onclick="ajax:car.edit()"></b:commandButton>
                                <b:commandButton value="" icon="trash" ajax="true" onclick=""></b:commandButton>
                            </b:dataTableColumn>
                        </b:dataTable>`

**Comment by stephanrauh** [comment]
There doesn't seem to be many differences with my version of the table. Probably you need to destroy the table before updating it. That's a bit ugly, because it makes the screen flicker.

You can do this using the widget variable. Currently (BootsFaces 1.0), there's no attribute widgetVar yet, so you best find out the name of the widget var using the developer tools of the browser. Basically, the name of the widget variable is the id of the datatable without the colons, plus the suffix Widget. For instance, the id of the datatable below is i18n:bcarPool2, so the code to call an AJAX request looks like so:

```xml
<form id="myForm">
<b:dataTable id="myGreatTable" ...
  <b:dataTableColumn>
     <b:commandButton update="@(.editableCarTable)" onclick="myFormMyGreatTableWidget.DataTable().destroy();ajax:car.edit()">  
     </b:commandButton>
  </b:dataTableColumn>
</b:dataTable>
```

**Comment by mel-galvan** [comment]
Thank you so much, it is working!

**Comment by mel-galvan** [comment]
Sorry, I've just realized that after a lot of times refreshing my page, when I click on the update button of a row, this row moves at the top of the table (e.g. from the fifth to the first row). When I click on the same button the row moves to its initial position (from the first to the fifth row).

**Comment by stephanrauh** [comment]
How come?

**Comment by mel-galvan** [comment]
I don't understand your question

**Comment by stephanrauh** [comment]
I just rebounded your question back to you :). I'm a bit puzzled. Which should the row move? Maybe the datatable is sorted by a column? You know, the sort algorithm doesn't cope with input fields.

**Comment by mel-galvan** [comment]
The problem is that if you click on the button to update the fifth row, then the row shouldn't move, but in my case it does. Doesn't matter if you click on the sixth, second or 100° row, it moves always to the top of the datatable to be updated and when I click the button again, it moves to its initial position.

**Comment by mel-galvan** [comment]
I just added the data-order attribute. Until now seems it works fine. I'll continue doing tests. Thanks :)

**Comment by stephanrauh** [comment]
Great! I wasn't optimistic I could help you with so little information. It's a nice surprise I manage to do this nonetheless!

**Comment by stephanrauh** [comment]
I've added some documentation about the data-order solution.

**Comment by mel-galvan** [comment]
Hi! I continue adding functionality to my dataTable. Thanks for helping me. Now I'm trying to modify the style of the the columns using my own CSS file, but I don't know how I can change width by the id. Currently I´m doing it by the classes 'nombreUsuario', 'usuarioUsuario' and 'tipoUsuarioUsuario', but I would rather use ids. Furthermore, I wish I could change the style of the inputs using id attribute too.

Here is my .xhtml code:
`<b:dataTable id="usuarios" value="#{dtFilterView.usuarios}" var="usuario" class="tablaUsuario" lang="es" paginated="false" scroll-size="400px" save-state="true">
	<b:dataTableColumn class="nombreUsuario" label="Nombre" data-order="#{usuario.nombre}">
		<b:inputText id="campoNombre" value="#{usuario.nombre}" maxlength="80" required="true" rendered="#{usuario.editable}" label="Nombre" onkeyup="this.value=this.value.toUpperCase()">
				<f:validator validatorId="validador_nombre"></f:validator>
		</b:inputText>
		<b:message for="campoNombre"></b:message>
		<h:outputText value="#{usuario.nombre}" rendered="#{!usuario.editable}" />
	</b:dataTableColumn>
	
	<b:dataTableColumn class="usuarioUsuario" label="Usuario" data-order="#{usuario.usuario}">
		<b:inputText id="campoUsuario" value="#{usuario.usuario}" maxlength="20" required="true" rendered="#{usuario.editable}" label="Usuario" >
			<f:validator validatorId="validador_usuario"></f:validator>
		</b:inputText>
		<b:message for="campoUsuario"></b:message>
		<h:outputText value="#{usuario.usuario}" rendered="#{!usuario.editable}" />
	</b:dataTableColumn>
	
	<b:dataTableColumn class="tipoUsuarioUsuario" label="Tipo de usuario" data-order="#{usuario.tipo_usuario}">
		<h:selectOneMenu id="selectorTipoUsuario" value="#{usuario.tipo_usuario}" disabled="#{!usuario.editable}"> 
			<f:selectItem itemValue = "Capturista" itemLabel = "Capturista" /> 
			<f:selectItem itemValue = "Observador" itemLabel = "Observador" />
			<f:selectItem itemValue = "Administrador" itemLabel = "Administrador" />
		</h:selectOneMenu> 
	</b:dataTableColumn>
   
	<b:dataTableColumn class="accionUsuario" label="Acción">
		<b:commandButton value="" icon="pencil" ajax="true" update="@(.tablaUsuario)" onclick="actualizacionUsuariosUsuariosWidget.DataTable().destroy();ajax:usuario.editar()"></b:commandButton>
		<b:commandButton value="" icon="trash" ajax="true" onclick=""></b:commandButton>
	</b:dataTableColumn>
</b:dataTable>`

And my little CSS code:
`.nombreUsuario{
    width: 10em!important;
}

.usuarioUsuario{
    width: 15em!important;
}

.tipoUsuarioUsuario{
    width: 10em!important;
}

.accionUsuario{
    width: 5em!important;
}`
