### ISSUE TITLE
b:dataTable with scroll-x="true" allign header/footer when no scroll required

### ISSUE THREAD

**Issue by Coolius70** [TheCoder4eu/BootsFaces-OSP#658]
When creating a datatable which does not fit into screen it is just drawn out f the container. By adding scroll-x="true" the table is scrollable when the browser window is smaller than the datatable. 
So far everything is fine, but when the browser window is big enough to hold the data table the search and navigation fields are not anymore right allign but some pixel to the right shifted which does not look very nice. See screenshots attached. Somehow it should be alligned everything to the same raster.

![grafik](https://cloud.githubusercontent.com/assets/12995510/24100602/36796d90-0d75-11e7-97ce-fe30bfae6afb.png)
![grafik](https://cloud.githubusercontent.com/assets/12995510/24100615/469737a2-0d75-11e7-975e-79d2f530f7c4.png)

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
