### ISSUE TITLE
New Features for the data table

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#659]
Alexander suggested in #389 to add these datatable features:
- [ ] Hidden Columns (https://datatables.net/examples/basic_init/hidden_columns.html)
- [ ] Row Grouping (https://datatables.net/examples/advanced_init/row_grouping.html)
- [ ] rowClasses (provided by JSF)
- [ ] Hover (CSS)
- [ ] Compact  (CSS)
- [ ] Index column (https://datatables.net/examples/api/counter_columns.html)

**Comment by lyahim** [comment]
Is it possible to add varStatus or index column will be solve the Datamodel nightmare?

**Comment by stephanrauh** [comment]
We've run out of team members. Let's close this ticket.
