### ISSUE TITLE
b:messages

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#66]
How do we want to display error messages? The standard Mojarra widget looks a bit odd in a BootsFaces dialog:

![image](https://cloud.githubusercontent.com/assets/3045767/6423010/11656986-bee0-11e4-9c26-ad55acf74c4e.png)

I suggest to invent a ```<b:messages />``` component.

**Comment by TheCoder4eu** [comment]
Yes this would be a nice addition.
We could take advantage of alert markup for multiple errors.

**Comment by stephanrauh** [comment]
I implemented and documented a simple ```<b:messages />``` component.
