### ISSUE TITLE
Dismiss modal

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#660]
I have declared and shown a modal as below which shows at render time.
```xml
<b:modal title="Unseen news item" styleClass="modalUnseen" closable="false" close-on-escape="false" backdrop="false">
    ...
</b:modal>
<script type="text/javascript">
    $(window).load(function() {
        $('.modalUnseen').modal('show');
    });
</script>
```
i cannot trigger an ajax action from a `b:commandButton` inside the modal therefore i cannot use `dismiss="modal"`.  `h:commandButton` triggers ajax but in the backing bean
```java
RequestContext requestContext = RequestContext.getCurrentInstance(); 
requestContext.execute("$('.modalUnseen').modal('hide');");
```
only hides the modal but the transparent overlay remains and i cannot click anything on the screen

**Comment by chongma** [comment]
by the way this is the code i tried for `b:commandButton`
```
<f:facet name="footer">
    <h:form>
        <b:commandButton value="Ok" look="primary" ajax="true" dismiss="modal" onclick="return false;" action="#{myBean.someAction}" />
    </h:form>
</f:facet>
```
there seems to be no effect of clicking the button

**Comment by stephanrauh** [comment]
The button doesn't do anything because of the `onclick="return false;"` bit.

**Comment by stephanrauh** [comment]
Does it make any difference if you close the modal on the client side, using <b:commandButton `onclick="$('.modalUnseen').modal('hide');" />`?

**Comment by chongma** [comment]
It works with `onclick="$('.modalUnseen').modal('hide');"`. i tried previously without the `onclick="return false;"` which didn't work. I will check `dismiss="modal"` when i get back to my desk. Is the context wrong for using primefaces to run JavaScript from managed bean?

**Comment by chongma** [comment]
`dismiss="modal"` does not work in this way `<b:commandButton ajax="true" dismiss="modal" value="Action" look="primary" action="#{myBean.action}"/>`.  Should modal be the class name of the modal?

**Comment by chongma** [comment]
i have also tried `oncomplete="$('.modalUnseen').modal('hide');"`.  this has exactly the same effect as executing using Primefaces `requestContext.execute("$('.modalUnseen').modal('hide');");` .  so basically once the ajax event has been fired the transparent overlay prevents anything being clicked

**Comment by chongma** [comment]
hmmm i just realised that the `@Named` bean was `@RequestScoped`and now I have changed it to `@ViewScoped`it works using PrimeFaces `RequestContext`.  sorry for reporting as a bug when it was a misconfiguration

**Comment by chongma** [comment]
sorry this morning it is more obviously not working.  on a `h:commandLink` i cannot use `oncomplete="$('.modalName').modal('show');"` so i basically cannot execute any ajax before showing a modal.  if i use `b:commandButton` then it works but i do not want a button in that place.  is it possible to have a `b:commandLink`?  or find out why h:commandLink is not compatible?  another problem is `oncomplete="$('.modalName').modal('hide');"` does not work.  only `onclick`.  maybe i should make a project to demonstrate the problem?

**Comment by stephanrauh** [comment]
As far as I remember, we thought about introducing `b:commandLink` some time ago. But we didn't see any difference to the existing `b:navCommandLink`. Maybe you can simply use this one?

If you need to use `h:commandLink`for some reason, there's an alternative to the `oncomplete` attribute:
```javascript
<script>
jsf.ajax.addOnEvent(function (data) {
		if (data.status === 'begin') {
			// this is equivalent to onstart
		}
		if (data.status === 'complete') {
			// this is equivalent to oncomplete
		}
		if (data.status === 'success') {
			// this is equivalent to onsuccess
		}
	});
</script>
```

**Comment by chongma** [comment]
`b:navCommandLink` is bold and acts as a block level element so it is not ideal.  although i tried it and it doesn't seem to support `f:setPropertyActionListener` or possibly `f:ajax` and fails to render.  the script you provided works but it fires for all links and i don't understand how to tailor it for one component.  does `data` contain the id of the component which fired the event?

**Comment by chongma** [comment]
i used `console.log(data);` and it has 3 attributes type, status, source.  source is the id of the component but seems to be unusable because it is autogenerated by JSF

**Comment by stephanrauh** [comment]
- Probably you're right about the drawbacks of `b:navCommandLink`.
- Yes, of course, the script fires for all events. The `source` attribute is (as to my memory) the attribute you're looking for. It's the clientId of JSF. Which may be a bit cumbersome to work with :(.

**Comment by chongma** [comment]
hi, sorry again.  i tracked it down to a REST error that wasn't giving any output.  it was causing inconsistent responses across various links.  the oncomplete seems to work fine with bootsfaces components.  i have not tested with standard JSF components.  thanks for your help and i will let you know if i run into any other problems

**Comment by stephanrauh** [comment]
Lucky me! This error really sounded scary! :)

**Comment by chongma** [comment]
i now realise this error is still happening under a specific condition and i have more information.  it could be that when using a `b:modal`with `backdrop="false"` that calling `oncomplete="$('.modalName').modal('hide');"` doesn't dismiss the transparent overlay.

**Comment by chongma** [comment]
hmm...spoke too soon.  it was because the `b:modal` was inside a form.  once it was moved outside it started working ok again
