### ISSUE TITLE
Column header are not scrollable

### ISSUE THREAD

**Issue by rajmylav** [TheCoder4eu/BootsFaces-OSP#664]
while creating <b:datatable> the column headers are not scrolling did any one get the same issue

**Comment by stephanrauh** [comment]
Please elaborate. What do you expect to happen, and what does happen? Do you scroll to the right or downwards? Do the column header scroll out of the page (along with the rest of the page), or are they fixed at the (x, y) coordinates? Maybe a little screencast helps (for example taken by licecap, see http://www.cockos.com/licecap/).

**Comment by rajmylav** [comment]
while using the datatable column if I dont use 'scroll-size' it goes out of the window, if i use i.e. table columns and rows goes out of the screen, if use scroll-size i was able to see the horizontal scroller but the column headers are not scrolling only the data is being scrolled I need to embed datat table in any container as of i am using <b:panel> <b:dataTable></b:dataTable></panel>


One more question how I do the dynamic columns for e.g in primefaces we have something like <p:columns> is there any similar thing in bootsfaces in my code log the columns are generated on a dynamic logic is there any way to do that if so can you please provide me any sample app

**Comment by rajmylav** [comment]
while using the datatable column if I dont use 'scroll-size' it goes out of the window, if I use scroll-size i was able to see the horizontal scroller but the column headers are not scrolling only the data is being scrolled and the column headers get stuck, do I need to embed data table in any container??? as of now i am using <b:panel> <b:dataTable></b:dataTable></b:panel>

One more question how I do the dynamic columns for e.g in primefaces we have something like <p:columns> is there any similar thing in bootsfaces in my code the columns are generated on a dynamic logic is there any way to do that if so can you please provide me any sample app

**Comment by stephanrauh** [comment]
Most people consider the sticky headers a feature :). If you want to scroll the datatable without sticky headers, just surround it by a `<div>` like so:

```html
<div style="height: 200px; overflow-y: auto">
  <b:dataTable ...>
     ...
  </b:dataTable>
</div>
```

**Comment by stephanrauh** [comment]
As for the second question: no, we didn't implement dynamic columns yet. If you need them, please open a new ticket.

**Comment by rajmylav** [comment]
awesome it works but as i scroll horizontally the show entries and search block scroll out of the screen since we have datatable inside div, is there a way we can stick search label stick to the right irrespective of the table scroll

**Comment by rajmylav** [comment]
is there a way to loop b:dataTableColumn

**Comment by stephanrauh** [comment]
Currently, there's no option to wrap b:dataTableColumn in a `ui:repeat` loop. I'll keep the idea in mind, but currently, that's nothing we want to support in the short term. But that doesn't mean we've forgotten the feature request. Stay tuned!
