### ISSUE TITLE
Drop jQuery Slider in favor of Bootstrap Slider

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#665]
Bootstrap Slider ( http://seiyria.com/bootstrap-slider/ )
can be used without JQuery , just create an input element in the DOM, and then create an instance of Slider, passing it a selector string referencing the input element.

Drop jQuery Slider in favor of Bootstrap Slider (part of road to Vanilla JS).

**Comment by stephanrauh** [comment]
@TheCoder4eu We've announce this more than a year ago, and we've provided a good replacement. Let's do it!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
