### ISSUE TITLE
dateTimePicker label issue

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#666]
Hi all,

When I try to use dateTimepicker label attribute, in generated code couldn't display the popup box.
And an other notice, if label attribute missing the generated element can't get form-group wrapper div.

I use the latest version, 1.0.2 

Thank you,
Mihaly

**Comment by NicolaIsotta** [comment]
It's fixed in the latest snapshot. Snapshot showcase: http://www3.bootsfaces.net/Showcase/forms/DateTimePicker.jsf#embeddingInAForm

**Comment by stephanrauh** [comment]
@NicolaIsotta Thanks for the info!

@lyahim Would you mind to try the latest snapshot and confirm the bug has been fixed? See #369 on how to get it. Thanks in advance!

I'll close this issue, but I'll keep listening to updates.

**Comment by stephanrauh** [comment]
@lyahim  May I mention you in the kudos section of the BootsFaces 1.1.0 announcement post?

**Comment by lyahim** [comment]
Thank you @stephanrauh.
That's nice from you. :)
