### ISSUE TITLE
f:selectItem on selectOneMenu ignores passthrough attributes

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#667]
Passthrough elements on an `f:selectItem` element inside a `b:selectOneMenu` are ignored. This is a more feature request to enhance passthrough support than a bug report.

The following snippet shows the usecase.

```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <h:selectOneMenu value="#{index.opcion}">
                <f:selectItem itemLabel="Select one" pt:selected="selected" pt:hidden="hidden" />
                <f:selectItems value="#{index.opciones}" />
            </h:selectOneMenu>

            <b:selectOneMenu value="#{index.option}">
                <f:selectItem itemLabel="Select one" pt:selected="selected" pt:hidden="hidden" />
                <f:selectItems value="#{index.options}" />
            </b:selectOneMenu>
        </h:form>
    </h:body>
</html>
```

Checking the generated HTML you can check the `h:` component includes the specified passthrough attributes, while the BootsFaces one completely ignores them.

**Comment by stephanrauh** [comment]
I'm starting to understand why this feature does not work. Looks like a messy fix. Currently I'm searching for an elegant (which is to say: sustainable and maintainable) solution.

**Comment by stephanrauh** [comment]
I've fixed the bug and uploaded a new developer snapshot of BootsFaces-1.1.0 to Maven Central. See #369 on how to get it.

**Comment by ggam** [comment]
@stephanrauh That's great! I'll test it ASAP. Any stimated date on when 1.1.0 will be available?

**Comment by stephanrauh** [comment]
I hope it'll be an Easter egg. But currently, our team is so busy that I can't say for sure. In any case, you can speed up the process by helping us to test the version. Interested? If you are, drop me an email at "webmaster at beyondjava dot de".

**Comment by stephanrauh** [comment]
Oops - there was a typo in my e-mail address, so just in case you're reading the e-mail notification, it's "webmaster1".

**Comment by ggam** [comment]
Thanks for the info! I've sent you an email to the corrected email address.

Have you thought about releasing some kind of beta version? People may accept to use "unstable" versions, but relying on snapshots is more tricky as the artifact may change on each download
