### ISSUE TITLE
b:inputText doesn't call ajax events

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#668]
Hi

I'm using Bootsfaces 1.1.0-SNAPSHOT, and in the last few days I realized that the  `<b:inputText>` 
no longer executes actions via ajax, But I didn't change nothing in my code. Example:

`<b:inputText label="Cód" value="#{myBean.value}" onchange="ajax:myBean.onChangeField()" process="@this" update="someRegion @this" </b:inputText>`

It doesn't call the function. Same for `onblur`, etc.

Tks, Ruan

**Comment by stephanrauh** [comment]
I've modified the AJAX engine a couple of days ago, but I didn't expect the input field to break. I'll investigate the topic with top priority.

**Comment by stephanrauh** [comment]
@ruanfelisky After fixing the bug, I've uploaded a new snapshot of BootsFaces 1.1.0 to Maven Central. Would you mind to test the feature and report back whether the bug has been fixed?

**Comment by ruanfelisky** [comment]
@stephanrauh  I have tested and now it's ok, thank you.
