### ISSUE TITLE
jQuery loaded after user JS

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#669]
This seems to be related to #640 but I prefer to fill another issue just in case the solution for that doesn't automatically fix this one.

Take the following JSF page:

```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Facelet Title</title>
        <h:outputScript>
            $('body').html("hello 2");
        </h:outputScript>
    </h:head>
    <h:body>
        Hello from Facelets
        <b:dataTable rendered="false" />
    </h:body>
</html>
```

The hidden BootsFaces datatable just makes it add Bootstrap CSS, JS and jQuery, but they are added after user provided JS, making it imposible to use jQuery from it. 

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head id="j_idt2">
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <title>Facelet Title</title>
      <script type="text/javascript">
         $('body').html("hello 2");
      </script>
      <link type="text/css" rel="stylesheet" href="/mavenproject14/faces/javax.faces.resource/css/datatables.min.css?ln=bsf" />
      <link type="text/css" rel="stylesheet" href="/mavenproject14/faces/javax.faces.resource/css/default/core.css?ln=bsf" />
      <link type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
      <link type="text/css" rel="stylesheet" href="/mavenproject14/faces/javax.faces.resource/css/bsf.css?ln=bsf" />
      <!--[if lt IE 9]><script src="/mavenproject14/faces/javax.faces.resource/js/html5shiv.js?ln=bsf"></script><script src="/mavenproject14/faces/javax.faces.resource/js/respond.js?ln=bsf"></script><![endif]--><script type="text/javascript" src="/mavenproject14/faces/javax.faces.resource/jq/jquery.js?ln=bsf"></script><script type="text/javascript" src="/mavenproject14/faces/javax.faces.resource/jsf.js?ln=javax.faces&amp;stage=Development"></script><script type="text/javascript" src="/mavenproject14/faces/javax.faces.resource/js/tooltip.js?ln=bsf"></script><script type="text/javascript" src="/mavenproject14/faces/javax.faces.resource/js/bsf.js?ln=bsf"></script>
   </head>
   <body>
      Hello from Facelets
      <script type="text/javascript" src="/mavenproject14/faces/javax.faces.resource/js/datatables.min.js?ln=bsf"></script>
   </body>
</html>
```

Setting the target to head also doesn't help (the generated markup is still the same):

```xml
<h:outputScript target="head">
   $('body').html("hello 2");
</h:outputScript>
```

I'd expect BF assets to be loaded before mine. The same happens with `<h:outputStylesheet />`.

I'm not sure this is a BootsFaces "issue" or a JSF one.

**Comment by stephanrauh** [comment]
Try using `<h:outputScript>` with defining the target. When I tried, 

- `<h:outputScript target="head">` is put before the library imports generated by BootsFaces,
- <h:outputScript> is put at the end of the header (after the other library imports)
- <h:outputScript target="body"> is put at the end of the body, but before the body scripts added by BootsFaces.

**Comment by stephanrauh** [comment]
Note that you can't add more than one inline `<h:outputScript target="head">` script. So you can't add multiple inline scripts with different position attributes. However, this works well with external libraries.

If my hints didn't solve your problem, don't hesitate do re-open the ticket.

**Comment by ggam** [comment]
@stephanrauh Hi and thanks for the fast response!

I've tested what you say, but my results are differnet:

- position="last": I can't find that attribute on the documentation (https://docs.oracle.com/javaee/7/javaserver-faces-2-2/vdldocs-facelets/h/outputScript.html). Also, Mojarra 2.2.13 seems to ignore that attribute. What implementation have you tried?
- `<h:outputScript>` (without target) is rendered exactly where it's found. If I put it on the head, it gets rendered before BootsFaces js.

The other two cases work for me as you stated.

Also, are there any workarounds to the `<h:outputStylesheet />` case? There's no `target` on it and to override Bootstrap styling I need my CSS to be loaded after the library provided ones.

**Comment by ggam** [comment]
I've just tested PrimeFaces and there it works as you said: without `target`,  it gets rendered *after* library's scripts. So I guess this is indeed a BootsFaces bug?

**Comment by stephanrauh** [comment]
Yes, Mojarra ignores the attribute because it's a BootsFaces attribute. Unfortunately, some popular IDEs such as Netbeans mark the attribute with squiggly lines, and depending on the configuration, they even mark it as an error.

**Comment by stephanrauh** [comment]
As for the CSS files: move the CSS rules to an external file and use the position attribute. You can see the effect in our showcase. Sourcecode is at line 24-26 of the [pageTemplate.xhtml](https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/applayout/pageTemplate.xhtml).

**Comment by stephanrauh** [comment]
The behavior of <h:outputScript> (without target) is more or less random and may change with the implementation of Mojarra. That's why I prefer to use the `position` attribute. BTW, the implementation of the position attribute is in the [AddResourcesListener](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/listeners/AddResourcesListener.java) at line 585ff.

**Comment by ggam** [comment]
Adding `position="last"` to my code doesn't have any effect. Do I have to enable to listener in some way?

Also, just by including PrimeFaces on the classpath, outputScript without target is placed after any other else. Seems like PrimeFaces overrides the default behavior. Will have to check how they do that. Could BootsFaces do something similar?

In the meantime, I'll check the spec to see if it says something about this, and I'll fill an issue or write to the EG mailing list asking for a more explicit behavior. Thanks!

**Comment by stephanrauh** [comment]
Ah, that's the difference. I've tested the resource ordering with our showcase, and that includes PrimeFaces. Yes, you're right - the PrimeFaces team do reorder the resources (see the [HeadRenderer](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/renderkit/HeadRenderer.java) class.

The `AddResourcesHandler` is always activated. We've deliberately chosen this approach in order to maximize compatibility to LifeRayFaces and PrimeFaces. Maybe we could implement a `<b:head />` tag. BTW, PrimeFaces offers a similar way to influence the sort order. Instead of adding the `position` attribute to the `<h:outputScript>`, you put the `<h:outputScript>` in a facet named "first", "middle", or "last".

**Comment by ggam** [comment]
I've checked how it behaves with only standard JSF elements (no other library on classpath) and both Mojarra and MyFaces put users scripts before component assets, so it seems like PrimeFaces is the one changing the rules here.

The standard behavior seems clear, so what's needed then is a standard mechanism to reorder elements (I like what BootsFaces does). I'll open the issue for them.

In the case of BootsFaces and in order to simplify migration path for PrimeFaces users, would you consider adding a context-param option like `bootsfaces.ENABLE_PRIMEFACES_SCRIPT_ORDERING`?

Thanks a lot for you time helping to clarify this!

**Comment by stephanrauh** [comment]
You're right, adding such a context parameter may help many developers.
