### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by cattleyalinda** [TheCoder4eu/BootsFaces-OSP#67]
I used the datepicker, but its not working. The calendar does not appear when it is clicked. I used thw development tools in firefox to determine whar could be wrong. In the console under js it says, TypeError: $(...).datepicker is not a function.

I hope i can get a feedback on this matter.

Thanks

**Comment by stephanrauh** [comment]
Usually that's a missing Javascript resource, or incorrect load ordering of these resources. Please check the network tab of your browser's developer tools if everythings loaded correctly. Among others, there should be these three files:
* http://localhost:8080/BootsFacesWeb/javax.faces.resource/jq/jquery.js.jsf?ln=bsf
* http://localhost:8080/BootsFacesWeb/javax.faces.resource/jquery-ui-1.11.2.js.jsf?ln=jQuery
* http://localhost:8080/BootsFacesWeb/javax.faces.resource/jq/ui/datepicker.js.jsf?ln=bsf

If one of the file aren't loaded, or if they are loaded and initialized in a different order, you end up with the error message.

As a workaround, you could add ```<h:outputScript library="bsf" name="jq/ui/datepicker.js"         target="body"/>``` to your JSF file (if it's the datepicker.js that's missing or that's loaded to early).

**Comment by TheCoder4eu** [comment]
Can we close this?
