### ISSUE TITLE
DateTimePicker locale not defined

### ISSUE THREAD

**Issue by rickygil** [TheCoder4eu/BootsFaces-OSP#672]
Hi,
I'm trying to use the DateTimePicker component with the attribute "locale" set to "it", but a Javascript error is thrown. 
`Uncaught ReferenceError: it is not defined
    at HTMLDocument.<anonymous> (editActivity.jsf:16)
    at i (jquery.js.jsf?ln=bsf:2)
    at Object.fireWith [as resolveWith] (jquery.js.jsf?ln=bsf:2)
    at Function.ready (jquery.js.jsf?ln=bsf:2)
    at HTMLDocument.J (jquery.js.jsf?ln=bsf:2)`

This is the code I'm using on the latest version of Bootsfaces (1.0.2):
```html
<b:dateTimePicker locale="it" placeholder="Data di inizio" format="DD/MM/YYYY" />
```
Thank you all,
rickygil

**Comment by stephanrauh** [comment]
First analysis: the datetimepicker uses the locales of moment.js, and it seems that our moment.js copy doesn't include Italian.

**Comment by geopossachs** [comment]
in the current version 1.4.1 i could not reproduce the error

**Comment by stephanrauh** [comment]
Indeed. The error has gone away. I've added an example in Italian language to the showcase.
