### ISSUE TITLE
b:label and b:badge column sizes generated invalid Bootstrap markup

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#673]
Similar to #670, but now with `<b:label />`.

Example reproducer:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <b:container style="background-color:yellow;">
            <b:row>
                <b:label col-xs="12" text="This doesn't work" style="background-color: blue;" />
            </b:row>
            <b:row style="margin-top: 10px;">
                <b:column col-xs="12">
                    <b:label text="This works" style="display: block;background-color: blue;" />
                </b:column>
            </b:row>
        </b:container>
    </h:body>
</html>
```

![captura](https://cloud.githubusercontent.com/assets/2109040/24654178/e57710da-1938-11e7-9f1e-f8b1f5cc1e94.PNG)

Seems like label needs to be wrapped with a column and `display: block;`. The same happens when using `tinyScreen` and the like attributes.

I'll check the other components to see if they are also affected.

**Comment by stephanrauh** [comment]
Fixed. 

For some reason, the label doesn't seem to need the CSS inline style `display=block`, so I only added it for b:badge.
