### ISSUE TITLE
b:progressBar value should be required

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#674]
Using `<b:progressBar />` without a `value` attribute throws a NullPointerException. The attribute should be marked required or a default value (like 0) applied.

**Comment by stephanrauh** [comment]
Is it sufficient to mark it "required" in the taglib? If so, bug can be closed now.

**Comment by ggam** [comment]
Marking it as required on the taglib only serves to instruct IDEs AFAIK. The null pointer exception still happens. A FacesException explaining the problem would be more informative (apart from the required=true)

**Comment by stephanrauh** [comment]
OK!
