### ISSUE TITLE
Some components render invalid BS markup with col-XX attributes

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#675]
This is a followup from #673.

After testing all the "Bootstrap Widget" components from the showcase, I've found the following failing:
- [x] alert: needs column wrapper
- [x] carousel: needs column wrapper
- [ ] b:dropDown: no visual effect. I guess Bootstrap does not support it. Maybe the attributes could be removed on this component (as they have no effect anyway).
- [x] labels and badges: as reported on #673 
- [x] thumbnail: needs column wrapper
- [ ] tabView: missing col-XX attributes. Should they be added?
- [ ] Tree: haven't tested this. Will need to verify. Noted here just so I don't forget about it.
- [x] Socialshare: missing wrapper.
- [ ] slider2: missing col-XX attributes. Should they be added?
- [ ] canvas: needs column wrapper
- [x] messages: addressed by #715
Interestingly, all the components I've tested from the "Forms" section worked as expected.

**Comment by stephanrauh** [comment]
When I implemented the feature I was mostly interested in forms. But you're right, orthogonality is an important goal.

I don't think we'll manage to solve all this before Easter, so let's postpone it to BootsFaces 1.1.0+.

**Comment by ggam** [comment]
I plan to submit a PR for this soon. Could you please change the milestone to 1.1.0?

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
