### ISSUE TITLE
b:tree without value throws NullPointerException

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#676]
Not setting the value attribute on a `<b:tree />` results in an exception. I think this has to be supported in the same way the datatable shows a blank table when no value is set.

**Comment by stephanrauh** [comment]
Done. For some reason, the exception doesn't show on the HTML page, but at least there's a useful exception hinting at the cause of the error in the server log now.

**Comment by stephanrauh** [comment]
PR #708 modifies the behavior again. Now the tree doesn't throw an exception, but simply renders an empty tree. In other words, it doesn't render anything, but there's no error, either.
