### ISSUE TITLE
<b:selectOneMenu ajax="true" /> listens wrong HTML event

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#679]
A `<b:selectOneMenu value="#{...}" ajax="true">` generates a HTML `<select>` with a `onvalueChange` attribute. That's wrong as the HTML defined event is `onchange`. As a result, the event is never fired.

The workaround is to use `<f:ajax />`

The same happens on <b:inputTextarea />

**Edit by Stephan:** The error also occurs with `<b:selectBooleanCheckbox>`, `<b:colorPicker>`,  and `<b:selectMultiMenu>`.

**Comment by stephanrauh** [comment]
Now the `b:selectOneMenu` listens to the `change` event by default.

**Comment by stephanrauh** [comment]
Fixed <b:selectBooleanCheckbox>, <b:colorPicker>, and <b:selectMultiMenu>.
