### ISSUE TITLE
Support for mobile clients

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#68]
Just a few ideas:
- event listeners for touch and swipe gestures (see padilicious)
- adding support for native mobile widgets
- keyboard layout selection in input fields

**Comment by TheCoder4eu** [comment]
Nice Ideas (I'll have a look at padilicius), however there might be something under the hoods for Bootstrap 4.0 .

support for native mobile widgets: have a look at Ratchet http://goratchet.com/about/ although it seems non very up to date...

**Comment by stephanrauh** [comment]
Not quite. We've implemented b:shake and b:gyroscope. b:swipe and drag'n'drop support are still on our wish list. b:touch was just a placeholder for new ideas.

**Comment by stephanrauh** [comment]
It seems we can close the issue. The features don't seem to be in high demand among JSF developers.
