### ISSUE TITLE
b:selectBooleanCheckbox  converter is not called on form submit

### ISSUE THREAD

**Issue by LukaszCaputa** [TheCoder4eu/BootsFaces-OSP#684]
I have written a custom converter that converts Longs to Booleans as my Hibernate Entity uses a Long variable for Oracles Database Number(1) column. The conversion is working fine for displaying a page - that is, a long variable is indeed converted to boolean - but when i try to submit a form, an error message is displayed that boolean cannot be converted to long. It seems that boolean checkbox renderer is not using a converter to convert already converted value to their original form. 

```xml
<b:selectBooleanCheckbox value="#{chargeDetail.entity.pricedEvent}">
<f:converter converterId="boolConverter" />
</b:selectBooleanCheckbox>	
```

chargeDetail.entity.pricedEvent is a long
Error Message:
`serverError: class javax.faces.component.UpdateModelException Cannot convert false of type class java.lang.Boolean to class java.langLong`

**Comment by stephanrauh** [comment]
It's no excuse not to implement converter support, but standard JSF `<b:selectBooleanCheckbox>` [doesn't support converters](http://stackoverflow.com/questions/6356871/convert-hselectbooleancheckbox-value-between-boolean-and-string), either.

**Comment by stephanrauh** [comment]
The bug is fixed in BootsFaces 1.1.0-SNAPSHOP. I've also fixed the other form widgets of BootsFaces. Before the bugfix, only `<b:inputText>` and `<b:inputTextarea>` got it right.

**Comment by stephanrauh** [comment]
Now the converters are also documented: http://www3.bootsfaces.net/Showcase/forms/converters.jsf

**Comment by stephanrauh** [comment]
May I mention you in the "kudos" section of the BootsFaces 1.1.0 announcement post?

**Comment by LukaszCaputa** [comment]
sure, thank you !
