### ISSUE TITLE
Font Awesome loaded by default from CDN

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#686]
Font Awesome icons are loaded by default from CDN, in contrast to all other resources which are by default loaded from the Jar.

From what I see in the documentation, this seems unintended.

**Comment by ggam** [comment]
Also, when disabling loading from CDN via the context param, it doesn't load Awesome icons at all. Even when the b:iconAwesome component is used

**Comment by ggam** [comment]
My fault. It is explained on the Icons page.

Btw, what's the reason to not bundling it directly?

**Comment by stephanrauh** [comment]
The context parameter works as designed. But I think it's a bad design. Maybe we should deprecate the context parameter and replace it with another, less confusing parameter. For example:

```xml
    <context-param>
        <param-name>net.bootsfaces.fontawesome</param-name>
        <param-value>local</param-value>
    </context-param>
```
The values of the parameter could be `local`, `CDN`or `none`.

**Comment by stephanrauh** [comment]
Let's close the ticket after such a long time.
