### ISSUE TITLE
f:selectItems does not work with b:selectOneMenu

### ISSUE THREAD

**Issue by brolnik** [TheCoder4eu/BootsFaces-OSP#69]
Hi,

I try to create b:selectOneMenu with f:selectItems but all the time an exception 'javax.faces.component.UISelectItems cannot be cast to javax.faces.component.UISelectItem' is thrown. I have also copied sample code from http://www.bootsfaces.net/forms/selectOneMenu.jsf but effect is the same - the exception is thrown. When I use simple <f:selectItem> everything is ok. Please let me know if you need more information.

Regards,
Bartek

**Comment by stephanrauh** [comment]
The error message sounds like you've forgotten the plural s of f:selectItems. Can you upload your JSF file and the JSF bean, please?

**Comment by brolnik** [comment]
Sure, I am sending codes below

ManagedBean (session scope):

```
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;

/**
 *
 * @author developer
 */
public class ExampleBean implements Serializable {
    
    private List<String> words;
    private String word = "";
    
    @PostConstruct
    public void init() {
        words = new ArrayList<>();
        words.add("Car");
        words.add("Phone");
        words.add("Tree");
        words.add("Home");
    }

    public List<String> getWords() {
        return words;
    }

    public void setWords(List<String> words) {
        this.words = words;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

}
```

JSF page:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:include src="../templates/head.xhtml"/>
    <h:body>
        <b:container>
            <b:row>
                <b:column col-lg="6" offset-lg="3" >
                    <h:form prependId="false">
                        <b:panel look="success" title="Title">
                            <b:selectOneMenu value="#{exampleBean.word}">
                                <f:selectItems value="#{exampleBean.words}" var="wordVar" itemLabel="#{wordVar}" itemValue="#{wordVar}"/>
                            </b:selectOneMenu>
                        </b:panel>
                    </h:form>
                </b:column>
            </b:row>
        </b:container>
    </h:body>
</html>
```

**Comment by stephanrauh** [comment]
Your demo works like charm on my machine. I guess something else is wrong - maybe within the template. 

I've created a GitHub project (https://github.com/stephanrauh/BootsFaces-Examples/tree/master/Combobox) and uploaded the running program on http://angularfaces.net/BootsFacesCombobox/index.jsf. Hope it helps to find the error.

![image](https://cloud.githubusercontent.com/assets/3045767/6563007/10a36302-c69e-11e4-9981-5947faeb903c.png)

**Comment by brolnik** [comment]
Thanks a lot :) ! I use bootsfaces lib (v 0.6.0) integrated with bootswatch theme. Maybe I have made mistake and there is a problem. I have to check it and I will let you know.

Best regards,
Bartek

**Comment by stephanrauh** [comment]
Ah, I see. Now that you say it: I added ```<f:selectItems>``` in BootsFaces 0.6.5. It didn't make it into the New Years Eve version (0.6.0).

**Comment by brolnik** [comment]
Oh ok, I see. I will upgrade to the newest lib version soon. Thanks a lot for your help. I am going to close the issue. 

Best regards
