### ISSUE TITLE
icon, iconAwesome and carousel need to be in a form

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#692]
When using JSF in development mode (project stage = Development), a warning is registered when using the following components outside a form:
- icon
- iconAwesome
- carousel

This may happen on more components. For now I've only seen those.

At least in the case of icon and iconAwesome, I think it's because they are ClientBehaviorHolders. I don't know if we can prevent that warning when there are not behaviors attached.

**Comment by stephanrauh** [comment]
Oh. That really sounds odd. Good finding!

**Comment by stephanrauh** [comment]
Removing the `ClientBehaviorHolders ` deactivates AJAX. Currently, I don't understand exactly why, but this seems to be a topic we should investigate in the next version. Let's postpone it to BootsFaces 1.1.0+.

**Comment by stephanrauh** [comment]
I believe there's no easy way to improve this. Plus, there's a workaround. Wrapping the components in a form is inconvenient, but still, it works. Let's close the issue.
