### ISSUE TITLE
Add "value" attribute to b:alert

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#693]
Making `b:alert` extend UIOutput would reduce some boilerplate on simple alerts.
From:
```
<b:alert>message</b:alert>
```
To:
```
<b:alert value="message" />
```

**Comment by stephanrauh** [comment]
Recently someone suggested supporting both options for another component. This may be a general topic. For example, it applies to `b:badge`, `b:commandButton` and `b:well`.

**Comment by stephanrauh** [comment]
- [ ] b:alert
- [ ] b:label, 
- [ ] b:navLink, 
- [ ] b:navCommandLink and 
- [ ] b:badge
- [ ] b:well
- [ ] b:commandButton

**Comment by stephanrauh** [comment]
Done and documented. Most components already had the `value` attribute. In these cases, I didn't add the option to use the content of the tag.
