### ISSUE TITLE
Proposal for new b:tooltip and b:inputLabel components

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#696]
This is just and idea so please let me know what you think about it.

Most components implements the IHasTooltip interface, meaning they support all 5 options we now offer for tooltips. That not only means lots of duplicated code, but also using all of them is a bit verbose. Take this example:
```
<b:row>
    <b:column colMd="6" tooltip="Message" tooltipContainer="" tooltipDelay="" tooltipDelayHide="" tooltipDelayShow="" tooltipPosition="">
        Column context
    </b:column>
    <!-- ... -->
</b:row>
```

All that options just for the tooltip! Isn't that difficult to read?

I think we can gain expresiveness doing:
```
<b:row>
    <b:column colMd="6">
        <b:tooltip tooltip="Message" tooltipContainer="" tooltipDelay="" tooltipDelayHide="" tooltipDelayShow="" tooltipPosition=""/>
        Column context
    </b:column>
    <!-- ... -->
</b:row>
```
The tooltip would be attached to the parent component. Every component would be supported fairly automatically. Going this way, I would deprecate all the methods from the IHasTooltip interface, except "getTooltip". I would retain that single property to give support for basic use cases (probably 99% of cases).

And the same applies for input labels. I know there's an issue there considering the creation of a b:outputLabel.

The  IResponsiveLabel has the following methods:
```
public interface IResponsiveLabel {                                                                                                                 
	public String getLabelColXs();                                                                                                             
	public String getLabelColSm();                                                                                                             
	public String getLabelColMd();                                                                                                             
	public String getLabelColLg();                                                                                                             
	public String getLabelTinyScreen();                                                                                                        
	public String getLabelSmallScreen();                                                                                                       
	public String getLabelMediumScreen();                                                                                                      
	public String getLabelLargeScreen();                                                                                                       
}
```

All of them are supported on **every** input component. But you know the more common usecase is just `<b:inputText value="#{...}" label="Description" />`.

For more complex cases, instead on rendering the input and a label with the for attribute, I'd simply nest the the label inside the input:
```
<b:inputText value="#{...}">
    <b:outputLabel value="" colXs="12" colMd="6" />
</b:inputText>
```

That would generate the same markup we now have. Additionally, the use of the `for` attribute should be supported to allow for more complex scenarios.

To simplify rendering, Tooltip and InputLabel components would be dinamycally added when the "simplified" (`label`, `tooltip`) attribute is used. I know JSF has been difficult in the past in regard to dynamically modified component trees, but JSF 2.3 has finally stated that this is a supported feature, so I don't think this should be a real problem now.

This is obviously a proposal for a future version (1.5.0 or what comes next).

What do you think?

**Comment by chongma** [comment]
i like the idea as it can get messy putting all the options in the parent.  how hard is it to make `b:tooltip` support `h:outputText` as well?  is it hard to extend base components?

**Comment by stephanrauh** [comment]
Before we start removing attributes that are already there, I suggest waiting for BootsFaces 2.0. This version, in turn, isn't far away. It's simply the version of BootsFaces supporting Bootstrap 4. In other words, we should start work on BootsFaces 2.0 soon.

Other than that, it sounds like an interesting idea. My goal is to make JSF simple and fun.

**Comment by ggam** [comment]
My idea was to deprecate, never remove attributes, on the 1.X branch. Doing so would allows us to experiment and innovate, and them from that base, remove "failed" and deprecated stuff on 2.0.

That way 2.0 would start over a solid foundation of innovative ideas.

**Comment by stephanrauh** [comment]
I still like the idea, but I don't see how our small team can implement it any time soon. So I'll close the ticket reluctantly.
