### ISSUE TITLE
b:message rendering can be improved

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#701]
- a `null` may appear in the generated `class` attribute
- if there is a `col-` class, wrap the alert in an outer div (see #675 )

I've already prepared a PR

**Comment by stephanrauh** [comment]
@NicolaIsotta The change looks OK to me. Thanks!

I've got two questions:
- [ ] Do we have to add something to the documentation? (http://www3.bootsfaces.net/Showcase/forms/messages.jsf)
- [ ] What about `b:messages`? Should we improve it in the same way as `b:message`?

**Comment by stephanrauh** [comment]
Done and documented.
