### ISSUE TITLE
GPL Licence in POM

### ISSUE THREAD

**Issue by PokimonZerg** [TheCoder4eu/BootsFaces-OSP#707]
What does it means? I see Apache license on github page, but GPL in POM.
Can I use BootsFaces in commercial project?

```xml
<licenses>
		<license>
			<name>GNU General Public License (GPL) version 3.0</name>
			<url>http://www.gnu.org/licenses/gpl-3.0.txt</url>
		</license>
		<license>
			<name>GNU Lesser General Public License (LGPL) version 3.0</name>
			<url>http://www.gnu.org/licenses/lgpl.txt</url>
		</license>
	</licenses>
```

**Comment by stephanrauh** [comment]
Oops! We've updated the license in several hundred files but missed the pom.xml. I've fixed that. 

You can use BootsFaces in commercial projects with only a few limitations.
