### ISSUE TITLE
Style support for Button / CommandButton

### ISSUE THREAD

**Issue by MSzturc** [TheCoder4eu/BootsFaces-OSP#71]
It seams that style property of Button gets ignored on rendering:

Example:
```
<b:commandButton id="xxx" value="Register" style="width: 100%"/>
```

creates the following html code:
```
<button type="submit" id="login:Register" name="Register" class="btn btn-default">Register</button>
```

i would expect:
```
<button type="submit" id="login:xxx" name="login:xxx" class="btn btn-default" style="width: 100%">Register</button>
```

**Comment by TheCoder4eu** [comment]
Hi,
I'll verify this ASAP, anyway I think we should add the styleClass standard JSF attribute for styling to
```
<b:commandButton>
```
Inline style is not a best practice and should be avoided unless you really have a meaningful use case in favor of CSS.

**Comment by MSzturc** [comment]
StyleClass was not availible in auto-completion.

**Comment by TheCoder4eu** [comment]
styleClass was not available in the attributes but was already supported by the component.
Added missing rendering of style attribute.

Tests Passed.
