### ISSUE TITLE
b:canvas needs wrapper div when using responsive features

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#711]
Seems like I forgot b:canvas on #694 

Additionaly, a `width:100%` should be added to the element when using them, so the canvas goes full width. That CSS should be moved to a new class so the user can still override it using `style`.

**Comment by ggam** [comment]
This may also need some JS to adjust width (see https://github.com/szimek/signature_pad#handling-high-dpi-screens)

**Comment by stephanrauh** [comment]
Now responsive design seems to work well. Thanks for the hint!
