### ISSUE TITLE
b:dataTable pager

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#719]
i don't know how much control you have over the layout but...
when i use a `b:dataTable` i click the pager to flick through the pages of data. if there is different amounts of data in each row the length of the table changes.  the result is that the pager flicks up and down so you have to move the mouse to click the next or previous buttons.  if it was moved to the top of the table it wouldn't bounce around.  also the "show x entries" is less important so it should go at the bottom with the page count.  search could go top left and pager top right...

**Comment by stephanrauh** [comment]
You can achieve this using the custom options and the `dom` property of Datatables.net. Here's the documentation: https://datatables.net/examples/basic_init/dom.html
