### ISSUE TITLE
b:row, b:column and b:container don't support style

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#72]
b:row, b:column and b:container don't support the style attribute.
b:container doesn't support the styleClass attribute.

**Comment by TheCoder4eu** [comment]
At least b:column does support it, I used it in Dashboard demo:
```
<b:column col-sm="3" col-md="2" styleClass="sidebar">
```
Source:
https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/web/examples/dashboard.xhtml

For b:row the attribute is defined in taglib, I have to verify if it is rendered.

**Comment by stephanrauh** [comment]
Yes, styleClass is supported by both b:row and b:column. Still, it would be nice to add inline CSS styles for "quick and dirty" experiments.

**Comment by TheCoder4eu** [comment]
The components:
- b:container
- b:row
- b:column
now render both style and styleClass attributes.

Tests Passed.
