### ISSUE TITLE
Typeahad with tags responsive doesn't work

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#721]
Can be seen on the Showcase: https://showcase.bootsfaces.net/forms/inputTextWithTags.jsf

The problem is the placement of the col-xs div.

**Comment by geopossachs** [comment]
Hello @ggam,
will the Fix for Ticket #1081 also solve this problem reported by you? 

If not, you can give an example with a screenshot?

**Comment by stephanrauh** [comment]
@geopossachs I'm afraid ggam left our project in late 2017. So it's unlikely he'll answer your question. 

But what about you? You've sent us several good pull requests. Would you like to join our team? Drop me a mail at webmaster1 at beyondjava.de.

**Comment by geopossachs** [comment]
the current CSS styling
![grafik](https://user-images.githubusercontent.com/10324450/82148220-3bba6400-9853-11ea-8163-9ba3b35cf40a.png)

my solution - change the width - is not perfekt but okay :-)
![grafik](https://user-images.githubusercontent.com/10324450/82148250-64425e00-9853-11ea-8830-b1cfd2a7da4b.png)

**Comment by geopossachs** [comment]
@stephanrauh would this already be sufficient for a solution?

**Comment by stephanrauh** [comment]
Yes, I think that's an improvement. Thanks!
