### ISSUE TITLE
b:navLink without value prints "null"

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#722]
The following example: 

`<b:navLink outcome="inputText">the documentation of <code>&lt;b:inputText&gt;</code></b:navLink>`

Renders "nullthe documentation of <b:inputText>".

**Comment by stephanrauh** [comment]
I hoped to have fixed this bug with #716. Has something gone wrong?

**Comment by ggam** [comment]
I may have an outdated build on my machine. Let me check it.

**Comment by stephanrauh** [comment]
I've just tested it again. I believe the bug has been fixed.
