### ISSUE TITLE
Improve b:panelGrid integration with inputs

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#724]
I think this will be a bit tricky, but would be great if:

```xml
<b:form>
    <b:panelGrid cols="3,9">
        <b:inputText value="XX" label="zz" />
        <b:inputText value="XX" label="zz" />
    </b:panelGrid>
</b:form>
```

could be equivalent to:

```xml
<b:form>
    <b:row>
        <b:inputText value="XX" label="zz" labelColXs="3" colXs="9" />
    </b:row>
    <b:row>
        <b:inputText value="XX" label="zz" labelColXs="3" colXs="9" />
    </b:row>
</b:form>
```

Special integration for horizontal forms would be needed as well. Would really reduce boilerplate.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
