### ISSUE TITLE
Inputs on horizontal form should default to colXs="12"

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#725]
When using horizontal forms, a responsive class must be specified to prevent margin to be lost. Defaulting to colXs="12" fixes the problem reducing boilerplate. This would only work when no label is set though.

Also, when the size of either input or label is set, we can default the other one to 12-(specified size) so it goes full width.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
