### ISSUE TITLE
RTl doesn't work for labels of checkboxes 

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#727]
You can see it at https://showcase.bootsfaces.net/forms/checkBox.jsf (RTL support)

**Comment by stephanrauh** [comment]
The attribute `rtl="true"` had to be added to the `form-group` div. I hope that's not a general problem.

**Comment by ggam** [comment]
Thanks. We should check if this affects other components. I'm listing it to verify. Btw, I plan to continue working on the showcase tomorrow.
