### ISSUE TITLE
Target attribute in the b:navBar component

### ISSUE THREAD

**Issue by ErickPezoa** [TheCoder4eu/BootsFaces-OSP#728]
It would be neat to be able to open the brandHref in a new tab, similar to the <a> HTML tag target attribute: i.e: target=_blank. I posted SO question here: http://stackoverflow.com/questions/43572994/bootsfaces-navbar-open-brand-url-in-a-new-tab/43576748#43576748.

**Comment by stephanrauh** [comment]
I've implemented the feature as part of BootsFaces 1.1.0.
