### ISSUE TITLE
b:commandButton - title and rendered attribute are ignored

### ISSUE THREAD

**Issue by TomKrauss** [TheCoder4eu/BootsFaces-OSP#73]
* Setting the `rendered` attribute to false will not hide a command button as expected (e.g. using a value expression). I haven't checked this, but just from studying the code I would expect that this problem probably applies to other BootsFaces components (b:button, b:icon, etc...) as well
* The `title` attribute in command buttons is completely ignored - no title attribute is rendered in the HTML code.

**Comment by stephanrauh** [comment]
At first glance, this seems to be correct. Only b:row and b:column adhere to the rendered attribute. But then, those components are so beautiful, we simply couldn't imagine someone wants to hide them :).

As for the commandButton title: should we use an ordinary tooltip, or a Bootstrap tooltip (http://getbootstrap.com/javascript/#tooltips)?

**Comment by stephanrauh** [comment]
Done. Every BootsFaces component now respects the rendered attribute.
The CommandButton supports a standard HTML version of title. I'll open another ticket to add Bootstrap tooltips to every BootsFaces component.

**Comment by TomKrauss** [comment]
The design decision with the title attribute looks reasonable to me. Thank you very much for fixing this!
