### ISSUE TITLE
b:navCommandLink with iconAwesome and no value

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#730]
using 1.1.0-RC1 if i define `<b:navCommandLink iconAwesome="toggle-up"/>` it only outputs an empty `<li>` type bullet point.  if i add a value `<b:navCommandLink iconAwesome="toggle-up" value="test"/>` then i correctly get the icon and the text.

**Comment by chongma** [comment]
works fine as `<b:navCommandLink><b:iconAwesome name="toggle-up"/></b:navCommandLink>`

**Comment by stephanrauh** [comment]
Solved.
