### ISSUE TITLE
b:inputText labelColMd

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#735]
i have been using `<b:inputText label="something" value="#{myBean.myValue}" />` for a while because it looks nice and cuts down a lot on coding.  i noticed that there were the `labelColXx` attributes and thought these were intended to allow the label to layout next to the control.  i tried `labelColMd="one-third"` but it doesn't seem to have any effect other than add a couple of spaces in front of the label. does it need to be used in conjunction with `colMd="two-thirds"`?  if so fit does not seem to work on my setup

**Comment by ggam** [comment]
`labelColMd` is intented to be used with a numeric (1 to 12) value. If you want to use the special string, you'll need to use the `labelMediumScreen` attribute.

**Comment by chongma** [comment]
on my setup it does not work with numbers it is exactly the same.  i tried `labelColMd="3"`. also if it is only numeric then should the documentation be changed to reflect this?

**Comment by stephanrauh** [comment]
> labelColMd is intented to be used with a numeric (1 to 12) value.

My intention was to leave the programmer as much freedom as possible. If `labelColMd` requires numeric values, I'd consider this a (minor) bug. I'll check this later.

**Comment by stephanrauh** [comment]
Which HTML code should `<b:inputText label="something" labelColMd="one-third" />` render? 

Currently it renders this HMTL code:

```html
<div id="j_idt174" class="form-group">
  <label for="input_j_idt174" class=" col-md-4 control-label">something</label>
  <input id="input_j_idt174" name="input_j_idt174" type="text" class="form-control">
</div>
```
It works as designed, but this particular cornercase isn't really supported because we never defined the semantics of `labelColXX="4" colXX="(nothing)"`.

**Comment by chongma** [comment]
I tried adding both labelColMd and colMd earlier and it didn't help

**Comment by stephanrauh** [comment]
Let's track the bug down step by step. What's the behavior you expected? Or putting it the other way round, what did not happen after adding both `labelColMd` and `colMd`?

More technically speaking: which HTML code is rendered, and which HTML code do you want BootsFaces to rendered?

**Comment by stephanrauh** [comment]
@chongma May I "ping" you? :)

**Comment by chongma** [comment]
Sorry I never replied your to your previous comment

**Comment by chongma** [comment]
Sorry I closed the issue accidentally. I am on a phone. My understanding of the documentation was that defining those two attributes like
```
<b:inputText value="#{myBean.value}" labelColMd="3" colMd="9"/>
```
would lay out text input like
```
<b:row>
  <b:column colMd="3">
    <h:outputLabel value="something"/>
  </b:column>
  <b:column colMd="9">
    <b:inputText value=”#{myBean.value}”/>
  </b:column>
</b:row>
```
It doesn't seem to do that so maybe I don't understand it correctly

**Comment by stephanrauh** [comment]
If you're using horizontal forms, the HTML code looks almost like you're expecting:

```xml
<b:form horizontal="true">
  <b:inputText value="#{myBean.value}" labelColMd="3" colMd="9" label="My label"/>
</b:form>
```

generates
```html
<div id="j_idt20:j_idt21" class="form-group ">
  <label for="input_j_idt20:j_idt21" class=" col-md-3 control-label">My label</label>
  <div class="col-md-9">
    <input id="input_j_idt20:j_idt21" name="input_j_idt20:j_idt21" type="text" class="form-control">
  </div>
</div>
```

**Comment by stephanrauh** [comment]
You're right that the generated code for stacked forms is a bit odd. I think that's exactly the breaking change introduced by correcting the HTML code (#682, #685, #614, and #493).

**Comment by chongma** [comment]
is the problem that i am using `h:form` instead of `b:form`?  i tend to stick to `h:form` as i don't fully understand the difference

**Comment by ggam** [comment]
Responsive attributes only work on horizontal forms (b:form
horizontal="true").

For non horizontal forms, you'll need to at least create a b:row, and
possibly add the columns.

We could do it better here. Could you please post the whole html you would
expect to get? Having a full example we could search for better handling on
this on the next release.

**Comment by stephanrauh** [comment]
@chongma @ggam I've just seen that there is a difference between `h:form` and `b:form`, indeed. Both horizontal and inline forms require `b:form`. As far as I remember, the original design was a bit more lenient. You could use both tags. I've invented the BootsFaces version because it's the only way to get rid of the error messages of Netbeans, which doesn't accept non-standard attributes on JSF components.

**Comment by chongma** [comment]
you can probably close this bug?  i haven't tried horizontal b form or form-group as i don't have much time at the moment but i imagine it will work.  i read the documentation for labelColMd and colMd on inputText so i didn't see it related to the main horizontal forms documentation.

**Comment by stephanrauh** [comment]
I guess we've changed the meaning of horizontal, stacked and inline forms recently, confusing you and (probably) many other programmers. I hope this doesn't cause too many problems.
