### ISSUE TITLE
b:label puts col-XX both on its div and on its wrapper

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#741]
The following html gets rendered when using col-sm-4 on a label:

```
<div class="col-sm-4" id="j_idt231">
    <span class="label label-danger col-sm-4 ">small-screen='one-third'</span>
</div>
```

The col-sm-4 class should only be present on the outer div. This does not affect badges.

**Comment by stephanrauh** [comment]
Fixed. Like requested in #673, I also added `display="block"`. Apparently, that didn't work when I looked at the bug two weeks ago because of the double column definition.
