### ISSUE TITLE
b:label "text" attribute should be replaced by "value"

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#742]
For consistency purposes. I propose to deprecate it (and let if behave in the same way as value), and remove it on 2.0

**Comment by chongma** [comment]
yes i spotted the same today.  `text` is annoying as i expected it to be `value`

**Comment by chongma** [comment]
maybe not quite the same but `b:iconAwesome` uses default attribute `name` instead of `value`

**Comment by ggam** [comment]
I think `b:iconAwesome` and `b:icon` could be changed too. @stephanrauh we should maintain a list of newly deprecated attributes, as the documentation will need to be updated to reflect that (once I've finished the current task).

**Comment by ggam** [comment]
I've created an issue for that now: TheCoder4eu/BootsFacesWeb#41

**Comment by stephanrauh** [comment]
I've move the `b:icon` part of the the ticket to a dedicated ticket: #745
