### ISSUE TITLE
data-show support for modals

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#744]
The documentation currently states that the `data-show` attribute on modals isn't supported, but I think that's a misunderstanding of how data-show works: http://stackoverflow.com/questions/18855331/bootstrap-3-data-show-not-working

The modal needs some JS to be initialized. BootsFaces could support that by adding a new `show` attribute on the `modal` and then render the JS if needed.

**Comment by ggam** [comment]
That means that data-show is already supported. It just needs you to add the required JavaScript for it to work.

**Comment by stephanrauh** [comment]
@ggam Good point. Thank for pointing this out! I've corrected the documentation. Please have a look at it. Did I get it right this time?

¡muchas gracias!
Stephan

**Comment by frankyhoffmann** [comment]
dede
