### ISSUE TITLE
`b:iconAwesome` uses default attribute `name` instead of `value`

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#745]
This is a follow-up of #742. Many developers expect `b:icon` and `b:iconAwesome` to use the `value` attribute instead of the `name` attribute. So we should add support for `value` while deprecating `name`.

**Comment by jepsar** [comment]
What should be done with the mandatory `name`? Should both `value` and `name` be optional and an exception be thrown if none of the two is set when rendering?

**Comment by stephanrauh** [comment]
I've implemented and documented the feature, following the suggestion of @jepsar.
