### ISSUE TITLE
Create a JavaScript API for b:poll

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#746]
Currently, there's no good way to stop a `b:poll`. We should assign it an optional `widgetVar` and publish (or create) an API allowing to stop and to restart a running poll.

**Comment by jepsar** [comment]
I've also noticed that the poll fails when you have multiple instances of it. I could do some improvements there and add a `stop` attribute.

**Comment by jepsar** [comment]
When you update a poll you will get a new instance while the old instance remains active (maybe that is what you were referring to). Another thing that needs improvement is the `update` attribute. It now only takes a full clientId. You cannot use an id of an element that is in the same naming container.

**Comment by jepsar** [comment]
Please see PR https://github.com/TheCoder4eu/BootsFaces-OSP/pull/788

**Comment by stephanrauh** [comment]
@jepsar @TheCoder4eu It's a pity it's not possible to assign this issue to Jasper, too. After all, you, Jasper, have provided the solution. Or is there a way, and I just don't have the access privileges to do so?

**Comment by stephanrauh** [comment]
BTW, if I'm not mistaken, we can close this ticket. If I'm mistaken, just re-open it.

**Comment by jepsar** [comment]
One thing though, do you want me to add `(re)start` to the JS API?

**Comment by stephanrauh** [comment]
Sounds like a good idea to me. I don't know if the current implementation allows this feature, but if so, go ahead.
