### ISSUE TITLE
b:form regression

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#747]
- No warning when a form is horizontal and inline at the same time
- The horizontal and inline style classes are not generated

@stephanrauh , it seems like your commit https://github.com/TheCoder4eu/BootsFaces-OSP/commit/520b2ce6f6ae0028a032143c15706d28ae4e8136 caused the issue. Maybe the class has been overwritten by your jsfdl code generator?

**Comment by stephanrauh** [comment]
Fixed.

**Comment by ggam** [comment]
Could you please upload a snapshot with this fix?
