### ISSUE TITLE
growl isn't show

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#748]
Hi all,

In the new release 1.1.0, the growl component not shown at all. 
https://showcase.bootsfaces.net/forms/Growl.jsf

Best Regards,
Mihaly

**Comment by NicolaIsotta** [comment]
Could be caused by https://github.com/TheCoder4eu/BootsFaces-OSP/commit/520b2ce6f6ae0028a032143c15706d28ae4e8136

**Comment by stephanrauh** [comment]
Now b:growl works again. Seems like we need to publish a 1.1.1 soon.

**Comment by stephanrauh** [comment]
I've just uploaded the first snapshot of BootsFaces 1.1.1.
