### ISSUE TITLE
b:navLink

### ISSUE THREAD

**Issue by cristian3** [TheCoder4eu/BootsFaces-OSP#75]
navLink extends LInk and not CommandLink and you can´t call bean methods from navlink

**Comment by stephanrauh** [comment]
I suppose we don't want to break compatibility, but it sure would be nice do add ```actionListener``` and ```action``` as new options. How do you like the idea?

**Comment by TheCoder4eu** [comment]
+1 This is the JSF-ish way to go .

**Comment by stephanrauh** [comment]
I implemented a prototype of a new widget, ```<b:navCommandLink />```, which can process actionListeners. 

The original plan - adding action and actionListener to ```<b:navLink />``` - would break compatibility because both attributes require an HTML form. However, ```<b:navCommandLink />``` can be used in the same way as ```<b:navLink />```, so this shouldn't be a problem.

**Comment by stephanrauh** [comment]
Done (already published with BootsFaces 0.7.0).
