### ISSUE TITLE
b:formGroup can be used only inside horizontal forms

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#751]
I think there's no reason to forbid `b:formGroup` inside inline or stacked forms. For example, it could be useful to add some helper text under an input. Example:
![help text](https://cloud.githubusercontent.com/assets/18428155/25664181/22260052-301a-11e7-824a-192d3f954bb0.jpg)

**Comment by ggam** [comment]
Could you please post the xhtml of the screenshot? Isn't just what gets rendered when putting the text below the input?

**Comment by NicolaIsotta** [comment]
Consider this example:

	<b:column span="4">
		<b:formGroup>
			<b:inputText id="test1" label="Test 1" required="true"/>
			<span class="help-block">I'm inside the form group.</span>
		</b:formGroup>
		<h:commandButton value="Submit"/>
	</b:column>
	<b:column span="4">
		<b:inputText id="test2" label="Test 2" required="true"/>
		<span class="help-block">I'm outside, instead.</span>
		<h:commandButton value="Submit"/>
	</b:column>

The rendered output is:
![inside-outside](https://cloud.githubusercontent.com/assets/18428155/25693783/810c8ad2-30ab-11e7-80cb-b5e29c1c83a1.jpg)

Also, if the `help-block` is inside the `form-group`, it inherits the class:

	<b:formGroup style-class="has-success">
		<b:inputText id="test1" label="Test 1" required="true" value="blabla"/>
		<span class="help-block">Success!</span>
	</b:formGroup>

![success](https://cloud.githubusercontent.com/assets/18428155/25694351/80a073a8-30ae-11e7-846d-9555f31c1635.jpg)

**Comment by ggam** [comment]
I see. I only thought about `form-group` in the terms of a `row`, but this makes sense too. You are right, it should be usable also on non horizontal forms.
