### ISSUE TITLE
b:panel could have iconAwesome

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#753]
in the showcase the way to add an icon to a panel is to use a heading facet
```
<b:panel>
   <f:facet name="heading">
     <i class="fa fa-battery-three-quarters" style="padding-right:20px" />
     <h:outputText value="Battery charge left: 75% " />
     <b:badge style="margin-left:10px; background-color:#5cb85c" value="good"  />
   </f:facet>
   <h:outputText value="Panel Content"/>
</b:panel>
```
BTW this also seems to reduce the font size of the panel title

a nice enhancement might be to also be able to specify an icon using the icon and iconAwesome attributes.

**Comment by chongma** [comment]
if i give a `b:panel`a title it renders like
```
<div class="panel-heading"><h4 class="panel-title">Subjects</h4></div>
```
if i give it a

**Comment by TheCoder4eu** [comment]
@chongma , can I close this issue?

**Comment by chongma** [comment]
I submitted a PR. Did you merge? I was going to add an example to the showcase as well so it can be demonstrated

**Comment by TheCoder4eu** [comment]
@chongma if you are referring to #805 yes, I did merge.
