### ISSUE TITLE
Update DataTable 

### ISSUE THREAD

**Issue by bameur** [TheCoder4eu/BootsFaces-OSP#756]
This page is not working : https://www.bootsfaces.net/forms/DataTable.jsf !!

Hellp me ! update datatable not working 

	<h:form id="formAclUser">
								<b:dataTable id="tableAclUsers" value="#{modifyUser.aclUsers}" var="aclUser"
									class="aclUserTable">

									<b:dataTableColumn label="Id">
										<h:outputText value="#{aclUser.id}" />
									</b:dataTableColumn>

									<b:dataTableColumn label="Handle">
										<shiro:hasRole name="user">
											<h:outputText value="#{aclUser.handle}" />
										</shiro:hasRole>
										<shiro:hasRole name="admin">
											<b:inputText value="#{aclUser.handle}" immediate="true" onchange="ajax:modifyUser.eventTable()"/>
												
										</shiro:hasRole>
									</b:dataTableColumn>

									<b:dataTableColumn label="Depth type">
										<shiro:hasRole name="user">
											<h:outputText value="#{aclUser.depthType}" />
										</shiro:hasRole>
										<shiro:hasRole name="admin">
											<b:selectOneMenu value="#{aclUser.depthType}" immediate="true"  onchange="ajax:modifyUser.eventTable()">
												<f:selectItems value="#{modifyUser.depthTypes}" />
											</b:selectOneMenu>
										</shiro:hasRole>
									</b:dataTableColumn>

									<b:dataTableColumn label="Depth">
										<shiro:hasRole name="user">
											<h:outputText value="#{aclUser.depth}" />
										</shiro:hasRole>
										<shiro:hasRole name="admin">
											<b:inputText value="#{aclUser.depth}" immediate="true"  onchange="ajax:modifyUser.eventTable()"/>
										</shiro:hasRole>
									</b:dataTableColumn>

									<shiro:hasRole name="admin">
										<b:dataTableColumn label="Action">
											<b:commandButton value="" icon="trash" ajax="true" onclick="" rendered="#{aclUser.id != 0}"></b:commandButton>
											<b:commandButton value="" icon="plus" onclick="ajax:modifyUser.addACLUser()" rendered="#{aclUser.id == 0}" update="@form" />
										</b:dataTableColumn>
									</shiro:hasRole>

								</b:dataTable>
								</h:form>

**Comment by stephanrauh** [comment]
I've fixed the problem with the showcase.

As for your other bug: would you mind to tell us what's wrong?

**Comment by bameur** [comment]
The link problem is not yet settled !.

The first bug I noticed is that the update of the bean (java object) does not do it autematically. The second point: the update does not work too!

**Comment by bameur** [comment]
<shiro:hasRole name="admin">
<b:dataTableColumn label="Action">
	<b:commandButton value="" icon="trash" ajax="true" onclick="" rendered="#{aclUser.id != 0}"></b:commandButton>
	<b:commandButton value="" icon="plus" onclick="ajax:modifyUser.addACLUser()" rendered="#{aclUser.id == 0}"#  update="@form" />
</b:dataTableColumn>
</shiro:hasRole>

**Comment by bameur** [comment]
https://showcase.bootsfaces.net/forms/DataTable.jsf

Internal Server Error

**Comment by stephanrauh** [comment]
Forget about the showcase bug - it'll show until we've actually updated the showcase. And that's something I can't do myself. Stay tuned!

**Comment by stephanrauh** [comment]
> The first bug I noticed is that the update of the bean (java object) does not do it autematically.

The update of the Java bean doesn't do *what* automatically? 
(I guess that's one of the situations when you're trying to explain something to me that's absolutely obvious to you, but I don't get it because there's some context information missing).

**Comment by stephanrauh** [comment]
Let's close the ticket after more than two years.
