### ISSUE TITLE
Add severity filter to b:growl and b:messages

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#758]
I love the `b:growl` component to show info messages. When it comes to showing error messages the growl sucks. Errors should be shown until the user dismisses them. You could do that using `b:messages` component... but there an info message like "Your data has been stored" seems out of place to me. Messages like that should disappear after a short while (like in the growl).

I was checking out the Bootstrap Notify code to check if it was possible to have "sticky" messages, but it is not.

So I was kind of thinking if it would be a good idea to have an `ignoreSeverity` attribute on the growl and an `includeSeverity` attribute on messages. That way you could for example show all info messages in a growl and all warn, error and fatal messages in the messages component.

Does this make any sense to you?

**Comment by jepsar** [comment]
Or maybe add `severity` to both (same as the PrimeFaces growl). Let me see if I can provide a pull request for this.

**Comment by stephanrauh** [comment]
+1 for offering a PR!

Limiting the growl to certain severities makes a lot of sense to me. I just wonder what a good API might look like. Chances are people won't agree which messages to show via `b:growl` and which via `b:message`. Therefore, I'd like to see an API that's both as flexible as possible and as simple as possible at the same time.

**Comment by jepsar** [comment]
I've submitted a pull request for this issue:

https://github.com/TheCoder4eu/BootsFaces-OSP/pull/784

If it's accepted I could also update the showcase, or is it common practice to change both at once?

**Comment by stephanrauh** [comment]
In theory, it's common practice to update the showcase and the core library simultaneously. In practice, I'm happy with everything we get. Most people forget to send us a PR for the showcase :).

**Comment by jepsar** [comment]
OK. I'll update the showcase as well.

**Comment by jepsar** [comment]
@stephanrauh See https://github.com/TheCoder4eu/BootsFacesWeb/pull/44

Note: there still is a TODO for the since version.

**Comment by jepsar** [comment]
Hi, this has been released in version 1.1.2. This issue can be closed ;-)

**Comment by stephanrauh** [comment]
Good point. Thanks for the hint!
