### ISSUE TITLE
b:commandButton in b:dataTableColumn does not start bean

### ISSUE THREAD

**Issue by diegocsilva** [TheCoder4eu/BootsFaces-OSP#759]
I am using a b:dataTable and I need a column with the b:commandButton for report printing per record, so I used the following code:

```
<b:dataTable var="autorizacao" striped="true"
   value="#{transparenciaMB.processoLicencaWrapper.licencas}"
   customLangUrl="resources/pt-br.json" searchable="true"
   searching="true"
   select="true"
   selectionMode="single">
   <b:dataTableColumn value="#{autorizacao.numeroLicenca}"
      label="Número da Licença" />
   <b:dataTableColumn label="Autorização">
      <div align="center">
         <b:commandButton immediate="true"
            onclick="ajax:transparenciaMB.clearNumeroDoc()">
            <b:iconAwesome name="print" />
         </b:commandButton>
      </div>
      <div align="center">
         <b:commandButton immediate="true"
            action="#{transparenciaMB.newMessageInfo()}">
            <b:iconAwesome name="print" />
         </b:commandButton>
      </div>
   </b:dataTableColumn>
</b:dataTable>
```

I did several tests and none of them called my bean, I tried using h: column instead of b: dataTableColumn, I used h: commandButton, h: commandButton, h: commandLink ... all to no avail, none is calling my bean. Below I left two examples using b: commandButton, an attempt to call with AJAX and another attempt without AJAX. One note is that the command button outside the dataTable works normally. I'm using version 1.1.0 of bootsfaces. In the button where the call attempt is made via ajax the same happens nothing does not call the bean. In the button where the call is made without ajax, when clicking on it the bean is also not called, the button does an update of the screen and lose all the data of the table and of the forms of search.

**Comment by stephanrauh** [comment]
@diegocsilva Did you manage to solve the problem?
