### ISSUE TITLE
InternalFALink breaks sites without internet access

### ISSUE THREAD

**Issue by degenerinfosim** [TheCoder4eu/BootsFaces-OSP#76]
The InternalFALink class has a hard reference to BootstrapCDN which is not always reachable, e.g. from intranet pages. The page therefore runs into a timeout which makes it nearly useless.
This behavior should be configurable in my opinion.

**Comment by TheCoder4eu** [comment]
Yes you are right, it was the first implementation so we wanted to improve it by letting the choice to include the heavyweight font in the jar or configure a different URL.

**Comment by degenerinfosim** [comment]
Thanks for the fast feedback :-)

**Comment by degenerinfosim** [comment]
Is there a good workaround for this problem you are aware of? I can only think of patching it.

**Comment by stephanrauh** [comment]
As a quick but unreliable workaround, you could overwrite the class net.bootsfaces.listeners.InternalFALink.

**Comment by stephanrauh** [comment]
The next version of BootsFaces allows you to deactivate the automatic FontAwesome import by setting a parameter in the ```web.xml``` file. It will also suppress the CDN FontAwesome support if you load FontAwesome yourself via a ```<h:outputStylesheet />```. In most case, you'll add such a statement to load FontAwesome manually, so effectively you don't have to configure anything.
The current version of BootsFaces already allows you do deactivate the import by adding a "no-fa" facet in the header.

**Comment by stephanrauh** [comment]
Added all three options to the documentation page and tested them.
