### ISSUE TITLE
1.1.1-Snapshot highlight fields which failed validation

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#760]
it used to put a faint red line around a `b:inputText`if it failed validation but not filled and it doesn't seem to do that now

**Comment by stephanrauh** [comment]
Probably that's one of the breaking changes - see https://showcase.bootsfaces.net/forms/inputText.jsf#labels.

**Comment by chongma** [comment]
Is it possible my CSS has not updated? I can check that tomorrow. Reading the documentation does it mean the components need to be inside a form group? I never usually use form groups at all. I have no idea what they are for but I bump into them a lot at the moment. It would be a shame if that feature no longer works now it did

**Comment by chongma** [comment]
i have force updated the css in chrome but the issues persists.  the b:inputText have a solid border and then when they fail validation they only have a light grey border at the top.  it is not very noticeable.  it was better as red.

**Comment by chongma** [comment]
actually just noticed that the label is missing altogether from `b:inputText`.  i am going to try rolling back to 1.1.0 to see if it works there

**Comment by chongma** [comment]
the label is there at the beginning but disappears during validation

**Comment by TheCoder4eu** [comment]
@stephanrauh did you manage to reproduce this?
@chongma what are the steps to reproduce? The examples in Showcase seem all to run fine.

**Comment by chongma** [comment]
@TheCoder4eu are you looking at the showcase which uses 1.1.0 or have you updated to 1.1.1-snapshot?

**Comment by chongma** [comment]
hmmm...i updated my development version of showcase and osp to 1.1.1 and it works ok.  the label displays and turns red but the `b:inputText`no longer gets a red outline.  in my project the label disappears.  i am going to clean my .m2 and update my projects and try again

**Comment by chongma** [comment]
ahhhh...i just figured it out.  the labels are there but they have gone white so seem "invisible".  also it is only on the project that uses the `flatly` theme.  another project which uses a different theme is ok and the `b:inputText` gets red outline as well.  so it could be related to the css changes you made for `b:alert`?

**Comment by chongma** [comment]
the project that works fine is using cerulean theme

**Comment by TheCoder4eu** [comment]
@chongma thanks, so it seems only a flatly theme issue!
I don't think it is related to the alert change I made, it was very specific and had nothing to do with labels.

**Comment by stephanrauh** [comment]
@chongma OK, that's good news. Even so, it's a bit disturbing. Is there anything we should do to improve the situation? Missing red borders are a nuisance, and invisible labels are a no-go, even if only a few themes are affected.

**Comment by chongma** [comment]
@stephanrauh I switched to flatly theme in the showcase but it looks different to the one I have in my project. Do you want me to create a test which demonstrates the problem?

**Comment by stephanrauh** [comment]
@chongma Yes, that'd be a good idea. I still suspect your bug is simply one of the breaking changes of BootsFaces 1.1.0. But I can't say for sure because I haven't seen the actual code yet.

**Comment by chongma** [comment]
@stephanrauh ok i created a test called `input text` on https://github.com/chongma/test
![2017-05-07 06 54 00 pm](https://cloud.githubusercontent.com/assets/6253322/25783120/c4d4d316-3356-11e7-939b-ca79592822a0.png)
![2017-05-07 06 54 11 pm](https://cloud.githubusercontent.com/assets/6253322/25783121/c79bb876-3356-11e7-801c-34b7ebb2b83b.png)
also i noticed that when the required message is displayed on growl i get
```
May 07, 2017 6:54:03 PM org.apache.myfaces.lifecycle.RenderResponseExecutor execute
WARNING: There are some unhandled FacesMessages, this means not every FacesMessage had a chance to be rendered.
These unhandled FacesMessages are: 
- This is required
```
i don't know if it relevant

**Comment by stephanrauh** [comment]
Quick and pragmatic workaround: add these lines to your page or to your page template:

```xml
	<style>
	   .has-error .control-label {
	      color:#ff0000;
	   }
	   .has-error .form-control {
	      border-color: #ff0000;
	   }
	</style>
```

**Comment by chongma** [comment]
ok.  will it be fixed in a future release?  i would rather not customise anything if i can just skip a release

**Comment by chongma** [comment]
i have those lines loaded in my css but it still doesn't work

**Comment by stephanrauh** [comment]
@chongma What's the current state of the ticket? Is this bug still open?

**Comment by chongma** [comment]
Unfortunately I changed my project to the default theme because cerulean didn't work properly. So i am not sure what the status is. The showcase seems to work OK. But in my test project I have a page that shows the issue. It is only the colour scheme on the b:alert as far as I know

**Comment by stephanrauh** [comment]
I've run your reproducer (it's still there after two years!). After copying the CSS I suggested into the HTML code, the read line is there. Tested with BF 1.2.0 and 1.4.2-SNAPSHOT.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/3045767/62424295-45f8e080-b6cd-11e9-873b-7cfbc2838e39.png">
