### ISSUE TITLE
b:Switch cannot be cast to java.lang.CharSequence

### ISSUE THREAD

**Issue by LuisToro** [TheCoder4eu/BootsFaces-OSP#761]
Hello bootsfaces team, I currently use the BootsFaces 1.1.0 version. I will try to explain the inconvenience I had using the `switch`. Appreciate your help.

When I try to assign the `value="#{solicitudesController.estadoRequisito}"` to a String type variable located in the Controller (SolicitudesController) works perfect.

```xml
<ui:repeat id="idRequisitos" value="#{solicitudesController.listTramiteSolicitudes}"
                                   var="itemTramiteSolicitudes">

      <b:switch  value="#{solicitudesController.estadoRequisito}"
                       label="#{itemTramiteSolicitudes.idRequisito.nombre}" render-label="true"
                       process="@this" onchange="ajax:solicitudesController.updateRequisitos()"/>
 </ui:repeat>
```

But when I try to assign the value=`"#{itemTramiteSolicitudes.estadoRequisito}"` directly to an object in the list instantiated directly from the entity (Tramitesolicitudes). I get the following error.

**serverError: class javax.validation.ValidationException java.lang.Boolean cannot be cast to java.lang.CharSequence**

```xml
<ui:repeat id="idRequisitos" value="#{solicitudesController.listTramiteSolicitudes}"
                                   var="itemTramiteSolicitudes">
                            <b:switch  value="#{itemTramiteSolicitudes.estadoRequisito}"
                                       label="#{itemTramiteSolicitudes.idRequisito.nombre}" render-label="true"
                                       process="@this" onchange="ajax:solicitudesController.updateRequisitos()"/>
                        </ui:repeat>
```

Controller

```java
public class SolicitudesController extends BaseControllers implements Serializable {
    
    private List<Tramitesolicitudes> listTramiteSolicitudes;
    String estadoRequisito = "false";
```

Entity

```java
public class Tramitesolicitudes implements Serializable {

    private static final long serialVersionUID = 1L;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Id
    @Basic(optional = false)
    @NotNull
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_tramitesolicitudes")
    @Column(name = "ID_TRAMITESOLICITUDES")
    private BigDecimal idTramitesolicitudes;
    @Size(max = 5)
    @Column(name = "ESTADO_REQUISITO")
    private String estadoRequisito;


    public String getEstadoRequisito() {
        return estadoRequisito;
    }

    public void setEstadoRequisito(String estadoRequisito) {
        this.estadoRequisito = estadoRequisito;
    }
```

**Comment by stephanrauh** [comment]
As the error message says, `b:switch` expects a boolean. We could also support other data types, but we'd end with something like JavaScript's "truthy" concept. So I suggest you simply convert the string to a boolean in an additional getter/setter pair. Alternatively, you can implement a  JSF converter (although I didn't test that yet, so I can't guarantee we've implemented converters with `b:switch` correctly).

Please give us a hint if this answer helps you, so we can close the issue.

**Comment by LuisToro** [comment]
Hi stephanrauh, Thanks for helping.

I try and keep trying to use converter but it does not work for me. It seems as if he ignores the convert.

I also do not understand why the error message says: can not be cast to java.lang.CharSequence.

As I wrote the component works perfect when you assign the value to a String in the controller, but something happens when you assign the value to a String directly from the entity. 

The component does not need a convert to work with String, because I already tried it. The problem is to work with a String of the entity.

Now I will try to make an additional getter and setter. But as I try to use the Switch component inside a Repeat. The getter / setter must have additional For cycles, to assign them the True or False state.

If someone has an example Converter that worked for you I would appreciate it. Thx

**Comment by stephanrauh** [comment]
It seems to be a shortcoming of the standard EL expressions engine. It has a standard converter for `String`, but not for the base class `CharSequence`.

**Comment by stephanrauh** [comment]
It seems to be true: `<b:switch>` doesn't support converters.

**Comment by stephanrauh** [comment]
When you replace `<b:switch>` by `<b:selectBooleanCheckbox>`, things get interesting. The converter is used. But only for rendering. The error message is still there. It seems that the converter is ignored when setting the value in the backend bean.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
