### ISSUE TITLE
Let the b:slider2 accept additional custom classes accepted other than triangle square and custom(handleShape).

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#762]
To let the Bootstrap Slider accept additional custom classes accepted other than triangle square and custom(handleShape) we patched the JS library.

This is hardcoded in the library.

Open a issue to Bootstrap Slider team and eventually provide a PR to make the handle CSS class configurable.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
