### ISSUE TITLE
FontAwesome Webfont

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#765]
Am getting following error when Using PatternFly theame.
![capture](https://cloud.githubusercontent.com/assets/18460380/25771668/98b2b7f8-3275-11e7-8df6-cc26b06e846d.PNG)
It seems that **FontAwesome Webfont** files are missing in `BootsFaces-OSP-1.1.0-dist.jar`

**Comment by stephanrauh** [comment]
The FontAwesome files are not part of BootsFaces. By default, they are loaded from http(s)://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css. 

I don't have any idea why your application tries to load FontAwesome as a JSF resource. We've updated to version 4.7.0 last November, so I don't believe it's a BootsFaces problem. Is there another JSF page or JSF framework trying to load FontAwesome 4.6.3 in your project?

**Comment by chsreedhar** [comment]
BootsFaces Integrated with `PrimeFaces-6.1` and context-parameter `net.bootsfaces.get_fontawesome_from_cdn` set to `false` in `web.xml`
The Request header Reference parameter is `http://sree/stds2/javax.faces.resource/css/patternfly/core.css?ln=bsf`

This happens in case of `BootsFaces_THEME` set to `patternfly`.

![capture2](https://cloud.githubusercontent.com/assets/18460380/25941977/e4b56566-362a-11e7-866f-a4c042544cea.PNG)

**Comment by stephanrauh** [comment]
You're right, there's a reference to Font Awesome in the Patternfly CSS file.

@TheCoder4eu Is it possible to remove these lines from the core.css during the Gradle build?

**Comment by TheCoder4eu** [comment]
@stephanrauh , I'll drop the inclusion of Font Awesome CSS , but we must document that when using the patternfly theme , the context-parameter `net.bootsfaces.get_fontawesome_from_cdn` must be set to `true` in `web.xml`.
