### ISSUE TITLE
Offset indents several components on small screens

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#766]
For example, `b:button` is indended if the screen is smaller than the `md` breakpoint:

![image](https://cloud.githubusercontent.com/assets/3045767/25782914/2cb26e98-3353-11e7-9943-240f6046691e.png)

**Comment by stephanrauh** [comment]
- [ ] `b:button`
- [ ] `b:badge`
- [ ] `b:datepicker`
- [ ] `b:label`
- [ ] to be continued

**Comment by TheCoder4eu** [comment]
@stephanrauh , what's the status of this issue?

**Comment by stephanrauh** [comment]
This doesn't have to do anything with the offset. In fact, this doesn't seem to be a bug at all. The `col-md-6` attribute causes the indent because it's nested inside a `col-md-9`.

Probably we only need to correct the demo to avoid confusion.

**Comment by TheCoder4eu** [comment]
@stephanrauh I agree, thanks!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
