### ISSUE TITLE
Second PrimeFaces demo looks a bit odd

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#769]
http://www3.bootsfaces.net/Showcase/integration/PrimeFaces.jsf:
![image](https://cloud.githubusercontent.com/assets/3045767/25783054/cc978770-3355-11e7-8e4d-1b819a245790.png)

**Comment by chongma** [comment]
is this fixed now?  i couldn't find the dialog box on the page

**Comment by geopossachs** [comment]
https://showcase.bootsfaces.pecer.de/BootsFacesWeb/integration/PrimeFaces.jsf#example_for_scenario_2

**Comment by geopossachs** [comment]
![grafik](https://user-images.githubusercontent.com/10324450/83598959-57b84800-a56b-11ea-8ada-19fa0256e66e.png)
