### ISSUE TITLE
TabView breaks with comments inside

### ISSUE THREAD

**Issue by dani-garcia** [TheCoder4eu/BootsFaces-OSP#77]
TabView breaks when any of its children is a comment.
For example, this code works as supposed:
```html
<b:tabView activeIndex="1">
    <b:tab title="First Tab">
        <p>This is the first tab.</p>
    </b:tab>
    <b:tab title="Another Tab">
        <p>This is the second tab.</p>
    </b:tab>
</b:tabView>
```
but the moment you add a comment inside, it stops working:
```html
<b:tabView activeIndex="1">
    <b:tab title="First Tab">
        <p>This is the first tab.</p>
    </b:tab>
    <!-- This doesn't work -->
    <b:tab title="Another Tab">
        <p>This is the second tab.</p>
    </b:tab>
</b:tabView>
```

**Comment by stephanrauh** [comment]
Fixed. Thanks for the hint!

BTW, using XML comments in JSF applications is always a bad idea. XML comments are inserted to in the JSF tree as text nodes, which often leads to unexpected side-effect. Just think of putting comments in a h:panelGrid component! Therefore, the JSF guys have invented the ui:remove tag. That's a bit tedious, but much more reliable. 

That said, I consider this behavior a bug of JSF, so BootsFaces should deal gracefully with XML comments :).

**Comment by stephanrauh** [comment]
Successfully tested. The showcase tab demo now contains a comment to ensure continuous testing.
