### ISSUE TITLE
b:slider has a negative indent

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#770]
http://www3.bootsfaces.net/Showcase/jquery-ui/slider.jsf:
![image](https://cloud.githubusercontent.com/assets/3045767/25783077/5d4f9f14-3356-11e7-9e58-1c16ecdadc5a.png)

**Comment by BonifacioJose** [comment]
Is it necessary to include a "row" class at line 136 from SliderRenderer.java? Removing this class apparently solve this issue without any side effects.

![img1](https://user-images.githubusercontent.com/7031658/29535123-14611012-868f-11e7-9f9d-9c6d4fefa812.png)

**Comment by stephanrauh** [comment]
Oh, now I see. We've nested two rows without putting any columns between them. OK, that's clearly not what we intended.

@BonifacioJose Thanks for analyzing the problem and suggesting a solution!

**Comment by stephanrauh** [comment]
Solved by #854.
