### ISSUE TITLE
b:slider tooltip demo is extremely small

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#771]
http://www3.bootsfaces.net/Showcase/bootstrap/tooltips.jsf:

![image](https://cloud.githubusercontent.com/assets/3045767/25783095/85dba306-3356-11e7-88db-41d8f3156165.png)

**Comment by TheCoder4eu** [comment]
L'et's use a b:slider2 .

**Comment by stephanrauh** [comment]
In general, that's what we've agreed on. But until we've officially deprecated `b:slider`, I think we should still support it. Or we should document that we don't support it because it's our intention to replace it by a better slider. In any case, I think we have to offer a solution to developers using our slider and running into problems :).

**Comment by TheCoder4eu** [comment]
I fixed this, there was a `span="4"` attribute in the code not shown in the example source  , now I changed it to `span="11"` and updated the source section accordingly.
