### ISSUE TITLE
RemoteCommand not working

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#772]
You can verify it on the showcase: http://showcase.bootsfaces.net/forms/RemoteCommand.jsf

It is missing an `event` parameter.

**Comment by stephanrauh** [comment]
The demo seems to work. Which browser do you use? I only tested Chrome on OSX.

**Comment by ggam** [comment]
Firefox on Windows. I'll try on Chrome too.

**Comment by NicolaIsotta** [comment]
It doesn't work in my Firefox, too.
It works in IE and Edge instead.

**Comment by chongma** [comment]
i am using OSX.  i can verify this does not work on firefox.  works fine on chrome

**Comment by oliver-klein** [comment]
Hi, I've the same problem on Firefox (windows) but I found a simple workaround: 
Just add the `event` parameter to the `parameters` element or in case your function doesn't have any parameters add the attribute to your command `<b:remoteCommand ... parameters="event" .../>`
Firefox seems to be a bit too strict with non-existent variables.

**Comment by mddorfli** [comment]
Yes, this issue is visible on the showcase for me also, on Windows 10 using Firefox 59.0.2 (64-bit). The workaround by @oliver-klein worked for me.

**Comment by stephanrauh** [comment]
I does work on my FireFox. Plus, I can see the parameter `event` that's reported to be missing.

After such a long time, I can only guess: probably we've solved the bug without closing this ticket.
