### ISSUE TITLE
b:well doesn't clear both

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#773]
just noticed that if i add a floating image to a `b:well` component it bleeds outside.  not a big problem to clear it but i thought it might have done it automatically
![2017-05-10 09 21 38 am](https://cloud.githubusercontent.com/assets/6253322/25887348/1c6b97e2-3562-11e7-8412-b01a54a38525.png)

**Comment by jepsar** [comment]
Why don't you simply add `style=overflow:auto` to your `b:well`?

**Comment by ggam** [comment]
I don't exactly know how `clear` works but I've always had headaches with it. What are the side effects we can expect from adding it?

Does `style=overflow:auto` do the trick?

**Comment by chongma** [comment]
I am checking it but I had a problem running my project yesterday. Yes clear can affect other elements on the page

**Comment by chongma** [comment]
`style=overflow:auto` does indeed work.  shall we add it to `b:well` or just let people add it manually when they want it?  will anybody ever want things to bleed outside a `b:well`?

**Comment by stephanrauh** [comment]
I'm almost sure nobody wants images to bleed outside the well. But at the same time, I'm reluctant to add CSS rules to standard Bootstrap widgets. That's always breaking somebody's expectations.

How does happen in Bootstrap 4? (Or is the well one of the components BS 4 drop?)

**Comment by chongma** [comment]
Closing this because it should be handled with css

**Comment by stephanrauh** [comment]
@chongma I agree. But would you mind to add a few lines to the showcase explaining how to do this?
