### ISSUE TITLE
b:growl on showcase isn't respecting html

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#777]
on page https://showcase.bootsfaces.net/forms/Growl.jsf if i click the buttons info, warn, error etc at the top the growl messages show raw html instead of formatted

**Comment by stephanrauh** [comment]
Maybe we should set `escape="false"` and explain in the text why this is a dangerous setting.

**Comment by chongma** [comment]
I looked at this but I was not sure how to fix it as the faces message is set in renderer and doesn't seem to escape html

**Comment by TheCoder4eu** [comment]
@stephanrauh @chongma , it's not a bug it's like it's meant to work, by clicking on a button you get a partial update via AJAX, the string in Messages.java contains markup that is encoded for being sent to the client.

**Comment by stephanrauh** [comment]
I've added the explanation of the `escape` attribute to the documentation. Along the way, I added remarks about the copyright and the animations.
