### ISSUE TITLE
fixed b:navBar should have a js to clear limits

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#778]
currently if i add a `b:navbar fixed="top"` then i need to add to the body declaration (taken from the examples page)
```
<!-- Add 50px padding top to the body for the navbar -->
<h:body style="padding-top: 50px;">
```
in order for the `b:navBar` to clear the top of the page and not overlay.

if i change theme different themes have different font sizes which results in the `b:navBar` being slightly different sizes resulting in gaps or overlay.  e.g. if font size is smaller gap will be larger
![2017-05-15 09 23 05 am](https://cloud.githubusercontent.com/assets/6253322/26046644/2a791ad4-3950-11e7-9a89-c201b4c20774.png)

also if the `b:navBar` gets too crowded and things wrap then the size will grow beyond the fixed padding set.
![2017-05-15 09 22 14 am](https://cloud.githubusercontent.com/assets/6253322/26046606/087d1232-3950-11e7-8d06-89826c04e906.png)

the upshot is it needs some clever javascript to calculate the size of the `b:navBar` during page load and to dynamically add some padding to the top of the page.  i have worked with this before on a wordpress site and it is not as easy as it seems.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
