### ISSUE TITLE
b:panel collapsed closes on ajax

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#779]
Maybe i need to create a test for this but it seems like if i have a collapse `b:panel` with an ajax form inside it the panel collapses. pseudocode:
```
<h:form>
<b:panel collapsed="true">
<h:commandButton value="Click me"><f:ajax render="@form"/></h:commandButton>
</b:panel>
</h:form>
```
obviously rendering the form reinitialises the `b:panel` and recollapses it.  but i would have expected `collapsed` to represent the initial state only.  the `collapsed` property could be stored inside a `@ViewScoped` bean manually but i would have expected this to be handled by BootsFaces...

**Comment by stephanrauh** [comment]
Bind the `collapsed` state to a bean variable. One of the showcase demos does that, too.
