### ISSUE TITLE
[BootsFaces 0.6.5] Custom converter in b:selectOneMenu - question

### ISSUE THREAD

**Issue by brolnik** [TheCoder4eu/BootsFaces-OSP#78]
Hi,

I have tried to use custom converter (String <-> my class) in b:selectOneMenu but an exception is thrown:
```
java.lang.ClassCastException: com.teaman.data.model.Player cannot be cast to java.lang.String
```

I have also placed f:converter binding="#{myConverter"} inside b:selectOneMenu

```
<b:selectOneMenu>
     <f:converter binding="#{myConverter"}/>
</b:selectOneMenu>
```

With standard JSF, custom converter works fine passed as 'converter' attribute of tag h:selectOneMenu
and works fine when it is placed inside h:selectOneMenu as f:converter binding="#{myConverter"}

How should I use my converter with b:selectOneMenu ? 

Regards,
Bartek

**Comment by stephanrauh** [comment]
You are right: BootsFaces 0.6.5 ignores the converter. In fact, I'm not entirely convinced you need a converter at all. Each time I employed a converter, things got messy. That's why I hesitate to add the feature. But if you want to convince me: I'm open to new insights.

My approach to displaying the players looks like so:

```Java
public class Player {
    private String name; // plus getter and setter
}
@Named
@ViewScoped
public class TeamBean {
  private Player keeper; // plus getter and setter
  /** team is a list of at least 11 soccer players */
  private List<Player> team; // plus getter and setter
}
```
```xml
<b:selectOneMenu value="#{teamBeam.keeper}"  >
        <f:selectItems value="#{teamBeam.team}" 
                               var="player" 
                               itemValue="#{player}" 
                               itemLabel="#{player.name}"/>
    </b:selectOneMenu>
```
So you can use the selectOneMenu to chose an object and store it in the ```keeper``` attribute of the bean, but it's still displayed as a String (the player's name).

Does this solve your problem?

**Comment by brolnik** [comment]
Hi,

thank you for your answer. I have to admit that it was my first solution - version without custom converter only atributes of f:selectItems, but all the time I got an excpetion:

```
java.lang.ClassCastException: com.teaman.data.model.Player cannot be cast to java.lang.String
```

So, I decided to use custom converter and no changes. I thought that I made mistake in my 1st version of comboBox and I have copied your code into mine:

```
public class PlayerTemp {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public PlayerTemp(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "PlayerTemp{" + "name=" + name + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PlayerTemp other = (PlayerTemp) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }

}
```

@Named(value = "newMessageBean")
@ViewScoped
public class NewMessageBean implements Serializable {

    private List<PlayerTemp> team;
    private PlayerTemp playerTemp;

public void init(ComponentSystemEvent e) {

**Comment by stephanrauh** [comment]
Can you add a few more lines of the stacktrace, please? I'd like to see whether it's a rendering or a decoding problem. 

Thanks in advance,
Stephan

**Comment by brolnik** [comment]
Yes, sure. I am sending more lines below:

```
java.lang.ClassCastException: com.teaman.web.bean.PlayerTemp cannot be cast to java.lang.String
	net.bootsfaces.component.SelectOneMenu.renderOption(SelectOneMenu.java:384)
	net.bootsfaces.component.SelectOneMenu.renderOptions(SelectOneMenu.java:349)
	net.bootsfaces.component.SelectOneMenu.renderSelectTag(SelectOneMenu.java:251)
	net.bootsfaces.component.SelectOneMenu.encodeBegin(SelectOneMenu.java:112)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1894)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1896)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	javax.faces.component.UIComponent.encodeAll(UIComponent.java:1899)
	com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:451)
	com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:131)
	com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
```

Regards,
Bartek

**Comment by stephanrauh** [comment]
Thanks! Oops - this sounds like a bug on my side. I'll have a look at it later.

**Comment by brolnik** [comment]
Ok, I see. I am waiting for info :)

**Comment by stephanrauh** [comment]
Your example enabled me to reproduce the error in virtually no time. Thanks!
I overhauled the implementation and added the [soccer example to the showcase](http://www.bootsfaces.net/BootsFacesWeb/forms/selectOneMenu.jsf).

**Comment by brolnik** [comment]
Thanks a lot ! I have one more question - when are you going to release a new version of BootsFaces (0.7) ?

**Comment by stephanrauh** [comment]
Hi Bartek,

following a great tradition, we'd have to publish an Easter release :). I'm not sure we manage to publish the next version that soon, but we plan to publish the next release within the next few weeks.

Regards,
Stephan

**Comment by brolnik** [comment]
Hi,

Ok, I see. So, We are waiting for new release :)

regards,
Bartek
