### ISSUE TITLE
f:selectItem: itemValue vs itemLabel

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#781]
Consider this xhtml:
```xml
<h:selectOneMenu label="h:selectOneMenu">
	<f:selectItem itemValue="item"/>
</h:selectOneMenu>

<b:selectOneMenu label="b:selectOneMenu">
	<f:selectItem itemValue="item"/>
</b:selectOneMenu>
```
The generated HTML is:
```html
<select name="j_idt4" size="1">	<option value="item">item</option></select>
<div class="form-group bf-warning has-warning" id="j_idt13">
	<label for="j_idt13Inner" class=" control-label">b:selectOneMenu</label>
	<select id="j_idt13Inner" name="j_idt13Inner" class="form-control">
		<option data-label="&amp;nbsp;" value="item">&nbsp;</option>
	</select>
</div>
```
As you can see, in the bootsfaces `select` the label of the option is missing; Mojarra instead derives it from they `itemValue` if `itemLabel` is not specified by the user (and not the other way round, like Bootsfaces).
[The constructors of `javax.faces.model.SelectItem`](http://static.javadoc.io/org.glassfish/javax.faces/2.3.0/javax/faces/model/SelectItem.html#constructor.summary) confirm the priority of value over the label.

I'm not submitting a PR since this can be considered a breaking change (and PrimeFaces behaves the wrong (?) way too).

**Comment by stephanrauh** [comment]
I suggest we implement a two-way derivation. If either the `item-label` or the `item-value` is omitted, it's simply derived from the other one. That way, this isn't a breaking change.

Any objections?

**Comment by stephanrauh** [comment]
I've implemented the feature.
