### ISSUE TITLE
b:form horizontal seems restrictive

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#783]
`b:form horizontal="true"` displays a classic standard form, where each component is on a separate line with the label on the left and the component on the right. as shown here in the showcase
![2017-05-15 04 45 58 pm](https://cloud.githubusercontent.com/assets/6253322/26063329/0163bc1a-398e-11e7-912e-4a0b05158f07.png)
but it doesn't seem to offer any flexibility if you want to only show a section of the form in a classic way and then the rest of the form in another way?
what would be good is a new component for example `b:formSection horizontal="true"` which only controls the layout of the components inside, e.g.
```
<h:form>
  <b:formSection horizontal="true">
    <b:inputText label="I am horizontal" value="#{myBean.horizontal}"/>
  </b:formSection>
  <b:inputText label="I don't want to be horizontal!" value="#{myBean.free}/>
</h:form>
```

**Comment by chongma** [comment]
also in the demo the user has to define `label-small-screen="4" small-screen="8"` on every component which seems wasteful.  this could be defined at the `b:formSection` level as a default and overridden at the component level?

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
