### ISSUE TITLE
b:iconawesome isn't shown correctly in title header facet p:datatable with reflow="true"

### ISSUE THREAD

**Issue by nokiajavi** [TheCoder4eu/BootsFaces-OSP#785]
I Use bootfaces 0.9.1

![captura](https://cloud.githubusercontent.com/assets/13865234/26101239/b1b1209c-3a30-11e7-9a09-025de3b51841.PNG)
Hi, I have a display problem when I use an `<b: icon awesome />` with tooltip inside the `<facet = "header">` of a `<p: column>` of a primefaces table

When the datatable is displayed in mobile and rendered responsive, instead of leaving the title in the header, I sea a script of the tooltip instead.

For example, if I put a `<p: commandbutton title = "add" ...`
When the datatable is rendered in responsive mode, the title of the button is displayed.

The problem seems to be that a span tag is added with the script and the datatable shows that script. If I do not put tooltip to `<b: iconawesome`, nothing is displayed.

**The span generated.**
```html
<span class="ui-column-title">$(function () {
$('#tblDocAnexosProcedimiento\\:j_idt83').tooltip({'delay':{show:0,hide:0}})
});
$('.tooltip').tooltip('destroy'); </span>
```

```html
<p:column styleClass="ancho4 align_centro">
   <f:facet name="header">
      <b:iconAwesome name="fa-eye" tooltip="#{text['button.title.verDocumento']}"/>
   </f:facet>
   <p:commandButton icon="fa fa-eye" />
</p:column>
<p:column styleClass="ancho4 align_centro">
   <f:facet name="header">
      <b:iconAwesome name="fa-pencil-square-o" tooltip="#{text['button.title.verAnotaciones']}"/>
   </f:facet>
   <p:commandButton icon="fa fa-pencil-square-o"/>
</p:column>
```

It can be fixed simply by including a title attribute to `<b: iconAwesome>` that replaces the script that is written in the span, so that text or nothing comes out when the tooltip has that element. Or use the tooltip to display.

Thanks greetings

**Comment by stephanrauh** [comment]
Judging from the CSS class, the `span` tag is added by PrimeFaces. Currently, I don't see how to fix that (except kindly asking @tandraschko or @cagataycivici to do so). (But before you start: it's a bit guesswork, I didn't run the actual code yet).

BTW, we won't fix a bug in BootsFaces 0.9.1. Any bugfix we do goes into 1.1.2 or above. Would you mind to check if your bug exists with the current version of BootsFaces, 1.1.1?

Thanks in advance,
Stephan

**Comment by nokiajavi** [comment]
Good, I just tried on the 1.1.1 version of bootfaces and it also happens. In effect it is a label that primefaces uses to display the text in responsive mode of the table column, when using a <p: commandButton ... with title, that title is the one that primefaces uses as text from the header of the Column, in case it can help. Thank you very much

**Comment by stephanrauh** [comment]
Is this ticket still a problem? I'd like to close it because our team is so small.

**Comment by nokiajavi** [comment]
Good, the last time I tried it kept failing, right now I can't test when I return to the project where the error is I test it and tell you whether or not the problem is resolved. Thank you. By the end of this month I can test you.

**Comment by stephanrauh** [comment]
Awesome! Truth to tell, I'm desperately trying to bring down the number of issues. The peak of 158 open issues was simply intimidating. So it's possible I've been too fast. I'm looking forward to the result of your test!

**Comment by stephanrauh** [comment]
Abriendo el ticket de nuevo. ¡Gracias por probarlo de nuevo! ¡Y por tu paciencia!

**Comment by geopossachs** [comment]
I think the render-error is more located in primefaces 

the js code comes from this renderer class but with a surrounding script tag
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/render/Tooltip.java

in the Html is the surrounding script tag missing there. that made me stinky. but I cloud not found the code part in primefaces, how is picking the code block without your script tags

https://github.com/primefaces/primefaces/blob/7643be24cf77a5bd5371147408b4db03fe2041d3/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java 

I have a solution, not nice but she is working 

``

                <f:facet name="header">
                    <b:iconAwesome id="fade" name="fa-pencil-square-o" value="Look at my tooltip!"  />                        
                    <p:tooltip id="toolTipFade" for="fade" value="MEHR TIPPS" position="top"/>                        
                </f:facet>
``

**Comment by nokiajavi** [comment]
I have tried the solution, and the script is no longer shown on the web, the problem is that nothing is shown to me, but well I think that is a problem of primefaces, which uses the title property to display the text instead of what have in the column header

**Comment by geopossachs** [comment]
So we can close this issue @nokiajavi ?

**Comment by nokiajavi** [comment]
yes, thanks
