### ISSUE TITLE
http://bootsfaces.net/ui 302 move to https and give a 404 not found

### ISSUE THREAD

**Issue by emimarz** [TheCoder4eu/BootsFaces-OSP#789]
with the next warning 
Warning: This page calls for XML namespace http://bootsfaces.net/ui declared with prefix b but no taglibrary exists for that namespace

**Comment by emimarz** [comment]
only happen with BootsFaces-OSP-1.1.0-dist-default.jar
I change it for BootsFaces-OSP-1.1.1-dist.jar
and work fine, I don't understand

**Comment by TheCoder4eu** [comment]
The namespace identifier is a URI and not a URL, using a URI is done by convention,  because it is guaranteed to be unique if you control the domain, but it is not intended as a reference to a real webpage.
