### ISSUE TITLE
How to achieve complex header in bootsfaces datatable?

### ISSUE THREAD

**Issue by chaoqian** [TheCoder4eu/BootsFaces-OSP#795]
Hi, I have tried multiple ways trying to achieve complex header like this: https://datatables.net/examples/basic_init/complex_header.html in bootsfaces, but not working. 

How can we achieve complex header in datatable component? Any suggestions or examples? Thanks.
-Chao

**Comment by stephanrauh** [comment]
Also see https://stackoverflow.com/questions/44209415/how-to-achieve-complex-header-in-bootsfaces-datatable.

**Comment by stephanrauh** [comment]
I think you're already on the right track. The only problem is you've nested the `<tr>` tag into a `<tr>` tag rendered by BootsFaces, which confused the browser. This complex header works:

```
<b:dataTableColumn value="#{car.brand}">
	<f:facet name="header">
	     <ul style="margin-bottom:0;list-style-type:none;padding-left:0">
	       <li>Name</li>
	       <li>HR Information</li>
	       <li>Contact</li>
	     </ul>
	</f:facet>
</b:dataTableColumn>
```

![image](https://user-images.githubusercontent.com/3045767/27185747-90f7bea6-51e6-11e7-8609-9ddf29f17694.png)

@chaoqian Does this solve your problem?

**Comment by stephanrauh** [comment]
I've implemented the variant described at https://datatables.net/examples/basic_init/complex_header.html. To use it, don't add the header facet to an individual column but to the entire table. The preview showcase has examples for both variants (http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf).

**Comment by stephanrauh** [comment]
![image](https://user-images.githubusercontent.com/3045767/27197045-1e2541f6-520d-11e7-9729-4d5cf1ddd985.png)
