### ISSUE TITLE
Fix ordering of CSS imports

### ISSUE THREAD

**Issue by shoutcool** [TheCoder4eu/BootsFaces-OSP#80]
If you put `<h:outputstylesheet>` tag in the `<h:head>` section the ordering will be randomized after submitting a request to the own site. I am using a bootswatch theme for styling my page and after sending the request to my own site (e.g with a link `href="#"`) my page is looking completly different because of the scrumbled css ordering.

I would suggest if i put a `<h:outputstylesheet>` Tag inside the `<h:body>` section, these imports should always appear after all bootsfaces css imports. This way i can be sure my own css stylesheets always overrides the bootsfaces stylesheets.

**Comment by stephanrauh** [comment]
I also noted that some resources where added twice on post-backs. Both errors are fixed now (version 0.6.6).

**Comment by TheCoder4eu** [comment]
Thanks Stephan, I included this issue on v0.6.6 Milestone, may I close it?

**Comment by stephanrauh** [comment]
I successfully ran a couple of tests. There's a demo at http://angularfaces.net/BootsFacesCombobox/index.jsf (sourcecode at https://github.com/stephanrauh/BootsFaces-Examples/tree/master/Combobox).
