### ISSUE TITLE
Feature Request  Adding help icon option to components (dropdowns, input text, etc.)

### ISSUE THREAD

**Issue by ErickPezoa** [TheCoder4eu/BootsFaces-OSP#800]
So I think it would be useful to have the option to add a help icon to the label of any input components like <b:inputText and <b:selectOneMenu> to mention a few. For example, the below code does kind of what I mean by help icon (see the image below) I am thinking that it shouldn't be hard to modify the components, like <b:inputText> (and other necessary components) to add an option for **showHelpIcon** and **helpIconText** to accomplish below. What does everyone thinks about this? I think this would be beneficial. This way people don't have to create their own components but instead we can use it from bootsfaces directly.

```
<h:outputLabel value="Help:" for="test"></h:outputLabel>
<b:iconAwesome name="question-circle" tooltip="help text"/>
<b:inputText id="test"/>
```

![image1](https://cloud.githubusercontent.com/assets/6473137/26565150/a77fde66-44b6-11e7-9fad-ec2a52e0f1c1.jpg)

**Comment by chsreedhar** [comment]
@stephanrauh  It is useful to have the option like [Field Level Help](http://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/#/overview).

**Comment by stephanrauh** [comment]
With a little effort, you can implement this with pure JSF components. I've already seen that in the wild. So I'll close the ticket since we've run out of team members.
