### ISSUE TITLE
Disabling BSF-Resources doesn´t work... 

### ISSUE THREAD

**Issue by cljk** [TheCoder4eu/BootsFaces-OSP#806]
I want to use my own bootstrap css and jQuery files since I´ve a ready layout for it (purchased). So I added context-params
```
<context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>false</param-value>
</context-param>

<context-param>
    <param-name>net.bootsfaces.get_jquery_from_cdn</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>net.bootsfaces.get_jqueryui_from_cdn</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>net.bootsfaces.get_bootstrap_from_cdn</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>net.bootsfaces.get_fontawesome_from_cdn</param-name>
    <param-value>true</param-value>
</context-param>
```
But the header tags of BSF are still generated. Is it possible to disable them all or did I configure it wrong?

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head id="j_idt2">
      [... my CSS tags & prime faces...]
	  
	  <link type="text/css" rel="stylesheet" href="/javax.faces.resource/css/default/core.css.xhtml?ln=bsf" />
      <link type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
      <link type="text/css" rel="stylesheet" href="/javax.faces.resource/css/bsf.css.xhtml?ln=bsf" />
      <!--[if lt IE 9]><script src="/javax.faces.resource/js/html5shiv.js.xhtml?ln=bsf"></script><script src="/javax.faces.resource/js/respond.js.xhtml?ln=bsf"></script><![endif]-->
	  
	  <script type="text/javascript" src="/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&amp;v=6.1"></script>
	  <script type="text/javascript" src="/javax.faces.resource/core.js.xhtml?ln=primefaces&amp;v=6.1"></script>
	  <script type="text/javascript" src="/javax.faces.resource/components.js.xhtml?ln=primefaces&amp;v=6.1"></script>
	  <script type="text/javascript" src="/javax.faces.resource/jsf.js.xhtml?ln=javax.faces&amp;stage=Development"></script>
	  
	  <script type="text/javascript" src="/javax.faces.resource/js/tooltip.js.xhtml?ln=bsf"></script>
	  <script type="text/javascript" src="/javax.faces.resource/js/bsf.js.xhtml?ln=bsf"></script>
	  
	  [... rest of header ...]
	  
```
Stack: Jetty 9.4.5 with Mojarra 2.2.14 and primefaces 6.1

**Comment by cljk** [comment]
I made up a small example. If you want you can clone https://github.com/cljk/bsf-issue-806-example and run
`mvn jetty:run
`
and open
`http://localhost:8080/`

It should not render correctly.... but it does ;-)
Because Bootstrap core.css is added...

**Comment by TheCoder4eu** [comment]
Hi @cljk , I am not sure what you exactly want to obtain, but it sounds more like you would like to provide your own theme.
With your configuration you only switched to the flat version and changed the origin of css/js files.
Try to follow the instructions in the Themes section of the Configuration page for a custom theme:

https://showcase.bootsfaces.net/miscellaneous/Configuration.jsf

**Comment by cljk** [comment]
Yes... I want to add my own (newer and altered) version of bootstrap CSS - so I want BFS to stop output "core.css" in the header. The generated structure-tags are great... but I need to add my own version of Bootstrap.

Hmmm... I don´t understand
According to the page you linked...

> These parameters allow you to replace the built-in version of these libraries by your own libary. For instance, you might prefer to load it from a CDN (hence the name). Setting these parameters to true stops BootsFaces from adding them itself. You have to care about that yourself.

Since I set them to true (see my web.xml excerpt above) I thougt this would be correct?! Am I doing smth. wrong?
I still get 
` <link type="text/css" rel="stylesheet" href="/javax.faces.resource/css/default/core.css.xhtml?ln=bsf" />
`

**Comment by cljk** [comment]
@TheCoder4eu 

I finally got it!
I checked out the code and debugged my example with the latest snapshot... I had to...

* set `BootsFaces_USETHEME` to`true`
* set `BootsFaces_THEME` to `other` (special keyword in AddResourcesListener.java removeBootstrapResources)
* set `net.bootsfaces.get_bootstrap_from_cdn` to `false` (the logic seems to be inverted in AddResourcesListener.java addCss - contrary to the doc?!)

The logic in `addCSS` is to call `removeBootstrapResources` when `loadBootstrapFromCDN` is true.... BUT `loadBootstrapFromCDN` is inverted in `shouldLibraryBeLoaded` and not inverted back again (bug?!).

`removeBootstrapResources` gets called but only removes resources when a theme is set and the theme is `default` or `other`. But `default` CONTAINS the complete bootstrap CSS ... so I had to chose `other`.

I´ll try to find the time to file a pulll request the next days.

**Comment by TheCoder4eu** [comment]
@cljk 
set `net.bootsfaces.get_bootstrap_from_cdn` to `false` should be correct otherwise you would also get loaded it from the CDN.

However we'll have a review of the logic/docs and we welcome your PR if you correcting inconsistencies.
