### ISSUE TITLE
b:buttonGroup last Item

### ISSUE THREAD

**Issue by stevekv** [TheCoder4eu/BootsFaces-OSP#816]
Hi,

just found out that if one uses tooltips on the last button in a button group, that button gets rendered in a wrong way - the corners don't have a radius because its interpreted as internal button. That is due to the fact that the last element in the button group is not the button but the script tag associated with the tooltip for the last button. Stinking feature of bootstrap because that will be hard to fix when the button does not know if it is in a button group (it does not need to know except for this bug). It works if the script and the button html change places. But one can not do that for all the buttons in the group, because then the problem is shifted to the first button :(

Stephan

**Comment by stephanrauh** [comment]
This ticket rings a bell. Some time ago, we had a similar bug. I hope it's not a recurring bug :).

**Comment by stephanrauh** [comment]
Wait. We did solve this problem some time ago by shifting the JavaScript code into the `<button>` tag (as opposed to putting it behind the `<button>` tag). Which BootsFaces version are you using?

```html
<button id="j_idt189" name="j_idt189" type="button" class="btn btn-default" data-toggle="tooltip" data-placement="auto" data-container="body" title="" data-original-title="last">4<script type="text/javascript">$(function () {
$('#j_idt189').tooltip({'delay':{show:0,hide:0}})
});
$('.tooltip').tooltip('destroy'); </script></button>
```

```xml
<b:buttonGroup>
  <b:button value="1" tooltip="first"/>
  <b:button value="2" tooltip="second"/>
  <b:button value="3" tooltip="third"/>
  <b:button value="4" tooltip="last"/>
</b:buttonGroup>
```

![image](https://user-images.githubusercontent.com/3045767/28039788-ca78325a-65c3-11e7-93f0-2e8f01cabcc9.png)

**Comment by stevekv** [comment]
I'm currently using maven dependency with version 1.1.0.

**Comment by stephanrauh** [comment]
Can you send me a reproducer? In this case, that'd be the XHTML file. Plus, I'd like to see the generated HTML code.

I can't promise anything, but the next version of BootsFaces is scheduled for Saturday, and I'd like to fix this error in 1.1.2.

**Comment by stevekv** [comment]
Attached two files. nachbuchung.xhtml the source code and nachbuchung.html the rendered code.

[nachbuchung.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/1140990/nachbuchung.zip)

**Comment by stevekv** [comment]
Guess I found the problem. I forgot to tell you, that I've used CommandButtons. The ButtonRenderer is Ok. In the CommandButtonRenderer the Tooltip.activateTooltips() Method is called after the endElement("button").

![commandbutton](https://user-images.githubusercontent.com/30043129/28114997-71ed6d9e-6703-11e7-9e10-09965cdebead.png)

**Comment by stephanrauh** [comment]
Thanks for the extra info! I've implemented your proposed solution and uploaded the new developer snapshot to Maven Central. See #369 on how to get it.

**Comment by stevekv** [comment]
Excellent, the last button now has a radius. I tip my hat in your general direction ;-)

Unfortunately there is another issue. Since I switched to 1.1.2-SNAPSHOT, the datatables have a nasty scollbar:

![datatable](https://user-images.githubusercontent.com/30043129/28152411-9c67e2be-67a0-11e7-9c25-110a0ff71fe1.png)

**Comment by chongma** [comment]
This is caused by #794. The overflow needs to be fixed somehow

**Comment by stephanrauh** [comment]
That's the answer to my (unspoken) question: Yes, we do need to make the new datatable wrapper configurable. The challenge is to find a good name :).
