### ISSUE TITLE
b:growl successfully shows messages but console still shows error

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#819]
i first reported this problem in #760 but thought it might be best to have its own issue.

`b:growl` successfully shows `FacesMessage` but for some reason console thinks it has not and i repeatedly get messages like
```
May 07, 2017 6:54:03 PM org.apache.myfaces.lifecycle.RenderResponseExecutor execute
WARNING: There are some unhandled FacesMessages, this means not every FacesMessage had a chance to be rendered.
These unhandled FacesMessages are: 
- This is required
```

**Comment by stephanrauh** [comment]
Should be fixed by now. Would you mind to test it? I've uploaded the bug fix to Maven Central as a developer snapshot.

**Comment by chongma** [comment]
it looks fixed to me
