### ISSUE TITLE
b:datepicker doesn't work in a b:modal

### ISSUE THREAD

**Issue by soyalejoramirez** [TheCoder4eu/BootsFaces-OSP#82]
Hi there.

When I put a ```<b:datepicker>``` inside a ```<b:modal>``` this doesn't work as expected.

I think this issue applies to all jQuiery Widgets of BootsFaces (I tried too with a ```<b:slider>```).

**Comment by stephanrauh** [comment]
No error message in the Javascript console. The datepicker's popup won't open. I wonder if the generated JS code executed at all?

**Comment by soyalejoramirez** [comment]
Seems to be a common issue.

I'm reading a bit about it on the web and suggest changing the ````z-index```` in css.

References:
* https://github.com/eternicode/bootstrap-datepicker/issues/464
* http://stackoverflow.com/questions/12978254/twitter-bootstrap-datepicker-within-modal-window
* http://cazaresluis.com/bootstrap-datepicker/

**Comment by TheCoder4eu** [comment]
Hi, I think you are right, I remember we already had an issue with datepicker where we had to raise the z-index, I'll add a specific rule for datepicker in modals and see if it fixes this issue.

**Comment by stephanrauh** [comment]
Also see https://github.com/TheCoder4eu/BootsFaces-OSP/issues/45.

**Comment by stephanrauh** [comment]
Raising the z-index to 2000 seems to do the trick. I hope there are not side-effects now :).

Strange thing is that the z-index is calculated automatically when there's a modal. I observed a value of 1042. However, there seem to be situations where this isn't enough, so I decided to override the calculated value in the bsf.css file.

@soyalejoramirez : I didn't observe any difficulty with the slider. Could you have a look again, please? ¡Gracias!

**Comment by soyalejoramirez** [comment]
Hi @stephanrauh, 

I just made some tests and this issue continues for me. I'm working with 0.6.6 version manually.

Am I doing something wrong? How do I test this?

**Comment by stephanrauh** [comment]
As for testing: I simply added a datapicker to the "modal" example page of BootsFacesWeb. I'll have a look at it tomorrow.

**Comment by stephanrauh** [comment]
Here's my test file: https://github.com/stephanrauh/BootsFaces-Examples/blob/master/ModalDialogs/src/main/webapp/index.xhtml. It's part of a Maven project which still uses BootsFaces 0.6.5. As a consequence, the datapicker is broken. But it *should* work with BF 0.6.6. I couldn't test that yet, but if should work if the datapicker's z-index is set to 2000 in the bsf.css file. Maybe you could check this in your browser.

**Comment by soyalejoramirez** [comment]
In the ````.ui-datepicker```` of bsf.css (0.6.6 version) still shows ````z-index: 5 !important;````

This is the screenshot of the bsf.css file:

![bsf](https://cloud.githubusercontent.com/assets/12086580/7640202/5c43e1e2-fa47-11e4-8e36-b2dc6889fddf.PNG)

Am I doing something wrong?

Thanks in advance!

**Comment by stephanrauh** [comment]
¡Hola Alejandro!,

The current version of bsf.css in the repository has z-index 2000, so probably something is wrong with your custom build. 
https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/BootsFaces/css/bsf.css

**Comment by stephanrauh** [comment]
I just saw that you use version 0.6.6, which has been published on MavenCentral before I fixed the bug. Until we publish the next version, you can checkout the current master branch of the BootsFaces-OSP project and build it as a Maven project. This way, you get version 0.6.7-SNAPSHOT which already contains the bugfix. 

![image](https://cloud.githubusercontent.com/assets/3045767/7641005/40696ed4-fa87-11e4-8441-b1a2ec379bc9.png)
