### ISSUE TITLE
fixed-header offset for DataTable

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#821]
The fixedHeader attribute activates the fixed header plugin of the dataTable, but when Sticky NavBar at the top,  fixedHeader is not visible. The dataTable fixed header is behind the NavBar.
In BootsFaces showcase also  fixedHeader is not visible, http://showcase.bootsfaces.net/forms/DataTable.jsf#customizing

The offset option for fixedHeader solves the issue, link https://datatables.net/extensions/fixedheader/examples/options/offset.html

**Comment by stephanrauh** [comment]
Oh... and I thought the feature was just broken. Thanks for the hint!

**Comment by stephanrauh** [comment]
Off topic: I like your avatar image. If I'm not mistaken, it's a vegetarian chicken?

**Comment by geopossachs** [comment]
how can i find out if exits an navBar on the page to set the class fh-fixedHeader there?

**Comment by geopossachs** [comment]
_Offset - manual_
```
		if (dataTable.isFixedHeader()) {
			options = addOptions("fixedHeader: {header: true, headerOffset: $('#fixed').height()}", options);
		}else{
			options = addOptions("fixedHeader: false", options);
		}
```
    Using the fixedHeader.headerOffset and fixedHeader.footerOffset options.

The question is can we find an element to get the offset?

**Comment by geopossachs** [comment]
@stephanrauh Do you have any ideas?

**Comment by stephanrauh** [comment]
We could use the id of the wrapper, e.g.
```
"#" + clientIdRaw.replace(":", "\\\\:") + "_wrapper'"
```

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
