### ISSUE TITLE
Width of DataTable

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#822]
It seems that for `<b:dataTable >` width attribute is being set to some value like `1108px;`  based on window size, this value not changing when the browser resizes. 
Because of this fixed width `responsive` attribure of `<b:dataTable >` not working properly.
But, in [DataTables](https://datatables.net) the width attribute is `100%`

**Comment by stephanrauh** [comment]
The datatables of our showcase resize when the browser window gets smaller. There seems to be a minimum size (roughly 400-450 pixel), but that's probably caused by the content of the table.

![image](https://user-images.githubusercontent.com/3045767/28285786-370d7854-6b36-11e7-8aa5-a487cb4495ef.png)

**Comment by stephanrauh** [comment]
Can you try to find out where the fixed size comes from in your application? Alternatively, would you mind to check whether our showcase demos show the same behavior?

**Comment by chsreedhar** [comment]
Screen shot attached
![capture](https://user-images.githubusercontent.com/18460380/28300357-b358fa1c-6b9c-11e7-9421-f5a9724c1453.PNG)

**Comment by stephanrauh** [comment]
Do you use Patternfly? There's only one "980px" in the entire project. It's the container size of medium-sized containers in the Patternfly layout.

**Comment by chsreedhar** [comment]
Am using `patternfly.min.css` and `patternfly.min.js` by setting `BootsFaces_THEME` to `custom` and `BootsFaces_USETHEME` to `false`

**Comment by chsreedhar** [comment]
@stephanrauh to solve the issue set the width attribute of the table to 100%
## `<b:dataTable style="width:100%">`
![image](https://user-images.githubusercontent.com/18460380/33195996-7c248428-d102-11e7-8976-4b1d605d15eb.png)

**Comment by chsreedhar** [comment]
@stephanrauh you may set style attribute <code>style="width:100%"</code> for table element.

**Comment by stephanrauh** [comment]
Thanks for the reminder. For some reason, I've missed your November message. 

I just wonder how to implement your proposal. Of course we could generate `style="width:100%` into the HTML code. We could even guard it with a check examining the `style` attribute in the *.xhtml file. But there's no way we can guard against a width attribute in the CSS class.

So I recommend simply mentioning the issue in the showcase, documenting that adding `style="100%"` solves problems with certain themes. What's your opinion? Is that enough?

**Comment by chsreedhar** [comment]
@stephanrauh mention the issue in the showcase and document it.

**Comment by stephanrauh** [comment]
Good idea. Done!
