### ISSUE TITLE
Ajax call on b:tree

### ISSUE THREAD

**Issue by Sprechen** [TheCoder4eu/BootsFaces-OSP#823]
Hi guys,

I'm using the b:tree component with links enabled on my web page, with the following code:
```
		<h:form prependId="false">
			<b:tree
				render-root="false"
				value="#{geographicAreaList.tree}"
				showCheckbox="false"
				enableLinks="true"
				showBorder="true"  />
		</h:form>
```

Unfortunately, when I click on an element of the tree which opens a new link, on Safari a popup message is displayed, saying:
```
httpError: The Http Transport returned a 0 status code.  This is usually the result of mixing ajax and full requests.  This is usually undesired, for both performance and data integrity reasons.
```

I followed the documentation and the code example in the github repositories. I also attach a screenshot of the popup.

Any ideas or solution in order not to show the popup?

Thanks!

<img width="947" alt="bug" src="https://user-images.githubusercontent.com/10724424/28457495-9c8ac4a2-6e06-11e7-9208-72551a6c4d90.png">

**Comment by kvj2020** [comment]
In your example, you don't seem to be using a node-selection-listener="#{geographicAreaList}".  This listener must implement TreeNodeEventListener.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
