### ISSUE TITLE
b:dataTable rowStyleClass

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#824]
i want to conditionally hide a row.  with `h:dataTable` this can be achieved with `rowStyleClass` for example
```xml
<h:dataTable var="detail" value="#{entityTestBean.entity.details}" 
    rowStyleClass="#{detail.archived ne null ? 'entityTestHidden' : ''}">
```
i can't seem to find a similar method with `b:dataTable`?

**Comment by stephanrauh** [comment]
I'd prefer to document how to achieve the same goal with CSS. From a technical perspective, we could use the datatables.net API to set different classes for each row, but I think we'd run into all kinds of problems using this approach. For instance, the classical example is striping. What happens to the stripes if the table is filtered or sorted?

However, your example is a bit different. It depends on the data, so it can't be implemented using simple CSS rules, nor is it broken by sorting or filtering. A quick test showed that we can implement it.

So let's document the CSS rules for the majority of cases, and implement row classes for CSS rules depending on the data.

**Comment by stephanrauh** [comment]
It was surprisingly easy to implement the feature you requested. So I'll postpone the documentation of the CSS approach.

**Comment by stephanrauh** [comment]
I've uploaded the developer snapshot to Maven Central. As usual, see #369 on how to get it.
