### ISSUE TITLE
Buttons extension datatables (export to excel)

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#827]
Hi, 

Is it possible to use the datatable's extension (https://datatables.net/reference/button/) with the b:datatable? 

I want to export to excel, and I know that there are some ways to do it using js, but I was wondering if i could do by another way using the reference above.

**Comment by stephanrauh** [comment]
At first glance, this plugin looks interesting.

**Comment by atsoares** [comment]
as suggestion we could have also this one https://datatables.net/extensions/scroller/

**Comment by atsoares** [comment]
I solved the excel export by using a js code as I said I would do. It was the fastest way to do it. 

About the enhancement, it's really interesting not just the plugin to export but all others. 

As right now I have to implement an infinite scroll to these tables, and even knowing how to procede with js and css, would be much better to have something like scroller.

**Comment by stephanrauh** [comment]
The button extension is already delivered with BootsFaces. The infinite scroller is not. Let's concentrate on the button extension first because infinite scroll gets its data from a file or an AJAX data source. In other words: the API doesn't match the current implementation of `b:datatable`.

**Comment by stephanrauh** [comment]
I've implemented a provisional version supporting the buttons extension. However, I think we have to remove the pdf library and the zip library from the BootsFaces.jar. Both add 1.1 Mb and 365 Kb, respectively. It's better to get them from a CDN.

**Comment by stephanrauh** [comment]
Live demo here: http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf (the topmost demo).

**Comment by chongma** [comment]
looks great!

**Comment by ggam** [comment]
Awesome!

**Comment by stephanrauh** [comment]
@TheCoder4eu Is the size of the BootsFaces.jar as important as it used to be? The latest addition to the data table catapults the size of the file beyond 3 megabytes. I suppose we can reduce the amount of JavaScript sent to the client easily, but it's difficult to reduce the size of the BootsFaces.jar unless we rely on a CDN hosted by a third party.

What's your opinion?

**Comment by TheCoder4eu** [comment]
@stephanrauh well, I think the best solution is CDN, since it is a feature mainly not used for rendering but for exporting data.
And I also would like to avoid excessive burden on the Jar too: if the libraries have a large footprint then a CDN should be more efficient than self-hosting the lib.

**Comment by gezertab** [comment]
Hello, datatable predefined buttons for excel,pdf etc not working. My code is
 <b:dataTable
			  value="#{xxxxxxxxxxxxxxxxx}" var="xxxxx"
			  excel='true' 
			  pdf='true'
			  customLangUrl="//cdn.datatables.net/plug-ins/1.10.15/i18n/Greek.json"
			  multi-column-search="true"
			  multi-column-search-position='top' >
All parameters  working except excel/pdf . Any tips?

**Comment by stephanrauh** [comment]
@gezertab Which version of BootsFaces do you use? The PDF and Excel export is a new feature of BootsFaces 1.1.3. We haven't published this version yet, but plan to do so next week.

**Comment by gezertab** [comment]
Ok then, i ll look forward for it. Currently Im using BootsFaces-OSP-1.1.2-dist.jar

Thanks for your reply

**Comment by stephanrauh** [comment]
@gezertab The developer shapshot is here: https://oss.sonatype.org/content/repositories/snapshots/net/bootsfaces/bootsfaces/1.1.3-SNAPSHOT/
