### ISSUE TITLE
Combobox (<b:selectOneMenu>) with readonly="true"

### ISSUE THREAD

**Issue by matasci** [TheCoder4eu/BootsFaces-OSP#828]
The `selectOneMenu` with `readonly="true"` it does not block changes.

```xml
<b:row>
	<b:selectOneMenu label="Test-selectOneMenu" readonly="true">
		<f:selectItem itemLabel="Test1" itemValue="1" />
		<f:selectItem itemLabel="Test2" itemValue="2" />
		<f:selectItem itemLabel="Test3" itemValue="2" />
	</b:selectOneMenu>
</b:row>
```

**Comment by stephanrauh** [comment]
Interesting find. The good news is that the input is rejected by the backend, so little harm is done (apart from displaying a confusing UI, which is bad enough).

**Comment by stephanrauh** [comment]
Also, see https://stackoverflow.com/questions/32846865/twitter-bootstrap-select-readonly-still-able-to-change-options. Apparently, there's no `readonly` attribute in standard HTML.

**Comment by stephanrauh** [comment]
Now `<b:selectOneMenu readonly="true" />` renders more or less the same code as `<b:selectOneMenu disabled="true" />`.
