### ISSUE TITLE
inputText with rendered="false" display label

### ISSUE THREAD

**Issue by matasci** [TheCoder4eu/BootsFaces-OSP#829]
Not rendered inputText render the label.

```xml
<b:row>
   <b:inputText label="Test" rendered="false" />
</b:row>
```

**Comment by stephanrauh** [comment]
So you've tried to hide an input field by setting `rendered="false"`? And you've seen the label nonetheless?

I suppose you error description is incomplete. It's very unlikely that `b:inputText` renders a label if `rendered="false"`. The first statement of the renderer checks this, and returns immediately. The code rendering the label comes after that.

```java
public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
		if (!component.isRendered()) {
			return;
		}
```

**Comment by matasci** [comment]
I'll verify, but on my tests:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	<b:container id="orderTest" layout="fluid" >
		<b:row>
			<b:label text="Test-inputText(rendered=false)" />
		</b:row>
		<b:row>
			<b:inputText label="inputText-Label" rendered="false" />
		</b:row>
	</b:container>
</h:body>
</html>
![renderedfalse](https://user-images.githubusercontent.com/5858948/28829245-64602ba0-76d3-11e7-9343-7e7e1970dcd7.PNG)

**Comment by uschti** [comment]
I have the same issue. I tried the following code (by adding the `<b:column>`):

		<b:panel title="regular BootsFaces b:form (stacked)" look="success">
			<b:form>
				<b:row>
					<b:column medium-screen="full">
						<b:inputText label="b:inputText" label-style="width:150px" value="0" update="@this" rendered="false" />
					</b:column>
				</b:row>
			</b:form>
		</b:panel>

unfortunately the result is the same, the label still there:

![screen shot 2017-08-08 at 11 59 55](https://user-images.githubusercontent.com/24552497/29066955-22daad78-7c31-11e7-9a40-6ec30b25c9a3.png)

**Comment by uschti** [comment]
I figured out that the problem was not in bootsfaces!

I'm using a spring-boot environment with joinfaces (https://github.com/joinfaces/joinfaces) as a parent pom to get spring-boot running with JSF. In my configuration I was using a starter pom to use bootsfaces library but this starter was also including the AngularFaces library that was causing me this kind of problem. After privately discussing the problem with the user "matasci" I figured out that he has the same problem.
You can close the issue!

Thanks
uschti

**Comment by stephanrauh** [comment]
Awesome analysis, thanks! I have to admit that I thought of AngularFaces, too, but it wasn't mentioned in the ticket, so I dismissed the idea.

I guess you've already figured out yourself that you can deactivate the automatic rendering of the labels by adding the attribute `addlabel="false"` (http://angularfaces.net/version2.1/tutorial/step_01/index.jsf).
