### ISSUE TITLE
Any plans for Tree component? i'd suggest looking at jstree. there is also bootstrap theme for it.

### ISSUE THREAD

**Issue by ravshansbox** [TheCoder4eu/BootsFaces-OSP#83]

**Comment by stephanrauh** [comment]
Yes, jstree looks nice. We could give it a try.

**Comment by zhedar** [comment]
To track progress on this: This seems to be implemented in https://github.com/TheCoder4eu/BootsFaces-OSP/pull/313 by @asterd with some fixes in https://github.com/TheCoder4eu/BootsFaces-OSP/pull/315.

**Comment by stephanrauh** [comment]
The b:tree component has been implemented and documented.
