### ISSUE TITLE
Is there any example to use the RowReorder feature of the datatable?

### ISSUE THREAD

**Issue by hei1233212000** [TheCoder4eu/BootsFaces-OSP#833]
I see the datatables.mim.js inside the Bootsfaces already included the RowReorder 1.2.0.

Then I tried to enable it via the custom option: customOptions="rowReorder:{selector: 'tr'}".
```html
<b:form id="form">
    <b:dataTable id="bf-data-table" value="#{dataTableTestBean.data}" var="data" widgetVar="tableWidget"
                 customOptions="colReorder:true, rowReorder:{selector: 'tr'}">
        <b:dataTableColumn label="Order">
            ${data.order}
        </b:dataTableColumn>
        <b:dataTableColumn label="Name">
            ${data.name}
        </b:dataTableColumn>
        <b:dataTableColumn label="Age">
            ${data.age}
        </b:dataTableColumn>
        <b:dataTableColumn label="Sex">
            ${data.sex}
        </b:dataTableColumn>
    </b:dataTable>
</b:form>
```
In this setting, I could drag and drop the row BUTI found that I have 2 problems:

1. the row is ONLY moved by one line. e.g: I move the 1st row to the last, after I drop the row, the "1st row" will ONLY be moved to the 2nd row. I found a similar question on [stackoverflow](https://stackoverflow.com/questions/38790388/datatables-rowreorder-moves-only-by-one-line) but I think I already provide the sequence number(order in my case).

2. In the [Bootsfaces DataTables tutorial](https://showcase.bootsfaces.net/forms/DataTable.jsf),  it claims that Bootsfaces offers only a subset of the events. So, may I know if it is possible to bind callback to the "row-reorder" event?

Thank you.

**Comment by hei1233212000** [comment]
Any update?

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
