### ISSUE TITLE
datatable footer not responsive

### ISSUE THREAD

**Issue by chaoqian** [TheCoder4eu/BootsFaces-OSP#837]
bootsfaces datatable footer is not responsive as normal rows.

Attached a screen shot.
![image](https://user-images.githubusercontent.com/3410645/29337749-5e9e2e0c-81c7-11e7-83ca-4bc7daf394f3.png)

**Comment by stephanrauh** [comment]
I've been looking at this ticket yesterday again. I'm not sure it can be solved. It's a bit weird, but the "responsive" plugin of datatables.net doesn't seem to support responsive footers.

@TheCoder4eu @asterd @chongma @zhedar @ggam Anybody got an idea?

**Comment by ggam** [comment]
Sorry I don't really see it from the screenshot. What's the expected outcome?

If the plugin we're using cannot handle the case, I suppose our best chance is to reach the library authors and maybe open a PR? The project seems to be pretty active, but we would obviously need to dig into their source...

**Comment by stephanrauh** [comment]
@ggam The expected outcome is that the "+" icon is active in the footer. The table has - say - 10 columns, but only six of them can be displayed. So the other four are displayed only if you click the "plus" button. Thing is, the footer doesn't display the "plus" button.

As for reaching out to the authors: I guess you're right, but I've also learned it pays to check if it's our fault before doing so.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
