### ISSUE TITLE
dataTableColumn code completion does not work

### ISSUE THREAD

**Issue by stevekv** [TheCoder4eu/BootsFaces-OSP#838]
First, I'm not sure if this is a problem of the library or the IDE. I just drop it here and hope that you might have an idea where this comes from.

When I use 

`b:dataTable var="b"` 

for instance, and try to use the variable in a column like

`b:dataTableColumn value="#{b.` 

the IDE does not open a code completion window. If I change the table to 

`h:dataTable var="b"` 

it works. 

I'm using Netbeans 8.2. 

Thanks for any hint,
Stephan

**Comment by stephanrauh** [comment]
I don't think we can solve this bug. It's a peculiarity of Netbeans. You can temporarily replace `b:dataTableColumn` by `h:column` to activate code completion.

**Comment by stevekv** [comment]
Yeah, might be some exotic issue. Thanks any way.
