### ISSUE TITLE
severe errors using ui:param

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#846]
I get these severe errors although so far they don't seem to affect anything:
```
24-Aug-2017 13:48:16.946 SEVERE [http-nio-8080-exec-22] net.bootsfaces.beans.ELTools.getField Can't read the bean '#{instruct}'. Thus JSR 303 annotations can't be read, let alone used by the AngularJS / AngularDart client.
24-Aug-2017 13:48:16.946 SEVERE [http-nio-8080-exec-22] net.bootsfaces.beans.ELTools.getGetter Can't read the bean '#{instruct}'. Thus JSR 303 annotations can't be read, let alone used by the AngularJS / AngularDart client.

```
it occurs if i pass a param to a ui template using 
```
<ui:include src="/WEB-INF/include/bootstrap/quoteInstruct.xhtml">
	<ui:param name="instruct"
		value="#{quoteQuestionsInstructBean.quoteWrapper.instruct}" />
</ui:include>
```
and refer to it inside the template e.g.
```
<b:inputText label="#{msg.quoteInstruct10}" value="#{instruct.name}"
			placeholder="#{msg.quoteInstruct10}" required="true" />
```

**Comment by stephanrauh** [comment]
It's not really an improvement, but as a first step, I've improved the weird error message.

**Comment by stephanrauh** [comment]
Looks like a really hard problem to me. For some reason, the method `getValue2Render()` manages to resolve the parameter name, but the `ELTools` can't. Currently, I'm stuck because my IDE isn't able to show the source code of the code in the stack trace resolving the parameter.

**Comment by chongma** [comment]
when i step into ELTools.evalAsObject after line 120 and hover over context it tells me it is the PrimeFacesContext.  in another application i get FacesContextImpl.  it might not make a difference

**Comment by chongma** [comment]
https://stackoverflow.com/questions/14459854/how-to-retrieve-value-of-a-uiparam-in-the-backing-bean

**Comment by chongma** [comment]
yes indeed this works.  adding:
```
...
xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
...
<c:set var="testArticle" value="#{ta}" scope="request" />
```
in the included file seems to get rid of the error.  although it is rather disappointing as a solution.  it can be seen in the test project https://github.com/chongma/test under ui param

i am using MyFaces so it seems ui:param will never be available in FacesContext after render time.  the error seems harmless so maybe ignore it or remove it?

**Comment by stephanrauh** [comment]
Now it works for MyFaces, but keeps failing for Mojarra.

**Comment by stephanrauh** [comment]
I've fixed it for Mojarra, too, using the trick found by you, @chongma . The Mojarra solution is a bit scary, but it seems to do the trick.

I've uploaded a new developers snapshot to Maven Central (#369).

**Comment by chongma** [comment]
Thanks @stephanrauh. Well done for figuring it out. I will check the snapshot and let you know if there are any problems

**Comment by chongma** [comment]
sorry is it 1.1.3 or 1.2.0 snapshot?

**Comment by stephanrauh** [comment]
1.2.0-SNAPSHOT. The 1.1.3 has already been released.
