### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#847]
i am currently using the primefaces component for recaptcha https://www.primefaces.org/showcase/ui/misc/captcha.xhtml which means my pages have to load in all the primefaces components etc slowing the page down.  it should be fairly easy to implement the recaptcha component... https://www.google.com/recaptcha/intro/android.html

**Comment by stephanrauh** [comment]
Can we use the CAPTCHA for free? I remember it used to be a commercial product you have to pay for, but I'm not sure.

**Comment by chongma** [comment]
you have to have a google account. i have never paid anything to use it.  that might change in the future

**Comment by stephanrauh** [comment]
IMHO, GDPR makes the Google captcha pretty much illegal. It's not impossible to use it legally, but it's difficult. To me, that sounds like Pandora's box. I prefer not to open it.
