### ISSUE TITLE
Support for JSF 2.0

### ISSUE THREAD

**Issue by srbala** [TheCoder4eu/BootsFaces-OSP#85]
I have noticed that currently BootFaces uses JSF 2.2 to compile. But only in few places it uses the 2.2 features. It would be great if BootFaces can be used in JSF 2.0 environments in run time. Rendering can dynamically detect JSF version, If 2.0 version found by pass any 2.2 version calls.

**Comment by stephanrauh** [comment]
I replaced the offending source code by a bit of reflection magic. The showcase seems to work with JSF 2.0.11-01 without problems (apart from the AngularFaces demos, of course).

**Comment by srbala** [comment]
Thank you, I will test it out.
