### ISSUE TITLE
more flexible CSS styling options for b:progressbar

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#850]
`<b:progressBar>` consists of two nested divs. The inner div is can be influenced by setting `style` and `styleClass`.

I suggest to apply the styles to the outer div. For the inner div, we could add `content-style` and `content-class`. 

However, that's a breaking change. Do you think that's a problem? The alternative would be to introduce new attributes name `container-style` and `container-class`, which makes the attribute names harder to learn.

**Comment by stephanrauh** [comment]
I've pushed the change to GitHub so you can test it yourself.

**Comment by stephanrauh** [comment]
@asterd @TheCoder4eu @ggam @chongma @zhedar I haven't heard from you, so allow me to "ping" you explicitly. As you can see in the history of the GitHub issue, I've committed a breaking change. I suppose we can get away with it, but I'd like to hear your opinion.

I close the issue nonetheless. We can re-open it at any time :).

**Comment by chongma** [comment]
Hi i didn't realise you were the original reporter of this issue or that you were awaiting feedback from me. I haven't used the progress bar component before so I am not familiar with how it works.
