### ISSUE TITLE
<b:panel> : inView attribute not documented ?

### ISSUE THREAD

**Issue by Kristover** [TheCoder4eu/BootsFaces-OSP#852]
Hi,

i  found accidentally in b:panel an attribute that is not referenced into the showcase doc : ...inView=""...
For what purpose is this attribute for please ?

Thanks in advance for your precisions.

**Comment by stephanrauh** [comment]
`inView` is an internal flag of the JSF engine. Every component that's part of the view tree gets the flag `inView=true`. Currently, I don't see how application developers can make use of this flag.
