### ISSUE TITLE
b:dataTable causes JavaScript errors in Liferay 7.0 due to CDN resource

### ISSUE THREAD

**Issue by stiemannkj1** [TheCoder4eu/BootsFaces-OSP#853]
Liferay 7.0 exposes an AMD loader and [certain JS resources do no behave well when an AMD loader is present due to anonymous modules](http://requirejs.org/docs/errors.html#mismatch). In order to work around these errors, the Liferay Faces Bridge filters the content of these resources slightly to disable their AMD loader features. **`datatables.min.js`** is one of the resources that we must filter. With BootsFaces `v1.1.2` things worked fine, but with `v1.1.3` **`datatables.min.js`** was moved to using a CDN. Since **`datatables.min.js`** is no longer present on the server, the Liferay Faces custom `ResourceHandler` can no longer filter the **`datatables.min.js`** resource to make it compatible with Liferay 7.0's frontend JS.

In order to fix this, **`datatables.min.js`** should be included in the BootsFaces jar (or a ResLib jar) as it was in `v1.1.2` and an option should probably be included to enable loading the resource from a CDN.

**Comment by chsreedhar** [comment]
@stephanrauh, include **`datatables.min.js`** and **`datatables.min.css`** in to `jar`, otherwise [`<b:dataTable />`](https://showcase.bootsfaces.net/forms/DataTable.jsf) not going to work without internet connection.

**Comment by stephanrauh** [comment]
@chsreedhar We've extracted the file because it adds a huge amount of memory to the core library. However, we can split the BootsFaces.jar into two jars: one containing the core library, and an optional jar containing the datatable files. If the optional library is not there, we use the CDN approach. How do you like this idea?

**Comment by chsreedhar** [comment]
@stephanrauh nice idea.

**Comment by paulohva** [comment]
@stephanrauh Is this enhancement planned to be in upcoming releases? I can't update my version of Bootsfaces without a solution for this.

**Comment by stephanrauh** [comment]
@TheCoder4eu What's your opinion?

**Comment by NMagarreiro** [comment]
@stephanrauh and @TheCoder4eu, there are any news about this issue? Our client machines does not have internet connection, so we need this issue resolved in order to upgrade BootsFaces version.

**Comment by NMagarreiro** [comment]
Hi @stephanrauh and @TheCoder4eu,
I checked that this problem still happens on BootsFaces 1.3.0. 
Is this correction planned to a future release?

Thanks.

**Comment by stiemannkj1** [comment]
@sephanrauh, @TheCoder4eu, could you make the URL for the resource configurable via init-param so that people could provide their own local version if they want?

**Comment by stephanrauh** [comment]
@stiemannkj1 @chsreedhar @NMagarreiro First of all, sorry for forgetting this ticket. Somehow, it got buried under a pile of new tickets.

But maybe it's good we didn't implement the solution in a hurry. Kyle, I like your idea better than my original idea. Maybe you're familiar with our approach to using jQuery? I'd like to implement the same idea for the datatable:
 
 - BootsFaces checks the header and the body for JS and CSS resources. If it finds something containing the keyword "datatables" and ending with either ".js" or ".css", we assume the user brings their own copy of <code>datatables.min.{css|js}</code>.
 - We also add a `web.xml` parameter stopping BootsFaces from loading the datatable resources. I suppose nobody needs such a feature, but you never know.

How do you like the idea?

**Comment by stiemannkj1** [comment]
@stephanrauh, sounds good to me. Perhaps you could include an example or documentation showing how to use this feature as part of the ticket?

**Comment by stiemannkj1** [comment]
@stephanrauh, looks good :) Minor tweaks:

You may be able to skip the looping check if `get_datatable_from_cdn` == `false`. 
You may be able to abort the loop (`break`) when `loadDatatables` is set to `false`.

**Comment by stephanrauh** [comment]
Current state of the art: there's some documentation, but the live demo is still being developed. What's already there should appear soon at https://showcase.bootsfaces.net/layout/resourcemanagement.jsf.

**Comment by chsreedhar** [comment]
@stephanrauh use context parameter `net.bootsfaces.get_datatable_from_cdn` and go ahead with your [proposal ](https://github.com/TheCoder4eu/BootsFaces-OSP/issues/853#issuecomment-326832205) above.

**Comment by stephanrauh** [comment]
I've finished the first demo at https://staging.bootsfaces.net/Showcase/layout/resourcemanagement.jsf.

Currently, the demo only demonstrates how to use the web.xml parameter. The other detection mechanisms still need a demo in the showcase.
