### ISSUE TITLE
tabs damage usage of file upload

### ISSUE THREAD

**Issue by jottyfan** [TheCoder4eu/BootsFaces-OSP#855]
verified behavior in version 1.1.3 of bootsfaces:

```java
import javax.servlet.http.Part;

@ManagedBean
@SessionScoped
public class MyBean {
  private Part file;
  public Part getFile() {
    return this.file;
  }
  public void setFile(Part file) {
    this.file = file;
  }
  public String upload() {
    if (file == null) {
      FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("file is null"));
    }
  }
}
```

```xml
<b:tabView>
  <b:tab title="damaged">
    <h:form enctype="multipart/form-data">
      <h:inputFile value="#{myBean.file}" />
      <b:commandButton action="#{myBean.upload}" value="upload" />
    </h:form>
  </b:tab>
</b:tabView>
```

produces a "file is null" message, while

```xml
<b:panel title="undamaged">
  <h:form enctype="multipart/form-data">
    <h:inputFile value="#{myBean.file}" />
    <b:commandButton action="#{myBean.upload}" value="upload" />
  </h:form>
</b:panel>
```

doesn't crash. Therefore, using tabs with file uploads is not possible yet.

**Comment by stephanrauh** [comment]
Just double-checking: tabs complain a lot if you don't put them inside a form tag (at least in the developer stage). Did you do so? In other words: does your program nest two forms into each other?

**Comment by jottyfan** [comment]
Simply take the examples, there is no form in a form. I've even tried it with b:form, but the error still is the same.

I want to have a form inside of multiple tabs, therefore, a h:form outside of the tabView is no solution.

**Comment by stephanrauh** [comment]
The bug is a side effect of #807. I've uploaded a new version of BootsFaces-1.2.0-SNAPSHOT to Maven Central. As usual, see #369 on how to get it. Would you mind to run a test and confirm the bug has been fixed?

**Comment by jottyfan** [comment]
Yes, with version 1.2.0-SNAPSHOT, the bug is solved. Thanks for the fast solution, looking forward to see 1.2.0 soon. 👍
