### ISSUE TITLE
DataTable Missing Feature?

### ISSUE THREAD

**Issue by kvj2020** [TheCoder4eu/BootsFaces-OSP#856]
I cannot find a way to show a datable row as selected without a user clicking on the row.  I have a use case to show a row as preselected.  I am using BootsFaces 1.1.2

As an example, PrimeFaces supports this feature: 
<p:datatable id="carTable" var="car" value="#{carBean.cars}"  
                 selection="#{carBean.selectedCar}">

**Comment by stephanrauh** [comment]
Done and documented.
