### ISSUE TITLE
dropMenu error message

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#860]
I recently had a problem where when the code below is run, and `#{myBean.myClassList}` gets a NPE (or other initialisation problem) the error message outputs inside `<ul>` tags and is not visible to the user.  the user has to look through the page source to find out what the error was.
```xml
<b:dropMenu value="drop menu" active="true">
	<ui:repeat var="myClass" value="#{myBean.myClassList}">
		<b:navLink outcome="newPage?faces-redirect=true" value="#{myClass.name}">
			<f:param name="id" value="#{myClass.id}" />
		</b:navLink>
	</ui:repeat>
</b:dropMenu>
```

**Comment by stephanrauh** [comment]
Oops. BootsFaces shouldn't behave like that. But at first glance, I have no idea how to solve that. It's more like an HTML problem. Anybody got an idea?

**Comment by chongma** [comment]
could an EL error be caught before the drop menu is rendered ?  shall i create a reproducer?

**Comment by stephanrauh** [comment]
Yes, a reproducer would be nice! As much as I hate to admit it, our spare time is limited, so we love to cut corners :).

**Comment by stephanrauh** [comment]
I've thought about the issue again.

It's not entirely impossible to improve the HTML code:

- We could call each getter before starting rendering
- We could use a local `ResponseWriter`. Only when the component has successfully completed rendering, we'd pump the content of the local `ResponseWriter` to the global one.

But: in your case the error occurs in a different component. That makes it difficult to predict which HTML code to render. More likely than not, you end up with an empty page.

I think it's better to accept the annoying nuisance. Trying to improve things might make it worse. Luckily the current approach works in most cases.

Is it OK to close the issue?
