### ISSUE TITLE
AddResourcesHandler adds resources in wrong order - BootsFaces 1.2.0

### ISSUE THREAD

**Issue by kvj2020** [TheCoder4eu/BootsFaces-OSP#863]
When loading a page with ajax that contains <b:datatable>, the browser console reports the following error: "datatables.min.js:sourcemap:74 Uncaught ReferenceError: jQuery is not defined.".

This error only occurs when using MyFaces.

**Comment by stephanrauh** [comment]
Fixed by TheCoder4eu/BootsFaces-OSP@887aa07.
