### ISSUE TITLE
b:growl style and styleClass properties ignored

### ISSUE THREAD

**Issue by uschti** [TheCoder4eu/BootsFaces-OSP#864]
Hello,
I'm trying to apply a custom CSS class to the **Growl** component to change the z-index and have it over the modal but it doesn't work.

I tried both, **style** and **styleClass** but the custom css is not added to the Growl component.

If I try to modify the z-index of the **alert** class it works, but applying a custom css or style it's not added to the component.

my declaration of the grow message is the following:

```
<h:form id="pageForm" prependId="false">
<b:growl id="growlMsg" globalOnly="false" placement-from="top" placement-align="center" show-detail="true" show-summary="false" allowDismiss="true" delay="6000" escape="true" styleClass="myCssOverModal"  />
</h:form>
```

Best regards
uschti

**Comment by stephanrauh** [comment]
Oh - we simply forgot to add the styling options. There's even a `todo` at the beginning of the class. Sorry for letting you run into the trap!

Until we've fixed the bug, you can use CSS classes as described here: http://bootstrap-notify.remabledesigns.com/ (section "Customized notifications").

**Comment by TheCoder4eu** [comment]
@stephanrauh is there anything else to do or I can close this issue?

**Comment by stephanrauh** [comment]
I've just tested the ticket again. Obviously, I had simply forgotten to close it in September.

**Comment by ersigcha23** [comment]
Hi

I want to know how the "myCssOverModal" works to put the Growl in front of the modal?
I'm trying to do that but it's not working

Thanks

**Comment by stephanrauh** [comment]
You need to add the `!important` modifier to the CSS class. Plus, you can only influence the z-index using the CSS class. You can do that by providing the `style` attribute (for some technical reason). The z-index of the modal is 1049, so the growl needs to be z-index 1050 or above, as shown in this example:

```xml
<style>
   .beam-me-up {
      z-index:1050 !important;
  }
</style>
<b:growl id="growlMsg"
                styleClass="beamMeUp" />
```

**Comment by ersigcha23** [comment]
Thanks. It worked!.

 Apart from that I was forgetting to update the Bootsfaces dependency to 1.2.0
