### ISSUE TITLE
Field results per page disappears when using new features of b:dataTable

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#868]
Hi

When I enable some of the new features of `<b:dataTable>` (`excel`, `csv`, `pdf`, `columnVisibility`) the field to select results per page (in the upper left corner of the grid) disappears. It doesn't matter if I set or not some value to `pageLength` and/or `pageLengthMenu`.

Is it normal behavior?

Thanks.

**Comment by tg47** [comment]
I have noticed this behavior as well. I have also noticed that when the user uses one of these buttons the output only includes one header row. If two rows are present in the header the top row is excluded from the export, csv, pdf, print of the data table.

**Comment by stephanrauh** [comment]
I've tried to reproduce the first bug. I suspect it's been solved during one of the recent updates, probably one of the updates of the datatables.net plugin itself.

As for the header rows: please report that to the author of these plugins. 

BTW, please apologize the sluggish response. The BootsFaces teams virtually drowned in a flood of new issues.
