### ISSUE TITLE
New features for b:growl

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#869]
Hi

Is it possible to implement the following properties for `<b:growl>` (as in `<b:messages>`)?

`info-class` - `warn-class` - `error-class` - `fatal-class`

Reason: I would like to only show `info` messages in `<b:growl>` and the others (`warn`, `error`, `fatal`) in `<b:messages>`.

Currently I use Primefaces `<p:growl>` but I would like to use `<b:growl>` instead.

Example:
```xml
<b:messages id="mensagens" info-class="message-info-hidden" />
<p:growl autoUpdate="true" for="message-growl" life="2000" showDetail="true" showSummary="false" />
```
```css
.message-info-hidden {
	display: none;
}
```
```java
public void salvar() {
	if (StringUtils.isEmpty(senha)) {
		throw new NegocioException("É necessário informar Senha");
	}		
	usuario = usuarioService.salvar(usuario);
	FacesUtil.addInfoMessageGrowl("Gravação efetuada com sucesso.");
}

public static void addInfoMessageGrowl(String message) {
	FacesContext context = FacesContext.getCurrentInstance();		
	FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, message, message);		
	context.addMessage("message-growl", msg);
}
```
But actually `<b:growl>` does not allow me to use this way, and I think having these new properties would be perfect and more flexible.

Best regards
Ruan

**Comment by jepsar** [comment]
Hi, I've added the `severity` attribute to do this. It is available from version 1.1.2. See https://showcase.bootsfaces.net/forms/Growl.jsf and scroll down to "Severity".

````
<b:growl severity="info"/>
<b:messages severity="warn,error,fatal"/>
````

**Comment by ruanfelisky** [comment]
Hi, very nice!
Using `severity` worked perfectly and solved the issue.

Thank you very much!

**Comment by jepsar** [comment]
@ruanfelisky This issue can probably be closed. CC @TheCoder4eu

**Comment by ruanfelisky** [comment]
Yes can be closed, thanks :)

**Comment by stephanrauh** [comment]
OK, let's close the ticket :).
