### ISSUE TITLE
form label styling different from Bootstrap

### ISSUE THREAD

**Issue by kgeis** [TheCoder4eu/BootsFaces-OSP#871]
I see three ways that BootsFaces labels are different than Bootstrap labels.

- text is left-aligned
- text is top-aligned, so it does not look centered with the input field
- font is not bold

The first two are because the label does not have the "control-label" CSS class. The last is because what is emitted is a "puilabel" (I am using this with PrimeFaces) and does not match Bootstrap's CSS rule on "label" elements.

![image](https://user-images.githubusercontent.com/2237299/30834883-0bd353a6-a20a-11e7-8fcf-6728054d8824.png)

This is with BootsFaces 1.1.3.

FYI, I tried `label-style-class="control-label"` but it had no effect.

**Comment by stephanrauh** [comment]
It seems I've solved this in the meantime. You're right, the early implementations were buggy.
