### ISSUE TITLE
renderLabel not working

### ISSUE THREAD

**Issue by kgeis** [TheCoder4eu/BootsFaces-OSP#872]
I am using BootsFaces 1.1.3 with PrimeFaces 6.1. I am trying to create some forms, and on my fields (e.g. `inputText`, `dateTimePicker`) I am setting `render-label="false"` or `renderLabel="false"`, and there is no effect.

**Comment by chongma** [comment]
i am using bootsfaces 1.1.3 with primefaces 6.1 and i have just tested e.g. `<b:inputText label="test" value="test" renderLabel="false"/>` and it works fine.  can you give me more information about the problem?

**Comment by chongma** [comment]
sorry i must have missed your message.  i just ran your reproducer and can confirm that it doesn't hide the label

**Comment by stephanrauh** [comment]
That's AngularFaces interfering with your code. If you don't need it, remove it from the equation.

In theory, adding
```
jsf.angularfaces.add-labels=false
```
to the `application.properties` file should do the trick. Unfortunately, it didn't work when I tried. BTW, I didn't find out which file adds AngularFaces to the project. Even so, the HTML code of the `index.xhtml` clearly indicates that the offending label is generated by AngularFaces.
