### ISSUE TITLE
Unable to send parameters to method in bean via 'ajax:'

### ISSUE THREAD

**Issue by turbobrick** [TheCoder4eu/BootsFaces-OSP#876]
Currently I'm trying to send the key and value from a Map in a c:forEach to the bean itself to it can update certain elements in the view, but it seems that 'ajax:' expression can't parse them. Is there any workaround around this?

```xml
<c:forEach items="#{index.items}" var="item">
						<div>
							<b:commandButton value="test"
								size="lg"
								update="content"
								onclick="ajax:index.load(#{item.key}, #{item.value})"/>
						</div>
					</c:forEach>
```

And the error I'm getting is the following one...

`12:37:14,251 SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-10) com.sun.el.parser.ParseException: Encountered "," at line 1, column 30.
Was expecting one of: ...`

Or am I doing something wrong?

**Comment by chongma** [comment]
Why not pass the item to the bean and then get the key and value? Also why not use ui:repeat instead of a c:forEach?

**Comment by turbobrick** [comment]
If I pass the whole item it's the same, it's a matter or parsing not of what I'm sending to the bean. Why would I want to decompress an item in the bean when I can get the inner key and value from an entry already from the loop? I couldn't get ui:repeat to work with the collection I'm working with.

**Comment by chongma** [comment]
The error said the comma was causing the problem so i thought passing the item would eliminate that error.  I am not sure but in the ajax bit you might not need the braces as you are already in EL? i.e `ajax:index.load(item.key, item.value)`

**Comment by turbobrick** [comment]
Nope, that way I get null in both key and value, pretty strange actually as it was the first solution I was trying...

**Comment by chongma** [comment]
What does your bean function look like?

**Comment by turbobrick** [comment]
`	public void load(ItemDto item, List<Relation> relations) {
		this.item = item;
		this.relations = relations;
	}`

**Comment by chongma** [comment]
i imagined that `item.key` was type `long` or `int` and `item.value` was a type `String`.  so i imagined that your bean function was 
```
public void load(int key, String value) {}
```
i am a bit old fashioned and tend to use `f:setPropertyActionListener` so my normal method would be like this:
bean:
```
public class Index {
...
// declared at top of bean
private Item item;
...
public String load() {
  //do something with item
  System.out.println(item.getValue());
}
...
public Item getItem() {
 return item;
}
public void setItem(Item item) {
  this.item = item;
}
...
}
```
xhtml file:
```
...
<ui:repeat var="item" value="#{index.items}"
<b:commandButton action="#{item.load}" >
  <f:setPropertyActionListener target="#{index.item}" value="#{index}" />
</b:commandButton>
</ui:repeat>
...
```
it still wouldn't answer why your ajax function is not working though :(

**Comment by chongma** [comment]
actually i just realised that you are using c:forEach because you are iterating over a map.  have you thought of using a list instead?  let me write you an example

**Comment by chongma** [comment]
create a POJO that represents your map entry
```
public class Item implement Serializable {
 private ItemDto item;
 private List<Relation> relations;

public ItemDto getItem() {
 return item;
}
public void setItem(ItemDto item) {
  this.item = item;
}

public List<Relation> getRelations() {
 return relations;
}
public void setItem(List<Relation> relations) {
  this.relations = relations;
}

}
```

in your data class or bean where you populate the map:
```
public List<Item> selectItems() {
  List<Item> itemList = new ArrayList();

//do a for loop here or whatever
  Item item = new Item();
  item.setItem(theItemDtoObject);
  item.setRelations(theRelationsList);
  itemList.add(item)

  return itemList;
}
```

**Comment by stephanrauh** [comment]
I've tried to reproduce the code with strings as keys and values. That works, if you put the strings into single quotes, like so:
```xml
<b:commandButton value="#{item.key}"
	size="lg"
	update="@form"
	onclick="ajax:inputTextBeanle.load('#{item.key}', '#{item.value}')"/>
```

**Comment by stephanrauh** [comment]
If the arguments are objects, BootsFaces uses the `toString()` method in the EL expression. So the object can't be resolved.

I'll keep the problem in mind, but I don't think we should solve the bug. The code dealing with AJAX is already very complex. Adding this feature would push it over the edge. I suggest using the older approach (`f:ajax` and `f:setPropertyActionListener`) in this particular case.
