### ISSUE TITLE
b:selectOneMenu does not work with enums anymore

### ISSUE THREAD

**Issue by b0m0x** [TheCoder4eu/BootsFaces-OSP#877]
The following stopped working recently (worked with a previous version of bootsfaces):

```
<b:selectOneMenu value="#{controller.selectedValue}">
      <f:selectItems value="#{controller.selectItems}" />
</b:selectOneMenu/>
```
when getSelectItems() returns items with enums values:
```
public SelectItem[] getSelectItems() {
        SelectItem[] items = new SelectItem[2];
        items[0] = new SelectItem(ChronoUnit.WEEKS, "Weeks");
        items[1] = new SelectItem(ChronoUnit.MONTHS, "Months");
        return items;
}
```
h:selectOneMenu [supports this](https://stackoverflow.com/questions/2868778/jsf-2-0-use-enum-values-for-selectonemenu?answertab=votes#tab-top), too - JSF has an inbuilt converter for enum values. (related to #797 ?)

**Comment by TheCoder4eu** [comment]
@b0m0x , could you be more specific about the version? it could help us to identify what change might have broken something. Is it a v1.1.x fix release or you upgraded from a previous release (v1.0.x or less)?

**Comment by b0m0x** [comment]
I upgraded from v1.0.2.

**Comment by stephanrauh** [comment]
I've just tried to reproduce the bug. What precisely is broken? I copied your code into my test page and it worked like charm. Both with and without AJAX.

I'll close the ticket for the moment, but we'll reopen it if you provide us a reproducer showing the bug. Ideally as a small GitHub project (for example, like [this one](https://github.com/chongma/test)).
