### ISSUE TITLE
<b:dataTable>: Individual column searching (both input and select inputs)

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#879]
The `searching=true (Default value)` attribute add ability to search functionality of the datatable (i.e. both the UI and the JavaScript API). But, to search in individual coloumns, as per [DataTable example](https://datatables.net/examples/api/multi_filter_select.html) following script to be executed after initilisation completes

    function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
 
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
Above function is not working thourgh `customOptions` attribute, since multiple`double quotes (&#34;) and single quotes (&#39;)`
This individual coloumns searching functionality may be added to `<b:dataTable>`

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
