### ISSUE TITLE
Remove unsafe deserialization from net.bootsfaces.utils.BsfUtils.java

### ISSUE THREAD

**Issue by tommandera** [TheCoder4eu/BootsFaces-OSP#880]
On June 30, 2016’s [commit](https://github.com/TheCoder4eu/BootsFaces-OSP/commit/d909c3135b88d94293c6f47fd5a4bccc80800cc5#diff-923e912973a2692c79aeb85c9df2be7e) two methods were added to BsfUtils.java to support Issue  #422.  This change included the following two new methods in BsfUtils.java:

public static Object fromString(String s) 
public static String toString(Serializable o) 

As well as a change to net.bootsfaces.component.tree.TreeRenderer.java in the decode method that referenced the fromString call (component.tree.model.TreeModelUtils.java used the toString method).

if (value != null &&   !"".equals(value.trim())) {
Node n = (Node) BsfUtils.fromString(value);

Subsequent commit on April 4, 2017 “[Increase performance of b:tree control](https://github.com/TheCoder4eu/BootsFaces-OSP/commit/4e680005306bb9dfa432ff9417cebe0f9f57d41f#diff-825b0d818d1848ba6451fb9fa60897da)” removed the references to the BsfUtils.toString and BsfUtils.fromString from TreeModelUtils.java and TreeRenderer.java.

BsfUtils.toString and fromString appear to be unused code, orphaned, that was not removed when the modules that used it were altered.

The toString and fromString methods perform a potentially unsafe serialization/deserialization operation. While unused, they are present, and as public static methods they are available to be used in a potentially unsafe manner.

I propose these two methods be removed before they can be used again.

**Comment by TheCoder4eu** [comment]
Hi @tommandera thanks for your help, it is very much appreciated!
We really missed this while refactoring and keeping unused code is never a best practice, in particular if it can be potentially unsafe.
