### ISSUE TITLE
BootsFaces Datatable

### ISSUE THREAD

**Issue by medienwerkstatt-niederrhein** [TheCoder4eu/BootsFaces-OSP#883]
Hello
I use Bootfaces Datatable. Everthing works fine  but i have one big problem. The Programm show me only 11 data sets. But there are 22000 data sets  in the Mysql Database.

**Comment by ggam** [comment]
Could you please provide some more insight or show us some code (or even better, a sample reproducer)?

Some more info of the environment would help too.

**Comment by medienwerkstatt-niederrhein** [comment]
Here is my code Example. <?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTblFlaschenlisteTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form>
  <b:dataTable value="#{tblFlaschenlisteController.items}"
               var="item"
               excel="true"
                 csv="true"
                 pdf="true"
                 columnVisibility="true"
                 copy="true"
                 print="true"
               >
     <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKriId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKriId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGasId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGasId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKon}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKon}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_konEinheit1}"/>
                            </f:facet>
                            <h:outputText value="#{item.konEinheit1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaFlgGroesse}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaFlgGroesse}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaWstId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaWstId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaVrfId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaVrfId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaVrwId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaVrwId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaNummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaNummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaRestmenge}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaRestmenge}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaEinheit}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaEinheit}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaEingangsdatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaEingangsdatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaTourNr}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaTourNr}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKunde}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKunde}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKundennr}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKundennr}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBemerkung}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBemerkung}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBegleitschein}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBegleitschein}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaServiceauftrag}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaServiceauftrag}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaIlanummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaIlanummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaSennummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaSennummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaPalette}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaPalette}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaDispodatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaDispodatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaLeerungsdatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaLeerungsdatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaFuellgrad}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaFuellgrad}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaAnbohren}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaAnbohren}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBw}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBw}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaAnalyse}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaAnalyse}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGemischId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGemischId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBearb}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBearb}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaUsername}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaUsername}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBearbdat}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBearbdat}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBruttogewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBruttogewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaTaragewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaTaragewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaClipnummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaClipnummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaNettogewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaNettogewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGasId1}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGasId1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKon1}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKon1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flazusatzID}"/>
                            </f:facet>
                            <h:outputText value="#{item.flazusatzID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{tblFlaschenlisteController.prepareView}" value="#{bundle.ListTblFlaschenlisteViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tblFlaschenlisteController.prepareEdit}" value="#{bundle.ListTblFlaschenlisteEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tblFlaschenlisteController.destroy}" value="#{bundle.ListTblFlaschenlisteDestroyLink}"/>
                        </h:column>
                    </b:dataTable>
               
              
 
            </h:form>
        </ui:define>
    </ui:composition>

</html>

**Comment by medienwerkstatt-niederrhein** [comment]
When i use datatable with primefaces there is no problem and everthing works fine

**Comment by chongma** [comment]
With a large dataset you might want to consider using a PrimeFaces LazyDataModel.  That doesn't explain why the `b:dataTable` isn't loading the records though...

**Comment by chongma** [comment]
Are the items definitely loaded in the backing bean?

**Comment by medienwerkstatt-niederrhein** [comment]
yes

**Comment by chongma** [comment]
if you change to an `h:dataTable` does it work?

**Comment by medienwerkstatt-niederrhein** [comment]
Yes, this code works. (But i need bootsfaces)
<ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTblFlaschenlisteTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListTblFlaschenlisteEmpty}" rendered="#{tblFlaschenlisteController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{tblFlaschenlisteController.items.rowCount > 0}">
                    <h:outputText value="#{tblFlaschenlisteController.pagination.pageFirstItem + 1}..#{tblFlaschenlisteController.pagination.pageLastItem + 1}/#{tblFlaschenlisteController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{tblFlaschenlisteController.previous}" value="#{bundle.Previous} #{tblFlaschenlisteController.pagination.pageSize}" rendered="#{tblFlaschenlisteController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{tblFlaschenlisteController.next}" value="#{bundle.Next} #{tblFlaschenlisteController.pagination.pageSize}" rendered="#{tblFlaschenlisteController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{tblFlaschenlisteController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKriId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKriId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGasId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGasId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKon}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKon}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_konEinheit1}"/>
                            </f:facet>
                            <h:outputText value="#{item.konEinheit1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaFlgGroesse}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaFlgGroesse}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaWstId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaWstId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaVrfId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaVrfId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaVrwId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaVrwId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaNummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaNummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaRestmenge}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaRestmenge}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaEinheit}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaEinheit}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaEingangsdatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaEingangsdatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaTourNr}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaTourNr}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKunde}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKunde}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKundennr}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKundennr}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBemerkung}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBemerkung}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBegleitschein}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBegleitschein}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaServiceauftrag}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaServiceauftrag}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaIlanummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaIlanummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaSennummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaSennummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaPalette}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaPalette}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaDispodatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaDispodatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaLeerungsdatum}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaLeerungsdatum}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaFuellgrad}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaFuellgrad}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaAnbohren}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaAnbohren}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBw}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBw}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaAnalyse}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaAnalyse}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGemischId}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGemischId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBearb}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBearb}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaUsername}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaUsername}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBearbdat}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBearbdat}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaBruttogewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaBruttogewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaTaragewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaTaragewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaClipnummer}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaClipnummer}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaNettogewicht}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaNettogewicht}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaGasId1}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaGasId1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flaKon1}"/>
                            </f:facet>
                            <h:outputText value="#{item.flaKon1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTblFlaschenlisteTitle_flazusatzID}"/>
                            </f:facet>
                            <h:outputText value="#{item.flazusatzID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{tblFlaschenlisteController.prepareView}" value="#{bundle.ListTblFlaschenlisteViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tblFlaschenlisteController.prepareEdit}" value="#{bundle.ListTblFlaschenlisteEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tblFlaschenlisteController.destroy}" value="#{bundle.ListTblFlaschenlisteDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{tblFlaschenlisteController.prepareCreate}" value="#{bundle.ListTblFlaschenlisteCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTblFlaschenlisteIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

**Comment by ggam** [comment]
Hi @medienwerkstatt-niederrhein. I've tried to reproduce your problem with a simplified but I couldn't. Here is the code I'm using: [datatable-error.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/1398549/datatable-error.zip)

It shows the 22K rows and exports them correctly. Could you please provide a reproducer? Have you checked your server logs? Perhaps an exception is occurring during rendering?

Btw, you should use `<b:datatableColumn />` instead of `<h:column />` with BootsFaces Datatable.

**Comment by stephanrauh** [comment]
After receiving no response after such a long time, let's close the ticket.
