### ISSUE TITLE
DateTimePicker

### ISSUE THREAD

**Issue by gezertab** [TheCoder4eu/BootsFaces-OSP#886]
Hello, 
Even triggering  with ondtchange="ajax:listOfValuesBean.periodChangeListener" after DateTimePicker change is not working.
The periodChangeListener code is :
public void periodChangeListener(AjaxBehaviorEvent event) throws DataSourceException, ConnectionException, StatementException, SQLException{
String objectnewperiod = (String) ((UIOutput)event.getSource()).getValue();
setNewperiod(objectnewperiod.toString());
//System.out.println("objectnewperiod...>"+objectnewperiod); 
}
the objectnewperiod variable is always null and the event is never triggered. 
Am I doing sth wrong?

**Comment by chongma** [comment]
the ondtchange doesn't seem to be working on the showcase either so it needs to be fixed https://showcase.bootsfaces.net/forms/DateTimePicker.jsf

**Comment by stephanrauh** [comment]
I've manage to fix the bug, but I failed to understand how the bug works. I know it's a bit pedantic, but I'm not happy about that. 

@chongma @TheCoder4eu @ggam Would you mind to have a look at the bug and my bug fix?

Thanks in advance,
Stephan
