### ISSUE TITLE
Releasedate 1.2.0

### ISSUE THREAD

**Issue by TTTThomas** [TheCoder4eu/BootsFaces-OSP#890]
Hallo, 

this is maybe not be right place to ask, but I havent found any different.
Is there already a release date scheduled for release 1.2.0?

**Comment by stephanrauh** [comment]
Hi,

sorry for the late answer - it took some time to decide on the release date. Currently, we plan to publish BootsFaces 1.2.0 in December. Most likely it'll be mid-December, but there are no promises on that.

BTW, you can speed up things by testing. Are you interested?

Best regards,
Stephan

**Comment by chongma** [comment]
i was using different maven profiles the other day and it occurred to me that i could set a default profile which depends on the latest BootsFaces snapshot on localhost and then uses stable in production.  that way i am aways testing during development.  might be something worth putting in the documentation?  in case others want to do the same...

**Comment by TTTThomas** [comment]
Thank you for the information. 
At the moment I am developing with the latest snapshot build and if I find any problems, I will report it.

**Comment by TheCoder4eu** [comment]
@TTTThomas , thanks, we appreciate your help!
