### ISSUE TITLE
b:inputText doesn't process ajax calls if fieldId is set

### ISSUE THREAD

**Issue by oliver-klein** [TheCoder4eu/BootsFaces-OSP#896]
Hi

I'm using Bootsfaces 1.1.3 and also experienced this issue in 1.1.0.
In the `<b:inputText>` component ajax calls are not processed if fieldId (field-id) attribute is set
Here is my example code:
```xhtml
<b:inputText fieldId="searchInputText" ajax="true" process="@form" 
	update="@form resultForm messages" onchange="ajax:statusController.update();"
	tooltip="Enter Container No. or Customer Reference"
	value="#{statusController.searchText}" placeholder="search">
</b:inputText>
```
If I change `fieldId` to `id` everything works fine!

This is not really a showstopper but good to know if someone wants to save time debugging ;-)

Best regards, 
Oliver

**Comment by stephanrauh** [comment]
Good hint. I've fixed it now. Thanks!
