### ISSUE TITLE
form input file

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFaces-OSP#899]
@stephanrauh This plugin [(Bootstrap FileStyle)](https://github.com/markusslima/bootstrap-filestyle) has an interesting way to present a form for sending files so attractive, simple and consistent look across browser, may consider to add in Bootsfaces components.

**Comment by stephanrauh** [comment]
Yeah, at first glance, it looks nice. Thanks for the hint!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
