### ISSUE TITLE
Message.severity is documented, but it hasn't been implemented yet

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#901]
At some point in time, we've implemented the attribute `Messages#severity` to filter which messages are to be displayed. We've documented it both for `b:messages` and `b:message`, but it seems we've only implemented it in the plural version.

**Comment by jepsar** [comment]
Does it make sense for a single message? I thought it wouldn't and only implemented it on the plural version. Anyhow, I could add it the the singular version as well to keep things consistent.

**Comment by stephanrauh** [comment]
Ah, that's why it's missing! I think we should keep things consistent - either by removing the attribute from the *jsfdsl (thus removing it from the documentation and from the taglib), or by implementing it.

If you'd like to provide a PR, we'd appreciate this a lot!

**Comment by jepsar** [comment]
I just checked, there is no severity attribute for `b:message`. Maybe the text at https://showcase.bootsfaces.net/forms/messages.jsf#severity could be improved, explicitly stating it only works with `b:messages`.

**Comment by stephanrauh** [comment]
I've updated the documentation.
