### ISSUE TITLE
Please help me: How to get datatable row index?

### ISSUE THREAD

**Issue by tamtc84** [TheCoder4eu/BootsFaces-OSP#910]
I use Bootsfaces 1.2.0:
`<b:dataTable value="#{aBean.getDataList()}" var="item">
  <b:dataTableColumn label="Row number">
                            <h:outputText value="" />
</b:dataTableColumn>`
I want to view index column in "Row number" column.
I saw it in [https://datatables.net/examples/api/counter_columns.html](https://datatables.net/examples/api/counter_columns.html)
But i don't know how to use in <b:dataTable >.
Please help me to do it.
Thank you.

**Comment by stephanrauh** [comment]
The example on the DataTable.net page uses some fancy JavaScript. I'm reluctant to include something like this in BootsFaces. The idea of JSF is to provide a simple, easy-to-grasp abstraction between you and the HTML5 page. If you need more power, JSF enables you to use HTML5 directly.

So I suggest you look for a simpler approach. For example, you could add the row index to the elements of the array in the backing bean. Is that an option to you?

**Comment by stephanrauh** [comment]
Any news on this? I'll close this ticket because I didn't hear from you. IMHO, the approach using the JSF bean should do the trick, so there's a workaround (even if it may be less elegant than the approach shown at the DataTables.net documentation).

**Comment by gmanjon** [comment]
Hello everyone,

I know is a bit late for this, but even though every data table helper library that I came across had the index feature (I really think is something worth adding), I've though of a workaround worth sharing. In the case exposed here would be the following:
```
<b:dataTable value="#{aBean.getDataList()}" var="item">
    <b:dataTableColumn label="Row number">
        <h:outputText value="#{aBean.getDataList().indexOf(item) + 1}" />
    </b:dataTableColumn>
```
That would render the index of the element in the list.

Thanks to the authors of Bootsfaces for this great library.
