### ISSUE TITLE
<b:datatable> searching is wrong when the row contains buttons

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#911]
When using a data table we may have controls inside the rows. The search functionality of the data table however searches inside their generated html (expected but not desired) - so if you have a table with some buttons in the last column, if you type "3" (without the quotes) in the search field, you'll most probably get the third row visible, no matter if there are 3-s or not - mainly because of the button ids being like `something:3:mybutton` -- containing the row number.
I tried using the `searchable=false` attribute in the dataTableColumn, but, as specified, it only works with multi-column search.
It would be nice if `searchable` would also work when `multi-column-search` is false. This behaviour exists in DataTables.net -- `columns: [null, null, ... , {searchable: false}, ...]`

**Comment by stephanrauh** [comment]
OK, it took a while, but I think now I've got it. You want to be able to exclude certain columns from the search while still having a single search field for the entire table?

**Comment by vsvetoslavov** [comment]
@stephanrauh yes. And the reason for the exclusion is because the search also searches in some of the custom HTML code. I added an example to make it more clear:
https://jsfiddle.net/nupkc/wrjzggwj/

**Comment by stephanrauh** [comment]
I've implemented the feature. Thank for creating the Fiddle. It helped me a lot!

**Comment by stephanrauh** [comment]
There's a new developer snapshot at Maven Central, so you can test the feature. See #369 how to get it.

**Comment by vsvetoslavov** [comment]
I won't be able to test this any time soon. Maybe someone else...
