### ISSUE TITLE
How to use the events of the TypeAhead library in BootsFaces?

### ISSUE THREAD

**Issue by nikosit** [TheCoder4eu/BootsFaces-OSP#912]
Hello,

i am new to Bootsfaces and just started using it into our new company project. I try to use the <b:inputText/> element by its autocomplete function. We have a problem because we can not find yet an equal event, as 'selectInput' from primefaces autocomplete, and we can not fire the update event direct after clicking the chosen element.
Is there a workaround or do you indent to implement an ajax update function similar to <p:autocomplete/> from primefaces?

Thank you in advance.

**Comment by stephanrauh** [comment]
I'm reluctant to add such a feature to BootsFaces itself, but it's easy to implement a workaround. A quick research on https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md revealed that you're probably referring to the `typeahead:select` event. You can intercept this event by assigning a pseudo CSS class to the input field and applying a litte jQuery magic:

```xml
<b:inputText styleClass="csv-autocomplete"  
                      typeahead="true" 
                      typeahead-values="#{tagsBean.bandsCSV}" />
<script>

$('.typeahead').bind('typeahead:select', function(ev, suggestion) {
  console.log('Selection: ' + suggestion);
});
</script>
```

You didn't mention it, but I suppose you want to call a server-side method via AJAX. You can do so using `<b:remoteCommand>`, which has been inspired by its PrimeFaces counterpart.

**Comment by stephanrauh** [comment]
I'll close this issue because I assume the workaround already helps you. If it doesn't, please feel free to re-open the issue. In any case, we'd appreciate if you report back even if (and especially if!) the hint solved your problem. 

Thanks in advance,
Stephan

**Comment by nikosit** [comment]
Hello,

thank you very much for your quick response and the solution suggestion. The workaround worked partly and only in approach to the binding of the 'select' event. The problem is, that the 'update' function of the <b:inputText/> element triggers the update after the element loses focus. Further more the solution of the <b:remoteCommand/> didnt seam to work at all... I mean the is no triggering of an action or update. Maybe i am doing something wrong but all of my efforts did lead to a solution.
What i itend to is, that, by select of an item from the suggestions of the 'typeahead' attribute immediatly, the partial update of chosen jsf elements occurs.

Thank you in advance.
