### ISSUE TITLE
Remote command used with onclick event in Firefox

### ISSUE THREAD

**Issue by Entrodox** [TheCoder4eu/BootsFaces-OSP#916]
Hi,

We get an error when using b:remoteCommand with a simple div with onclick event referencing the remoteCommand.

ReferenceError: event is not defined
openChat_0

`<script id="ticket_form:j_idt33:0:j_idt39">function openChat_0(){BsF.ajax.callAjax(document.getElementById('ticket_form:j_idt33:0:j_idt39'), event,'ticket_form:chatWindows','ticket_form:j_idt33:0:j_idt39', null, null, null, null);}</script>`

The above script generated from our code. I saw a similair issue ( #490 ), could something like that can happen here too? 

It works well with the primefaces remoteCommand.

BootsFaces version: 1.2.0
PrimeFaces version: 6.1
Firefox version: 58.0.2 (64-bit)

**Comment by stephanrauh** [comment]
Seems like no team member's using Firefox... but you're right, we should support it!

**Comment by stephanrauh** [comment]
I've fixed the bug. You can test the bugfix using the developer snapshot BootsFaces-1.2.1-SNAPSHOT. See #369 on how to get it.

BTW, thanks for the good analysis which made finding and repairing the bug a breeze!
