### ISSUE TITLE
NullpointerException at net.bootsfaces.component.messages.encodeEnd if FacesContext contains global messages

### ISSUE THREAD

**Issue by gitmotte** [TheCoder4eu/BootsFaces-OSP#917]
please filter 
`Iterator<String> clientIdsWithMessages = facesContext.getClientIdsWithMessages();`
by null at line 63.
Otherwise a NullpointerException occures at line 80 for global messages (clientId = null)
`if (currentId.equals(parentId)) {`

bootsfaces 1.2.0

**Comment by stephanrauh** [comment]
I've fixed this bug and uploaded a new developer snapshot BootsFaces-1.2.1-SNAPSHOT to Maven Central. If you want to test it, see #369 on how to get the snapshot.

BTW, this is the first bug I've simultaneously fixed in both BootsFaces 1.2 and the new BootsFaces 2.0 featuring Bootstrap 4!
