### ISSUE TITLE
Check if b:inputText mask supports regexp

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#920]
If so, add it to documentation, if not add / fix it.

`{ regex: "insertRegExpHere" }`

https://github.com/RobinHerbots/Inputmask#via-inputmask-class

https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/inputText/InputTextRenderer.java#L319

https://stackoverflow.com/questions/49107339/how-to-use-arabic-letters-in-bootsfaces-inputtext-mask-and-primefaces-inputmask

**Comment by jepsar** [comment]
I'll have a look one of these days and provide a PR.

**Comment by stephanrauh** [comment]
I've tested your PR. It works great! Thanks a lot!

Oh, and I've added the version hint :). It's good that you remembered to mention it!

**Comment by jepsar** [comment]
@stephanrauh  I see you've used 1.2.1 in the showcase, but added 1.5.0 as a milestone here. Which one is correct?

**Comment by stephanrauh** [comment]
I don't know :). Until now, the next release looks focuses on bug fixes, so it's probably going to be a 1.2.1. But we haven't talked about it yet.
