### ISSUE TITLE
Ajax event not fired for b:selectOneMenu inside ui:repeat and b:tabView for 2nd and following TABs

### ISSUE THREAD

**Issue by radorybar** [TheCoder4eu/BootsFaces-OSP#921]
* **Overview of the issue**

Ajax event not fired for b:selectOneMenu inside ui:repeat and b:tabView for 2nd and following TABs, if these are added dynamically.
If ui:repeat do just one iteration, than ajax event is fired correctly.
Also when b:tabView is replaced by primefaces p:tabView, ajax event gets fired correctly.

* **Motivation for or Use Case** 

It is not possible to set a value in b:selectOneMenu in dynamically added TAB.

* **BootsFaces Version(s)** 

1.2.1-SNAPSHOT

* **Browsers and Operating System** 

apache-tomee-webprofile-7.0.4 AS used.
No browser dependant issue.

* **Reproduce the error** 

Using attached reproducer:
1. Select origin for Hazard1 in type1
debug output produced by this step:
```
originChanged event: net.bootsfaces.issues.issue921.Hazard_@27ea7a0e - null
 Hazard:Hazard1 Origin:origin2origin2
 Hazard:Hazard2 Origin:null
 Hazard:Hazard3 Origin:null
```
2. Add new hazard in type1
debug output produced by this step:
```
Before add:
 Hazard:Hazard1 Origin:origin2origin2
 Hazard:Hazard2 Origin:null
 Hazard:Hazard3 Origin:null
After add:
 Hazard:Hazard1 Origin:origin2origin2
 Hazard:Hazard2 Origin:null
 Hazard:Hazard3 Origin:null
 Hazard:Hazard4 Origin:null
```
3. Select origin for Hazard4 in type1
this step produces no debug output although it should - similar to step 1

If primefaces p:tabView is used instead of b:tabView, or if ui:repeat value is limited to 1 iteration ( .get(0) ), step 3 produces this debug output:

```
originChanged event: net.bootsfaces.issues.issue921.Hazard_@1a636872 - origin3origin3
 Hazard:Hazard1 Origin:origin2origin2
 Hazard:Hazard2 Origin:null
 Hazard:Hazard3 Origin:null
 Hazard:Hazard4 Origin:origin3origin3

```

* **Related issues** 

Issue can be related to #918 

* **Suggest a Fix** 

N/A

[IssueReproducer.zip.txt](https://github.com/TheCoder4eu/BootsFaces-OSP/files/1789183/IssueReproducer.zip.txt)

**Comment by stephanrauh** [comment]
`setOrigin` is always called with `null`, although the `decode()` method of the `SelectOneMenuRenderer` get the correct value. Maybe this has something to with the nested repeats?

**Comment by chongma** [comment]
i can't deploy the reproducer on TomEE 7.0.5 plus.  it seems to have some JBoss specific stuff. i tried hacking it but no joy.  i could investigate running a JBoss instance but i know nothing about JBoss.  you could try moving everything into bootsfaces archetype https://github.com/chongma/bootsfaces-webapp-archetype. i also had a bit of trouble with the zip.  it might be easier to share the example as a github repo rather than a zip file

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
