### ISSUE TITLE
selectMultiMenu initialise component with a list with space after comma. 

### ISSUE THREAD

**Issue by gtstewart** [TheCoder4eu/BootsFaces-OSP#923]
Not sure if this is considered a bug or inconsistent behaviour.
When initialising the String variable in the backing bean to a comma separated list before displaying the selectMultiMenu, requires that there not be a space after the comma otherwise the items after the first will not be pre-selected. ie the list must be "Item 1,Item 2,Item 3". This how the String variable would appear after selecting those three items from the list.
However the the selected items in the  closed (not dropdown) selectMultiMenu are displayed with a space after the comma. ie the above list of selected items is displayed as Item 1, Item 2, Item 3
BootsFaces version 1.1.3
The problem was that I was displaying the variable elsewhere using an outputText component and was including the spaces to correctly format the text and it would not then work in the selectMultiMenu.

**Comment by stephanrauh** [comment]
The comma-separated list is a list of (internal) values, not of (user-readable) labels. So I consider the bug a mere inconsistency.

However, I also believe there's no harm in checking for spaces. It's only a fallback, so it's still possible to use values with leading or trailing spaces. I don't believe anybody does that, but still, it should be possible :).

I've uploaded a developer snapshot containing the bug fix to Maven Central. See #369 on how to get it.
