### ISSUE TITLE
JSF page lost style after partial update

### ISSUE THREAD

**Issue by maciass2008** [TheCoder4eu/BootsFaces-OSP#926]
when i try to update the content of modal using jsf + bootsfaces with 
```xml
<b:commandButton icon="edit" ajax="true" update=":modalFormUpdate"
oncomplete="$('#myModalUpdate').modal('show')"
action="#{documentBean.getDocToUpdate(doc)}">
```
all work fine:  i retrieve data in the modal but i lose the javascript and style of my components
any idea??
**note well : i use a template page and i include in it the modal panel using ui:include**

**Comment by stephanrauh** [comment]
No idea. These things happened in the past when we updated the wrong part of the DOM tree. But BootsFaces 1.2.0 has been published several months ago and there are 2000+ downloads per month. So I don't think it's really a BootsFaces bug. 

Nonetheless, I'll hunt the bug if you provide us a reproducer. That's a small but complete GitHub project (or a zip file containing the sources, including the pom.xml). It shouldn't need any database. Ideally it's just a simple project that runs on a simple Tomcat out-of-the-box.

I know that's demanding a lot (and I know how much work it is to create such a reproducer), but usually that's the key to solve the issue fast and efficiently. 

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
So you've used a standard `h:selectOneMenu` and converted it to a Bootstrap component using the CSS class? Don't get me wrong, there's nothing wrong with this approach, but BootsFaces is ill prepared for such a scenario. We've implemented `b:selectOneMenu`. One of the challenges was to initialize this component after an AJAX request.

If you need to use `h.selectOneMenu` for some reason, you have to re-initialize it yourself. I didn't try it yet, but I suppose you need to add something like this to the commandbutton:

```xml
oncomplete="$('#myModalUpdate').modal('show');$('.selectpicker').selectpicker();"
```

Hope that help!
(and please report back if it does :))

**Comment by maciass2008** [comment]
fixed ^^
**This is different to calling val() directly on the select element. If you call val() on the element directly, the bootstrap-select ui will not refresh (as the change event only fires from user interaction). You will have to call the ui refresh method yourself.

$('.selectpicker').val('Mustard');
$('.selectpicker').selectpicker('render');**

so to fix the problem i had to add at the "oncomplete" attribute $('.selectpicker').selectpicker('render');

```
<b:dataTableColumn label="Action">
<b:commandButton icon="edit" ajax="true"
update=":modalFormUpdate"
oncomplete="$('#myModalUpdate').modal('show');$('.selectpicker').selectpicker('render');"
action="#{documentBean.getDocToUpdate(doc)}">
</b:commandButton>
</b:dataTableColumn>
```
now it work correctly ^^

**Comment by maciass2008** [comment]
yes exactly that's what I just shared with you
