### ISSUE TITLE
b:commandButton and b:poll cause error message in development mode

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#93]
Both b:commandButton and b:poll seem to cause a lot of debug message in development mode:

```
Mai 24, 2015 9:30:28 PM com.sun.faces.application.view.FaceletPartialStateManagementStrategy saveDynamicActions
WARNING: Unable to save dynamic action with clientId 'j_id190' because the UIComponent cannot be found
```
There seems to be a list of dynamically created components that get longer on every postback. The error message is suppressed in production mode, but there seems to be a memory leak, so the issue has to be cared about even if it's not visible and doesn't do harm on the short run.

**Comment by TheCoder4eu** [comment]
'j_id190' is strange, the prefix of the ids is 'j_idt', so there is a 't' missing.
Is some code creating the id in a wrong way?

**Comment by stephanrauh** [comment]
It seems to be an OmniFaces bug. Removing the CombinedResourceHandler eliminates the warnings. Possibly the bug is caused by OmniFaces removing the resource files and replacing them with a new resource file.

**Comment by stephanrauh** [comment]
I've opened an issue on the OmniFaces project page: https://github.com/omnifaces/omnifaces/issues/135

**Comment by stephanrauh** [comment]
Bauke Scholz confirmed this bug, and considers it harmless. So I suggests it's enough to document this behavior, but there's no need to fix anything.

**Comment by stephanrauh** [comment]
Added the documentation to the "OmniFaces" page of the showcase.

**Comment by stephanrauh** [comment]
The next version of OmniFaces won't show the error.
