### ISSUE TITLE
Trying use datetimepicker

### ISSUE THREAD

**Issue by lucashespanhol** [TheCoder4eu/BootsFaces-OSP#930]
I'm trying to use datetimepicker in my project but I found some difficulty.
When I run the project on localhost the moment.js is loaded before datetimepicker.js, but when I run the project on my server the datetimepicker.js is loaded first and after moment.js.
How can I fix this issue on my project?

**Comment by stephanrauh** [comment]
No idea, so let's tackle the problem systematically.

Please examine the HMTL files generated by the server version of your project to the HTML files generated by the local version. In particular, check if both versions load moment.js and datatimepicker.js in the same order. More precisely, I refer to the position of the `<script type="text/javascript" src="/javax.faces.resource/js/bootstrap-datetimepicker.min.js.jsf?ln=bsf">` instruction (and the corresponding instruction loading moment.js).

Talking of which, our showcase doesn't seem to load moment.js. Where does your import of moment.js come from? Did you add it to the source code manually?

**Comment by lucashespanhol** [comment]
Hello, I updated the version of bootsfaces and now it's working well.

**Comment by stephanrauh** [comment]
Awesome! Not exactly the answer I was expecting, but I'm glad you could solve the issue in such a simple way! May I close the ticket?

Best regards,
Stephan
