### ISSUE TITLE
b:inputText delay triggers immediately

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#931]
i just tried to add a keyup delay on a `b:inputText` but there is no delay and it triggers as soon as the key is lifted.  e.g.
```
<b:inputText value="#{myBean.value}">
    <f:ajax event="keyup" delay="1000" listener="#{myBean.trigger}"
        render="@form" execute="@this" />
</b:inputText>
```
it works fine with `h:inputText`

**Comment by stephanrauh** [comment]
I've just implemented this feature and uploaded a new developer snapshot to Maven Central. Would you mind to run a test?

Thanks in advance,
Stephan
