### ISSUE TITLE
Autocomplete not working correctly

### ISSUE THREAD

**Issue by bkoubik88** [TheCoder4eu/BootsFaces-OSP#933]
My question is, why the autocomplete not working at all.
I get my data String list from a Database.
FirstName works but LastName not working/is shown.
So my question is, must the value be formatted in a particular  way ?

**Comment by stephanrauh** [comment]
@bkoubik88  Sorry for the late answer.

Did you manage to solve the issue in the meantime? If you didn't, can you provide us more details?

**Comment by stephanrauh** [comment]
I'll close the ticket for the moment because our showcase shows that the autocomplete does work.

If we get more information, we'll happily re-open the ticket.
