### ISSUE TITLE
Add option to hide dropMenu caret

### ISSUE THREAD

**Issue by shafinmahmud** [TheCoder4eu/BootsFaces-OSP#934]
Currently `dropMenu` renders with a caret besides Drop Menu. Though an option (`drop`) is available for *down* or *up* (default is *down*) but there is no way to hide them by native support from BootsFaces.

There should be an option or `drop` option should have some parameter to facilitate this flexibility.

**Comment by shafinmahmud** [comment]
yes. the CSS rule works nicely. But I was looking an in-house option from Bootsfaces. I think that would be nicer. Like `drop` option could have some value like `none` to do this charm.

**Comment by stephanrauh** [comment]
Also see https://stackoverflow.com/questions/49899345/how-to-remove-dropmenu-caret-in-bootsfaces

**Comment by stephanrauh** [comment]
After pondering this question for a week, I've decided not to implement a dedicated BootsFaces feature. The CSS rule does the trick. It even works if you want to show or hide the caret depending on a breakpoint. Just add a media query to it.
