### ISSUE TITLE
Kebab won't show dropdown list

### ISSUE THREAD

**Issue by mandapie** [TheCoder4eu/BootsFaces-OSP#938]
Hello,
The kebab menu icon shows up on my jsf page, but it won't show the items when I click on it.
My bootsfaces version 1.2.0. I have tried on different browsers (Chrome, Firefox, IE 11).
This is how i implement it:
```
<b:form>
  <p:dataScroller value="#{backingBean.List}" var="list" chunkSize="10">
    <b:row>
      <b:column tiny-screen="2">
        <h:outputLabel value="Name"/>
       </b:column>
      <b:column tiny-screen="4">
        <h:outputText value="#{list.name}"/>
      </b:column>
      <b:kebab >
        <b:listLinks>
          <b:navCommandLink value="Some Value" action="#{backingBean.someAction}"/>
          <b:navCommandLink value="Another Value" action="#{backingBean.anotherAction}}"/>
        </b:listLinks>
      </b:kebab>
    </b:row>
  </p:dataScroller>
</b:form>
```
I have also tried with <h:form> tag, and copy paste the example code from the documentation on a clean page. The command links work. I am just not sure why the kebab won't show the links.

**Comment by stephanrauh** [comment]
I've found and fixed the error. As a temporary workaround, adding a hidden `<b:dropDown>` repairs the kebab menu, too.

The PrimeFaces datascroller makes the kebab menu appear at the beginning of the row. At the moment, I don't see any simple way to solve that without JavaScript. A partial solution is this CSS rule:

```css
 <style>
  .ui-datascroller .dropdown-kebab ul {
  	left: 200px;
  }
  </style>
```

**Comment by stephanrauh** [comment]
I've uploaded a developer snapshot containing the bugfix to Maven Central. #369 describes how to get it.
