### ISSUE TITLE
b:selectOneMenu null itemValue

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#939]
consider the following `h:selectOneMenu` code snippet:
```
<h:selectOneMenu value="#{myBean.value}">
	<f:selectItem itemValue="#{null}" itemLabel="Not selected" />
	<f:selectItem itemValue="choice1" itemLabel="choice1" />
	<f:selectItem itemValue="choice2" itemLabel="choice2" />
</h:selectOneMenu>
```
when `Not selected` is selected then `myBean.value` equals `null`
```
<b:selectOneMenu label="Nice formatting" value="#{myBean.value}">
	<f:selectItem itemValue="#{null}" itemLabel="Not selected" />
	<f:selectItem itemValue="choice1" itemLabel="choice1" />
	<f:selectItem itemValue="choice2" itemLabel="choice2" />
</b:selectOneMenu>
```
whereas with `b:selectOneMenu` when `Not selected` is selected then `myBean.value` equals `Not selected`

**Comment by dguna** [comment]
I am not sure this is the correct way to do. Selectonemenu does not support null value. If it is empty then the bean has to convert as null.

**Comment by stephanrauh** [comment]
It was a deliberate choice to use the label if the value is missing, but probably it wasn't a wise choice. I've removed it because we've never documented the feature. Still, it's a breaking change.

Passing null values to the bean is difficult. During my test the null value has always been replaced by an empty string. To avoid that, you probably have to set the parameter `javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL` to `true`.

@chongma Can you review and test my changes, please?

**Comment by dguna** [comment]
Null is not an value. It means empty. JSF treats everything as string and the converters to the rest of the work to convert it to objects. There is no "null" object. This will fail always.

**Comment by chongma** [comment]
I have been passing nulls for a long time with (usually) no problem. But looking at this answer by @balusc it seems that @dguna is correct and that the preferred method is to pass an empty string. Not sure why null always worked for me before https://stackoverflow.com/questions/17052503/using-a-please-select-fselectitem-with-null-empty-value-inside-a-pselectonem?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by stephanrauh** [comment]
@dguna You are right... mostly. Have a look at [Bauke's well-researched article](http://balusc.omnifaces.org/2015/10/the-empty-string-madness.html).

**Comment by stephanrauh** [comment]
I'll close this ticket. If anyone of your finds a bug in my bugfix, don't hesitate to re-open the ticket.

**Comment by dguna** [comment]
Don"t close it yet. You have to give an option as f:selectitems noSelectionOption="true", it means empty string and if required=true, it should not be submitted. JSF automatically converts empty as null, if I am correct. Please look at the Primefaces selectonemenu.

**Comment by stephanrauh** [comment]
There are several references to `noSelectionOption` in our source code, so I assume we've already implemented it. For example, have a look at this one:

```java
private SelectItemAndComponent determineSelectedItem(FacesContext context, SelectOneMenu menu, List<SelectItemAndComponent> items, Converter converter) {
		Object submittedValue = menu.getSubmittedValue();
		Object selectedOption;
		if (submittedValue != null) {
			selectedOption = submittedValue;
		} else {
			selectedOption = menu.getValue();
		}

		for (int index = 0; index < items.size(); index++) {
			SelectItemAndComponent option = items.get(index);

                        
			if (option.getSelectItem().isNoSelectionOption()) continue;


			
			Object itemValue = option.getSelectItem().getValue();
			String itemValueAsString = getOptionAsString(context, menu, itemValue, converter);

			Object optionValue;
			if (submittedValue != null) {
				optionValue = itemValueAsString;
			} else {
				optionValue = itemValue;
			}

			if (itemValue != null) {
				if (isSelected(context, menu, selectedOption, optionValue, converter)) {
					return option;
				}
			} 
		}
		return null;
	}
	
```
