### ISSUE TITLE
disable modal backdrop and close icon

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#94]
Hello, 
is there way how to disable modal backdrop (I want to disable close of modal on click outside of modal) and modal close (X) icon in top right corner?

I tried $('.myModalPseudoClass').modal({backdrop: 'static', keyboard: false}); 
and also <b:modal id="myModal" title="Order" styleClass="myModalPseudoClass" pe:data-backdrop="static">

but with no luck
I'm on 0.6.6 version
Thanks

**Comment by stephanrauh** [comment]
I didn't try to reproduce the error myself yet, but a quick internet search revealed a promising trace:

According to [this ticket](https://github.com/angular-ui/bootstrap/issues/2970), it's an issue of Bootstrap 3.3.1-3.3.3. But we're already on Bootstrap 3.3.4, so maybe it's another problem.

**Comment by stephanrauh** [comment]
I added, implemented and documented the attributes
. dropback
. close-on-escape
. closable
in BootsFaces 0.6.7. 

Unfortunately, pass-through-attributes don't work with ```<b:modal />```, so there's no workaround in BootsFaces 0.6.6 except adding Javascript. However, I don't see any reason why your Javascript snippet shouldn't work.
