### ISSUE TITLE
Add ability to alter position of Datatable's page length and search UI

### ISSUE THREAD

**Issue by shafinmahmud** [TheCoder4eu/BootsFaces-OSP#941]
Currently, datatable's **Searching** box comes on the RHS and the **Show entries** (page length filter) comes on the LHS. And I find no way of altering their position, like what if I want the **Searching** on the LHS and don't want to have the **Show entries** filter?

**Comment by stephanrauh** [comment]
Sorry for answering late. I hope the answer is still relevant!

I'd use some CSS to achieve your goal. Put something like this in front of your `<b:dataTable>`:

```html
  <style>
     div.dataTables_wrapper div.dataTables_filter { 
     	text-align:left; 
     }
     .dataTables_wrapper > .row:first-child > div:first-child { 
     	display: none;
     }
  </style>
```

**Comment by stephanrauh** [comment]
This is the result of the CSS rules above (on a German PC):
![image](https://user-images.githubusercontent.com/3045767/40684559-ec63fdd2-6391-11e8-8a97-0c867c2879b5.png)
