### ISSUE TITLE
The RowGroup extension on <b:Datatable >

### ISSUE THREAD

**Issue by deathkryz** [TheCoder4eu/BootsFaces-OSP#945]
is this extension on develop ? or planning to add this feature ?

**Comment by stephanrauh** [comment]
I've implemented and documented the feature. I've also uploaded a new developer snapshot to Maven Central. See #369 on how to get it.

Currently, we don't have a developer snapshot of the showcase, but you can finde the documentation here: https://github.com/TheCoder4eu/BootsFacesWeb/commit/c750761746cf4f0b51c79108823079bb2114a40c

**Comment by deathkryz** [comment]
Thank you very much for answer
