### ISSUE TITLE
 onselect problem when using dataTable inside composite component 

### ISSUE THREAD

**Issue by rac021** [TheCoder4eu/BootsFaces-OSP#947]
Hi,

I have the following code : 

  **index.xhtml** : 
```xml
         <ez:service_list data="#{myBean.services}" 
                                 select="ajax:myBean" 
                                  updateDetails="formeServiceDetails:formeDetails" />
```

**service_list.xhtml** 

```xml
 <cc:interface>
        <cc:attribute name="data"/>
        <cc:attribute name="select" required="true" />
        <cc:attribute name="updateDetails"/>
    </cc:interface>


    <!-- IMPLEMENTATION -->    
    <cc:implementation>
        <b:panel look="primary" title="Services" collapsible="false">            
            <h:form>                
                <b:dataTable value="#{cc.attrs.data}" var="service"
                               onselect="#{cc.attrs.select.selectedService[service]}"
                               update="#{cc.attrs.updateDetails}" >   
                <b:dataTableColumn value="#{service.serviceName}" label="Service Name" />
            <h:form/>
  ```

And **MyBean.java** 
 
   ```java
  public void selectedService( ServiceDescription sc ) {
   }

  public List<ServiceDescription> getServices( ServiceDescription sc ) {
      return .....
   }

```
       
 The problem that I have is that **selectedService method is never called from the onselect of the dataTable.**      

Any one to tell me what's wrong ?

Thank you

R

**Comment by dguna** [comment]
Please see the code below. It works!!
`<b:dataTable id="table" value="#{categoryProductController.items}" var="var" widgetVar="tableWV"
                             select="true" selection-mode="single" update="eModal" 
                             onselect="ajax:categoryProductController.onSelect(var)"
                             oncomplete="$('.pseudoModal').modal()">`

**Comment by chongma** [comment]
in your implementation you do not close the `b:dataTable`.
also as @dguna says you need to call the selectedService using an ajax call like `onselect="ajax:myBean.selectedService(service)"`

**Comment by rac021** [comment]
Yes, this works fine.

I would like to know if there's a way to use **cc.attrs** in the **onselect** like the following : 

```
 <b:dataTable value="#{cc.attrs.data}" var="service"
              onselect="#{cc.attrs.select.selectedService[service]}" 
 <b:dataTable/>
```

` <ez:service_list  select="ajax:myBean"  data="#{myBean.services}" />`


Thank you

**Comment by chongma** [comment]
Did you try `onselect="ajax:cc.attrs.select.selectedService(service)"`? It might evaluate correctly?

**Comment by rac021** [comment]
Great, works fine

Thank you

**Comment by stephanrauh** [comment]
Sounds like I can close the issue. Thanks @dguna and @chongma for helping @rac021!
