### ISSUE TITLE
Any option in datatable to iterate through json file 

### ISSUE THREAD

**Issue by primeO** [TheCoder4eu/BootsFaces-OSP#948]
Is there any option how to iterate datatable from a json file directly instead of pojo .

**Comment by stephanrauh** [comment]
So you can wire the datatable to a REST service?

**Comment by chongma** [comment]
You could convert the json into a `List` in the backing bean

**Comment by stephanrauh** [comment]
Currently, I'm thinking about offering a native REST or JSON integration. Probably, it's not even difficult. Have a look at the documentation of the underlying JavaScript widget: https://datatables.net/examples/ajax/objects.html

What's I'm not sure about yet, is, if that approach is compatible to the myriad of other features we've already implemented. I'm 90% positive it is compatible, but the 10% require me to double-check that.

**Comment by primeO** [comment]
Tried the example which u had mentioned : it is showing as unexpected identifier 

I had returned a jsonobject from bean and mentioned as "ajax": "#{action.showdetails()}, 

Any suggestions

**Comment by stephanrauh** [comment]
@primeO Did you try it with or without the `<b:dataTable />`? I suppose we have to prepare the HTML code rendered by the datatable to make it work. But it's also possible to use are "bare-metal" approach. We've described the idea in the early version of BootsFaces (see https://github.com/TheCoder4eu/BootsFacesWeb/blob/v0.8.1/src/main/webapp/forms/DataTable.xhtml).

**Comment by primeO** [comment]
I had tried with out b:datatable @stephan

**Comment by stephanrauh** [comment]
Let's close the ticket. It's possible to convert the object in the backend bean, so there's a workaround.
