### ISSUE TITLE
how to check if form is valid in commandButton oncomplete

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#95]
Hi,
as mentioned [here](http://stackoverflow.com/questions/9195756/keep-pdialog-up-when-a-validation-error-occurs-after-submit) is there any option how to check if validation was successful in onsubmit of commandButton? I have modal, after submit I'm navigated to next modal. When I return back to first modal, I can see validation messages and now I'm not able to move to next modal.

this is my button
`<b:commandButton ajax="true" value="#{label['button.next']}" type="submit"
                                         actionListener="#{registerUserMB.register}"
                                         look="primary" styleClass="pull-right" update="registerUserForm"
                                         oncomplete="hideModalAndShowAnother('registerUserModalPseudoClass','testModalPseudoClass');"/>
`

**Comment by stephanrauh** [comment]
If ```args.validationFailed``` is a standard JSF api parameter, it should be simple to access it using the b:commandButton (possibly it's only shadowed by our current implementation). However, every reference I found to ```args.validationFailed``` is about PrimeFaces, so I wonder if it's a PrimeFaces feature which is not available in standard JSF.

**Comment by bilak** [comment]
I think it's the PF feature https://code.google.com/p/primefaces/issues/detail?id=714

**Comment by stephanrauh** [comment]
I've implemented a component that allows you to bring server side info to the Javascript window scope. Currently, it only sets the global variable ```validationFailed```. Note that this is a prototype - names and implementation details are still subject to change. A live demo of the prototype is available at http://www.bootsfaces.net/BootsFacesWeb/forms/commandButton.jsf.

**Comment by stephanrauh** [comment]
I've added a page to document this component.

**Comment by Nick2324** [comment]
Hi,

I know this is a closed issue, but I'm using bootsfaces 1.3.0 from maven repository and I'm trying to use this commandButton example that is in the docs (https://showcase.bootsfaces.net/forms/commandButton.jsf):

<b:commandButton value="Ajax Modal" ajax="true" update="form:inform amodal" look="inverse"
                 oncomplete="if(validationFailed) alert('Please enter valid input before opening the modal'); else $('#amodal').modal('show')" />

It fails because it says validationFailed is not defined. Could somebody help me with showing me how to do this or showing me where it's explained in the docs?

**Comment by stephanrauh** [comment]
I guess you're Nick2324 from [StackOverflow](https://stackoverflow.com/questions/53860939/how-to-validate-whether-my-form-is-valid-from-an-oncomplete-function-in-a-bcomm)? Just for the record, if someone else stumbles over this question: the solution is to add a `<b:fetchBeanInfos />` to the form. This widget adds the variable `validationFailed` (and several others) to the JavaScript namespace of the JSF page and updates it on every AJAX request.
