### ISSUE TITLE
Blank page, it seems like none of the bootfaces components are rendered

### ISSUE THREAD

**Issue by dguna** [TheCoder4eu/BootsFaces-OSP#950]
This was working very well. I have not changed the configuration. All of a sudden I am getting only blank pages. I am strugling with this for the past two days.

Here is my faces-config.xml
`<application>
        <resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
    </application>`

Here is my web.xml
`<context-param>
        <param-name>javax.faces.PROJECT_STAGE</param-name>
        <param-value>Development</param-value>
    </context-param>
    <context-param>
        <param-name>BootsFaces_THEME</param-name>
        <param-value>spacelab</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.DEFAULT_SUFFIX</param-name>
        <param-value>.xhtml</param-value>
    </context-param>
<servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>`

I am using glassfish5. Again I insist it was working very well before, suddenly this is happenning.

Thanks in advance!!

**Comment by dguna** [comment]
This is becasue of jsf mojarra 2.3 and 2.2. Now it works fine. Sorry for this.

**Comment by stephanrauh** [comment]
Don't blame Mojarra for that. Glassfish is just a flaky application server. Look, I've written an article for you this morning: https://beyondjava.net/running-bootsfaces-on-glassfish-or-payara

**Comment by stephanrauh** [comment]
Also see #636 and #732.
