### ISSUE TITLE
Feature request - autoupdate in growl, message

### ISSUE THREAD

**Issue by abraham1980** [TheCoder4eu/BootsFaces-OSP#953]
Do it like primefaces. it is very usefull

<p:messages **autoUpdate="true"**></p:messages>
<p:growl **autoUpdate="true"**> </p:growl>

so you dont need to refer thoses componente in the update clause of other components. 

Thank all you for that great framework!!!

**Comment by stephanrauh** [comment]
I guess this feature could be useful for almost every component. I've implemented it for every visual component. There's a new developer snapshot at Maven Central, so you can test it. See #369 how to get the snapshot.
