### ISSUE TITLE
Datatable: Width of Columns

### ISSUE THREAD

**Issue by msteinbeck** [TheCoder4eu/BootsFaces-OSP#957]
I would like to configure the width of the columns of a datatable. According to https://datatables.net/reference/option/columns.width I can use "columnDefs" to set the width for each column. I tried to set the desired values with "columnInfo" without any luck. Is there a simple way to set the width of columns?

**Comment by joepal1976** [comment]
You can use custom-options on dataTableColumn, like so:

    <b:dataTableColumn custom-options="'width':'150px'">

Note that it is 'width' and '150px'. Not including the 's will cause a javascript crash.

**Comment by chongma** [comment]
should it pass the width property through as an attribute of `b:dataTableColumn`? or should it just be specified in style or as a custom-option?

**Comment by stephanrauh** [comment]
It sounds sensible to me to add a `width` attribute, so I implemented the feature.
