### ISSUE TITLE
FR: add style to required inputs

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#96]
If I have input (b:inputText) which is required it will be nice to have some style class rendered with it.

**Comment by stephanrauh** [comment]
I've added the pseudo CSS class bf-required to ```<b:inputText />``` and ```<b:selectOneMenu />```. Is that's what you wanted us to do?

![image](https://cloud.githubusercontent.com/assets/3045767/7870367/216fc700-0589-11e5-9a96-d1d6e9bc33b7.png)

**Comment by bilak** [comment]
Yes that's correct. Thanks
