### ISSUE TITLE
commandLink actionListener not triggering bean method

### ISSUE THREAD

**Issue by kwrobel** [TheCoder4eu/BootsFaces-OSP#960]
I'm using **Bootsfaces 1.2.0** and am trying to use the `commandLink` with an `actionListener`. The problem is that the `actionListener` method never executes. If I turn the tag into a `commandButton`, it works immediately. I've tried this with **Wildfly 10.1.0 Final** as well as with **Apache Tomee 7.0.2** Web Profile. I created a very simple test project just to make sure I don't have any other code that might interfere. In essence, I created a new project in NetBeans 8 targeting Tomee 7.0.2, then added the `beans.xml` to indicate that I want to use **CDI**, added a new Managed Bean called `HelloBean`. I made sure it implements the `Serializable` interface and added a very simple method with the following signature: `public void doSomething(ActionEvent e)`. Then I modified the generated `index.xhtml` to have a container, a Bootsfaces `<b:form>`, then a `<b:row>`, then a `<b:panel>`, and then my `<b:commandButton>` and `<b:commandLink>` tags. Each of these has `ajax="true"`, a `value` and an `actionListener` attribute. The `commandButton` works without problems, but the link does not work. In fact, the link does not even behave link a typical link. The browser normally changes the cursor into a hand when it hovers over a link (true for standard JSF as well as PrimeFaces commandLinks), but with Bootsfaces, the cursor changes into a cursor that looks like a *edit* cursor. Has anybody else experienced this issue?

**Comment by chongma** [comment]
can you post the relevant code of your xhtml and your backing bean?

**Comment by chongma** [comment]
we used to use `<b:navCommandLink />` as a `commandLink`.  Stephan created the commandLink as a clone of commandLink due to many requests.  maybe it misses something in the implementation.  could you try with `<b:navCommandLink value="Do Something" ajax="true" actionListener="#{helloBean.doSomething}"/>`

**Comment by kwrobel** [comment]
Yup. That works, but I would have never thought of that since it looks like it is an element that relates to the `navBar` due to the name. And since there was a separate `commandLink` which I have used in the past with PrimeFaces and regular JSF, I didn't think much of it. I would suggest, though, to fix the implementation since it just doesn't seem to work. I guess for my current project I can get away with using the `navCommandLink`, but I'd probably change it in the future once `commandLink` works as expected.

**Comment by stephanrauh** [comment]
Actually, the `CommandLinkRenderer` simply derives from the `NavLinkRenderer`, and `NavCommandLink` uses the `NavLinkRenderer`, too, so I didn't expect this bug:

```java 
@FacesRenderer(componentFamily = "net.bootsfaces.component", rendererType = "net.bootsfaces.component.commandLink.CommandLink")
public class CommandLinkRenderer extends NavLinkRenderer {
}
```

**Comment by chongma** [comment]
maybe `CommandLink` should extend `NavCommandLink` rather than `NavLink`?

**Comment by chongma** [comment]
i have changed it here https://github.com/TheCoder4eu/BootsFaces-OSP/pull/959/commits/fe272ffdfbbd9b3a988033aadbefb99e06361fc2 and it seems to work ok.  i have added a test in the showcase here https://github.com/TheCoder4eu/BootsFacesWeb/pull/56/commits/6f995ac76cdc54fec4342d7f02cd02f5568ec64c

**Comment by stephanrauh** [comment]
IMHO that's solved by merging the PRs of @chongma yesterday.
