### ISSUE TITLE
Question: How to use Spinner widget for AJAX status feedback?

### ISSUE THREAD

**Issue by kwrobel** [TheCoder4eu/BootsFaces-OSP#962]
I've seen the documentation page for the `<b:spinner>` widget, and the widget looks cool. However, I am struggling to make it work as I intend it, which is that I'd like to show this spinner only during an AJAX request in the lower right corner. My current app searches a rather large database for records, and depending on the underlying hardware, the query may take a few seconds. I'd like to show the spinner during such an AJAX request. It would be nice if there was a **howto** page that can explain this. I know you support the *BlockUI*, which might be where I'd have to put this, but I cannot put any JSF code there (or can I?). But so far, I found the customization of BlockUI rather unintuitive since it has to be done in JavaScript. Any advice from the dev team on this topic?

**Comment by stephanrauh** [comment]
Thanks for pointing out how to improve the documentation! You know, we're so familiar with BootsFaces, we desperately need some feedback about what we forgot to document yet.

That said, the spinner is basically just an icon. The middle demo of the showcase boils down to this HTML code:
```html
<i class="fa fa-refresh fa-3x fa-spin" />
```
I  suppose it should be fairly simple to include this HTML snippet with the blockUI customization. If it doesn't, just tell us, so we can improve the documentation.

(BTW, if my clue helps you, please report back, too, so we can close the ticket).

**Comment by jepsar** [comment]
I more or less wanted to create the same issue. I would have liked to use

````
<b:blockUI>
  <b:spinner .../>
</b:blockUI>
````

to customize the block UI HTML. Or, simply only set the icon using:

````
<b:blockUI icon="cog" size="3x"/>
````

and then take care of the rest using CSS.

**Comment by kwrobel** [comment]
I agree with the last suggestion. Then again, Bootsfaces has no `<b:blockUI>` widget. But my question was leaning more towards trapping the AJAX lifecycle, like AjaxStatus in PrimeFaces. But for now, I'd just be happy if `BlockUI` (which happens with every AJAX event -- good) was easier to customize, specifically with `<b:spinner>`. The desired outcome is to show the spinner in the lower right corner of the browser window, similar to what you see in the PrimeFaces Showcase. Or, having the spinner next to a button that performs an AJAX task. So in the end, I was hoping that the spinner widget was somehow wired to a specific AJAX event handler or at least a button causing AJAX, or maybe the ability to wire up the spinner to whichever the dev sees fit, and then show it only during the referenced event. And having such an example would save devs like me who are not accustomed to CSS and styling stuff lots of time.
The instructions for BlockUI, in particular on how to override settings, were very brief and in many cases didn't even work for me. For example, the CSS Color attribute which was supposed to affect the color of the foreground text inside the BlockUI box never changed because the text was actually enclosed in an <h1> tag, which did not get affected by that setting. I ended up using an example from a site where they showed how to completely restyle the BlockUI by turning all CSS off for it and running their own, which I simply copied without really knowing what I was doing. Then again, I'm not used to styling. I'm a programmer who is more of a data guy.

**Comment by jepsar** [comment]
I've used this bit of script to create such a spinner (bottom right):

````
function ready(fn) {
  if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading") {
    fn();
  } else {
    document.addEventListener("DOMContentLoaded", fn);
  }
}
ready(function() {
  $.blockUI.defaults.css = {
    padding: "1em",
    right: 0,
    bottom: 0,
    border: 0,
    color: "#000",
    backgroundColor: "transparent",
    opacity: .5
  };
  $.blockUI.defaults.overlayCSS.opacity = 0;
  $.blockUI.defaults.message = "<span class=\"fa fa-cog fa-3x fa-spin\"/>";
});
````

**Comment by kwrobel** [comment]
Thanks. I used your suggestion and applied it to how the documentation of Bootsfaces showed me. Which is: I activated BlockUI in the `web.xml` file:
```
    <context-param>
        <param-name>net.bootsfaces.blockUI</param-name>
        <param-value>true</param-value>
    </context-param>
```
Then I added the following lines to my JSF template:
```
        <script>
            $.blockUI.defaults.css = {
                padding: "1em",
                right: 0,
                bottom: 0,
                border: 0,
                color: "#000",
                backgroundColor: "transparent",
                opacity: 1.0
            };
            $.blockUI.defaults.overlayCSS.opacity = 0;
            $.blockUI.defaults.message = '<span class="fa fa-circle-o-notch fa-2x fa-spin"/>';
        </script>
```

**Comment by stephanrauh** [comment]
@kwrobel You've closed the ticket. That's good because it shows your current problem has been solved. However, as a framework designer, I also want to support the rest of the community. Many other developers have the same background as you. Taking this in mind, do you want us to do something? Like improving the documentation, adding the solution of @jepsar, something like this?

**Comment by jepsar** [comment]
@stephanrauh I'm still in favour of creating a `b:blockUI` component which allows you to set an icon, a size and maybe a position. Do you agree? If so, I can see if / when I can provide a PR.

**Comment by kwrobel** [comment]
@stephanrauh @jepsar Thank you. I think it would be a good idea to expand the `BlockUI` page the example this discussion. Pointing to the reference of the BlockUI addon was not enough from my perspective. Applying their [Demos](http://malsup.com/jquery/block/#demos) code to my app somehow didn't work as expected. Styling was completely off or incomplete. Not sure why their sample code didn't translate into Bootsfaces' BlockUI version. So maybe it would be a better idea to implement a `<b:blockui>` component. It would also allow scoping of which section of the page should be blocked instead of generally blocking the UI on every page on the entire page.

Another thing I'd like to mention: I was able to use the `<b:spinner>` tag inside the `$.blockUI.defaults.message` code. However, the page gave me a JSF error that the component needed to be part of a form which was impossible for me to do that high up in the JSF chain (template). I'm thinking, if the `<b:spinner>` could produce a simple `<span>` tag with just the right CSS classes applied, that might be cleaner. Again, I'm just looking at it from my own perspective. I'm sure there were design decisions involved. Maybe an option could be added to the spinner widget that can control how the tag gets rendered. Like `renderas="span"` or something. Anyway, please let me know if there's anything I can contribute.

**Comment by jepsar** [comment]
@stephanrauh @kwrobel I've opened a new issue regarding a new component.

**Comment by stephanrauh** [comment]
@jepsar These days, I hardly manage to keep up with my mails, so this answer is a bit late. Yeah, sure, feel free to send us a pull request!

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
BTW, using `<b:spinner>` in the message still works without using a form. I'm afraid I can't reproduce the error. Have a look at the showcase: https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/forms/blockUI.xhtml

**Comment by kwrobel** [comment]
@stephanrauh Yeah, unfortunately, I cannot reproduce it either. So I guess I will have to blame it on my project's template file. I have to admit, I was also very surprised that I was able to use a server-side JSF tag inside the `blockUI` message expression. But, it does work.

**Comment by stephanrauh** [comment]
Be that as it may: you've convinced me that we can improve the documentation of blockUI. I have to admit I was confused by my own text. Thanks for pointing that out!
