### ISSUE TITLE
dataTable column widths change with number of characters in header

### ISSUE THREAD

**Issue by joepal1976** [TheCoder4eu/BootsFaces-OSP#967]
Expected: columns should be equally wide, unless content overflows.

Actual: A column with the label "1234567890" is wider than a column with the label "12345" despite there being plenty of space.

There seems to be a linear relation, but a column with the label "1" is not ten percent of the width of "1234567890". 

![colwidth](https://user-images.githubusercontent.com/10105480/42617709-e56989e6-85b2-11e8-914c-4b0dcba53d41.png)

Debugging this, it seems there is an "autowidth" feature of datatables: https://datatables.net/reference/option/autoWidth. However, toggling this (custom-options="autoWidth:false") does not seem to have any effect. 

This is a minor glitch since it's possible to set explicit widths on columns (via custom-option on dataTableColumn), but it's a confusing behavior when first encountered.

**Comment by stephanrauh** [comment]
After some Googling, I start to believe that `autoWidth` is a broken feature. I've found an alternative to setting the width on the individual columns:

```xml
<b:dataTable value="#{carPool.carPool}"
                     var="car"
                     custom-options="'aoColumns': [{'sWidth':'16%'},{'sWidth':'16%'},{'sWidth':'16%'},{'sWidth':'16%'},{'sWidth':'16%'},{'sWidth':'16%'}]">
````
But I don't think that's an improvement :).

Also see https://datatables.net/forums/discussion/41870/column-width-not-working (and scroll to the latest answer).

In 2010, the feature wasn't broken, at least according to this article: http://www.craiglotter.co.za/2010/08/16/jquery-datatables-how-to-force-specific-column-widths/

**Comment by stephanrauh** [comment]
Also see #957.
