### ISSUE TITLE
Global FacesMessage (without explicit clientId) are not displayed in <b:messages/> in 1.3.0

### ISSUE THREAD

**Issue by JonathanLalou** [TheCoder4eu/BootsFaces-OSP#969]
Hi,

Regression appeared in version 1.3.0:

I declare this:
```        
<b:messages id="messages" showSummary="false" showDetail="true" autoUpdate="true" closable="false" />
```
When this code is executed:
```
        final FacesMessage facesMessage = new FacesMessage(javax.faces.application.FacesMessage.SEVERITY_INFO, "summary", "my detail message");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
```
(note that the `null` corresponds to the parameter `clientId`) then the <b:messages/> does not display the message.
But if I execute with the specific `clientId`, like this:
```
        FacesContext.getCurrentInstance().addMessage("messages", facesMessage);
```        
then the message is displayed.        
The conclusion of this is that global messages are not cast to the `<b:messages/>`.

I also confirm that:
* it worked in version 1.2.0
* when I replace the `<b:messages/>` with Primefaces' `<p:messages/>`, the message appears.

**Comment by stephanrauh** [comment]
@JonathanLalou I hate to use that sticker, but it

![image](https://user-images.githubusercontent.com/3045767/42969962-389a7828-8ba8-11e8-802e-9a13b8e5ccd5.png)

What do I different that you do? I've uploaded my reproducer to the showcase project:

https://github.com/TheCoder4eu/BootsFacesWeb/commit/65804e6417f52009c892aed4c548588d2abe3fd4

![image](https://user-images.githubusercontent.com/3045767/42970056-86c81046-8ba8-11e8-9cd8-c1e56e8d5d3d.png)

**Comment by JonathanLalou** [comment]
Hi @stephanrauh ,

Thanks for verifying. 
Running your code, I got the same result: it works...

I will dive in and give you updates.

Regards

**Comment by stephanrauh** [comment]
@JonathanLalou Any progress on your side?

**Comment by JonathanLalou** [comment]
Hi @stephanrauh ,

-I still have the issue in my code.
-I have not been able to isolate the bug, I can just say that it occurs because some ManagedBeans are instantiated two times (for me they should not). This seems to be related to life cycle of beans. I did not have enough time to dig more.
(With Managed Beans that are instantiated one time the issue does not appear)

I thought there could be a conflict between Spring and JSF contexts, but I was able to exclude this possibility.

Regards,

**Comment by stephanrauh** [comment]
@JonathanLalou Is there anything we can do to help you? If you send us a reproducer (i.e. a minimal but complete example showing the bug without setting up a database and without having to configure the application), we could have a look at the bug ourselves.

**Comment by JonathanLalou** [comment]
@stephanrauh Sorry, I have not been able to isolate the bug in a minimal application.  
I will try to work on it over the week-end.

**Comment by stephanrauh** [comment]
Let's close the bug. It's been open so long I assume it's been solved in one way or another.
