### ISSUE TITLE
New component: b:blockUI

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#972]
Maybe it's good to have a component to easily configure blockUI. Now it's quite a hassle to set a spinning icon and customize styling.

Related: #962 

See also: https://www.primefaces.org/showcase-ext/sections/blockui/blockPage.jsf

**Comment by stephanrauh** [comment]
Sounds like a good idea.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
