### ISSUE TITLE
Poll: Which breakpoints would you like to add to BootsFaces?

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#973]
I'm unhappy with the choice of breakpoints of the Bootstrap teams. It matches none of the devices I'm using on a daily basis. I've already added a breakpoint in BootsFaces 1.3 (1400 pixel) and I'd like to add more breakpoints in future versions.

Which breakpoints would you like to see? My suggestions:

- 1024 px (iPad and Nexus 9)
- 1600 px
- 1920 px
- 4K

**Comment by chongma** [comment]
i am not very good with the interface stuff so i can't really comment on this.  i find that bootsfaces works ok on most of the devices i need to support.  with the exception that data tables bleed out on mobile devices

**Comment by stephanrauh** [comment]
Oops - that's something I wasn't aware of. I do not want our datatables to bleed out. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
