### ISSUE TITLE
Does b:spinner need a form?

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#975]
Reported in #962 by @kwrobel:

I was able to use the `<b:spinner>` tag inside the `$.blockUI.defaults.message` code. However, the page gave me a JSF error that the component needed to be part of a form which was impossible for me to do that high up in the JSF chain (template). I'm thinking, if the `<b:spinner>` could produce a simple `<span>` tag with just the right CSS classes applied, that might be cleaner. Again, I'm just looking at it from my own perspective. I'm sure there were design decisions involved. Maybe an option could be added to the spinner widget that can control how the tag gets rendered. Like `renderas="span"` or something. Anyway, please let me know if there's anything I can contribute.

**Comment by stephanrauh** [comment]
The spinner does generate a simple `<span>`, pretty much the way you requested. The only odd thing I found is that it derives from `UICommand`, which might explain the error message. However, our showcase demo page doesn't have a form.

@kwrobel I suppose you've found a different bug. Can you check your source code again, so we can find out which component really caused the "missing form" error?

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
Using `<b:spinner>` in the message still works without using a form. I'm afraid I can't reproduce the error. Have a look at the showcase: https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/forms/blockUI.xhtml

**Comment by kwrobel** [comment]
@stephanrauh See my response in #962. Thanks for your help.
