### ISSUE TITLE
disabled attribute missing from b:commandButton

### ISSUE THREAD

**Issue by xystra** [TheCoder4eu/BootsFaces-OSP#98]
Hi, is there a reason why the disabled attribute is missing from the commandButton tag? It's currently available via the b:button tag. I'm looking to disable a commandButton based on conditions defined within my bean.  thanks.

**Comment by stephanrauh** [comment]
No, there's no reason except our forgetfulness :). I suggest we add it in the next version (which is to say: soon).

**Comment by stephanrauh** [comment]
Actually, the attribute "disabled" was there from the beginning of BootsFaces. We only forgot to add it in the documentation and the taglib (so there's no autocompletion). I've done both things now.
