### ISSUE TITLE
doubt about <b: selectOneMenu>

### ISSUE THREAD

**Issue by nickolaz** [TheCoder4eu/BootsFaces-OSP#983]
the showcase in Basic Usage there is an example that has a search. I have not been able to reproduce that, if you could help me

Thank you

[https://showcase.bootsfaces.net/forms/selectOneMenu.jsf#basic_usage
![select](https://user-images.githubusercontent.com/18169294/43403158-6bcedb70-93e2-11e8-9405-bc72b4e92c08.png)
](url)

**Comment by stephanrauh** [comment]
Don't doubt the selectOneMenu :). It's just me who's forgotten to document @jottyfan 's great contribution (https://github.com/TheCoder4eu/BootsFaces-OSP/pull/903).

To answer your question: simply add the attribute `select2="true"`.

**Comment by stephanrauh** [comment]
The next version of the showcase does contain a demo, so I'll close the issue. Feel free to continue commenting in this ticket. We keep listening even if it's closed.

![image](https://user-images.githubusercontent.com/3045767/43419858-7c9bd024-9442-11e8-8f09-22daf29f6af6.png)
