### ISSUE TITLE
Adding aria-disabled="true"  when b:navLink are disabled

### ISSUE THREAD

**Issue by Lb-lea** [TheCoder4eu/BootsFaces-OSP#986]
Hello,
I think it would be nice if the links could have the _aria-disabled="true"_ tag when they are. It would help for those who have to develop accessible websites.
Or you could allow the dev to add arias manually but it seems much more complicated.

Thank you for your work ~

**Comment by stephanrauh** [comment]
I've implemented the feature and uploaded a developer snapshot of BootsFaces 1.3.1-SNAPSHOT to Maven Central. See #369 on how to get it.
