### ISSUE TITLE
<b: dataTable />

### ISSUE THREAD

**Issue by nickolaz** [TheCoder4eu/BootsFaces-OSP#987]
is it possible to implement lazy loading in the datatable ??
and if possible, how would they do it?

**Comment by stephanrauh** [comment]
Related to #948

**Comment by stephanrauh** [comment]
I'm afraid it's not easy to implement lazy loading. 

However, what you can do is to use the underlying JavaScript component directly (without assistance from BootsFaces). Datatables.net supports lazy loading. It just doesn't translate easily to BootsFaces.

Have a look here: https://datatables.net/examples/server_side/defer_loading.html

**Comment by chongma** [comment]
i use primefaces datatable for lazy loading.  it would be nice to have in bootsfaces but there are no plans as far as i am aware

**Comment by jepsar** [comment]
https://showcase.bootsfaces.net/forms/DataTable.jsf

"user interactions don't use AJAX to redraw the table, so you can't easily implement lazy loading"

So how would this work? Should I as a user do the lazy loading? Can anyone explain how?

**Comment by jepsar** [comment]
.. can someone please improve the title of this issue?
