### ISSUE TITLE
Expose slider2 JS object to window

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#988]
Now there is no way to customize things.

https://github.com/TheCoder4eu/BootsFaces-OSP/blob/fa2543991d414eb46d6cb880fc505467f917ba76/src/main/java/net/bootsfaces/component/slider2/Slider2Renderer.java#L376

Could be changed to:

````
"window." + VarName + "_sv =....
````

And maybe even an attribute could be added to set your var name (if your slider is in a form without an id attribute, you get a generated id based variable name like `j_idt8_slider_sv`).

@stephanrauh You could assign this to me if you like.

**Comment by stephanrauh** [comment]
Sound's like you're about to send a pull request. Go ahead! The feature sounds sensible to me.

**Comment by jepsar** [comment]
@stephanrauh This issue was not fixed in that PR, I'll provide a new PR fixing this issue. Please reopen for now.
