### ISSUE TITLE
navLink and navCommandLink not compatible with keyboard navigation

### ISSUE THREAD

**Issue by Lb-lea** [TheCoder4eu/BootsFaces-OSP#989]
Hello,
it seems that those two items are being skipped during keyboard navigation. 
You can see it on the first example [here]( https://showcase.bootsfaces.net/layout/navbars.jsf ) : when using tab, the selection goes from the brand link to the dropdown one skipping the two in between links. It makes the whole thing un-accessible  for keyboards only users.
It would be great  if there was a fully navigable navbar component.

**Comment by stephanrauh** [comment]
This ticket probably needs some investigation, but you're right, it's one of the things we definitely should support.

**Comment by Lb-lea** [comment]
I'm not sure but from what I gather it might been due to the ```tabindex="-1"``` attribute in the generated link

**Comment by stephanrauh** [comment]
Now keyboard navigation works a lot better. Thanks for reporting the bug and for suggesting the solution!
