### ISSUE TITLE
input with tags damages the setting process

### ISSUE THREAD

**Issue by ghost** [TheCoder4eu/BootsFaces-OSP#995]
BootsFaces Version 1.3.0

Assume this simple example:
```xml
<b:form>
  <b:inputText tags="true" value="#{myBean.myValue}" />
  <b:commandButton action="#{myBean.submit}" value="submit" />
</b:form>
```
```java
@ManagedBean
@SessionScoped
public class MyBean {
  private String myValue;
  public String getMyValue(){ return myValue; }
  public String setMyValue(String myValue){ this.myValue = myValue; }
  public String submit() {
    System.out.println(myValue);
  }
}
```
If the `tags`-attribute is set to true, the method `setMyValue` is not used or may be used, but the value does not be submitted. The output is clear for this case.

Removing the `tags`-attribute activates the setter again.

**Comment by stephanrauh** [comment]
My attempt to improve the feature in BootsFaces 1.3.0 has made it worse. I've fixed that in the developer Snapshot of 1.3.1. Would you mind to have a look if the bugs is solved in 1.3.1?

**Comment by jottyfan** [comment]
I'm afraid but it still does not work yet with 1.3.1-SNAPSHOT. The setter is simply not called.

**Comment by jottyfan** [comment]
why has this issue not been solved before 1.4.0 came out?

**Comment by stephanrauh** [comment]
I'm sorry. There's a simple reason: we've run out of active developers. Sometimes private life interferes with your passion for open source. Currently, we don't even manage to solve bugs faster than they are reported. Every once in a while I send a tweet asking for a helping hand, but nobody seems to be interested.

So, yes, I'm really sorry for starting to solve your ticket, only to forget it a short while later. It's lost in the pile of 126 open tickets. Bear with me!

(Or even better, convince your friends and co-workers to participate in an exciting open-source project which is downloaded roughly 4.000 times each month). :)

**Comment by jottyfan** [comment]
Thanks for the candidly answer, I do respect your privacy. It's awesome what you do for the community, and if I had time, I'd also like to give you a hand on some issues. Maybe I can do so in the next months...

I do also know that pull requests can speed up solving that issue, and as soon as I can find that bug in the framework, I will offer one. Currently, you've closed 131 pull requests and have 0 open, this is a very good indication of your fantastic collaboration way. Please don't give up, you're doing great work here.

**Comment by stephanrauh** [comment]
Well... you've contributed several PRs yourself, let me shout a "thank you" to you, too! :)

Oh, and I wish you a Happy New Year!

**Comment by Coolius70** [comment]
Hi

Was lost again for a day till I found out, that issue still exists in 1.4.1. Was struggling with 1.3 several days as well. I did rollback to 1.2 and it works again with tags. Would be great if this bug can be fixed in the nearer future because it is blocking to upgrade to a newer version and there is a very long list of improvements in the newer version. Thanks for that as well.

**Comment by geopossachs** [comment]
found the IE bug : Das Objekt unterstützt die Eigenschaft oder Methode "startsWith" nicht

**Comment by jottyfan** [comment]
> found the IE bug : Das Objekt unterstützt die Eigenschaft oder Methode "startsWith" nicht

Great that you've found this, but my bug report bases on a firefox on debian linux. So there might be another problem.

**Comment by stephanrauh** [comment]
Oops. Great work nonetheless, @geopossachs! THX!

**Comment by geopossachs** [comment]
I'm confused - i could not found bootstrap-tagsinput v0.7.2 on the project page, after an upgrade to v0.8.0 i have damage my test-setup - There is nothing in the form upload and there is no hiden input value that changes with an input. How does this lib work? - https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

**Comment by stephanrauh** [comment]
The current repository is here: https://github.com/stephanrauh/bootstrap-tagsinput

**Comment by geopossachs** [comment]
#1079

**Comment by geopossachs** [comment]
@stephanrauh in the version v0.8.0 there is no IE bug. can we use the version of the main repo or do we need the forked older version? if have found a bug with a missing css class in the newer version but i can fix this via jquery

**Comment by stephanrauh** [comment]
I've forked the version because the original bootstrap-tagsinput seems to be dead. So my fork should be newer than the 0.7.2 version. There's no need to use jQuery: I've forked the project specifally for BootsFaces, so you can fix bugs yourself.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
