### ISSUE TITLE
DataTables.net - provide possibility to use datatables.net from CDN or locally

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#997]
Currently it is possible to use jquery, jqueryUI, bootstrap.css etc. from CDN or provided with the app. It will be nice if the same possibility is provided for datatables.net (currently always from CDN).
In some environments using CDNs is not acceptable (at least as it was explained to me, because this means a runtime dependency on an external service/resource which can potentially be compromised, thus compromising the app or at least breaking its usability). From what I know ISO and PCIDSS certification might be mandating providing everything used as a local resource.
Also, since the requests are made to a CDN, I believe this means no specific changes (like in bootstrap, for instance).
As a side note, possibility to also provide bootstrap locally would be great - but I guess it might require some rethinking of the changes currently made, so that they'd extend the basic bootstrap code rather than having manual changes inside the core code (remember the Open/Closed Principle?) :)

**Comment by stephanrauh** [comment]
As for datatable.net.js / *.css: good idea.

As for your side note: Would you mind to elaborate? What do you mean with "provide bootstrap locally"? Both the BootsFaces.min.css and the Bootstrap.min.js can be provided locally by simply adding them to your *.war-file and to include them in the page header.

**Comment by TheTimeWalker** [comment]
@vsvetoslavov You should already be able to provide your own Bootstrap files by using `net.bootsfaces.get_bootstrap_from_cdn`. This is explained under [Resource Management](https://showcase.bootsfaces.net/layout/resourcemanagement.jsf)

**Comment by vsvetoslavov** [comment]
@stephanrauh @TheTimeWalker As far as I remember, there were some changes in the core bootstrap files - am I wrong? That was what I meant - try to somehow make the changes by overriding the core code, not by changing it.

**Comment by stephanrauh** [comment]
Now I've got it. Good point. I have to recollect how we modify the BootsFaces.css. Currently, I only remember the new "xl" breakpoint, but I think there are a few small modifications beyond that.

**Comment by stephanrauh** [comment]
The request for making dataTables.net configurable is addressed under #853 . Actually, I've finished the implementation. Only one of the demos is missing.
