### ISSUE TITLE
defaultCommand does not work on commandButton with col/span attribute

### ISSUE THREAD

**Issue by TheTimeWalker** [TheCoder4eu/BootsFaces-OSP#999]
After trying to fight forever on why `<b:defaultCommand/>` didn't work on `<b:commandButton/>`, I've finally figured out the culprit

Steps to reproduce:
1. Set up a form with a generic inputText
2. Add a commandButton with any of these attributes: colXs, colSm, colMd, colLg, span
3. Bind defaultCommand with a target to commandButton

What happens is that the button is being wrapped around a `<div>` which inherits the ID of the button. The button itself contains no ID. This means that defaultCommand instead clicks on the div as opposed to the button.

Tested on:
BootsFaces 1.3.0
PrimeFaces 6.2.0
Payara 5.181 with JSF 2.3

**Comment by stephanrauh** [comment]
Oops. Thanks for pointing this out!

**Comment by geopossachs** [comment]
i retest it, the bug was fixed with version 1.4.2
